lisaac ./bench/bench.li -q -boost
lisaac ./gui/predict_size/essai.li -q -boost
lisaac ./gui/msn/msn.li -q -boost
lisaac ./gui/mpg2/mpeg2dec.li -q -boost
lisaac ./gui/viewer/viewer.li -q -boost
lisaac ./gui/desktop/monitor.li -q -boost
lisaac gui/make.lip gui/desktop/desktop.li -boost -q
lisaac ./gui/draw/example.li -q -boost
lisaac ./gui/transparent/test_trans.li -q -boost
lisaac ./gui/about/about.li -q -boost
lisaac ./gui/gravity/gravity.li -q -boost
lisaac ./gui/hello.li -q -boost
lisaac ./gui/calculator/calculator.li -q -boost
lisaac ./gui/clock/clock_view.li -q -boost
lisaac ./block/master.li -q -boost
lisaac ./mailer/mailer.li -q -boost
lisaac ./base/pyramid2.li -q -boost
lisaac ./base/knight.li -q -boost
lisaac ./base/hello_world.li -q -boost
lisaac ./base/pyramid.li -q -boost
lisaac ./tetris/tetris.li -q -boost
lisaac ./tree/master.li -q -boost
lisaac ./acgt/acgt.li -q -boost
lisaac ./bottles/bottles.li -q -boost
lisaac ./super/master.li -q -boost
lisaac ./su_doku/su_doku.li -q -boost
lisaac ./tree2/master.li -q -boost
lisaac ./slot/master.li -q -boost
lisaac ./shell/shell.li -q -boost
lisaac ./calc/calc.li -q -boost
lisaac ./fouronline/fouronline.li -q -boost
lisaac ./demomaker/rotozoom/rotozoom.li -q -boost
lisaac ./demomaker/glass/glass.li -q -boost
lisaac ./demomaker/fire/fire.li -q -boost
lisaac ./tiny_object/tiny_object.li -q -boost
lisaac ./tp_lisaac/redef.li -q -boost
lisaac ./tp_lisaac/action.li -q -boost
lisaac ./tp_lisaac/factorial.li -q -boost
lisaac ./tp_lisaac/my_win.li -q -boost
lisaac ./tp_lisaac/herit.li -q -boost
lisaac ./hanoi/hanoi.li -q -boost
lisaac ./test_compiler/test1.li -q -boost
lisaac ./gcd/test_gcd.li -q -boost
lisaac ./external/external_example.li -q -boost
