lisaac ./super/master.li -q -boost
lisaac ./base/pyramid.li -q -boost
lisaac ./base/pyramid2.li -q -boost
lisaac ./base/hello_world.li -q -boost
lisaac ./base/knight.li -q -boost
lisaac ./hanoi/hanoi.li -q -boost
lisaac ./book/viewer.li -q -boost
lisaac ./glass/glass.li -q -boost
lisaac ./slot/master.li -q -boost
lisaac ./gcd/test_gcd.li -q -boost
lisaac ./tiny_object/tiny_object.li -q -boost
lisaac ./calc/calc.li -q -boost
lisaac ./su_doku/su_doku.li -q -boost
lisaac ./rotozoom/rotozoom.li -q -boost
lisaac ./shootout/spectral_norm/spectral_norm.li -q -boost
lisaac ./shootout/sum_file/sum_file.li -q -boost
lisaac ./shootout/nbody/nbody.li -q -boost
lisaac ./shootout/acgt/acgt.li -q -boost
lisaac ./shootout/fannkuch/fannkuch.li -q -boost
lisaac ./shootout/binary_trees/binary_trees.li -q -boost
lisaac ./shootout/thread-ring/threadring.li -q -boost
lisaac ./shootout/chameneos_redux/chameneos_redux.li -q -boost
lisaac ./shootout/fasta/fasta.li -q -boost
lisaac ./shootout/startup/startup.li -q -boost
lisaac ./shootout/mandelbrot/version-xav/mandelbrot.li -q -boost
lisaac ./shootout/mandelbrot/mandelbrot.li -q -boost
lisaac ./shootout/mandelbrot/mandelbrot2.li -q -boost
lisaac ./shootout/mandelbrot/old/mandelbrot.li -q -boost
lisaac ./shootout/nsieve/nsieve.li -q -boost
lisaac ./shootout/reverse_complement/reverse_complement.li -q -boost
lisaac ./shootout/recursive/recursive.li -q -boost
lisaac ./shootout/nbody3/nbody.li -q -boost
lisaac ./shootout/meteor_contest/meteor_contest.li -q -boost
lisaac ./shootout/nsieve-bits/nsieve_bits.li -q -boost
lisaac ./shootout/k_nucleotide/knucleotide.li -q -boost
lisaac ./shootout/k_nucleotide/other/knucleotide.li -q -boost
lisaac ./shootout/partial_sums/partial_sums.li -q -boost
lisaac ./shootout/regex-dna/regexdna.li -q -boost
lisaac ./gui/gravity/gravity.li -q -boost
lisaac ./gui/draw/example.li -q -boost
lisaac ./gui/clock/clock_view.li -q -boost
lisaac ./gui/desktop/desktop.li -q -boost
lisaac ./gui/desktop/monitor.li -q -boost
lisaac ./gui/viewer/viewer.li -q -boost
lisaac ./gui/about/about.li -q -boost
lisaac ./gui/msn/msn.li -q -boost
lisaac ./gui/transparent/test_trans.li -q -boost
lisaac ./gui/mpg2/mpeg2dec.li -q -boost
lisaac ./gui/freetype/view.li -q -boost
lisaac ./gui/calculator/calculator.li -q -boost
lisaac ./gui/hello.li -q -boost
lisaac ./gui/predict_size/essai.li -q -boost
lisaac ./agent/example.li -q -boost
lisaac ./external/external_example.li -q -boost
lisaac ./external/struct_c.li -q -boost
lisaac ./tp_lisaac/redef.li -q -boost
lisaac ./tp_lisaac/factorial.li -q -boost
lisaac ./tp_lisaac/my_win.li -q -boost
lisaac ./tp_lisaac/herit.li -q -boost
lisaac ./tp_lisaac/action_block.li -q -boost
lisaac ./chess/chess.li -q -boost
lisaac ./tree/master.li -q -boost
lisaac ./fouronline/fouronline.li -q -boost
lisaac ./gl_test/my_scene6.li -q -boost
lisaac ./gl_test/my_scene5.li -q -boost
lisaac ./gl_test/my_scene2.li -q -boost
lisaac ./gl_test/my_scene4.li -q -boost
lisaac ./gl_test/my_scene3.li -q -boost
lisaac ./gl_test/framework_test.li -q -boost
lisaac ./gl_test/my_scene7.li -q -boost
lisaac ./gl_test/my_scene9.li -q -boost
lisaac ./gl_test/my_scene1.li -q -boost
lisaac ./gl_test/my_scene11.li -q -boost
lisaac ./gl_test/my_scene8.li -q -boost
lisaac ./gl_test/my_scene10.li -q -boost
lisaac ./shell/shell.li -q -boost
lisaac ./bench/bench.li -q -boost
lisaac ./bottles/bottles.li -q -boost
lisaac ./fire/fire.li -q -boost
lisaac ./tetris/tetris.li -q -boost
lisaac ./block/master.li -q -boost
lisaac ./cube/cube.li -q -boost
