// ANSI C code generated by Lisaac compiler (www.isaacOS.com) //

/*
 * EXTERNAL
 */

#include <time.h> /* SYSTEM */
#include <stdio.h>
  
// Hardware 'print_char'
int print_char(char car)
{
  fputc(car,stdout);
}

// Hardware 'exit'
int die_with_code(int code)
{
  exit(code);
}

 /* SYSTEM_IO */

/*
 * STRING CONSTANT
 */

signed char *__string_0="/.bashrc";
signed char *__string_1="Unix - bash";
signed char *__string_2="\n# **** LISAAC COMPILER ****\n";
signed char *__string_3="export LISAAC=";
signed char *__string_4="\nexport PATH=";
signed char *__string_5="/bin:$PATH\n\n";
signed char *__string_6="/.cshrc";
signed char *__string_7="Unix - tcsh";
signed char *__string_8="setenv LISAAC ";
signed char *__string_9="\nset path=(";
signed char *__string_10="/bin $path)\n\n";
signed char *__string_11="C:\\autoexec.bat";
signed char *__string_12="Windows - DOS";
signed char *__string_13="\r\nREM **** LISAAC COMPILER ****\r\n";
signed char *__string_14="set LISAAC=";
signed char *__string_15="\r\nset path=";
signed char *__string_16="\\bin;%path%\r\n\r\n";
signed char *__string_17="Unknown";
signed char *__string_18="\n;; **** LISAAC MODE ****\n";
signed char *__string_19="(setq load-path (cons \"";
signed char *__string_20="/emacs/\" load-path))\n";
signed char *__string_21="(add-to-list 'auto-mode-alist '(\"\\\\.li\\\\'\" . lisaac-mode))\n(autoload 'lisaac-mode \"lisaac-mode\" \"Major mode for Lisaac Programs\" t)\n\n";
signed char *__string_22="\t\t================================\n\t\t= Auto-Install Lisaac Compiler =\n\t\t================================\n\n";
signed char *__string_23="HOME";
signed char *__string_24="SHELL";
signed char *__string_25="Detection system.";
signed char *__string_26="bash";
signed char *__string_27="tcsh";
signed char *__string_28="  System detect: ";
signed char *__string_29="path.li";
signed char *__string_30="  + target";
signed char *__string_31="  + target := WINDOWS;\n";
signed char *__string_32="\n  Note: You can to compile just for DOS with `+ target := DOS;' \n        or `-t dos' option for lisaac command.\n";
signed char *__string_33="  + target := UNIX;\n";
signed char *__string_34="Installation of environment variables.";
signed char *__string_35="  Auto-install fail !\n  You have to change your environment variables as following: \n    set LISAAC=";
signed char *__string_36="\n    set path=";
signed char *__string_37="\\bin;%path%\n\n";
signed char *__string_38="Installation of `lisaac-mode' for Emacs.";
signed char *__string_39="  Do you want to install the `lisaac-mode' for Emacs editor ? (y/n)";
signed char *__string_40="  Not install `lisaac-mode' for Emacs editor.\n\n";
signed char *__string_41="/.emacs";
signed char *__string_42="Compilation of Lisaac compiler.";
signed char *__string_43="  Have you got GCC version 4.0 or greater ? (y/n)\n";
signed char *__string_44="  (type `gcc --version' for information)\n";
signed char *__string_45="gcc -O2 bin/lisaac.c -o bin/lisaac.exe";
signed char *__string_46="gcc -O2 bin/lisaac.c -o bin/lisaac";
signed char *__string_47="\n  NOTE : Sorry, with GCC v.4.0 or greater, we have a problem (when -O3 gcc option)\n  and a lot of `warning' are display...\n\n";
signed char *__string_48="gcc -O3 bin/lisaac.c -o bin/lisaac.exe";
signed char *__string_49="gcc -O3 bin/lisaac.c -o bin/lisaac";
signed char *__string_50="\n  NOTE : If you want, you can update `path.li' with -O3 option for GCC.\n\n";
signed char *__string_51="  Execute command `";
signed char *__string_52="' (please wait ...)\n";
signed char *__string_53="  Auto-install fail !\n  You want to compile a `bin/lisaac.c' file.\n";
signed char *__string_54="Welcome to the Lisaac World !";
signed char *__string_55="  Installation successfull.\n  Run `lisaac' to compile.\n  Note: You'll have to reboot or reloaded environnement\n        to acknowledge the changes.\n";
signed char *__string_56="Step ";
signed char *__string_57=" : ";
signed char *__string_58="=";
signed char *__string_59="  A `";
signed char *__string_60="' file has no need to change. Current version is:\n";
signed char *__string_61="' file has been updated. Old value is:\n";
signed char *__string_62="  New value is:\n";
signed char *__string_63="' file has been updated with:\n";
signed char *__string_64="' file has been created with:\n";
signed char *__string_65="Not create file!";
signed char *__string_66="Error: ";

/*
 * STRUCT
 */

// Generic Object
struct ___OBJ {
  unsigned long __id;
};

// ABSTRACT_STRING
struct __ABSTRACT_STRING {
  signed char *storage__IP;
  signed long count__JP;
};

// STRING_CONSTANT
struct __STRING_CONSTANT {
  struct __ABSTRACT_STRING parent_abstract_string__3H;
};

// STRING
struct __STRING {
  struct __ABSTRACT_STRING parent_abstract_string__HM;
  signed long capacity__JM;
};

// MEM_BLOCK
struct __MEM_BLOCK {
  unsigned long size_and_flags__5U 	__attribute__ ((packed));
  void *prev__6U 	__attribute__ ((packed));
  void *prev_same__7U 	__attribute__ ((packed));
  void *next_same__8U 	__attribute__ ((packed));
  unsigned short small_size__9U 	__attribute__ ((packed));
  unsigned short first_free__AV 	__attribute__ ((packed));
} 	__attribute__ ((packed));


/*
 * GLOBAL
 */

// NULL
#ifndef NULL
#define NULL ((void *)0)
#endif
// CHARACTER
signed long pointer_size__OD;
// TRUE
#define TRUE 1
// FALSE
#define FALSE 0
// ABSTRACT_STRING
signed long lower__KP;
struct __ABSTRACT_STRING ABSTRACT_STRING__;
#define ABSTRACT_STRING (&ABSTRACT_STRING__)
// STRING_CONSTANT
struct __STRING_CONSTANT STRING_CONSTANT__;
#define STRING_CONSTANT (&STRING_CONSTANT__)
// INSTALL_LISAAC
signed long step_count__YK;
signed long step_max__ZK;
void *path_current__2K;
void *path_home__3K;
void *shell__4K;
void *system__5K;
void *system_unix_bash__6K;
void *system_unix_tcsh__7K;
void *system_windows__8K;
void *system_unknown__9K;
void *file_bashrc__AL;
void *file_cshrc__BL;
void *file_autoexec__CL;
void *comment_windows__DL;
void *comment_unix__EL;
void *lisaac_bash__FL;
void *lisaac_tcsh__GL;
void *lisaac_windows__HL;
void *path_bash__IL;
void *path_tcsh__JL;
void *path_windows__KL;
void *path_bash_next__LL;
void *path_tcsh_next__ML;
void *path_windows_next__NL;
void *lisaac_mode_comment__PL;
void *lisaac_mode_path__QL;
void *lisaac_mode_path_end__RL;
void *lisaac_mode__SL;
void *string_tmp__VL;
// STRING
struct __STRING STRING__;
#define STRING (&STRING__)
// OBJECT
signed long exit_failure_code__IR;
// MEMORY
void **small_fat__BS;
void *first_free__CS;
unsigned long begin_memory__DS;
unsigned long end_memory__ES;
unsigned long capacity__FS;
void *last_block__GS;
// MEM_BLOCK
unsigned long object_size__GV;
struct __MEM_BLOCK MEM_BLOCK__;
#define MEM_BLOCK (&MEM_BLOCK__)
// SYSTEM
unsigned long get_begin_memory__5Y;
unsigned long get_capacity_memory__6Y;
// STD_INPUT
signed char memory__WBB;

/*
 * PROTOTYPE
 */

int main(signed long ___count_arg__XL,signed char **___list_arg__YL);
static unsigned long realloc_c__61(unsigned long beg__81,unsigned long nb__91);
static void *create__H3D(int needed_capacity__J3D);
static void *new_intern__6O(signed char *p__8O,signed long nb_char__9O);
static void print__3XD(void *self__4XD);
static signed char *to_external__5FE(void *self__6FE);
static void from_external__5UF(void *self__6UF,signed char *p__7UF);
static void *create__FZF(signed long needed_capacity__HZF);
static void copy__H2F(void *self__I2F,void *other__J2F);
static void *get_environment_variable__97F(void *variable__B8F);
static void title__DDG(void *str__FDG);
static void *create_from_string__B2G(void *str__D2G);
static signed long first_substring_index__R5G(void *self__S5G,void *other__T5G);
static void append__MDH(void *self__NDH,void *other__ODH);
static void  *open_read__AMH(void *n__CMH);
static void update__idf__with__2RH(void *file__4RH,void *id__5RH,void *new_text__6RH);
static void print__BTG(void *self__CTG);
static void *create_from_string__U5I(void *str__W5I);
static void append__95I(void *self__A6I,void *other__B6I);
static void update__idf__with__B9I(void *file__D9I,void *id__E9I,void *new_text__F9I);
static signed char read_character__DSJ();
static void *to_string__A9F(void *self__B9F);
static void print_nbx__42(unsigned long n__62);
static void *clone__R3D();
static signed char *calloc__37D(signed long nb_elements__57D);
static void  *allocation__JU(signed long nb__LU);
static void copy__from__size__2ED(void  *dst__4ED,void  *src__5ED,signed long n__6ED);
static void add_last__1KE(void *self__2KE,signed char ch__3KE);
static void copy_from__until__K4F(signed char *self__L4F,signed char *model__M4F,signed long upper__N4F);
static void print__GEG(signed long self__HEG);
static void copy__M2G(void *self__N2G,void *other__O2G);
static signed char *realloc__with__3ME(signed char *self__4ME,signed long old_nb_elts__5ME,signed long new_nb_elts__6ME);
static void copy__to__until__DGH(signed char *self__EGH,signed char *src__FGH,signed long dest__GGH,signed long src_capacity__HGH);
static void copy__JMH(void *self__KMH,void *other__LMH);
static signed long file_size__DUH(void  *p__FUH);
static void *create__QUH(unsigned long needed_capacity__SUH);
static void read__in__size__VYH(void  *f__XYH,void *buf__YYH,signed long sz__ZYH);
static signed long fast_occurrences__until__A0H(signed char *self__B0H,signed long upper__D0H);
static void remove__J5H(void *self__K5H,signed long index__L5H);
static char fast_memcmp__until__HGI(signed char *self__IGI,signed char *other__JGI,signed long capacity__KGI);
static void resize__KNI(void *self__LNI,signed long new_count__MNI);
static void move__to__by__FTI(signed char *self__GTI,signed long lower__HTI,signed long upper__ITI,signed long offset__JTI);
static char make_file__Y0I(void *new_path__00I);
static void error__X1I(void *st__Z1I);
static void write__with__size__D3I(void  *f__F3I,void *buf__G3I,signed long sz__H3I);
static void *to_string__QOJ(void *self__ROJ);
static signed char code__69(signed char self__79);
static void make__9PB(void *self__AQB,unsigned long siz__BQB);
static char is_small_busy__9VC(void *self__EVC,unsigned long sz__FVC);
static unsigned long size__52B(void *self__62B);
static char __infix_less__J3B(unsigned long self__K3B,unsigned long other__L3B);
static void *get_next__WHC(void *block__YHC);
static char is_free__KAF(void *self__67B);
static void clear__to__FQF(signed char *self__GQF,signed long lower__HQF,signed long upper__IQF);
static unsigned long to_uinteger__UVC(unsigned short self__VUC);

/*
 * SOURCE CODE
 */

void copy_object(void *dst,void *src,int n)
{ int cpt,i;                               
  unsigned long *dst_l, *src_l;            
  unsigned char *dst_b, *src_b;            
                                           
  cpt = n >> 2;                            
  dst_l = (unsigned long *)dst;            
  src_l = (unsigned long *)src;            
  for (i=0 ; i<cpt ; i++) {                
    *dst_l = *src_l;                       
    dst_l++;                               
    src_l++;                               
  };                                       
  cpt = n & 3;                             
  dst_b = (unsigned char *)src_l;          
  src_b = (unsigned char *)dst_l;          
  for (i=0 ; i<cpt ; i++) {                
    *dst_b = *src_b;                       
    dst_b++;                               
    src_b++;                               
  };                                       
}                                          
//////////// MAIN ////////////
int main(signed long ___count_arg__XL,signed char **___list_arg__YL)
// INSTALL_LISAAC - ANSI code -
{
  void *self__40,*new_text__PZG,*file__QZG,*comment__RZG,*lisaac__SZG;
  void *path__TZG,*path_next__UZG,*file_name__NQJ,*new_text__OQJ;
  void *cmd__KVJ;
  unsigned long ___tmp__90,___tmp__PPB;
  void  *std_file__OZG;
  signed char char__MQJ,char__LVJ,*cwd__5L;
  signed long ___tmp__WZD,___tmp__09D,___tmp__JWG,___tmp__I2I;
  char ___tmp__8ZG;
  ___tmp__90=((unsigned long )(( 26843546)));
  ___tmp__PPB=((unsigned long )(( 16)));
  ___tmp__WZD=((signed long )(( 1)));
  ___tmp__09D=((signed long )(( 1)));
  ___tmp__JWG=((signed long )(( 5)));
  ___tmp__I2I=((signed long )(( 1)));
  capacity__FS= 0;
  get_capacity_memory__6Y=___tmp__90;
  get_begin_memory__5Y=realloc_c__61(((unsigned long )(( 0))),get_capacity_memory__6Y);
  begin_memory__DS= 0;
  end_memory__ES= 0;
  small_fat__BS=NULL;
  last_block__GS=NULL;
  object_size__GV=___tmp__PPB;
  MEM_BLOCK__.size_and_flags__5U= 0;
  MEM_BLOCK__.next_same__8U=NULL;
  MEM_BLOCK__.prev_same__7U=NULL;
  MEM_BLOCK__.prev__6U=NULL;
  first_free__CS=NULL;
  MEM_BLOCK__.small_size__9U= 0;
  MEM_BLOCK__.first_free__AV= 0;
  ABSTRACT_STRING__.storage__IP=NULL;
  STRING_CONSTANT__.parent_abstract_string__3H.storage__IP=ABSTRACT_STRING__.storage__IP;
  STRING__.parent_abstract_string__HM.storage__IP=ABSTRACT_STRING__.storage__IP;
  ABSTRACT_STRING__.count__JP= 0;
  STRING_CONSTANT__.parent_abstract_string__3H.count__JP=ABSTRACT_STRING__.count__JP;
  STRING__.parent_abstract_string__HM.count__JP=ABSTRACT_STRING__.count__JP;
  lower__KP=___tmp__WZD;
  STRING__.capacity__JM= 0;
  pointer_size__OD=___tmp__09D;
  string_tmp__VL=create__H3D( 256);
  path_current__2K=NULL;
  path_home__3K=NULL;
  shell__4K=NULL;
  step_count__YK= 0;
  step_max__ZK=___tmp__JWG;
  file_bashrc__AL=new_intern__6O(__string_0, 8);
  system_unix_bash__6K=new_intern__6O(__string_1, 11);
  system__5K=NULL;
  comment_unix__EL=new_intern__6O(__string_2, 29);
  lisaac_bash__FL=new_intern__6O(__string_3, 14);
  path_bash__IL=new_intern__6O(__string_4, 13);
  path_bash_next__LL=new_intern__6O(__string_5, 12);
  file_cshrc__BL=new_intern__6O(__string_6, 7);
  system_unix_tcsh__7K=new_intern__6O(__string_7, 11);
  lisaac_tcsh__GL=new_intern__6O(__string_8, 14);
  path_tcsh__JL=new_intern__6O(__string_9, 11);
  path_tcsh_next__ML=new_intern__6O(__string_10, 13);
  file_autoexec__CL=new_intern__6O(__string_11, 15);
  system_windows__8K=new_intern__6O(__string_12, 13);
  comment_windows__DL=new_intern__6O(__string_13, 33);
  lisaac_windows__HL=new_intern__6O(__string_14, 11);
  path_windows__KL=new_intern__6O(__string_15, 11);
  path_windows_next__NL=new_intern__6O(__string_16, 15);
  system_unknown__9K=new_intern__6O(__string_17, 7);
  exit_failure_code__IR=___tmp__I2I;
  memory__WBB='\0';
  lisaac_mode_comment__PL=new_intern__6O(__string_18, 26);
  lisaac_mode_path__QL=new_intern__6O(__string_19, 23);
  lisaac_mode_path_end__RL=new_intern__6O(__string_20, 21);
  lisaac_mode__SL=new_intern__6O(__string_21, 133);
  cwd__5L=NULL;
  print__3XD(new_intern__6O(__string_22, 106));
  ((struct __STRING *)string_tmp__VL)->parent_abstract_string__HM.count__JP=((signed long )(( 0)));
  cwd__5L=to_external__5FE(string_tmp__VL);
  getcwd((cwd__5L),255);
  from_external__5UF(string_tmp__VL,cwd__5L);
  path_current__2K=create__FZF(((struct __STRING *)string_tmp__VL)->parent_abstract_string__HM.count__JP);
  copy__H2F(path_current__2K,string_tmp__VL);
  path_home__3K=get_environment_variable__97F(new_intern__6O(__string_23, 4));
  shell__4K=get_environment_variable__97F(new_intern__6O(__string_24, 5));
  title__DDG(new_intern__6O(__string_25, 17));
  new_text__PZG=NULL;
  std_file__OZG=NULL;
  path_next__UZG=NULL;
  path__TZG=NULL;
  lisaac__SZG=NULL;
  comment__RZG=NULL;
  file__QZG=NULL;
  file__QZG=create_from_string__B2G(path_home__3K);
  if ((first_substring_index__R5G(shell__4K,new_intern__6O(__string_26, 4))!= 0)) {
    append__MDH(file__QZG,file_bashrc__AL);
    system__5K=system_unix_bash__6K;
    comment__RZG=comment_unix__EL;
    lisaac__SZG=lisaac_bash__FL;
    path__TZG=path_bash__IL;
    path_next__UZG=path_bash_next__LL;
    ___tmp__8ZG=TRUE;
  } else {
    ___tmp__8ZG=FALSE;
  };
  if (___tmp__8ZG) {
  } else {
    if ((first_substring_index__R5G(shell__4K,new_intern__6O(__string_27, 4))!= 0)) {
      append__MDH(file__QZG,file_cshrc__BL);
      system__5K=system_unix_tcsh__7K;
      comment__RZG=comment_unix__EL;
      lisaac__SZG=lisaac_tcsh__GL;
      path__TZG=path_tcsh__JL;
      path_next__UZG=path_tcsh_next__ML;
    } else {
      std_file__OZG=open_read__AMH(file_autoexec__CL);
      if ((std_file__OZG!=NULL)) {
        fclose((FILE*)((std_file__OZG)));
        append__MDH(file__QZG,file_autoexec__CL);
        system__5K=system_windows__8K;
        comment__RZG=comment_windows__DL;
        lisaac__SZG=lisaac_windows__HL;
        path__TZG=path_windows__KL;
        path_next__UZG=path_windows_next__NL;
      } else {
        system__5K=system_unknown__9K;
      };
    };
  };
  print__3XD(new_intern__6O(__string_28, 17));
  print__3XD(system__5K);
  fputc((int)('\n'),stdout);
  if ((system__5K!=system_unknown__9K)) {
    if ((system__5K==system_windows__8K)) {
      update__idf__with__2RH(new_intern__6O(__string_29, 7),new_intern__6O(__string_30, 10),new_intern__6O(__string_31, 23));
      print__3XD(new_intern__6O(__string_32, 113));
    } else {
      update__idf__with__2RH(new_intern__6O(__string_29, 7),new_intern__6O(__string_30, 10),new_intern__6O(__string_33, 20));
    };
  };
  fputc((int)('\n'),stdout);
  title__DDG(new_intern__6O(__string_34, 38));
  if ((system__5K==system_unknown__9K)) {
    print__3XD(new_intern__6O(__string_35, 100));
    print__BTG(path_current__2K);
    print__3XD(new_intern__6O(__string_36, 14));
    print__BTG(path_current__2K);
    print__3XD(new_intern__6O(__string_37, 13));
  } else {
    new_text__PZG=create_from_string__U5I(comment__RZG);
    append__MDH(new_text__PZG,lisaac__SZG);
    append__95I(new_text__PZG,path_current__2K);
    append__MDH(new_text__PZG,path__TZG);
    append__95I(new_text__PZG,path_current__2K);
    append__MDH(new_text__PZG,path_next__UZG);
    update__idf__with__B9I(file__QZG,comment__RZG,new_text__PZG);
  };
  title__DDG(new_intern__6O(__string_38, 40));
  new_text__OQJ=NULL;
  file_name__NQJ=NULL;
  char__MQJ='\0';
  print__3XD(new_intern__6O(__string_39, 67));
  while (((char__MQJ!='y') && (char__MQJ!='n'))) {
    char__MQJ=read_character__DSJ();
  };
  if ((char__MQJ=='n')) {
    print__3XD(new_intern__6O(__string_40, 47));
  } else {
    file_name__NQJ=create_from_string__B2G(path_home__3K);
    append__MDH(file_name__NQJ,new_intern__6O(__string_41, 7));
    new_text__OQJ=create_from_string__U5I(lisaac_mode_comment__PL);
    append__MDH(new_text__OQJ,lisaac_mode_path__QL);
    append__95I(new_text__OQJ,path_current__2K);
    append__MDH(new_text__OQJ,lisaac_mode_path_end__RL);
    append__MDH(new_text__OQJ,lisaac_mode__SL);
    update__idf__with__B9I(file_name__NQJ,lisaac_mode_comment__PL,new_text__OQJ);
  };
  title__DDG(new_intern__6O(__string_42, 31));
  cmd__KVJ=NULL;
  char__LVJ='\0';
  print__3XD(new_intern__6O(__string_43, 50));
  print__3XD(new_intern__6O(__string_44, 41));
  while (((char__LVJ!='y') && (char__LVJ!='n'))) {
    char__LVJ=read_character__DSJ();
  };
  if ((char__LVJ=='y')) {
    if ((system__5K==system_windows__8K)) {
      cmd__KVJ=new_intern__6O(__string_45, 38);
    } else {
      cmd__KVJ=new_intern__6O(__string_46, 34);
    };
    print__3XD(new_intern__6O(__string_47, 125));
  } else {
    if ((system__5K==system_windows__8K)) {
      cmd__KVJ=new_intern__6O(__string_48, 38);
    } else {
      cmd__KVJ=new_intern__6O(__string_49, 34);
    };
    print__3XD(new_intern__6O(__string_50, 74));
  };
  print__3XD(new_intern__6O(__string_51, 19));
  print__3XD(cmd__KVJ);
  print__3XD(new_intern__6O(__string_52, 20));
  if ((((signed long )(system(((char*)((to_external__5FE(to_string__A9F(cmd__KVJ))))))))!= 0)) {
    print__3XD(new_intern__6O(__string_53, 67));
  };
  fputc((int)('\n'),stdout);
  title__DDG(new_intern__6O(__string_54, 29));
  print__3XD(new_intern__6O(__string_55, 147));
}

static unsigned long realloc_c__61(unsigned long beg__81,unsigned long nb__91)
// SYSTEM realloc_c(SYSTEM,UINTEGER,UINTEGER)
{
  unsigned long result__A2;
  result__A2= 0;
  result__A2=((unsigned long )((unsigned long)realloc((void *)(beg__81),(nb__91)+15)));
  if (((beg__81!= 0) && (result__A2!=beg__81))) {
    print_nbx__42(beg__81);
    fputc((int)('\n'),stdout);
    print_nbx__42(result__A2);
    fputc((int)('\n'),stdout);
    exit((((signed long )(( 1)))));
  };
  return(result__A2);
}

static void *create__H3D(int needed_capacity__J3D)
// STRING create(STRING,NUMERIC)
{
  void *result__K3D,*self__X7D,*self__25D;
  int needed_capacity__35D;
  signed long self__NSK,other__OSK;
  result__K3D=NULL;
  result__K3D=clone__R3D();
  self__25D=result__K3D;
  needed_capacity__35D=needed_capacity__J3D;
  if ((needed_capacity__35D> 0)) {
    self__NSK=((struct __STRING *)self__25D)->capacity__JM;
    other__OSK=((signed long )((needed_capacity__35D)));
    if ((! ((self__NSK>other__OSK) | (self__NSK==other__OSK)))) {
      self__X7D=self__25D;
      ((struct __STRING *)self__X7D)->parent_abstract_string__HM.storage__IP=calloc__37D(((signed long )((needed_capacity__35D))));
      ((struct __STRING *)self__X7D)->capacity__JM=((signed long )((needed_capacity__35D)));
    };
  };
  ((struct __STRING *)self__25D)->parent_abstract_string__HM.count__JP=((signed long )(( 0)));
  return(result__K3D);
}

static void *new_intern__6O(signed char *p__8O,signed long nb_char__9O)
// STRING_CONSTANT new_intern(STRING_CONSTANT,NATIVE_ARRAY,INTEGER)
{
  void *result__AP,*result__1R,*self__VXD;
  void  *ptr__2R;
  signed long sz__3R;
  result__AP=NULL;
  ptr__2R=NULL;
  result__1R=NULL;
  sz__3R= 0;
  sz__3R=sizeof(struct __STRING_CONSTANT);
  if ((sz__3R== 0)) {
    result__1R=STRING_CONSTANT;
  } else {
    ptr__2R=allocation__JU(sz__3R);
    copy__from__size__2ED(ptr__2R,((void  *)((STRING_CONSTANT))),sz__3R);
    result__1R=((void *)((ptr__2R)));
  };
  result__AP=result__1R;
  self__VXD=result__AP;
  ((struct __STRING_CONSTANT *)self__VXD)->parent_abstract_string__3H.storage__IP=p__8O;
  ((struct __STRING_CONSTANT *)self__VXD)->parent_abstract_string__3H.count__JP=nb_char__9O;
  return(result__AP);
}

static void print__3XD(void *self__4XD)
// ABSTRACT_STRING print(STRING_CONSTANT)
{
  void *s__CYD;
  signed long self__4ZD,limit_up__5ZD;
  s__CYD=self__4XD;
  self__4ZD=lower__KP;
  limit_up__5ZD=((struct __STRING_CONSTANT *)s__CYD)->parent_abstract_string__3H.count__JP;
  while ((! (self__4ZD>limit_up__5ZD))) {
    fputc((int)(((struct __STRING_CONSTANT *)s__CYD)->parent_abstract_string__3H.storage__IP[(self__4ZD-((signed long )(( 1))))]),stdout);
    self__4ZD=(self__4ZD-(((signed long )(( 0)))-((signed long )(( 1)))));
  };
}

static signed char *to_external__5FE(void *self__6FE)
// STRING to_external(STRING)
{
  signed char *result__8FE;
  result__8FE=NULL;
  if ((((struct __STRING *)self__6FE)->capacity__JM>((struct __STRING *)self__6FE)->parent_abstract_string__HM.count__JP)) {
    ((struct __STRING *)self__6FE)->parent_abstract_string__HM.count__JP=(((struct __STRING *)self__6FE)->parent_abstract_string__HM.count__JP-(((signed long )(( 0)))-((signed long )(( 1)))));
    if ((((struct __STRING *)self__6FE)->parent_abstract_string__HM.storage__IP[(((struct __STRING *)self__6FE)->parent_abstract_string__HM.count__JP-((signed long )(( 1))))]!='\0')) {
      ((struct __STRING *)self__6FE)->parent_abstract_string__HM.storage__IP[(((struct __STRING *)self__6FE)->parent_abstract_string__HM.count__JP-((signed long )(( 1))))]='\0';
    };
  } else {
    add_last__1KE(self__6FE,'\0');
  };
  ((struct __STRING *)self__6FE)->parent_abstract_string__HM.count__JP=(((struct __STRING *)self__6FE)->parent_abstract_string__HM.count__JP-((signed long )(( 1))));
  result__8FE=((struct __STRING *)self__6FE)->parent_abstract_string__HM.storage__IP;
  return(result__8FE);
}

static void from_external__5UF(void *self__6UF,signed char *p__7UF)
// STRING from_external(STRING,NATIVE_ARRAY)
{
  void *self__TXF;
  ((struct __STRING *)self__6UF)->parent_abstract_string__HM.count__JP=((signed long )(( 0)));
  while ((! (p__7UF[((struct __STRING *)self__6UF)->parent_abstract_string__HM.count__JP]=='\0'))) {
    ((struct __STRING *)self__6UF)->parent_abstract_string__HM.count__JP=(((struct __STRING *)self__6UF)->parent_abstract_string__HM.count__JP-(((signed long )(( 0)))-((signed long )(( 1)))));
  };
  if ((((struct __STRING *)self__6UF)->parent_abstract_string__HM.storage__IP!=p__7UF)) {
    self__TXF=self__6UF;
    ((struct __STRING *)self__TXF)->parent_abstract_string__HM.storage__IP=p__7UF;
    ((struct __STRING *)self__TXF)->capacity__JM=(((struct __STRING *)self__6UF)->parent_abstract_string__HM.count__JP-(((signed long )(( 0)))-((signed long )(( 1)))));
  };
}

static void *create__FZF(signed long needed_capacity__HZF)
// STRING create(STRING,INTEGER)
{
  void *result__IZF,*self__U1F,*self__SZF;
  signed long needed_capacity__TZF,self__ITK,other__JTK;
  result__IZF=NULL;
  result__IZF=clone__R3D();
  self__SZF=result__IZF;
  needed_capacity__TZF=needed_capacity__HZF;
  if ((needed_capacity__TZF>((signed long )(( 0))))) {
    self__ITK=((struct __STRING *)self__SZF)->capacity__JM;
    other__JTK=needed_capacity__TZF;
    if ((! ((self__ITK>other__JTK) | (self__ITK==other__JTK)))) {
      self__U1F=self__SZF;
      ((struct __STRING *)self__U1F)->parent_abstract_string__HM.storage__IP=calloc__37D(needed_capacity__TZF);
      ((struct __STRING *)self__U1F)->capacity__JM=needed_capacity__TZF;
    };
  };
  ((struct __STRING *)self__SZF)->parent_abstract_string__HM.count__JP=((signed long )(( 0)));
  return(result__IZF);
}

static void copy__H2F(void *self__I2F,void *other__J2F)
// STRING copy(STRING,STRING)
{
  void *self__Y3F;
  signed long self__KTK,other__LTK;
  ((struct __STRING *)self__I2F)->parent_abstract_string__HM.count__JP=((struct __STRING *)other__J2F)->parent_abstract_string__HM.count__JP;
  if ((((struct __STRING *)self__I2F)->parent_abstract_string__HM.count__JP>((signed long )(( 0))))) {
    self__KTK=((struct __STRING *)self__I2F)->capacity__JM;
    other__LTK=((struct __STRING *)self__I2F)->parent_abstract_string__HM.count__JP;
    if ((! ((self__KTK>other__LTK) | (self__KTK==other__LTK)))) {
      self__Y3F=self__I2F;
      ((struct __STRING *)self__Y3F)->parent_abstract_string__HM.storage__IP=calloc__37D(((struct __STRING *)self__I2F)->parent_abstract_string__HM.count__JP);
      ((struct __STRING *)self__Y3F)->capacity__JM=((struct __STRING *)self__I2F)->parent_abstract_string__HM.count__JP;
    };
    copy_from__until__K4F(((struct __STRING *)self__I2F)->parent_abstract_string__HM.storage__IP,((struct __STRING *)other__J2F)->parent_abstract_string__HM.storage__IP,(((struct __STRING *)self__I2F)->parent_abstract_string__HM.count__JP-((signed long )(( 1)))));
  };
}

static void *get_environment_variable__97F(void *variable__B8F)
// ENVIRONMENT get_environment_variable(ENVIRONMENT,NULLxSTRING_CONSTANT)
{
  void *result__C8F;
  signed char *p__D8F;
  result__C8F=NULL;
  p__D8F=NULL;
  p__D8F=((signed char *)(getenv((char*)(to_external__5FE(to_string__A9F(variable__B8F))))));
  if ((p__D8F!=NULL)) {
    result__C8F=clone__R3D();
    from_external__5UF(result__C8F,p__D8F);
  };
  return(result__C8F);
}

static void title__DDG(void *str__FDG)
// INSTALL_LISAAC title(INSTALL_LISAAC,NULLxSTRING_CONSTANT)
{
  int limit_up__BXG,self__DYG;
  step_count__YK=(step_count__YK-(((signed long )(( 0)))-((signed long )(( 1)))));
  print__3XD(new_intern__6O(__string_56, 5));
  print__GEG(step_count__YK);
  fputc((int)('/'),stdout);
  print__GEG(step_max__ZK);
  print__3XD(new_intern__6O(__string_57, 3));
  print__3XD(str__FDG);
  fputc((int)('\n'),stdout);
  limit_up__BXG=((int )(((((struct __STRING_CONSTANT *)str__FDG)->parent_abstract_string__3H.count__JP-(((signed long )(( 0)))-((signed long )(( 11))))))));
  if ((! ( 1>limit_up__BXG))) {
    print__3XD(new_intern__6O(__string_58, 1));
    self__DYG= 2;
    while ((! (self__DYG>limit_up__BXG))) {
      print__3XD(new_intern__6O(__string_58, 1));
      self__DYG=(self__DYG- -1);
    };
  };
  fputc((int)('\n'),stdout);
}

static void *create_from_string__B2G(void *str__D2G)
// STRING create_from_string(STRING,NULLxSTRING)
{
  void *result__E2G;
  result__E2G=NULL;
  result__E2G=create__FZF(((struct __STRING *)str__D2G)->parent_abstract_string__HM.count__JP);
  copy__M2G(result__E2G,str__D2G);
  return(result__E2G);
}

static signed long first_substring_index__R5G(void *self__S5G,void *other__T5G)
// ABSTRACT_STRING first_substring_index(STRING,NULLxSTRING_CONSTANT)
{
  void *self__Q6G,*other__R6G;
  signed long ___tmp__M6G,i__T6G,s__U6G,result__V6G;
  ___tmp__M6G=((signed long )(( 1)));
  self__Q6G=self__S5G;
  other__R6G=other__T5G;
  i__T6G= 0;
  result__V6G= 0;
  s__U6G= 0;
  s__U6G=___tmp__M6G;
  while ((! ((result__V6G!= 0) || (((s__U6G-(((signed long )(( 0)))-((struct __STRING_CONSTANT *)other__R6G)->parent_abstract_string__3H.count__JP))-((signed long )(( 1))))>((struct __STRING *)self__Q6G)->parent_abstract_string__HM.count__JP)))) {
    i__T6G=((signed long )(( 1)));
    while ((! ((i__T6G>((struct __STRING_CONSTANT *)other__R6G)->parent_abstract_string__3H.count__JP) || (((struct __STRING *)self__Q6G)->parent_abstract_string__HM.storage__IP[(((s__U6G-(((signed long )(( 0)))-i__T6G))-((signed long )(( 1))))-((signed long )(( 1))))]!=((struct __STRING_CONSTANT *)other__R6G)->parent_abstract_string__3H.storage__IP[(i__T6G-((signed long )(( 1))))])))) {
      i__T6G=(i__T6G-(((signed long )(( 0)))-((signed long )(( 1)))));
    };
    if ((i__T6G>((struct __STRING_CONSTANT *)other__R6G)->parent_abstract_string__3H.count__JP)) {
      result__V6G=s__U6G;
    } else {
      s__U6G=(s__U6G-(((signed long )(( 0)))-((signed long )(( 1)))));
    };
  };
  return(result__V6G);
}

static void append__MDH(void *self__NDH,void *other__ODH)
// STRING append(STRING,NULLxSTRING_CONSTANT)
{
  signed long other_count__PDH,needed_capacity__QDH,self__AUK;
  void *self__OFH,*self__YFH;
  signed long other__BUK;
  needed_capacity__QDH= 0;
  other_count__PDH= 0;
  other_count__PDH=((struct __STRING_CONSTANT *)other__ODH)->parent_abstract_string__3H.count__JP;
  needed_capacity__QDH=(((struct __STRING *)self__NDH)->parent_abstract_string__HM.count__JP-(((signed long )(( 0)))-other_count__PDH));
  self__AUK=((struct __STRING *)self__NDH)->capacity__JM;
  other__BUK=needed_capacity__QDH;
  if ((! ((self__AUK>other__BUK) | (self__AUK==other__BUK)))) {
    if ((((struct __STRING *)self__NDH)->capacity__JM== 0)) {
      self__OFH=self__NDH;
      ((struct __STRING *)self__OFH)->capacity__JM=needed_capacity__QDH;
      ((struct __STRING *)self__OFH)->parent_abstract_string__HM.storage__IP=calloc__37D(((struct __STRING *)self__NDH)->capacity__JM);
    } else {
      self__YFH=self__NDH;
      ((struct __STRING *)self__YFH)->parent_abstract_string__HM.storage__IP=realloc__with__3ME(((struct __STRING *)self__NDH)->parent_abstract_string__HM.storage__IP,((struct __STRING *)self__NDH)->capacity__JM,needed_capacity__QDH);
      ((struct __STRING *)self__YFH)->capacity__JM=needed_capacity__QDH;
    };
  };
  copy__to__until__DGH(((struct __STRING *)self__NDH)->parent_abstract_string__HM.storage__IP,((struct __STRING_CONSTANT *)other__ODH)->parent_abstract_string__3H.storage__IP,((struct __STRING *)self__NDH)->parent_abstract_string__HM.count__JP,other_count__PDH);
  ((struct __STRING *)self__NDH)->parent_abstract_string__HM.count__JP=needed_capacity__QDH;
}

static void  *open_read__AMH(void *n__CMH)
// INSTALL_LISAAC open_read(INSTALL_LISAAC,NULLxSTRING_CONSTANT)
{
  signed char *buf__DMH;
  buf__DMH=NULL;
  copy__JMH(string_tmp__VL,n__CMH);
  buf__DMH=to_external__5FE(string_tmp__VL);
  return(((void  *)(fopen((char*)(buf__DMH),"rb"))));
}

static void update__idf__with__2RH(void *file__4RH,void *id__5RH,void *new_text__6RH)
// INSTALL_LISAAC update__idf__with(INSTALL_LISAAC,NULLxSTRING_CONSTANT,NULLxSTRING_CONSTANT,NULLxSTRING_CONSTANT)
{
  void *old_buffer__8RH,*input__9RH,*self__TZH,*self__7EI,*other__8EI;
  void *self__JLI,*s__KLI;
  int limit_up__33H,self__TCI;
  void  *std_file__ASH;
  signed char *buf__12I;
  signed long index__7RH,size_file__BSH,j__MLI,k__NLI,i__LLI;
  char result__9EI;
  old_buffer__8RH=NULL;
  index__7RH= 0;
  input__9RH=NULL;
  size_file__BSH= 0;
  std_file__ASH=NULL;
  print__3XD(new_intern__6O(__string_59, 5));
  print__3XD(file__4RH);
  std_file__ASH=open_read__AMH(file__4RH);
  if ((std_file__ASH!=NULL)) {
    size_file__BSH=file_size__DUH(std_file__ASH);
    input__9RH=create__QUH(((unsigned long )(((size_file__BSH-(((signed long )(( 0)))-((struct __STRING_CONSTANT *)new_text__6RH)->parent_abstract_string__3H.count__JP))))));
    read__in__size__VYH(std_file__ASH,input__9RH,size_file__BSH);
    fclose((FILE*)((std_file__ASH)));
    index__7RH=first_substring_index__R5G(input__9RH,id__5RH);
    if ((index__7RH!= 0)) {
      old_buffer__8RH=create__H3D( 200);
      self__TZH=new_text__6RH;
      limit_up__33H=((int )((fast_occurrences__until__A0H(((struct __STRING_CONSTANT *)self__TZH)->parent_abstract_string__3H.storage__IP,(((struct __STRING_CONSTANT *)self__TZH)->parent_abstract_string__3H.count__JP-((signed long )(( 1))))))));
      if ((! ( 1>limit_up__33H))) {
        while ((((struct __STRING *)input__9RH)->parent_abstract_string__HM.storage__IP[(index__7RH-((signed long )(( 1))))]!='\n')) {
          add_last__1KE(old_buffer__8RH,((struct __STRING *)input__9RH)->parent_abstract_string__HM.storage__IP[(index__7RH-((signed long )(( 1))))]);
          remove__J5H(input__9RH,index__7RH);
        };
        add_last__1KE(old_buffer__8RH,((struct __STRING *)input__9RH)->parent_abstract_string__HM.storage__IP[(index__7RH-((signed long )(( 1))))]);
        remove__J5H(input__9RH,index__7RH);
        self__TCI= 2;
        while ((! (self__TCI>limit_up__33H))) {
          while ((((struct __STRING *)input__9RH)->parent_abstract_string__HM.storage__IP[(index__7RH-((signed long )(( 1))))]!='\n')) {
            add_last__1KE(old_buffer__8RH,((struct __STRING *)input__9RH)->parent_abstract_string__HM.storage__IP[(index__7RH-((signed long )(( 1))))]);
            remove__J5H(input__9RH,index__7RH);
          };
          add_last__1KE(old_buffer__8RH,((struct __STRING *)input__9RH)->parent_abstract_string__HM.storage__IP[(index__7RH-((signed long )(( 1))))]);
          remove__J5H(input__9RH,index__7RH);
          self__TCI=(self__TCI- -1);
        };
      };
      self__7EI=old_buffer__8RH;
      other__8EI=new_text__6RH;
      result__9EI=FALSE;
      if ((((struct __STRING *)self__7EI)->parent_abstract_string__HM.count__JP==((struct __STRING_CONSTANT *)other__8EI)->parent_abstract_string__3H.count__JP)) {
        result__9EI=fast_memcmp__until__HGI(((struct __STRING *)self__7EI)->parent_abstract_string__HM.storage__IP,((struct __STRING_CONSTANT *)other__8EI)->parent_abstract_string__3H.storage__IP,((struct __STRING *)self__7EI)->parent_abstract_string__HM.count__JP);
      };
      if (result__9EI) {
        print__3XD(new_intern__6O(__string_60, 50));
      } else {
        print__3XD(new_intern__6O(__string_61, 39));
        print__BTG(old_buffer__8RH);
        print__3XD(new_intern__6O(__string_62, 16));
      };
    } else {
      print__3XD(new_intern__6O(__string_63, 30));
      index__7RH=(((struct __STRING *)input__9RH)->parent_abstract_string__HM.count__JP-(((signed long )(( 0)))-((signed long )(( 1)))));
    };
    print__3XD(new_text__6RH);
    self__JLI=input__9RH;
    s__KLI=new_text__6RH;
    i__LLI=index__7RH;
    k__NLI= 0;
    j__MLI= 0;
    j__MLI=((struct __STRING *)self__JLI)->parent_abstract_string__HM.count__JP;
    k__NLI=((struct __STRING_CONSTANT *)s__KLI)->parent_abstract_string__3H.count__JP;
    resize__KNI(self__JLI,(j__MLI-(((signed long )(( 0)))-k__NLI)));
    if ((! (i__LLI>j__MLI))) {
      move__to__by__FTI(((struct __STRING *)self__JLI)->parent_abstract_string__HM.storage__IP,(i__LLI-((signed long )(( 1)))),(j__MLI-((signed long )(( 1)))),k__NLI);
    };
    copy__to__until__DGH(((struct __STRING *)self__JLI)->parent_abstract_string__HM.storage__IP,((struct __STRING_CONSTANT *)s__KLI)->parent_abstract_string__3H.storage__IP,(i__LLI-((signed long )(( 1)))),k__NLI);
  } else {
    print__3XD(new_intern__6O(__string_64, 30));
    print__3XD(new_text__6RH);
    input__9RH=to_string__A9F(new_text__6RH);
    if ((! make_file__Y0I(to_string__A9F(file__4RH)))) {
      error__X1I(new_intern__6O(__string_65, 16));
    };
  };
  buf__12I=NULL;
  copy__JMH(string_tmp__VL,file__4RH);
  buf__12I=to_external__5FE(string_tmp__VL);
  std_file__ASH=((void  *)(fopen((char*)(buf__12I),"wb")));
  write__with__size__D3I(std_file__ASH,input__9RH,((struct __STRING *)input__9RH)->parent_abstract_string__HM.count__JP);
  fclose((FILE*)((std_file__ASH)));
}

static void print__BTG(void *self__CTG)
// ABSTRACT_STRING print(STRING)
{
  void *s__KTG;
  signed long self__8UG,limit_up__9UG;
  s__KTG=self__CTG;
  self__8UG=lower__KP;
  limit_up__9UG=((struct __STRING *)s__KTG)->parent_abstract_string__HM.count__JP;
  while ((! (self__8UG>limit_up__9UG))) {
    fputc((int)(((struct __STRING *)s__KTG)->parent_abstract_string__HM.storage__IP[(self__8UG-((signed long )(( 1))))]),stdout);
    self__8UG=(self__8UG-(((signed long )(( 0)))-((signed long )(( 1)))));
  };
}

static void *create_from_string__U5I(void *str__W5I)
// STRING create_from_string(STRING,NULLxSTRING_CONSTANT)
{
  void *result__X5I;
  result__X5I=NULL;
  result__X5I=create__FZF(((struct __STRING_CONSTANT *)str__W5I)->parent_abstract_string__3H.count__JP);
  copy__JMH(result__X5I,str__W5I);
  return(result__X5I);
}

static void append__95I(void *self__A6I,void *other__B6I)
// STRING append(STRING,NULLxSTRING)
{
  signed long other_count__C6I,needed_capacity__D6I,self__8UK;
  void *self__B8I,*self__L8I;
  signed long other__9UK;
  needed_capacity__D6I= 0;
  other_count__C6I= 0;
  other_count__C6I=((struct __STRING *)other__B6I)->parent_abstract_string__HM.count__JP;
  needed_capacity__D6I=(((struct __STRING *)self__A6I)->parent_abstract_string__HM.count__JP-(((signed long )(( 0)))-other_count__C6I));
  self__8UK=((struct __STRING *)self__A6I)->capacity__JM;
  other__9UK=needed_capacity__D6I;
  if ((! ((self__8UK>other__9UK) | (self__8UK==other__9UK)))) {
    if ((((struct __STRING *)self__A6I)->capacity__JM== 0)) {
      self__B8I=self__A6I;
      ((struct __STRING *)self__B8I)->capacity__JM=needed_capacity__D6I;
      ((struct __STRING *)self__B8I)->parent_abstract_string__HM.storage__IP=calloc__37D(((struct __STRING *)self__A6I)->capacity__JM);
    } else {
      self__L8I=self__A6I;
      ((struct __STRING *)self__L8I)->parent_abstract_string__HM.storage__IP=realloc__with__3ME(((struct __STRING *)self__A6I)->parent_abstract_string__HM.storage__IP,((struct __STRING *)self__A6I)->capacity__JM,needed_capacity__D6I);
      ((struct __STRING *)self__L8I)->capacity__JM=needed_capacity__D6I;
    };
  };
  copy__to__until__DGH(((struct __STRING *)self__A6I)->parent_abstract_string__HM.storage__IP,((struct __STRING *)other__B6I)->parent_abstract_string__HM.storage__IP,((struct __STRING *)self__A6I)->parent_abstract_string__HM.count__JP,other_count__C6I);
  ((struct __STRING *)self__A6I)->parent_abstract_string__HM.count__JP=needed_capacity__D6I;
}

static void update__idf__with__B9I(void *file__D9I,void *id__E9I,void *new_text__F9I)
// INSTALL_LISAAC update__idf__with(INSTALL_LISAAC,NULLxSTRING,NULLxSTRING_CONSTANT,NULLxSTRING)
{
  void *old_buffer__H9I,*input__I9I,*self__XCJ,*self__VHJ,*other__WHJ;
  void *self__XKJ,*s__YKJ;
  int limit_up__IDJ,self__HFJ;
  void  *std_file__J9I;
  signed char *buf__EBJ,*buf__ZPJ;
  signed long index__G9I,size_file__K9I,j__0KJ,k__1KJ,i__ZKJ;
  char result__XHJ;
  old_buffer__H9I=NULL;
  index__G9I= 0;
  input__I9I=NULL;
  size_file__K9I= 0;
  std_file__J9I=NULL;
  print__3XD(new_intern__6O(__string_59, 5));
  print__BTG(file__D9I);
  buf__EBJ=NULL;
  copy__M2G(string_tmp__VL,file__D9I);
  buf__EBJ=to_external__5FE(string_tmp__VL);
  std_file__J9I=((void  *)(fopen((char*)(buf__EBJ),"rb")));
  if ((std_file__J9I!=NULL)) {
    size_file__K9I=file_size__DUH(std_file__J9I);
    input__I9I=create__QUH(((unsigned long )(((size_file__K9I-(((signed long )(( 0)))-((struct __STRING *)new_text__F9I)->parent_abstract_string__HM.count__JP))))));
    read__in__size__VYH(std_file__J9I,input__I9I,size_file__K9I);
    fclose((FILE*)((std_file__J9I)));
    index__G9I=first_substring_index__R5G(input__I9I,id__E9I);
    if ((index__G9I!= 0)) {
      old_buffer__H9I=create__H3D( 200);
      self__XCJ=new_text__F9I;
      limit_up__IDJ=((int )((fast_occurrences__until__A0H(((struct __STRING *)self__XCJ)->parent_abstract_string__HM.storage__IP,(((struct __STRING *)self__XCJ)->parent_abstract_string__HM.count__JP-((signed long )(( 1))))))));
      if ((! ( 1>limit_up__IDJ))) {
        while ((((struct __STRING *)input__I9I)->parent_abstract_string__HM.storage__IP[(index__G9I-((signed long )(( 1))))]!='\n')) {
          add_last__1KE(old_buffer__H9I,((struct __STRING *)input__I9I)->parent_abstract_string__HM.storage__IP[(index__G9I-((signed long )(( 1))))]);
          remove__J5H(input__I9I,index__G9I);
        };
        add_last__1KE(old_buffer__H9I,((struct __STRING *)input__I9I)->parent_abstract_string__HM.storage__IP[(index__G9I-((signed long )(( 1))))]);
        remove__J5H(input__I9I,index__G9I);
        self__HFJ= 2;
        while ((! (self__HFJ>limit_up__IDJ))) {
          while ((((struct __STRING *)input__I9I)->parent_abstract_string__HM.storage__IP[(index__G9I-((signed long )(( 1))))]!='\n')) {
            add_last__1KE(old_buffer__H9I,((struct __STRING *)input__I9I)->parent_abstract_string__HM.storage__IP[(index__G9I-((signed long )(( 1))))]);
            remove__J5H(input__I9I,index__G9I);
          };
          add_last__1KE(old_buffer__H9I,((struct __STRING *)input__I9I)->parent_abstract_string__HM.storage__IP[(index__G9I-((signed long )(( 1))))]);
          remove__J5H(input__I9I,index__G9I);
          self__HFJ=(self__HFJ- -1);
        };
      };
      self__VHJ=old_buffer__H9I;
      other__WHJ=new_text__F9I;
      result__XHJ=FALSE;
      if ((((struct __STRING *)self__VHJ)->parent_abstract_string__HM.count__JP==((struct __STRING *)other__WHJ)->parent_abstract_string__HM.count__JP)) {
        result__XHJ=fast_memcmp__until__HGI(((struct __STRING *)self__VHJ)->parent_abstract_string__HM.storage__IP,((struct __STRING *)other__WHJ)->parent_abstract_string__HM.storage__IP,((struct __STRING *)self__VHJ)->parent_abstract_string__HM.count__JP);
      };
      if (result__XHJ) {
        print__3XD(new_intern__6O(__string_60, 50));
      } else {
        print__3XD(new_intern__6O(__string_61, 39));
        print__BTG(old_buffer__H9I);
        print__3XD(new_intern__6O(__string_62, 16));
      };
    } else {
      print__3XD(new_intern__6O(__string_63, 30));
      index__G9I=(((struct __STRING *)input__I9I)->parent_abstract_string__HM.count__JP-(((signed long )(( 0)))-((signed long )(( 1)))));
    };
    print__BTG(new_text__F9I);
    self__XKJ=input__I9I;
    s__YKJ=new_text__F9I;
    i__ZKJ=index__G9I;
    k__1KJ= 0;
    j__0KJ= 0;
    j__0KJ=((struct __STRING *)self__XKJ)->parent_abstract_string__HM.count__JP;
    k__1KJ=((struct __STRING *)s__YKJ)->parent_abstract_string__HM.count__JP;
    resize__KNI(self__XKJ,(j__0KJ-(((signed long )(( 0)))-k__1KJ)));
    if ((! (i__ZKJ>j__0KJ))) {
      move__to__by__FTI(((struct __STRING *)self__XKJ)->parent_abstract_string__HM.storage__IP,(i__ZKJ-((signed long )(( 1)))),(j__0KJ-((signed long )(( 1)))),k__1KJ);
    };
    copy__to__until__DGH(((struct __STRING *)self__XKJ)->parent_abstract_string__HM.storage__IP,((struct __STRING *)s__YKJ)->parent_abstract_string__HM.storage__IP,(i__ZKJ-((signed long )(( 1)))),k__1KJ);
  } else {
    print__3XD(new_intern__6O(__string_64, 30));
    print__BTG(new_text__F9I);
    input__I9I=to_string__QOJ(new_text__F9I);
    if ((! make_file__Y0I(to_string__QOJ(file__D9I)))) {
      error__X1I(new_intern__6O(__string_65, 16));
    };
  };
  buf__ZPJ=NULL;
  copy__M2G(string_tmp__VL,file__D9I);
  buf__ZPJ=to_external__5FE(string_tmp__VL);
  std_file__J9I=((void  *)(fopen((char*)(buf__ZPJ),"wb")));
  write__with__size__D3I(std_file__J9I,input__I9I,((struct __STRING *)input__I9I)->parent_abstract_string__HM.count__JP);
  fclose((FILE*)((std_file__J9I)));
}

static signed char read_character__DSJ()
//- STD_INPUT read_character(IO)
{
  memory__WBB=((signed char )(fgetc(stdin)));
  return(memory__WBB);
}

static void *to_string__A9F(void *self__B9F)
// STRING_CONSTANT to_string(STRING_CONSTANT)
{
  void *new__C9F,*self__5AG,*self__P9F,*other__Q9F;
  signed long self__QTK,other__RTK;
  new__C9F=NULL;
  new__C9F=create__FZF(((struct __STRING_CONSTANT *)self__B9F)->parent_abstract_string__3H.count__JP);
  self__P9F=new__C9F;
  other__Q9F=self__B9F;
  ((struct __STRING *)self__P9F)->parent_abstract_string__HM.count__JP=((struct __STRING_CONSTANT *)other__Q9F)->parent_abstract_string__3H.count__JP;
  if ((((struct __STRING *)self__P9F)->parent_abstract_string__HM.count__JP>((signed long )(( 0))))) {
    self__QTK=((struct __STRING *)self__P9F)->capacity__JM;
    other__RTK=((struct __STRING *)self__P9F)->parent_abstract_string__HM.count__JP;
    if ((! ((self__QTK>other__RTK) | (self__QTK==other__RTK)))) {
      self__5AG=self__P9F;
      ((struct __STRING *)self__5AG)->parent_abstract_string__HM.storage__IP=calloc__37D(((struct __STRING *)self__P9F)->parent_abstract_string__HM.count__JP);
      ((struct __STRING *)self__5AG)->capacity__JM=((struct __STRING *)self__P9F)->parent_abstract_string__HM.count__JP;
    };
    copy_from__until__K4F(((struct __STRING *)self__P9F)->parent_abstract_string__HM.storage__IP,((struct __STRING_CONSTANT *)other__Q9F)->parent_abstract_string__3H.storage__IP,(((struct __STRING *)self__P9F)->parent_abstract_string__HM.count__JP-((signed long )(( 1)))));
  };
  return(new__C9F);
}

static void print_nbx__42(unsigned long n__62)
// MEMORY print_nbx(MEMORY,UINTEGER)
{
  int self__63,self__I4;
  signed char car__M3,self__K7,other__L7,___tmp__Q7;
  car__M3= 0;
  self__63= 28;
  downto__by__do__53:
  {
    self__I4=self__63;
    if (((self__I4> 0) | (self__I4== 0))) {
      car__M3=((signed char )(((((unsigned long )((n__62)>>(((signed long )((self__63))))))&((unsigned long )(( 15)))))));
      ___tmp__Q7=((signed char )(( 10)));
      self__K7=car__M3;
      other__L7=___tmp__Q7;
      if (((self__K7>other__L7) | (self__K7==other__L7))) {
        fputc((int)(((signed char )(((code__69('A')-(((signed char )(( 0)))-code__69(((signed char )(((car__M3-((signed char )(( 10)))))))))))))),stdout);
      } else {
        fputc((int)(((signed char )(((code__69('0')-(((signed char )(( 0)))-code__69(((signed char )((car__M3)))))))))),stdout);
      };
      self__63=(self__63- 4);
      goto downto__by__do__53;
    };
  };
}

static void *clone__R3D()
// OBJECT clone(STRING)
{
  void *result__T3D;
  void  *ptr__U3D;
  signed long sz__V3D;
  ptr__U3D=NULL;
  result__T3D=NULL;
  sz__V3D= 0;
  sz__V3D=sizeof(struct __STRING);
  if ((sz__V3D== 0)) {
    result__T3D=STRING;
  } else {
    ptr__U3D=allocation__JU(sz__V3D);
    copy__from__size__2ED(ptr__U3D,((void  *)((STRING))),sz__V3D);
    result__T3D=((void *)((ptr__U3D)));
  };
  return(result__T3D);
}

static signed char *calloc__37D(signed long nb_elements__57D)
// NATIVE_ARRAY calloc(NATIVE_ARRAY,INTEGER)
{
  signed long capacity__18D,___tmp__A8D,self__YAE,limit_down__ZAE;
  signed long ___tmp__7AE,self__MDE,self__PSK,other__QSK,self__RSK;
  void  *p__28D;
  signed char *result__67D,*result__38D,*self__NAE;
  signed long other__SSK;
  result__67D=NULL;
  result__38D=NULL;
  p__28D=NULL;
  capacity__18D= 0;
  capacity__18D=(nb_elements__57D*pointer_size__OD);
  p__28D=allocation__JU(capacity__18D);
  result__38D=((signed char *)((void*)(p__28D)));
  result__67D=result__38D;
  ___tmp__A8D=(nb_elements__57D-((signed long )(( 1))));
  self__NAE=result__67D;
  ___tmp__7AE=((signed long )(( 0)));
  self__YAE=___tmp__A8D;
  limit_down__ZAE=___tmp__7AE;
  self__PSK=self__YAE;
  other__QSK=limit_down__ZAE;
  if (((self__PSK>other__QSK) | (self__PSK==other__QSK))) {
    self__NAE[self__YAE]='\0';
    self__MDE=(self__YAE-((signed long )(( 1))));
    downto__do__LDE:
    {
      self__RSK=self__MDE;
      other__SSK=limit_down__ZAE;
      if (((self__RSK>other__SSK) | (self__RSK==other__SSK))) {
        self__NAE[self__MDE]='\0';
        self__MDE=(self__MDE-((signed long )(( 1))));
        goto downto__do__LDE;
      };
    };
  };
  return(result__67D);
}

static void  *allocation__JU(signed long nb__LU)
// MEMORY allocation(MEMORY,INTEGER)
{
  unsigned long result__0U,index__1V,size__2V,offset__3V,a__SGB;
  void *first_block__YV,*lst_block__ZV,*new_block__0V,**self__WJB;
  void **___tmp__N0,*cur_block__0XB,*p_block__1XB,*n_block__2XB;
  unsigned long step__RGB,begin__WY,___tmp__CZ,size__4XB,new_size__5XB;
  void *new_block__3XB,*self__AKC,*self__1NC,*cur_block__9WC;
  signed long self__7JB,limit_down__8JB,___tmp__GKB,___tmp__TJB;
  void *p_block__AXC,*n_block__BXC,*new_block__CXC,*self__9LK,*self__9XK;
  unsigned short result__3NC;
  void *self__BYK,*self__EYK,*self__DYK,*self__58B,*self__ZCC;
  unsigned long add_size__6XB,size__DXC,new_size__EXC,add_size__FXC;
  signed long self__INB,self__NRK,other__ORK,self__NKB,other__OKB;
  result__0U= 0;
  offset__3V= 0;
  lst_block__ZV=NULL;
  new_block__0V=NULL;
  first_block__YV=NULL;
  index__1V= 0;
  size__2V= 0;
  if ((capacity__FS== 0)) {
    begin__WY= 0;
    begin_memory__DS=get_begin_memory__5Y;
    capacity__FS=get_capacity_memory__6Y;
    ___tmp__CZ=begin_memory__DS;
    step__RGB=((unsigned long )(( 16)));
    a__SGB= 0;
    a__SGB=(step__RGB-((unsigned long )(( 1))));
    begin__WY=((___tmp__CZ-(((unsigned long )(( 0)))-a__SGB))&((((unsigned long )(( 0)))-((unsigned long )(( 1))))-a__SGB));
    end_memory__ES=((begin__WY-(((unsigned long )(( 0)))-capacity__FS))-((unsigned long )(( 1))));
    small_fat__BS=((void **)((begin__WY)));
    ___tmp__N0=small_fat__BS;
    ___tmp__TJB=((signed long )(( 63)));
    self__WJB=___tmp__N0;
    ___tmp__GKB=((signed long )(( 0)));
    self__7JB=___tmp__TJB;
    limit_down__8JB=___tmp__GKB;
    self__NKB=self__7JB;
    other__OKB=limit_down__8JB;
    if (((self__NKB>other__OKB) | (self__NKB==other__OKB))) {
      self__WJB[self__7JB]=NULL;
      self__INB=(self__7JB-((signed long )(( 1))));
      downto__do__HNB:
      {
        self__NRK=self__INB;
        other__ORK=limit_down__8JB;
        if (((self__NRK>other__ORK) | (self__NRK==other__ORK))) {
          self__WJB[self__INB]=NULL;
          self__INB=(self__INB-((signed long )(( 1))));
          goto downto__do__HNB;
        };
      };
    };
    begin__WY=(begin__WY-(((unsigned long )(( 0)))-((unsigned long )(( 256)))));
    last_block__GS=((void *)((begin__WY)));
    make__9PB(last_block__GS,(((end_memory__ES-(((unsigned long )(( 0)))-((unsigned long )(( 1)))))-begin__WY)-object_size__GV));
    first_free__CS=last_block__GS;
  };
  if ((! (nb__LU>((signed long )(( 128)))))) {
    size__2V=((unsigned long )((((nb__LU-(((signed long )(( 0)))-((signed long )(( 1)))))&((signed long )(( 254)))))));
    index__1V=(((unsigned long )((size__2V)>>( 1)))-((unsigned long )(( 1))));
    first_block__YV=small_fat__BS[index__1V];
    if (((first_block__YV==NULL) || is_small_busy__9VC(first_block__YV,size__2V))) {
      new_block__3XB=NULL;
      new_size__5XB= 0;
      n_block__2XB=NULL;
      p_block__1XB=NULL;
      add_size__6XB= 0;
      cur_block__0XB=NULL;
      size__4XB= 0;
      size__4XB=((unsigned long )((( 4111& 4294967280LU))));
      cur_block__0XB=first_free__CS;
      while (((cur_block__0XB!=NULL) && __infix_less__J3B(size__52B(cur_block__0XB),size__4XB))) {
        cur_block__0XB=((struct __MEM_BLOCK *)cur_block__0XB)->next_same__8U;
      };
      if ((cur_block__0XB==NULL)) {
        add_size__6XB=(((size__4XB-(((unsigned long )(( 0)))-((unsigned long )(( 16)))))-(((unsigned long )(( 0)))-((unsigned long )(( 16777215)))))&((unsigned long )(( 4278190080LU))));
        capacity__FS=(capacity__FS-(((unsigned long )(( 0)))-add_size__6XB));
        realloc_c__61(begin_memory__DS,capacity__FS);
        if ((! ((((struct __MEM_BLOCK *)last_block__GS)->size_and_flags__5U&((unsigned long )(( 1))))!= 0))) {
          cur_block__0XB=last_block__GS;
          self__58B=cur_block__0XB;
          ((struct __MEM_BLOCK *)self__58B)->size_and_flags__5U=((((unsigned long )(( 0)))-((unsigned long )(( 1))))-(((((unsigned long )(( 0)))-((unsigned long )(( 1))))-(size__52B(cur_block__0XB)-(((unsigned long )(( 0)))-add_size__6XB)))&((((unsigned long )(( 0)))-((unsigned long )(( 1))))-(((struct __MEM_BLOCK *)self__58B)->size_and_flags__5U&((unsigned long )(( 1)))))));
        } else {
          cur_block__0XB=((void *)(((end_memory__ES-(((unsigned long )(( 0)))-((unsigned long )(( 1))))))));
          make__9PB(cur_block__0XB,(add_size__6XB-((unsigned long )(( 16)))));
          ((struct __MEM_BLOCK *)cur_block__0XB)->prev__6U=last_block__GS;
          last_block__GS=cur_block__0XB;
          ((struct __MEM_BLOCK *)cur_block__0XB)->next_same__8U=first_free__CS;
          if ((first_free__CS!=NULL)) {
            ((struct __MEM_BLOCK *)first_free__CS)->prev_same__7U=cur_block__0XB;
          };
          first_free__CS=cur_block__0XB;
        };
        end_memory__ES=(end_memory__ES-(((unsigned long )(( 0)))-add_size__6XB));
      };
      self__ZCC=cur_block__0XB;
      ((struct __MEM_BLOCK *)self__ZCC)->size_and_flags__5U=((((unsigned long )(( 0)))-((unsigned long )(( 1))))-(((((unsigned long )(( 0)))-((unsigned long )(( 1))))-((struct __MEM_BLOCK *)self__ZCC)->size_and_flags__5U)&((((unsigned long )(( 0)))-((unsigned long )(( 1))))-((unsigned long )(( 1))))));
      p_block__1XB=((struct __MEM_BLOCK *)cur_block__0XB)->prev_same__7U;
      n_block__2XB=((struct __MEM_BLOCK *)cur_block__0XB)->next_same__8U;
      if ((p_block__1XB==NULL)) {
        first_free__CS=n_block__2XB;
      } else {
        ((struct __MEM_BLOCK *)p_block__1XB)->next_same__8U=n_block__2XB;
      };
      if ((n_block__2XB!=NULL)) {
        ((struct __MEM_BLOCK *)n_block__2XB)->prev_same__7U=p_block__1XB;
      };
      new_size__5XB=(size__52B(cur_block__0XB)-size__4XB);
      if ((new_size__5XB>((unsigned long )((( 128-(-((int )((object_size__GV)))))))))) {
        new_size__5XB=(new_size__5XB-object_size__GV);
        new_block__3XB=((void *)((((((unsigned long )((cur_block__0XB)))-(((unsigned long )(( 0)))-object_size__GV))-(((unsigned long )(( 0)))-size__4XB)))));
        make__9PB(new_block__3XB,new_size__5XB);
        if ((first_free__CS!=NULL)) {
          ((struct __MEM_BLOCK *)first_free__CS)->prev_same__7U=new_block__3XB;
        };
        ((struct __MEM_BLOCK *)new_block__3XB)->next_same__8U=first_free__CS;
        first_free__CS=new_block__3XB;
        self__9XK=cur_block__0XB;
        ((struct __MEM_BLOCK *)self__9XK)->size_and_flags__5U=((((unsigned long )(( 0)))-((unsigned long )(( 1))))-(((((unsigned long )(( 0)))-((unsigned long )(( 1))))-size__4XB)&((((unsigned long )(( 0)))-((unsigned long )(( 1))))-(((struct __MEM_BLOCK *)self__9XK)->size_and_flags__5U&((unsigned long )(( 1)))))));
        ((struct __MEM_BLOCK *)new_block__3XB)->prev__6U=cur_block__0XB;
        n_block__2XB=get_next__WHC(new_block__3XB);
        if ((n_block__2XB==NULL)) {
          last_block__GS=new_block__3XB;
        } else {
          ((struct __MEM_BLOCK *)n_block__2XB)->prev__6U=new_block__3XB;
        };
      };
      new_block__0V=cur_block__0XB;
      if ((new_block__0V!=NULL)) {
        self__AKC=new_block__0V;
        ((struct __MEM_BLOCK *)self__AKC)->small_size__9U=((unsigned short )(( 4)));
        ((struct __MEM_BLOCK *)self__AKC)->first_free__AV=((unsigned short )(( 0)));
        ((struct __MEM_BLOCK *)self__AKC)->next_same__8U=self__AKC;
        ((struct __MEM_BLOCK *)self__AKC)->prev_same__7U=((struct __MEM_BLOCK *)self__AKC)->next_same__8U;
        small_fat__BS[index__1V]=new_block__0V;
        if ((first_block__YV!=NULL)) {
          lst_block__ZV=((struct __MEM_BLOCK *)first_block__YV)->prev_same__7U;
          ((struct __MEM_BLOCK *)new_block__0V)->next_same__8U=first_block__YV;
          ((struct __MEM_BLOCK *)new_block__0V)->prev_same__7U=lst_block__ZV;
          ((struct __MEM_BLOCK *)lst_block__ZV)->next_same__8U=new_block__0V;
          ((struct __MEM_BLOCK *)first_block__YV)->prev_same__7U=new_block__0V;
        };
      };
      first_block__YV=new_block__0V;
    };
    if ((first_block__YV!=NULL)) {
      self__1NC=first_block__YV;
      result__3NC= 0;
      if ((((struct __MEM_BLOCK *)self__1NC)->first_free__AV== 0)) {
        result__3NC=((struct __MEM_BLOCK *)self__1NC)->small_size__9U;
      } else {
        result__3NC=((unsigned short )((((struct __MEM_BLOCK *)self__1NC)->first_free__AV)<<( 1)));
        ((struct __MEM_BLOCK *)self__1NC)->first_free__AV=((unsigned short *)(((((unsigned long )((self__1NC)))-(((unsigned long )(( 0)))-object_size__GV)))))[((struct __MEM_BLOCK *)self__1NC)->first_free__AV];
      };
      ((struct __MEM_BLOCK *)self__1NC)->small_size__9U=(((struct __MEM_BLOCK *)self__1NC)->small_size__9U-(((unsigned short )(( 0)))-((unsigned short )((size__2V)))));
      offset__3V=((unsigned long )((result__3NC)));
      self__9LK=first_block__YV;
      if ((__infix_less__J3B((size__52B(self__9LK)-((unsigned long )((((struct __MEM_BLOCK *)self__9LK)->small_size__9U)))),size__2V) && (! is_small_busy__9VC(((struct __MEM_BLOCK *)first_block__YV)->next_same__8U,size__2V)))) {
        small_fat__BS[index__1V]=((struct __MEM_BLOCK *)first_block__YV)->next_same__8U;
      };
      result__0U=((((unsigned long )((first_block__YV)))-(((unsigned long )(( 0)))-object_size__GV))-(((unsigned long )(( 0)))-offset__3V));
    };
  } else {
    new_block__CXC=NULL;
    new_size__EXC= 0;
    n_block__BXC=NULL;
    p_block__AXC=NULL;
    add_size__FXC= 0;
    cur_block__9WC=NULL;
    size__DXC= 0;
    size__DXC=((unsigned long )((((nb__LU-(((signed long )(( 0)))-((signed long )(( 15)))))&((signed long )(( 4294967280LU)))))));
    cur_block__9WC=first_free__CS;
    while (((cur_block__9WC!=NULL) && __infix_less__J3B(size__52B(cur_block__9WC),size__DXC))) {
      cur_block__9WC=((struct __MEM_BLOCK *)cur_block__9WC)->next_same__8U;
    };
    if ((cur_block__9WC==NULL)) {
      add_size__FXC=(((size__DXC-(((unsigned long )(( 0)))-((unsigned long )(( 16)))))-(((unsigned long )(( 0)))-((unsigned long )(( 16777215)))))&((unsigned long )(( 4278190080LU))));
      capacity__FS=(capacity__FS-(((unsigned long )(( 0)))-add_size__FXC));
      realloc_c__61(begin_memory__DS,capacity__FS);
      if ((! ((((struct __MEM_BLOCK *)last_block__GS)->size_and_flags__5U&((unsigned long )(( 1))))!= 0))) {
        cur_block__9WC=last_block__GS;
        self__BYK=cur_block__9WC;
        ((struct __MEM_BLOCK *)self__BYK)->size_and_flags__5U=((((unsigned long )(( 0)))-((unsigned long )(( 1))))-(((((unsigned long )(( 0)))-((unsigned long )(( 1))))-(size__52B(cur_block__9WC)-(((unsigned long )(( 0)))-add_size__FXC)))&((((unsigned long )(( 0)))-((unsigned long )(( 1))))-(((struct __MEM_BLOCK *)self__BYK)->size_and_flags__5U&((unsigned long )(( 1)))))));
      } else {
        cur_block__9WC=((void *)(((end_memory__ES-(((unsigned long )(( 0)))-((unsigned long )(( 1))))))));
        make__9PB(cur_block__9WC,(add_size__FXC-((unsigned long )(( 16)))));
        ((struct __MEM_BLOCK *)cur_block__9WC)->prev__6U=last_block__GS;
        last_block__GS=cur_block__9WC;
        ((struct __MEM_BLOCK *)cur_block__9WC)->next_same__8U=first_free__CS;
        if ((first_free__CS!=NULL)) {
          ((struct __MEM_BLOCK *)first_free__CS)->prev_same__7U=cur_block__9WC;
        };
        first_free__CS=cur_block__9WC;
      };
      end_memory__ES=(end_memory__ES-(((unsigned long )(( 0)))-add_size__FXC));
    };
    self__DYK=cur_block__9WC;
    ((struct __MEM_BLOCK *)self__DYK)->size_and_flags__5U=((((unsigned long )(( 0)))-((unsigned long )(( 1))))-(((((unsigned long )(( 0)))-((unsigned long )(( 1))))-((struct __MEM_BLOCK *)self__DYK)->size_and_flags__5U)&((((unsigned long )(( 0)))-((unsigned long )(( 1))))-((unsigned long )(( 1))))));
    p_block__AXC=((struct __MEM_BLOCK *)cur_block__9WC)->prev_same__7U;
    n_block__BXC=((struct __MEM_BLOCK *)cur_block__9WC)->next_same__8U;
    if ((p_block__AXC==NULL)) {
      first_free__CS=n_block__BXC;
    } else {
      ((struct __MEM_BLOCK *)p_block__AXC)->next_same__8U=n_block__BXC;
    };
    if ((n_block__BXC!=NULL)) {
      ((struct __MEM_BLOCK *)n_block__BXC)->prev_same__7U=p_block__AXC;
    };
    new_size__EXC=(size__52B(cur_block__9WC)-size__DXC);
    if ((new_size__EXC>((unsigned long )((( 128-(-((int )((object_size__GV)))))))))) {
      new_size__EXC=(new_size__EXC-object_size__GV);
      new_block__CXC=((void *)((((((unsigned long )((cur_block__9WC)))-(((unsigned long )(( 0)))-object_size__GV))-(((unsigned long )(( 0)))-size__DXC)))));
      make__9PB(new_block__CXC,new_size__EXC);
      if ((first_free__CS!=NULL)) {
        ((struct __MEM_BLOCK *)first_free__CS)->prev_same__7U=new_block__CXC;
      };
      ((struct __MEM_BLOCK *)new_block__CXC)->next_same__8U=first_free__CS;
      first_free__CS=new_block__CXC;
      self__EYK=cur_block__9WC;
      ((struct __MEM_BLOCK *)self__EYK)->size_and_flags__5U=((((unsigned long )(( 0)))-((unsigned long )(( 1))))-(((((unsigned long )(( 0)))-((unsigned long )(( 1))))-size__DXC)&((((unsigned long )(( 0)))-((unsigned long )(( 1))))-(((struct __MEM_BLOCK *)self__EYK)->size_and_flags__5U&((unsigned long )(( 1)))))));
      ((struct __MEM_BLOCK *)new_block__CXC)->prev__6U=cur_block__9WC;
      n_block__BXC=get_next__WHC(new_block__CXC);
      if ((n_block__BXC==NULL)) {
        last_block__GS=new_block__CXC;
      } else {
        ((struct __MEM_BLOCK *)n_block__BXC)->prev__6U=new_block__CXC;
      };
    };
    first_block__YV=cur_block__9WC;
    if ((first_block__YV!=NULL)) {
      result__0U=(((unsigned long )((first_block__YV)))-(((unsigned long )(( 0)))-object_size__GV));
    };
  };
  if ((result__0U== 0)) {
    fputc((int)('M'),stdout);
    fputc((int)('E'),stdout);
    fputc((int)('M'),stdout);
    fputc((int)(':'),stdout);
    fputc((int)('N'),stdout);
    fputc((int)('O'),stdout);
    fputc((int)('T'),stdout);
    fputc((int)(' '),stdout);
    fputc((int)('E'),stdout);
    fputc((int)('N'),stdout);
    fputc((int)('O'),stdout);
    fputc((int)('U'),stdout);
    fputc((int)('G'),stdout);
    fputc((int)('H'),stdout);
    fputc((int)(' '),stdout);
    fputc((int)('M'),stdout);
    fputc((int)('E'),stdout);
    fputc((int)('M'),stdout);
    fputc((int)('O'),stdout);
    fputc((int)('R'),stdout);
    fputc((int)('Y'),stdout);
    while (1);
  };
  return(((void  *)((result__0U))));
}

static void copy__from__size__2ED(void  *dst__4ED,void  *src__5ED,signed long n__6ED)
// MEMORY copy__from__size(MEMORY,POINTER,POINTER,INTEGER)
{
  unsigned long *dst_array_32__CGD,*src_array_32__DGD,dst_int__0HD;
  int limit_up__NLD,limit_up__2SD,self__EPD,self__CWD;
  unsigned char *dst_array_8__YHD,*src_array_8__ZHD;
  unsigned long src_int__1HD;
  signed long cpt__2HD,i__BID,i__ZPD,i__OID,i__XWD;
  src_array_8__ZHD=NULL;
  dst_array_8__YHD=NULL;
  src_array_32__DGD=NULL;
  dst_array_32__CGD=NULL;
  cpt__2HD= 0;
  src_int__1HD= 0;
  dst_int__0HD= 0;
  dst_int__0HD=((unsigned long )((dst__4ED)));
  src_int__1HD=((unsigned long )((src__5ED)));
  cpt__2HD=((signed long )((n__6ED)>>( 2)));
  if ((cpt__2HD!= 0)) {
    dst_array_32__CGD=((unsigned long *)((dst_int__0HD)));
    src_array_32__DGD=((unsigned long *)((src_int__1HD)));
    limit_up__NLD=((int )(((cpt__2HD-((signed long )(( 1)))))));
    if ((! ( 0>limit_up__NLD))) {
      i__BID=((signed long )(( 0)));
      dst_array_32__CGD[i__BID]=src_array_32__DGD[i__BID];
      self__EPD= 1;
      while ((! (self__EPD>limit_up__NLD))) {
        i__ZPD=((signed long )((self__EPD)));
        dst_array_32__CGD[i__ZPD]=src_array_32__DGD[i__ZPD];
        self__EPD=(self__EPD- -1);
      };
    };
    dst_int__0HD=(dst_int__0HD-(((unsigned long )(( 0)))-((unsigned long )(((n__6ED&((signed long )(( 4294967292LU)))))))));
    src_int__1HD=(src_int__1HD-(((unsigned long )(( 0)))-((unsigned long )(((n__6ED&((signed long )(( 4294967292LU)))))))));
  };
  cpt__2HD=(n__6ED&((signed long )(( 3))));
  if ((cpt__2HD!= 0)) {
    dst_array_8__YHD=((unsigned char *)((dst_int__0HD)));
    src_array_8__ZHD=((unsigned char *)((src_int__1HD)));
    limit_up__2SD=((int )(((cpt__2HD-((signed long )(( 1)))))));
    if ((! ( 0>limit_up__2SD))) {
      i__OID=((signed long )(( 0)));
      dst_array_8__YHD[i__OID]=src_array_8__ZHD[i__OID];
      self__CWD= 1;
      while ((! (self__CWD>limit_up__2SD))) {
        i__XWD=((signed long )((self__CWD)));
        dst_array_8__YHD[i__XWD]=src_array_8__ZHD[i__XWD];
        self__CWD=(self__CWD- -1);
      };
    };
  };
}

static void add_last__1KE(void *self__2KE,signed char ch__3KE)
// STRING add_last(STRING,CHARACTER)
{
  void *self__CME,*self__QME;
  signed long new_capacity__4KE;
  new_capacity__4KE= 0;
  if ((! (((struct __STRING *)self__2KE)->capacity__JM>((struct __STRING *)self__2KE)->parent_abstract_string__HM.count__JP))) {
    if ((((struct __STRING *)self__2KE)->capacity__JM== 0)) {
      self__CME=self__2KE;
      ((struct __STRING *)self__CME)->capacity__JM=((signed long )(( 32)));
      ((struct __STRING *)self__CME)->parent_abstract_string__HM.storage__IP=calloc__37D(((struct __STRING *)self__2KE)->capacity__JM);
    } else {
      self__QME=self__2KE;
      new_capacity__4KE=(((struct __STRING *)self__2KE)->capacity__JM*((signed long )(( 2))));
      ((struct __STRING *)self__QME)->parent_abstract_string__HM.storage__IP=realloc__with__3ME(((struct __STRING *)self__2KE)->parent_abstract_string__HM.storage__IP,((struct __STRING *)self__2KE)->capacity__JM,new_capacity__4KE);
      ((struct __STRING *)self__QME)->capacity__JM=new_capacity__4KE;
    };
  };
  ((struct __STRING *)self__2KE)->parent_abstract_string__HM.storage__IP[((struct __STRING *)self__2KE)->parent_abstract_string__HM.count__JP]=ch__3KE;
  ((struct __STRING *)self__2KE)->parent_abstract_string__HM.count__JP=(((struct __STRING *)self__2KE)->parent_abstract_string__HM.count__JP-(((signed long )(( 0)))-((signed long )(( 1)))));
}

static void copy_from__until__K4F(signed char *self__L4F,signed char *model__M4F,signed long upper__N4F)
// NATIVE_ARRAY copy_from__until(NATIVE_ARRAY,NATIVE_ARRAY,INTEGER)
{
  signed long i__O4F,i__N6F,self__X4F,limit_down__Y4F,___tmp__64F;
  signed long self__35F,self__MTK,other__NTK,self__OTK,other__PTK;
  ___tmp__64F=((signed long )(( 0)));
  self__X4F=upper__N4F;
  limit_down__Y4F=___tmp__64F;
  self__MTK=self__X4F;
  other__NTK=limit_down__Y4F;
  if (((self__MTK>other__NTK) | (self__MTK==other__NTK))) {
    i__O4F=self__X4F;
    self__L4F[i__O4F]=model__M4F[i__O4F];
    self__35F=(self__X4F-((signed long )(( 1))));
    downto__do__25F:
    {
      self__OTK=self__35F;
      other__PTK=limit_down__Y4F;
      if (((self__OTK>other__PTK) | (self__OTK==other__PTK))) {
        i__N6F=self__35F;
        self__L4F[i__N6F]=model__M4F[i__N6F];
        self__35F=(self__35F-((signed long )(( 1))));
        goto downto__do__25F;
      };
    };
  };
}

static void print__GEG(signed long self__HEG)
// NUMERIC print(INTEGER)
{
  signed long ___tmp__9IG,self__5IG,other__6IG,___tmp__BJG,i1__EPG;
  signed long i2__FPG,val__ZEG,i__0EG,j__1EG,self__XEG,self__XTK;
  void *self__DPG,*buffer__YEG,*result__OEG;
  signed char result__1JG,tmp__GPG;
  signed long other__YTK;
  result__OEG=NULL;
  result__OEG=create__H3D( 11);
  self__XEG=self__HEG;
  buffer__YEG=result__OEG;
  j__1EG= 0;
  i__0EG= 0;
  val__ZEG= 0;
  if ((self__XEG==((signed long )(( 0))))) {
    add_last__1KE(buffer__YEG,'0');
  } else {
    if ((self__XEG>((signed long )(( 0))))) {
      val__ZEG=self__XEG;
    } else {
      val__ZEG=(((signed long )(( 0)))-self__XEG);
      add_last__1KE(buffer__YEG,'-');
    };
    i__0EG=(((struct __STRING *)buffer__YEG)->parent_abstract_string__HM.count__JP-(((signed long )(( 0)))-((signed long )(( 1)))));
    while ((! (val__ZEG==((signed long )(( 0)))))) {
      ___tmp__BJG=((signed long )(( 10)));
      self__5IG=val__ZEG;
      other__6IG=___tmp__BJG;
      ___tmp__9IG=(self__5IG-((self__5IG/other__6IG)*other__6IG));
      result__1JG='\0';
      result__1JG=((signed char )(((((signed char )((___tmp__9IG)))-(((signed char )(( 0)))-code__69('0'))))));
      add_last__1KE(buffer__YEG,result__1JG);
      val__ZEG=(val__ZEG/((signed long )(( 10))));
    };
    j__1EG=((struct __STRING *)buffer__YEG)->parent_abstract_string__HM.count__JP;
    until_do__NOG:
    {
      self__XTK=i__0EG;
      other__YTK=j__1EG;
      if ((! ((self__XTK>other__YTK) | (self__XTK==other__YTK)))) {
        self__DPG=buffer__YEG;
        i1__EPG=i__0EG;
        i2__FPG=j__1EG;
        tmp__GPG='\0';
        tmp__GPG=((struct __STRING *)self__DPG)->parent_abstract_string__HM.storage__IP[(i1__EPG-((signed long )(( 1))))];
        ((struct __STRING *)self__DPG)->parent_abstract_string__HM.storage__IP[(i1__EPG-((signed long )(( 1))))]=((struct __STRING *)self__DPG)->parent_abstract_string__HM.storage__IP[(i2__FPG-((signed long )(( 1))))];
        ((struct __STRING *)self__DPG)->parent_abstract_string__HM.storage__IP[(i2__FPG-((signed long )(( 1))))]=tmp__GPG;
        j__1EG=(j__1EG-((signed long )(( 1))));
        i__0EG=(i__0EG-(((signed long )(( 0)))-((signed long )(( 1)))));
        goto until_do__NOG;
      };
    };
  };
  print__BTG(result__OEG);
}

static void copy__M2G(void *self__N2G,void *other__O2G)
// STRING copy(STRING,NULLxSTRING)
{
  void *self__33G;
  signed long self__3TK,other__4TK;
  ((struct __STRING *)self__N2G)->parent_abstract_string__HM.count__JP=((struct __STRING *)other__O2G)->parent_abstract_string__HM.count__JP;
  if ((((struct __STRING *)self__N2G)->parent_abstract_string__HM.count__JP>((signed long )(( 0))))) {
    self__3TK=((struct __STRING *)self__N2G)->capacity__JM;
    other__4TK=((struct __STRING *)self__N2G)->parent_abstract_string__HM.count__JP;
    if ((! ((self__3TK>other__4TK) | (self__3TK==other__4TK)))) {
      self__33G=self__N2G;
      ((struct __STRING *)self__33G)->parent_abstract_string__HM.storage__IP=calloc__37D(((struct __STRING *)self__N2G)->parent_abstract_string__HM.count__JP);
      ((struct __STRING *)self__33G)->capacity__JM=((struct __STRING *)self__N2G)->parent_abstract_string__HM.count__JP;
    };
    copy_from__until__K4F(((struct __STRING *)self__N2G)->parent_abstract_string__HM.storage__IP,((struct __STRING *)other__O2G)->parent_abstract_string__HM.storage__IP,(((struct __STRING *)self__N2G)->parent_abstract_string__HM.count__JP-((signed long )(( 1)))));
  };
}

static signed char *realloc__with__3ME(signed char *self__4ME,signed long old_nb_elts__5ME,signed long new_nb_elts__6ME)
// NATIVE_ARRAY realloc__with(NATIVE_ARRAY,INTEGER,INTEGER)
{
  unsigned long self__KYE,other__LYE,self__9XE,limit_up__SXE;
  void *self__QXE,*self__90E,*p_block__B8E,*n_block__C8E,*pp_block__D8E;
  void *nn_block__E8E,*block__F8E,*blk__A8E,*result__VJF,*block__UJF;
  void *p_block__SHF,*n_block__THF,*pp_block__UHF,*nn_block__VHF;
  unsigned long limit_low__TXE,___tmp__LSE,size__G8E,next__WJF;
  void *block__WHF,*blk__RHF,*first_block__XRE,*cur_block__YRE;
  signed long ___tmp__HNE,___tmp__JNE,size__1RE,index__2RE,nb__WRE;
  void *p_block__ZRE,*n_block__0RE,*self__DTK,*self__0DF,*self__GYK;
  unsigned short idx__C1E;
  void *self__IYK;
  unsigned long size__XHF,p__3RE;
  void  *old_ptr__8ME,*new_ptr__9ME,*new_pointer__8PE,*old_ptr__5PE;
  signed char *new__7ME;
  signed long old_size__6PE;
  char result__GGF,___tmp__ZSE;
  new__7ME=NULL;
  new_ptr__9ME=NULL;
  old_ptr__8ME=NULL;
  old_ptr__8ME=((void  *)((self__4ME)));
  ___tmp__HNE=(old_nb_elts__5ME*pointer_size__OD);
  ___tmp__JNE=(new_nb_elts__6ME*pointer_size__OD);
  old_ptr__5PE=old_ptr__8ME;
  old_size__6PE=___tmp__HNE;
  new_pointer__8PE=NULL;
  new_pointer__8PE=allocation__JU(___tmp__JNE);
  copy__from__size__2ED(new_pointer__8PE,old_ptr__5PE,old_size__6PE);
  nb__WRE=old_size__6PE;
  p_block__ZRE=NULL;
  n_block__0RE=NULL;
  cur_block__YRE=NULL;
  first_block__XRE=NULL;
  index__2RE= 0;
  size__1RE= 0;
  p__3RE= 0;
  p__3RE=((unsigned long )((old_ptr__5PE)));
  if ((! (nb__WRE>((signed long )(( 128)))))) {
    size__1RE=((nb__WRE-(((signed long )(( 0)))-((signed long )(( 1)))))&((signed long )(( 254))));
    index__2RE=(((signed long )((size__1RE)>>( 1)))-((signed long )(( 1))));
    first_block__XRE=small_fat__BS[index__2RE];
    cur_block__YRE=first_block__XRE;
    until_do__EXE:
    {
      self__QXE=cur_block__YRE;
      limit_up__SXE= 0;
      limit_low__TXE= 0;
      limit_low__TXE=(((unsigned long )((self__QXE)))-(((unsigned long )(( 0)))-object_size__GV));
      limit_up__SXE=(limit_low__TXE-(((unsigned long )(( 0)))-size__52B(self__QXE)));
      self__9XE=p__3RE;
      self__KYE=self__9XE;
      other__LYE=limit_low__TXE;
      if ((! (((self__KYE>other__LYE) | (self__KYE==other__LYE)) && (! (self__9XE>limit_up__SXE))))) {
        cur_block__YRE=((struct __MEM_BLOCK *)cur_block__YRE)->next_same__8U;
        goto until_do__EXE;
      };
    };
    ___tmp__LSE=(p__3RE-(((unsigned long )((cur_block__YRE)))-(((unsigned long )(( 0)))-object_size__GV)));
    self__90E=cur_block__YRE;
    idx__C1E= 0;
    idx__C1E=((unsigned short )((((unsigned long )((___tmp__LSE)>>( 1))))));
    ((unsigned short *)(((((unsigned long )((self__90E)))-(((unsigned long )(( 0)))-object_size__GV)))))[idx__C1E]=((struct __MEM_BLOCK *)self__90E)->first_free__AV;
    ((struct __MEM_BLOCK *)self__90E)->first_free__AV=idx__C1E;
    ((struct __MEM_BLOCK *)self__90E)->small_size__9U=(((struct __MEM_BLOCK *)self__90E)->small_size__9U-((unsigned short )((size__1RE))));
    if ((((struct __MEM_BLOCK *)cur_block__YRE)->small_size__9U== 4)) {
      n_block__0RE=((struct __MEM_BLOCK *)cur_block__YRE)->next_same__8U;
      p_block__ZRE=((struct __MEM_BLOCK *)cur_block__YRE)->prev_same__7U;
      ((struct __MEM_BLOCK *)n_block__0RE)->prev_same__7U=p_block__ZRE;
      ((struct __MEM_BLOCK *)p_block__ZRE)->next_same__8U=n_block__0RE;
      if ((cur_block__YRE==first_block__XRE)) {
        if ((n_block__0RE==cur_block__YRE)) {
          small_fat__BS[index__2RE]=NULL;
        } else {
          small_fat__BS[index__2RE]=n_block__0RE;
        };
      };
      blk__A8E=cur_block__YRE;
      nn_block__E8E=NULL;
      pp_block__D8E=NULL;
      block__F8E=NULL;
      n_block__C8E=NULL;
      p_block__B8E=NULL;
      size__G8E= 0;
      size__G8E=size__52B(blk__A8E);
      p_block__B8E=((struct __MEM_BLOCK *)blk__A8E)->prev__6U;
      n_block__C8E=get_next__WHC(blk__A8E);
      if (((p_block__B8E!=NULL) && is_free__KAF(p_block__B8E))) {
        block__F8E=p_block__B8E;
        size__G8E=((size__G8E-(((unsigned long )(( 0)))-size__52B(block__F8E)))-(((unsigned long )(( 0)))-object_size__GV));
      } else {
        block__F8E=blk__A8E;
      };
      if (((n_block__C8E!=NULL) && is_free__KAF(n_block__C8E))) {
        size__G8E=((size__G8E-(((unsigned long )(( 0)))-size__52B(n_block__C8E)))-(((unsigned long )(( 0)))-object_size__GV));
        pp_block__D8E=((struct __MEM_BLOCK *)n_block__C8E)->prev_same__7U;
        nn_block__E8E=((struct __MEM_BLOCK *)n_block__C8E)->next_same__8U;
        if ((pp_block__D8E==NULL)) {
          first_free__CS=nn_block__E8E;
        } else {
          ((struct __MEM_BLOCK *)pp_block__D8E)->next_same__8U=nn_block__E8E;
        };
        if ((nn_block__E8E!=NULL)) {
          ((struct __MEM_BLOCK *)nn_block__E8E)->prev_same__7U=pp_block__D8E;
        };
        n_block__C8E=get_next__WHC(n_block__C8E);
      };
      self__GYK=block__F8E;
      ((struct __MEM_BLOCK *)self__GYK)->size_and_flags__5U=((((unsigned long )(( 0)))-((unsigned long )(( 1))))-(((((unsigned long )(( 0)))-((unsigned long )(( 1))))-size__G8E)&((((unsigned long )(( 0)))-((unsigned long )(( 1))))-(((struct __MEM_BLOCK *)self__GYK)->size_and_flags__5U&((unsigned long )(( 1)))))));
      if ((n_block__C8E==NULL)) {
        last_block__GS=block__F8E;
      } else {
        ((struct __MEM_BLOCK *)n_block__C8E)->prev__6U=block__F8E;
      };
      if ((! (! ((((struct __MEM_BLOCK *)block__F8E)->size_and_flags__5U&((unsigned long )(( 1))))!= 0)))) {
        self__0DF=block__F8E;
        ((struct __MEM_BLOCK *)self__0DF)->size_and_flags__5U=(((struct __MEM_BLOCK *)self__0DF)->size_and_flags__5U&((unsigned long )(( 4294967294LU))));
        ((struct __MEM_BLOCK *)block__F8E)->prev_same__7U=NULL;
        ((struct __MEM_BLOCK *)block__F8E)->next_same__8U=first_free__CS;
        if ((first_free__CS!=NULL)) {
          ((struct __MEM_BLOCK *)first_free__CS)->prev_same__7U=block__F8E;
        };
        first_free__CS=block__F8E;
      };
      ___tmp__ZSE=TRUE;
    } else {
      ___tmp__ZSE=FALSE;
    };
    if (___tmp__ZSE) {
    } else {
      result__GGF=FALSE;
      result__GGF=(cur_block__YRE!=first_block__XRE);
      if (result__GGF) {
        n_block__0RE=((struct __MEM_BLOCK *)cur_block__YRE)->next_same__8U;
        p_block__ZRE=((struct __MEM_BLOCK *)cur_block__YRE)->prev_same__7U;
        ((struct __MEM_BLOCK *)n_block__0RE)->prev_same__7U=p_block__ZRE;
        ((struct __MEM_BLOCK *)p_block__ZRE)->next_same__8U=n_block__0RE;
        p_block__ZRE=((struct __MEM_BLOCK *)first_block__XRE)->prev_same__7U;
        ((struct __MEM_BLOCK *)cur_block__YRE)->next_same__8U=first_block__XRE;
        ((struct __MEM_BLOCK *)cur_block__YRE)->prev_same__7U=p_block__ZRE;
        ((struct __MEM_BLOCK *)first_block__XRE)->prev_same__7U=cur_block__YRE;
        ((struct __MEM_BLOCK *)p_block__ZRE)->next_same__8U=cur_block__YRE;
        small_fat__BS[index__2RE]=cur_block__YRE;
      };
    };
  } else {
    blk__RHF=((void *)(((p__3RE-object_size__GV))));
    nn_block__VHF=NULL;
    pp_block__UHF=NULL;
    block__WHF=NULL;
    n_block__THF=NULL;
    p_block__SHF=NULL;
    size__XHF= 0;
    size__XHF=size__52B(blk__RHF);
    p_block__SHF=((struct __MEM_BLOCK *)blk__RHF)->prev__6U;
    block__UJF=blk__RHF;
    result__VJF=NULL;
    next__WJF= 0;
    next__WJF=((((unsigned long )((block__UJF)))-(((unsigned long )(( 0)))-object_size__GV))-(((unsigned long )(( 0)))-size__52B(block__UJF)));
    if ((next__WJF!=(end_memory__ES-(((unsigned long )(( 0)))-((unsigned long )(( 1))))))) {
      result__VJF=((void *)((next__WJF)));
    };
    n_block__THF=result__VJF;
    if (((p_block__SHF!=NULL) && is_free__KAF(p_block__SHF))) {
      block__WHF=p_block__SHF;
      size__XHF=((size__XHF-(((unsigned long )(( 0)))-size__52B(block__WHF)))-(((unsigned long )(( 0)))-object_size__GV));
    } else {
      block__WHF=blk__RHF;
    };
    if (((n_block__THF!=NULL) && is_free__KAF(n_block__THF))) {
      size__XHF=((size__XHF-(((unsigned long )(( 0)))-size__52B(n_block__THF)))-(((unsigned long )(( 0)))-object_size__GV));
      pp_block__UHF=((struct __MEM_BLOCK *)n_block__THF)->prev_same__7U;
      nn_block__VHF=((struct __MEM_BLOCK *)n_block__THF)->next_same__8U;
      if ((pp_block__UHF==NULL)) {
        first_free__CS=nn_block__VHF;
      } else {
        ((struct __MEM_BLOCK *)pp_block__UHF)->next_same__8U=nn_block__VHF;
      };
      if ((nn_block__VHF!=NULL)) {
        ((struct __MEM_BLOCK *)nn_block__VHF)->prev_same__7U=pp_block__UHF;
      };
      n_block__THF=get_next__WHC(n_block__THF);
    };
    self__IYK=block__WHF;
    ((struct __MEM_BLOCK *)self__IYK)->size_and_flags__5U=((((unsigned long )(( 0)))-((unsigned long )(( 1))))-(((((unsigned long )(( 0)))-((unsigned long )(( 1))))-size__XHF)&((((unsigned long )(( 0)))-((unsigned long )(( 1))))-(((struct __MEM_BLOCK *)self__IYK)->size_and_flags__5U&((unsigned long )(( 1)))))));
    if ((n_block__THF==NULL)) {
      last_block__GS=block__WHF;
    } else {
      ((struct __MEM_BLOCK *)n_block__THF)->prev__6U=block__WHF;
    };
    if ((! (! ((((struct __MEM_BLOCK *)block__WHF)->size_and_flags__5U&((unsigned long )(( 1))))!= 0)))) {
      self__DTK=block__WHF;
      ((struct __MEM_BLOCK *)self__DTK)->size_and_flags__5U=(((struct __MEM_BLOCK *)self__DTK)->size_and_flags__5U&((unsigned long )(( 4294967294LU))));
      ((struct __MEM_BLOCK *)block__WHF)->prev_same__7U=NULL;
      ((struct __MEM_BLOCK *)block__WHF)->next_same__8U=first_free__CS;
      if ((first_free__CS!=NULL)) {
        ((struct __MEM_BLOCK *)first_free__CS)->prev_same__7U=block__WHF;
      };
      first_free__CS=block__WHF;
    };
  };
  new_ptr__9ME=new_pointer__8PE;
  new__7ME=((signed char *)((void*)(new_ptr__9ME)));
  clear__to__FQF(new__7ME,old_nb_elts__5ME,(new_nb_elts__6ME-((signed long )(( 1)))));
  return(new__7ME);
}

static void copy__to__until__DGH(signed char *self__EGH,signed char *src__FGH,signed long dest__GGH,signed long src_capacity__HGH)
// NATIVE_ARRAY copy__to__until(NATIVE_ARRAY,NATIVE_ARRAY,INTEGER,INTEGER)
{
  signed long i1__IGH,i2__JGH;
  i2__JGH= 0;
  i1__IGH= 0;
  i1__IGH=dest__GGH;
  while ((! (i2__JGH==src_capacity__HGH))) {
    self__EGH[i1__IGH]=src__FGH[i2__JGH];
    i2__JGH=(i2__JGH-(((signed long )(( 0)))-((signed long )(( 1)))));
    i1__IGH=(i1__IGH-(((signed long )(( 0)))-((signed long )(( 1)))));
  };
}

static void copy__JMH(void *self__KMH,void *other__LMH)
// STRING copy(STRING,NULLxSTRING_CONSTANT)
{
  void *self__0NH;
  signed long self__EUK,other__FUK;
  ((struct __STRING *)self__KMH)->parent_abstract_string__HM.count__JP=((struct __STRING_CONSTANT *)other__LMH)->parent_abstract_string__3H.count__JP;
  if ((((struct __STRING *)self__KMH)->parent_abstract_string__HM.count__JP>((signed long )(( 0))))) {
    self__EUK=((struct __STRING *)self__KMH)->capacity__JM;
    other__FUK=((struct __STRING *)self__KMH)->parent_abstract_string__HM.count__JP;
    if ((! ((self__EUK>other__FUK) | (self__EUK==other__FUK)))) {
      self__0NH=self__KMH;
      ((struct __STRING *)self__0NH)->parent_abstract_string__HM.storage__IP=calloc__37D(((struct __STRING *)self__KMH)->parent_abstract_string__HM.count__JP);
      ((struct __STRING *)self__0NH)->capacity__JM=((struct __STRING *)self__KMH)->parent_abstract_string__HM.count__JP;
    };
    copy_from__until__K4F(((struct __STRING *)self__KMH)->parent_abstract_string__HM.storage__IP,((struct __STRING_CONSTANT *)other__LMH)->parent_abstract_string__3H.storage__IP,(((struct __STRING *)self__KMH)->parent_abstract_string__HM.count__JP-((signed long )(( 1)))));
  };
}

static signed long file_size__DUH(void  *p__FUH)
// INSTALL_LISAAC file_size(INSTALL_LISAAC,POINTER)
{
  signed long result__GUH;
  result__GUH= 0;
  fseek((FILE*)((p__FUH)),0,SEEK_END);
  result__GUH=((signed long )(ftell((FILE *)(p__FUH))));
  fseek((FILE*)((p__FUH)),0,SEEK_SET);
  return(result__GUH);
}

static void *create__QUH(unsigned long needed_capacity__SUH)
// STRING create(STRING,UINTEGER)
{
  void *result__TUH,*self__6XH,*self__3UH;
  unsigned long needed_capacity__4UH;
  signed long self__HUK,other__IUK;
  result__TUH=NULL;
  result__TUH=clone__R3D();
  self__3UH=result__TUH;
  needed_capacity__4UH=needed_capacity__SUH;
  if ((needed_capacity__4UH>((unsigned long )(( 0))))) {
    self__HUK=((struct __STRING *)self__3UH)->capacity__JM;
    other__IUK=((signed long )((needed_capacity__4UH)));
    if ((! ((self__HUK>other__IUK) | (self__HUK==other__IUK)))) {
      self__6XH=self__3UH;
      ((struct __STRING *)self__6XH)->parent_abstract_string__HM.storage__IP=calloc__37D(((signed long )((needed_capacity__4UH))));
      ((struct __STRING *)self__6XH)->capacity__JM=((signed long )((needed_capacity__4UH)));
    };
  };
  ((struct __STRING *)self__3UH)->parent_abstract_string__HM.count__JP=((signed long )(( 0)));
  return(result__TUH);
}

static void read__in__size__VYH(void  *f__XYH,void *buf__YYH,signed long sz__ZYH)
// INSTALL_LISAAC read__in__size(INSTALL_LISAAC,POINTER,NULLxSTRING,INTEGER)
{
  signed char *ptr__0YH;
  ptr__0YH=NULL;
  ptr__0YH=to_external__5FE(buf__YYH);
  ((signed long )(fread((void *)((ptr__0YH)),(size_t)(1), (size_t)((sz__ZYH)),(FILE*)((f__XYH)))));
  from_external__5UF(buf__YYH,ptr__0YH);
}

static signed long fast_occurrences__until__A0H(signed char *self__B0H,signed long upper__D0H)
// NATIVE_ARRAY fast_occurrences__until(NATIVE_ARRAY,CHARACTER,INTEGER)
{
  signed long count__E0H,self__P0H,limit_down__Q0H,___tmp__Y0H;
  signed long self__91H,self__JUK,other__KUK,self__NUK,other__OUK;
  count__E0H= 0;
  ___tmp__Y0H=((signed long )(( 0)));
  self__P0H=upper__D0H;
  limit_down__Q0H=___tmp__Y0H;
  self__JUK=self__P0H;
  other__KUK=limit_down__Q0H;
  if (((self__JUK>other__KUK) | (self__JUK==other__KUK))) {
    if (('\n'==self__B0H[self__P0H])) {
      count__E0H=(count__E0H-(((signed long )(( 0)))-((signed long )(( 1)))));
    };
    self__91H=(self__P0H-((signed long )(( 1))));
    downto__do__81H:
    {
      self__NUK=self__91H;
      other__OUK=limit_down__Q0H;
      if (((self__NUK>other__OUK) | (self__NUK==other__OUK))) {
        if (('\n'==self__B0H[self__91H])) {
          count__E0H=(count__E0H-(((signed long )(( 0)))-((signed long )(( 1)))));
        };
        self__91H=(self__91H-((signed long )(( 1))));
        goto downto__do__81H;
      };
    };
  };
  return(count__E0H);
}

static void remove__J5H(void *self__K5H,signed long index__L5H)
// STRING remove(STRING,INTEGER)
{
  void *self__I6H;
  signed long i__X6H,___tmp__W6H,len__L6H,end__K6H,self__L9H;
  self__I6H=self__K5H;
  end__K6H=index__L5H;
  len__L6H= 0;
  len__L6H=((end__K6H-index__L5H)-(((signed long )(( 0)))-((signed long )(( 1)))));
  if ((len__L6H>((signed long )(( 0))))) {
    ___tmp__W6H=((struct __STRING *)self__I6H)->parent_abstract_string__HM.count__JP;
    self__L9H=(end__K6H-(((signed long )(( 0)))-((signed long )(( 1)))));
    while ((! (self__L9H>___tmp__W6H))) {
      i__X6H=self__L9H;
      ((struct __STRING *)self__I6H)->parent_abstract_string__HM.storage__IP[((i__X6H-len__L6H)-((signed long )(( 1))))]=((struct __STRING *)self__I6H)->parent_abstract_string__HM.storage__IP[(i__X6H-((signed long )(( 1))))];
      self__L9H=(self__L9H-(((signed long )(( 0)))-((signed long )(( 1)))));
    };
    ((struct __STRING *)self__I6H)->parent_abstract_string__HM.count__JP=(((struct __STRING *)self__I6H)->parent_abstract_string__HM.count__JP-len__L6H);
  };
}

static char fast_memcmp__until__HGI(signed char *self__IGI,signed char *other__JGI,signed long capacity__KGI)
// NATIVE_ARRAY fast_memcmp__until(NATIVE_ARRAY,NATIVE_ARRAY,INTEGER)
{
  signed long i__LGI,self__5HI,other__6HI,___tmp__BII,self__UUK;
  signed long other__VUK;
  i__LGI= 0;
  i__LGI=(capacity__KGI-((signed long )(( 1))));
  while_do__SHI:
  {
    ___tmp__BII=((signed long )(( 0)));
    self__5HI=i__LGI;
    other__6HI=___tmp__BII;
    if ((((self__5HI>other__6HI) | (self__5HI==other__6HI)) && (self__IGI[i__LGI]==other__JGI[i__LGI]))) {
      i__LGI=(i__LGI-((signed long )(( 1))));
      goto while_do__SHI;
    };
  };
  self__UUK=i__LGI;
  other__VUK=((signed long )(( 0)));
  return((! ((self__UUK>other__VUK) | (self__UUK==other__VUK))));
}

static void resize__KNI(void *self__LNI,signed long new_count__MNI)
// STRING resize(STRING,INTEGER)
{
  signed long self__YUK,other__ZUK;
  if ((! (new_count__MNI>((struct __STRING *)self__LNI)->parent_abstract_string__HM.count__JP))) {
  } else {
    self__YUK=((struct __STRING *)self__LNI)->capacity__JM;
    other__ZUK=new_count__MNI;
    if ((! ((self__YUK>other__ZUK) | (self__YUK==other__ZUK)))) {
      if ((((struct __STRING *)self__LNI)->capacity__JM== 0)) {
        ((struct __STRING *)self__LNI)->parent_abstract_string__HM.storage__IP=calloc__37D(new_count__MNI);
      } else {
        ((struct __STRING *)self__LNI)->parent_abstract_string__HM.storage__IP=realloc__with__3ME(((struct __STRING *)self__LNI)->parent_abstract_string__HM.storage__IP,((struct __STRING *)self__LNI)->capacity__JM,new_count__MNI);
      };
      ((struct __STRING *)self__LNI)->capacity__JM=new_count__MNI;
    } else {
      clear__to__FQF(((struct __STRING *)self__LNI)->parent_abstract_string__HM.storage__IP,((struct __STRING *)self__LNI)->parent_abstract_string__HM.count__JP,(new_count__MNI-((signed long )(( 1)))));
    };
  };
  ((struct __STRING *)self__LNI)->parent_abstract_string__HM.count__JP=new_count__MNI;
}

static void move__to__by__FTI(signed char *self__GTI,signed long lower__HTI,signed long upper__ITI,signed long offset__JTI)
//- NATIVE_ARRAY move__to__by(NATIVE_ARRAY,INTEGER,INTEGER,INTEGER)
{
  signed long i__QTI,i__VTI,self__LWI,self__6XI,self__4UK,other__5UK;
  signed long self__0UK,other__1UK;
  if ((offset__JTI!= 0)) {
    self__0UK=offset__JTI;
    other__1UK=((signed long )(( 0)));
    if ((! ((self__0UK>other__1UK) | (self__0UK==other__1UK)))) {
      self__LWI=lower__HTI;
      while ((! (self__LWI>upper__ITI))) {
        i__QTI=self__LWI;
        self__GTI[(i__QTI-(((signed long )(( 0)))-offset__JTI))]=self__GTI[i__QTI];
        self__LWI=(self__LWI-(((signed long )(( 0)))-((signed long )(( 1)))));
      };
    } else {
      self__6XI=upper__ITI;
      downto__do__5XI:
      {
        self__4UK=self__6XI;
        other__5UK=lower__HTI;
        if (((self__4UK>other__5UK) | (self__4UK==other__5UK))) {
          i__VTI=self__6XI;
          self__GTI[(i__VTI-(((signed long )(( 0)))-offset__JTI))]=self__GTI[i__VTI];
          self__6XI=(self__6XI-((signed long )(( 1))));
          goto downto__do__5XI;
        };
      };
    };
  };
}

static char make_file__Y0I(void *new_path__00I)
// INSTALL_LISAAC make_file(INSTALL_LISAAC,NULLxSTRING)
{
  void  *stream__20I;
  signed char *p__10I;
  char result__30I;
  result__30I=FALSE;
  stream__20I=NULL;
  p__10I=NULL;
  p__10I=to_external__5FE(new_path__00I);
  stream__20I=((void  *)(fopen((char*)(p__10I),"w+b")));
  result__30I=(stream__20I!=NULL);
  if (result__30I) {
    fclose((FILE*)((stream__20I)));
  };
  return(result__30I);
}

static void error__X1I(void *st__Z1I)
// INSTALL_LISAAC error(INSTALL_LISAAC,NULLxSTRING_CONSTANT)
{
  print__3XD(new_intern__6O(__string_66, 7));
  print__3XD(st__Z1I);
  exit((exit_failure_code__IR));
}

static void write__with__size__D3I(void  *f__F3I,void *buf__G3I,signed long sz__H3I)
// INSTALL_LISAAC write__with__size(INSTALL_LISAAC,POINTER,NULLxSTRING,INTEGER)
{
  signed char *ptr__I3I;
  ptr__I3I=NULL;
  ptr__I3I=to_external__5FE(buf__G3I);
  ((signed long )(fwrite((void *)((ptr__I3I)),(size_t)(1), (size_t)((sz__H3I)),(FILE*)((f__F3I)))));
}

static void *to_string__QOJ(void *self__ROJ)
// ABSTRACT_STRING to_string(STRING)
{
  void *result__YOJ,*str__XOJ;
  str__XOJ=self__ROJ;
  result__YOJ=NULL;
  result__YOJ=create__FZF(((struct __STRING *)str__XOJ)->parent_abstract_string__HM.count__JP);
  copy__H2F(result__YOJ,str__XOJ);
  return(result__YOJ);
}

static signed char code__69(signed char self__79)
// CHARACTER code(CHARACTER)
{
  signed char result__89;
  result__89= 0;
  result__89=((signed char )((self__79)));
  return(result__89);
}

static void make__9PB(void *self__AQB,unsigned long siz__BQB)
// MEM_BLOCK make(MEM_BLOCK,UINTEGER)
{
  ((struct __MEM_BLOCK *)self__AQB)->size_and_flags__5U=siz__BQB;
  ((struct __MEM_BLOCK *)self__AQB)->next_same__8U=NULL;
  ((struct __MEM_BLOCK *)self__AQB)->prev_same__7U=((struct __MEM_BLOCK *)self__AQB)->next_same__8U;
  ((struct __MEM_BLOCK *)self__AQB)->prev__6U=((struct __MEM_BLOCK *)self__AQB)->prev_same__7U;
}

static char is_small_busy__9VC(void *self__EVC,unsigned long sz__FVC)
// MEM_BLOCK is_small_busy(MEM_BLOCK,UINTEGER)
{
  return(__infix_less__J3B((size__52B(self__EVC)-to_uinteger__UVC(((struct __MEM_BLOCK *)self__EVC)->small_size__9U)),sz__FVC));
}

static unsigned long size__52B(void *self__62B)
//- MEM_BLOCK size(MEM_BLOCK)
{
  unsigned long ___tmp__72B;
  ___tmp__72B=((struct __MEM_BLOCK *)self__62B)->size_and_flags__5U;
  return((___tmp__72B&((unsigned long )(( 4294967294LU)))));
}

static char __infix_less__J3B(unsigned long self__K3B,unsigned long other__L3B)
// NUMERIC __infix_less(UINTEGER,UINTEGER)
{
  unsigned long self__T3B,other__U3B;
  char ___tmp__Y3B;
  self__T3B=self__K3B;
  other__U3B=other__L3B;
  ___tmp__Y3B=(self__T3B>other__U3B);
  return((! (___tmp__Y3B | (self__T3B==other__U3B))));
}

static void *get_next__WHC(void *block__YHC)
// MEMORY get_next(MEMORY,MEM_BLOCKxNULL)
{
  void *result__ZHC;
  unsigned long next__0HC;
  result__ZHC=NULL;
  next__0HC= 0;
  next__0HC=((((unsigned long )((block__YHC)))-(((unsigned long )(( 0)))-object_size__GV))-(((unsigned long )(( 0)))-size__52B(block__YHC)));
  if ((next__0HC!=(end_memory__ES-(((unsigned long )(( 0)))-((unsigned long )(( 1))))))) {
    result__ZHC=((void *)((next__0HC)));
  };
  return(result__ZHC);
}

static char is_free__KAF(void *self__67B)
// MEM_BLOCK is_free(MEM_BLOCK)
{
  return((! ((((struct __MEM_BLOCK *)self__67B)->size_and_flags__5U&((unsigned long )(( 1))))!= 0)));
}

static void clear__to__FQF(signed char *self__GQF,signed long lower__HQF,signed long upper__IQF)
// NATIVE_ARRAY clear__to(NATIVE_ARRAY,INTEGER,INTEGER)
{
  signed long self__2RF;
  self__2RF=lower__HQF;
  while ((! (self__2RF>upper__IQF))) {
    self__GQF[self__2RF]='\0';
    self__2RF=(self__2RF-(((signed long )(( 0)))-((signed long )(( 1)))));
  };
}

static unsigned long to_uinteger__UVC(unsigned short self__VUC)
// USHORTINT to_uinteger(USHORTINT)
{
  return(((unsigned long )((self__VUC))));
}

