// ANSI C code generated by Lisaac compiler (www.isaacOS.com) //

/*
 * EXTERNAL
 */

#include <time.h> /* SYSTEM */
#include <stdio.h>
  
// Hardware 'print_char'
int print_char(char car)
{
  fputc(car,stdout);
}

// Hardware 'exit'
int die_with_code(int code)
{
  exit(code);
}

 /* SYSTEM_IO */

/*
 * STRING CONSTANT
 */

signed char *__string_0="Number of discus: ";
signed char *__string_1="Error in INPUT_STREAM.read_integer.\n";
signed char *__string_2="Crash system.\n";
signed char *__string_3="Usage: hanoi <NumberOfDiscus>\n";
signed char *__string_4="hanoi: bad argument (not an integer)\n";
signed char *__string_5="Situation at the beginning:\n";
signed char *__string_6="Situation at the end:\n";

/*
 * STRUCT
 */

// Generic Object
struct ___OBJ {
  unsigned long __id;
};

// ABSTRACT_STRING
struct __ABSTRACT_STRING {
  signed char *storage__CP;
  signed long count__DP;
};

// STRING_CONSTANT
struct __STRING_CONSTANT {
  struct __ABSTRACT_STRING parent_abstract_string__WH;
};

// HANOI
struct __HANOI {
  signed long nb__JK;
  void *tower1__KK;
  void *tower2__LK;
  void *tower3__MK;
};

// TOWER
struct __TOWER {
  void *t__5L;
  signed long top__6L;
};

// MEM_BLOCK
struct __MEM_BLOCK {
  unsigned long size_and_flags__3T 	__attribute__ ((packed));
  void *prev__4T 	__attribute__ ((packed));
  void *prev_same__5T 	__attribute__ ((packed));
  void *next_same__6T 	__attribute__ ((packed));
  unsigned short small_size__7T 	__attribute__ ((packed));
  unsigned short first_free__8T 	__attribute__ ((packed));
} 	__attribute__ ((packed));

// ARRAYED_COLLECTION
struct __ARRAYED_COLLECTION__INTEGER {
  signed long *storage__IUF;
  signed long capacity__JUF;
  signed long upper__KUF;
};

// ARRAY
struct __ARRAY__INTEGER {
  struct __ARRAYED_COLLECTION__INTEGER parent_arrayed_collection__5RF;
  signed long lower__6RF;
};


/*
 * GLOBAL
 */

// NULL
#ifndef NULL
#define NULL ((void *)0)
#endif
// TRUE
#define TRUE 1
// FALSE
#define FALSE 0
// INTEGER
signed long object_size__JH;
// ABSTRACT_STRING
signed long lower__EP;
struct __ABSTRACT_STRING ABSTRACT_STRING__;
#define ABSTRACT_STRING (&ABSTRACT_STRING__)
// STRING_CONSTANT
struct __STRING_CONSTANT STRING_CONSTANT__;
#define STRING_CONSTANT (&STRING_CONSTANT__)
// HANOI
signed long ___glob_count_arg__SK;
signed char **___glob_list_arg__TK;
struct __HANOI HANOI__;
#define HANOI (&HANOI__)
// TOWER
struct __TOWER TOWER__;
#define TOWER (&TOWER__)
// OBJECT
signed long exit_failure_code__7N;
// MEMORY
void **small_fat__IR;
void *first_free__JR;
unsigned long begin_memory__KR;
unsigned long end_memory__LR;
unsigned long capacity__MR;
void *last_block__NR;
// MEM_BLOCK
unsigned long object_size__EU;
struct __MEM_BLOCK MEM_BLOCK__;
#define MEM_BLOCK (&MEM_BLOCK__)
// SYSTEM
unsigned long get_begin_memory__2X;
unsigned long get_capacity_memory__3X;
// STD_INPUT
signed char memory__89;
// INPUT_STREAM
char push_back_flag__JAB;
signed long last_integer__KAB;
// ARRAYED_COLLECTION
struct __ARRAYED_COLLECTION__INTEGER ARRAYED_COLLECTION__INTEGER__;
#define ARRAYED_COLLECTION__INTEGER (&ARRAYED_COLLECTION__INTEGER__)
// ARRAY
struct __ARRAY__INTEGER ARRAY__INTEGER__;
#define ARRAY__INTEGER (&ARRAY__INTEGER__)

/*
 * PROTOTYPE
 */

int main(signed long ___count_arg__QK,signed char **___list_arg__RK);
static unsigned long to_uinteger__7Z(int self__8Z);
static signed long to_integer__PN(int self__QN);
static unsigned long realloc_c__20(unsigned long beg__40,unsigned long nb__50);
static signed long upper__0M();
static void *new_intern__0O(signed char *p__2O,signed long nb_char__3O);
static void print__DWD(void *self__EWD);
static char __infix_greater__F4D(signed long self__G4D,signed long other__H4D);
static char is_separator__15D(signed char self__25D);
static char is_digit__I8D(signed char self__J8D);
static signed long decimal_value__DBE(signed char self__EBE);
static signed long __prefix_sub__JSB(signed long self__KSB);
static signed long __infix_sub__YSB(signed long self__ZSB,signed long other__0SB);
static char end_of_input__FKE();
static char __infix_greater_equal__YIB(signed long self__ZIB,signed long other__0IB);
static char __infix_less_equal__QYD(signed long self__RYD,signed long other__SYD);
static void exit__LDB(signed long code__NDB);
static void die_with_code__LTE(signed long code__NTE);
static void *item__EUE(signed long idx__GUE);
static char __infix_greater__8IB(signed long self__9IB,signed long other__AJB);
static signed char item__DZD(void *self__EZD,signed long index__FZD);
static int to_numeric__8JD(signed long self__9JD);
static int __infix_mul__A7E(int self__B7E,int other__C7E);
static int __infix_sub__J7E(int self__K7E,int other__L7E);
static int __infix_add__C8E(int self__D8E,int other__E8E);
static signed long __infix_add__9RB(signed long self__ASB,signed long other__BSB);
static void *clone__TPF();
static void *create__to__5TF(signed long max_index__8TF);
static void put__to__TKG(void *self__UKG,signed long element__VKG,signed long i__WKG);
static signed long __infix_sub__KN(signed long self__LN,signed long other__MN);
static void *empty__2QG(signed long n__4QG);
static void move__ZTG(void *self__0TG,signed long how_many__1TG,void *source__2TG,void *intermediate__3TG,void *destination__4TG);
static void print__5UG(void *self__6UG);
static void print_nbx__01(unsigned long n__21);
static void print__09(signed char self__19);
static void  *allocation__HT(signed long nb__JT);
static void copy__from__size__CDD(void  *dst__EDD,void  *src__FDD,signed long n__GDD);
static void put_character__DBB(signed char c__FBB);
static signed char code__N8(signed char self__O8);
static char __infix_greater__Q6(signed char self__R6,signed char other__S6);
static char __infix_equal_equal__X6(signed char self__Y6,signed char other__Z6);
static signed char item__F0D(signed char *self__G0D,signed long index__H0D);
static int __prefix_sub__G0B(int self__H0B);
static int __infix_sub__0CB(int self__1CB,int other__2CB);
static void put__to__Q5F(signed long *self__R5F,signed long element__S5F,signed long index__T5F);
static void count__BBG(void *self__CBG);
static signed long item__4XG(void *self__5XG,signed long i__6XG);
static void show_a_discus__TWG(void *self__UWG,signed long d__VWG);
static int __infix_add__B0B(int self__C0B,int other__D0B);
static char __infix_greater_equal__D3(int self__E3,int other__F3);
static unsigned long __infix_and__L4(unsigned long self__M4,unsigned long other__N4);
static signed char to_smallint__85(int self__95);
static signed char to_character__L7(signed char self__M7);
static signed char __infix_add__F8(signed char self__G8,signed char other__H8);
static unsigned long __infix_sub__FFB(unsigned long self__GFB,unsigned long other__HFB);
static unsigned long __infix_add__PFB(unsigned long self__QFB,unsigned long other__RFB);
static unsigned long __prefix_logicnot__LGB(unsigned long self__MGB);
static unsigned long __infix_and__8GB(unsigned long self__9GB,unsigned long other__AHB);
static void put__to__UJB(void **self__VJB,signed long index__XJB);
static unsigned long __infix_add__4MB(unsigned long self__5MB,unsigned long other__6MB);
static void *get_block__KNB(unsigned long p__MNB);
static unsigned long __infix_sub__BGB(unsigned long self__CGB,unsigned long other__DGB);
static void make__JOB(void *self__KOB,unsigned long siz__LOB);
static signed long __infix_and__8SB(signed long self__9SB,signed long other__ATB);
static unsigned long to_uinteger__GTB(signed long self__HTB);
static char is_small_busy__NTC(void *self__OTC,unsigned long sz__PTC);
static unsigned long size__F1B(void *self__G1B);
static char __infix_less__T1B(unsigned long self__U1B,unsigned long other__V1B);
static char is_free__F6B(void *self__G6B);
static void set_size__E7B(void *self__F7B,unsigned long sz__G7B);
static void set_prev__S9B(void *self__T9B,void *block__U9B);
static void set_next_same__X9B(void *self__Y9B,void *block__Z9B);
static void set_prev_same__99B(void *self__AAC,void *block__BAC);
static void to_busy__8AC(void *self__9AC);
static int to_numeric__3DC(unsigned long self__4DC);
static int __infix_add__UDC(int other__WDC);
static char __infix_greater__HEC(unsigned long self__IEC,unsigned long other__JEC);
static unsigned long get_adress__ZEC(void *self__0EC);
static void *get_next__6FC(void *block__8FC);
static unsigned short to_ushortint__7IC(int self__8IC);
static void put__to__SJC(void **self__TJC,void *element__UJC,unsigned long index__VJC);
static unsigned short __infix_sub__VSC(unsigned short self__WSC,unsigned short other__XSC);
static unsigned long to_uinteger__4SC(unsigned short self__5SC);
static unsigned long to_uinteger__9HD(void  *self__AID);
static unsigned long *force_conversion__DJD(unsigned long obj__FJD);
static char __infix_less_equal__JKD(int self__KKD,int other__LKD);
static unsigned long item__6KD(unsigned long *self__7KD,signed long index__8KD);
static void put__to__XLD(unsigned long *self__YLD,unsigned long element__ZLD,signed long index__0LD);
static unsigned long __infix_add__4OD(unsigned long self__5OD,unsigned long other__6OD);
static unsigned char *force_conversion__SQD(unsigned long obj__UQD);
static unsigned char item__4RD(unsigned char *self__5RD,signed long index__6RD);
static void put__to__VSD(unsigned char *self__WSD,unsigned char element__XSD,signed long index__YSD);
static char __infix_greater__L3(int self__M3,int other__N3);
static signed char __infix_sub__S9(signed char self__T9,signed char other__U9);
static unsigned long __prefix_sub__WFB(unsigned long self__XFB);

/*
 * SOURCE CODE
 */

void copy_object(void *dst,void *src,int n)
{ int cpt,i;                               
  unsigned long *dst_l, *src_l;            
  unsigned char *dst_b, *src_b;            
                                           
  cpt = n >> 2;                            
  dst_l = (unsigned long *)dst;            
  src_l = (unsigned long *)src;            
  for (i=0 ; i<cpt ; i++) {                
    *dst_l = *src_l;                       
    dst_l++;                               
    src_l++;                               
  };                                       
  cpt = n & 3;                             
  dst_b = (unsigned char *)src_l;          
  src_b = (unsigned char *)dst_l;          
  for (i=0 ; i<cpt ; i++) {                
    *dst_b = *src_b;                       
    dst_b++;                               
    src_b++;                               
  };                                       
}                                          
//////////// MAIN ////////////
int main(signed long ___count_arg__QK,signed char **___list_arg__RK)
// HANOI - ANSI code -
{
  signed long ___tmp__6XD,___tmp__KRE,___tmp__23F,self__ILE,___tmp__TLE;
  char result__B8D,result__SEE,___tmp__91D,___tmp__B2D,___tmp__E2D;
  char sign__V1D,result__WSE,result__Y1E,result__R2E,___tmp__3YE;
  char ___tmp__4YE,result__P4E,___tmp__QZE,result__D6E,result__5BF;
  signed long ___tmp__WLE,self__KNE,___tmp__VNE,___tmp__YNE,state__U1D;
  char ___tmp__8YE,___tmp__EZE,___tmp__TZE,negative__UYE,result__VYE;
  char result__JHF,___tmp__TEF,result__GJF,result__MKF,result__ENF;
  signed long i__RYE,state__SYE,value__TYE,i__HEF,state__IEF;
  signed long result__LEF,result__DOF,self__BOF,other__COF,___tmp__HOF;
  signed long i__3SF,i__6NG,self__QJG,limit_down__RJG,___tmp__ZJG;
  char ___tmp__WEF,___tmp__0EF,___tmp__6EF,negative__KEF,___tmp__JL;
  void *self__1Z,*self__QYE,*self__GEF,*self__YRF,*result__OPF;
  unsigned long ___tmp__6Z,___tmp__ZNB;
  signed char cc__WYE,cc__JEF;
  signed long n__ZRF,___tmp__FM,self__MNG;
  char ___tmp__PL;
  ___glob_count_arg__SK=___count_arg__QK;
  ___glob_list_arg__TK=___list_arg__RK;
  ___tmp__6Z=to_uinteger__7Z( 268435456);
  ___tmp__ZNB=to_uinteger__7Z( 16);
  ___tmp__6XD=to_integer__PN( 1);
  ___tmp__KRE=to_integer__PN( 1);
  ___tmp__23F=to_integer__PN( 4);
  capacity__MR= 0;
  get_capacity_memory__3X=___tmp__6Z;
  get_begin_memory__2X=realloc_c__20(to_uinteger__7Z( 0),get_capacity_memory__3X);
  begin_memory__KR= 0;
  end_memory__LR= 0;
  small_fat__IR=NULL;
  last_block__NR=NULL;
  object_size__EU=___tmp__ZNB;
  MEM_BLOCK__.size_and_flags__3T= 0;
  MEM_BLOCK__.next_same__6T=NULL;
  MEM_BLOCK__.prev_same__5T=NULL;
  MEM_BLOCK__.prev__4T=NULL;
  first_free__JR=NULL;
  MEM_BLOCK__.small_size__7T= 0;
  MEM_BLOCK__.first_free__8T= 0;
  ABSTRACT_STRING__.storage__CP=NULL;
  STRING_CONSTANT__.parent_abstract_string__WH.storage__CP=ABSTRACT_STRING__.storage__CP;
  ABSTRACT_STRING__.count__DP= 0;
  STRING_CONSTANT__.parent_abstract_string__WH.count__DP=ABSTRACT_STRING__.count__DP;
  lower__EP=___tmp__6XD;
  push_back_flag__JAB=FALSE;
  memory__89='\0';
  last_integer__KAB= 0;
  exit_failure_code__7N=___tmp__KRE;
  HANOI__.nb__JK= 0;
  ARRAY__INTEGER__.lower__6RF= 0;
  ARRAYED_COLLECTION__INTEGER__.upper__KUF= 0;
  ARRAY__INTEGER__.parent_arrayed_collection__5RF.upper__KUF=ARRAYED_COLLECTION__INTEGER__.upper__KUF;
  ARRAYED_COLLECTION__INTEGER__.capacity__JUF= 0;
  ARRAY__INTEGER__.parent_arrayed_collection__5RF.capacity__JUF=ARRAYED_COLLECTION__INTEGER__.capacity__JUF;
  object_size__JH=___tmp__23F;
  ARRAYED_COLLECTION__INTEGER__.storage__IUF=NULL;
  ARRAY__INTEGER__.parent_arrayed_collection__5RF.storage__IUF=ARRAYED_COLLECTION__INTEGER__.storage__IUF;
  TOWER__.t__5L=NULL;
  TOWER__.top__6L= 0;
  HANOI__.tower1__KK=NULL;
  HANOI__.tower2__LK=NULL;
  HANOI__.tower3__MK=NULL;
  if ((upper__0M()== 0)) {
    print__DWD(new_intern__0O(__string_0, 18));
    sign__V1D=FALSE;
    state__U1D= 0;
    while ((! __infix_greater__F4D(state__U1D,to_integer__PN( 2)))) {
      if (push_back_flag__JAB) {
        push_back_flag__JAB=FALSE;
      } else {
        memory__89=((signed char )(fgetc(stdin)));
      };
      if ((state__U1D== 0)) {
        if (is_separator__15D(memory__89)) {
          ___tmp__91D=TRUE;
        } else {
          result__B8D=FALSE;
          result__B8D=is_digit__I8D(memory__89);
          if (result__B8D) {
            last_integer__KAB=decimal_value__DBE(memory__89);
            state__U1D=to_integer__PN( 2);
          };
          ___tmp__91D=result__B8D;
        };
        if (___tmp__91D) {
          ___tmp__B2D=TRUE;
        } else {
          result__SEE=FALSE;
          result__SEE=(memory__89=='-');
          if (result__SEE) {
            sign__V1D=TRUE;
            state__U1D=to_integer__PN( 1);
          };
          ___tmp__B2D=result__SEE;
        };
        if (___tmp__B2D) {
        } else {
          if ((memory__89=='+')) {
            state__U1D=to_integer__PN( 1);
          } else {
            state__U1D=to_integer__PN( 4);
          };
        };
        ___tmp__E2D=TRUE;
      } else {
        ___tmp__E2D=FALSE;
      };
      if (___tmp__E2D) {
      } else {
        if ((state__U1D== 1)) {
          if (is_separator__15D(memory__89)) {
          } else {
            if (is_digit__I8D(memory__89)) {
              last_integer__KAB=decimal_value__DBE(memory__89);
              state__U1D=to_integer__PN( 2);
            } else {
              state__U1D=to_integer__PN( 4);
            };
          };
        } else {
          if (is_digit__I8D(memory__89)) {
            last_integer__KAB=__infix_sub__YSB((last_integer__KAB*to_integer__PN( 10)),__prefix_sub__JSB(decimal_value__DBE(memory__89)));
          } else {
            state__U1D=to_integer__PN( 3);
          };
        };
      };
      if (end_of_input__FKE()) {
        ___tmp__TLE=to_integer__PN( 0);
        ___tmp__WLE=to_integer__PN( 1);
        self__ILE=state__U1D;
        if ((__infix_greater_equal__YIB(self__ILE,___tmp__TLE) && __infix_less_equal__QYD(self__ILE,___tmp__WLE))) {
          state__U1D=to_integer__PN( 4);
        };
        ___tmp__VNE=to_integer__PN( 2);
        ___tmp__YNE=to_integer__PN( 3);
        self__KNE=self__ILE;
        if ((__infix_greater_equal__YIB(self__KNE,___tmp__VNE) && __infix_less_equal__QYD(self__KNE,___tmp__YNE))) {
          state__U1D=to_integer__PN( 3);
        };
      };
    };
    if (end_of_input__FKE()) {
      push_back_flag__JAB=TRUE;
    };
    if ((state__U1D== 4)) {
      print__DWD(new_intern__0O(__string_1, 36));
      print__DWD(new_intern__0O(__string_2, 14));
      exit__LDB(exit_failure_code__7N);
    };
    if (sign__V1D) {
      last_integer__KAB=__prefix_sub__JSB(last_integer__KAB);
    };
    HANOI__.nb__JK=last_integer__KAB;
    ___tmp__JL=TRUE;
  } else {
    ___tmp__JL=FALSE;
  };
  if (___tmp__JL) {
    ___tmp__PL=TRUE;
  } else {
    result__WSE=FALSE;
    result__WSE=(upper__0M()!= 1);
    if (result__WSE) {
      print__DWD(new_intern__0O(__string_3, 30));
      die_with_code__LTE(exit_failure_code__7N);
    };
    ___tmp__PL=result__WSE;
  };
  if (___tmp__PL) {
  } else {
    self__QYE=item__EUE(to_integer__PN( 1));
    result__VYE=FALSE;
    value__TYE= 0;
    negative__UYE=FALSE;
    cc__WYE='\0';
    state__SYE= 0;
    i__RYE= 0;
    i__RYE=to_integer__PN( 1);
    while ((! ((state__SYE== 4) || __infix_greater__8IB(i__RYE,((struct __STRING_CONSTANT *)self__QYE)->parent_abstract_string__WH.count__DP)))) {
      cc__WYE=item__DZD(self__QYE,i__RYE);
      if ((state__SYE== 0)) {
        if (is_separator__15D(cc__WYE)) {
          ___tmp__3YE=TRUE;
        } else {
          result__Y1E=FALSE;
          result__Y1E=(cc__WYE=='+');
          if (result__Y1E) {
            state__SYE=to_integer__PN( 1);
          };
          ___tmp__3YE=result__Y1E;
        };
        if (___tmp__3YE) {
          ___tmp__4YE=TRUE;
        } else {
          result__R2E=FALSE;
          result__R2E=(cc__WYE=='-');
          if (result__R2E) {
            negative__UYE=TRUE;
            state__SYE=to_integer__PN( 1);
          };
          ___tmp__4YE=result__R2E;
        };
        if (___tmp__4YE) {
        } else {
          if (is_digit__I8D(cc__WYE)) {
            value__TYE=decimal_value__DBE(cc__WYE);
            state__SYE=to_integer__PN( 2);
          } else {
            state__SYE=to_integer__PN( 4);
          };
        };
        ___tmp__8YE=TRUE;
      } else {
        ___tmp__8YE=FALSE;
      };
      if (___tmp__8YE) {
        ___tmp__EZE=TRUE;
      } else {
        result__P4E=FALSE;
        result__P4E=(state__SYE== 1);
        if (result__P4E) {
          if (is_digit__I8D(cc__WYE)) {
            value__TYE=decimal_value__DBE(cc__WYE);
            if (negative__UYE) {
              value__TYE=__prefix_sub__JSB(value__TYE);
            };
            state__SYE=to_integer__PN( 2);
          } else {
            state__SYE=to_integer__PN( 4);
          };
        };
        ___tmp__EZE=result__P4E;
      };
      if (___tmp__EZE) {
        ___tmp__TZE=TRUE;
      } else {
        result__D6E=FALSE;
        result__D6E=(state__SYE== 2);
        if (result__D6E) {
          if (is_digit__I8D(cc__WYE)) {
            if (negative__UYE) {
              value__TYE=to_integer__PN(__infix_sub__J7E(__infix_mul__A7E( 10,to_numeric__8JD(value__TYE)),to_numeric__8JD(decimal_value__DBE(cc__WYE))));
            } else {
              value__TYE=to_integer__PN(__infix_add__C8E(__infix_mul__A7E( 10,to_numeric__8JD(value__TYE)),to_numeric__8JD(decimal_value__DBE(cc__WYE))));
            };
            if (((negative__UYE && __infix_greater__F4D(value__TYE,to_integer__PN( 0))) || ((! negative__UYE) && (! __infix_greater_equal__YIB(value__TYE,to_integer__PN( 0)))))) {
              state__SYE=to_integer__PN( 4);
            };
            ___tmp__QZE=TRUE;
          } else {
            ___tmp__QZE=FALSE;
          };
          if (___tmp__QZE) {
          } else {
            if (is_separator__15D(cc__WYE)) {
              state__SYE=to_integer__PN( 3);
            } else {
              state__SYE=to_integer__PN( 4);
            };
          };
        };
        ___tmp__TZE=result__D6E;
      };
      if (___tmp__TZE) {
      } else {
        result__5BF=FALSE;
        result__5BF=(state__SYE== 3);
        if (result__5BF) {
          if (is_separator__15D(cc__WYE)) {
          } else {
            state__SYE=to_integer__PN( 4);
          };
        };
      };
      i__RYE=__infix_add__9RB(i__RYE,to_integer__PN( 1));
    };
    if (((state__SYE!= 0) && (state__SYE!= 4))) {
      result__VYE=TRUE;
    };
    if (result__VYE) {
      self__GEF=item__EUE(to_integer__PN( 1));
      result__LEF= 0;
      negative__KEF=FALSE;
      state__IEF= 0;
      cc__JEF='\0';
      i__HEF= 0;
      i__HEF=to_integer__PN( 1);
      while ((! __infix_greater__8IB(i__HEF,((struct __STRING_CONSTANT *)self__GEF)->parent_abstract_string__WH.count__DP))) {
        cc__JEF=item__DZD(self__GEF,i__HEF);
        if ((state__IEF== 0)) {
          if (is_separator__15D(cc__JEF)) {
            ___tmp__TEF=TRUE;
          } else {
            result__JHF=FALSE;
            result__JHF=(cc__JEF=='+');
            if (result__JHF) {
              state__IEF=to_integer__PN( 1);
            };
            ___tmp__TEF=result__JHF;
          };
          if (___tmp__TEF) {
          } else {
            if ((cc__JEF=='-')) {
              negative__KEF=TRUE;
              state__IEF=to_integer__PN( 1);
            } else {
              result__LEF=decimal_value__DBE(cc__JEF);
              state__IEF=to_integer__PN( 2);
            };
          };
          ___tmp__WEF=TRUE;
        } else {
          ___tmp__WEF=FALSE;
        };
        if (___tmp__WEF) {
          ___tmp__0EF=TRUE;
        } else {
          result__GJF=FALSE;
          result__GJF=(state__IEF== 1);
          if (result__GJF) {
            result__LEF=decimal_value__DBE(cc__JEF);
            if (negative__KEF) {
              result__LEF=__prefix_sub__JSB(result__LEF);
            };
            state__IEF=to_integer__PN( 2);
          };
          ___tmp__0EF=result__GJF;
        };
        if (___tmp__0EF) {
          ___tmp__6EF=TRUE;
        } else {
          result__MKF=FALSE;
          result__MKF=(state__IEF== 2);
          if (result__MKF) {
            if (is_digit__I8D(cc__JEF)) {
              if (negative__KEF) {
                result__LEF=to_integer__PN(__infix_sub__J7E(__infix_mul__A7E( 10,to_numeric__8JD(result__LEF)),to_numeric__8JD(decimal_value__DBE(cc__JEF))));
              } else {
                result__LEF=to_integer__PN(__infix_add__C8E(__infix_mul__A7E( 10,to_numeric__8JD(result__LEF)),to_numeric__8JD(decimal_value__DBE(cc__JEF))));
              };
            } else {
              state__IEF=to_integer__PN( 3);
            };
          };
          ___tmp__6EF=result__MKF;
        };
        if (___tmp__6EF) {
        } else {
          result__ENF=FALSE;
          result__ENF=(state__IEF== 3);
          if (result__ENF) {
            i__HEF=((struct __STRING_CONSTANT *)self__GEF)->parent_abstract_string__WH.count__DP;
          };
        };
        i__HEF=__infix_add__9RB(i__HEF,to_integer__PN( 1));
      };
      ___tmp__HOF=to_integer__PN( 1);
      self__BOF=result__LEF;
      other__COF=___tmp__HOF;
      result__DOF= 0;
      if (__infix_greater__8IB(self__BOF,other__COF)) {
        result__DOF=self__BOF;
      } else {
        result__DOF=other__COF;
      };
      HANOI__.nb__JK=result__DOF;
    } else {
      print__DWD(new_intern__0O(__string_4, 37));
      die_with_code__LTE(exit_failure_code__7N);
    };
  };
  ___tmp__FM=HANOI__.nb__JK;
  result__OPF=NULL;
  result__OPF=clone__TPF();
  self__YRF=result__OPF;
  n__ZRF=___tmp__FM;
  ((struct __TOWER *)self__YRF)->t__5L=create__to__5TF(n__ZRF);
  ___tmp__ZJG=to_integer__PN( 1);
  self__QJG=n__ZRF;
  limit_down__RJG=___tmp__ZJG;
  if (__infix_greater_equal__YIB(self__QJG,limit_down__RJG)) {
    i__3SF=self__QJG;
    put__to__TKG(((struct __TOWER *)self__YRF)->t__5L,__infix_add__9RB(__infix_sub__YSB(n__ZRF,i__3SF),to_integer__PN( 1)),i__3SF);
    self__MNG=__infix_sub__KN(self__QJG,to_integer__PN( 1));
    while (__infix_greater_equal__YIB(self__MNG,limit_down__RJG)) {
      i__6NG=self__MNG;
      put__to__TKG(((struct __TOWER *)self__YRF)->t__5L,__infix_add__9RB(__infix_sub__YSB(n__ZRF,i__6NG),to_integer__PN( 1)),i__6NG);
      self__MNG=__infix_sub__KN(self__MNG,to_integer__PN( 1));
    };
  };
  ((struct __TOWER *)self__YRF)->top__6L=n__ZRF;
  HANOI__.tower1__KK=result__OPF;
  HANOI__.tower2__LK=empty__2QG(HANOI__.nb__JK);
  HANOI__.tower3__MK=empty__2QG(HANOI__.nb__JK);
  print__DWD(new_intern__0O(__string_5, 28));
  move__ZTG(HANOI,HANOI__.nb__JK,HANOI__.tower1__KK,HANOI__.tower2__LK,HANOI__.tower3__MK);
  print__DWD(new_intern__0O(__string_6, 22));
  print__5UG(HANOI);
}

static unsigned long to_uinteger__7Z(int self__8Z)
// NUMERIC to_uinteger(NUMERIC)
{
  return(((unsigned long )((self__8Z))));
}

static signed long to_integer__PN(int self__QN)
// NUMERIC to_integer(NUMERIC)
{
  return(((signed long )((self__QN))));
}

static unsigned long realloc_c__20(unsigned long beg__40,unsigned long nb__50)
// SYSTEM realloc_c(SYSTEM,UINTEGER,UINTEGER)
{
  unsigned long result__60;
  result__60= 0;
  result__60=((unsigned long )((unsigned long)realloc((void *)(beg__40),(nb__50)+15)));
  if (((beg__40!= 0) && (result__60!=beg__40))) {
    print_nbx__01(beg__40);
    print__09('\n');
    print_nbx__01(result__60);
    print__09('\n');
    exit__LDB(to_integer__PN( 1));
  };
  return(result__60);
}

static signed long upper__0M()
// COMMAND_LINE upper(COMMAND_LINE)
{
  return(__infix_sub__KN(___glob_count_arg__SK,to_integer__PN( 1)));
}

static void *new_intern__0O(signed char *p__2O,signed long nb_char__3O)
// STRING_CONSTANT new_intern(STRING_CONSTANT,NATIVE_ARRAY,INTEGER)
{
  void *result__4O,*result__8Q,*self__5VD;
  void  *ptr__9Q;
  signed long sz__AR;
  result__4O=NULL;
  ptr__9Q=NULL;
  result__8Q=NULL;
  sz__AR= 0;
  sz__AR=sizeof(struct __STRING_CONSTANT);
  if ((sz__AR== 0)) {
    result__8Q=STRING_CONSTANT;
  } else {
    ptr__9Q=allocation__HT(sz__AR);
    copy__from__size__CDD(ptr__9Q,((void  *)((STRING_CONSTANT))),sz__AR);
    result__8Q=((void *)((ptr__9Q)));
  };
  result__4O=result__8Q;
  self__5VD=result__4O;
  ((struct __STRING_CONSTANT *)self__5VD)->parent_abstract_string__WH.storage__CP=p__2O;
  ((struct __STRING_CONSTANT *)self__5VD)->parent_abstract_string__WH.count__DP=nb_char__3O;
  return(result__4O);
}

static void print__DWD(void *self__EWD)
// ABSTRACT_STRING print(STRING_CONSTANT)
{
  void *s__MWD;
  signed long self__EYD,limit_up__FYD;
  s__MWD=self__EWD;
  self__EYD=lower__EP;
  limit_up__FYD=((struct __STRING_CONSTANT *)s__MWD)->parent_abstract_string__WH.count__DP;
  while (__infix_less_equal__QYD(self__EYD,limit_up__FYD)) {
    put_character__DBB(item__DZD(s__MWD,self__EYD));
    self__EYD=__infix_add__9RB(self__EYD,to_integer__PN( 1));
  };
}

static char __infix_greater__F4D(signed long self__G4D,signed long other__H4D)
// NUMERIC __infix_greater(INTEGER,NUMERIC)
{
  return((self__G4D>other__H4D));
}

static char is_separator__15D(signed char self__25D)
// CHARACTER is_separator(CHARACTER)
{
  return((((((((self__25D==' ') || (self__25D=='\t')) || (self__25D=='\n')) || (self__25D=='\r')) || (self__25D=='\0')) || (self__25D=='\f')) || (self__25D=='\v')));
}

static char is_digit__I8D(signed char self__J8D)
// CHARACTER is_digit(CHARACTER)
{
  signed char self__48D,other__58D,___tmp__V8D,___tmp__W8D;
  char result__K8D;
  result__K8D=FALSE;
  ___tmp__V8D=code__N8(self__J8D);
  ___tmp__W8D=code__N8('0');
  self__48D=___tmp__V8D;
  other__58D=___tmp__W8D;
  if ((__infix_greater__Q6(self__48D,other__58D) | __infix_equal_equal__X6(self__48D,other__58D))) {
    result__K8D=(! __infix_greater__Q6(code__N8(self__J8D),code__N8('9')));
  };
  return(result__K8D);
}

static signed long decimal_value__DBE(signed char self__EBE)
// CHARACTER decimal_value(CHARACTER)
{
  signed long result__FBE,result__9BE;
  result__FBE= 0;
  result__9BE= 0;
  result__9BE=((signed long )((code__N8(self__EBE))));
  result__FBE=__infix_sub__KN(result__9BE,to_integer__PN( 48));
  return(result__FBE);
}

static signed long __prefix_sub__JSB(signed long self__KSB)
// NUMERIC __prefix_sub(INTEGER)
{
  return(__infix_sub__YSB(to_integer__PN( 0),self__KSB));
}

static signed long __infix_sub__YSB(signed long self__ZSB,signed long other__0SB)
// NUMERIC __infix_sub(INTEGER,INTEGER)
{
  return((self__ZSB-other__0SB));
}

static char end_of_input__FKE()
// STD_INPUT end_of_input(IO)
{
  char result__HKE;
  result__HKE=FALSE;
  if ((! push_back_flag__JAB)) {
    result__HKE=(memory__89==((signed char )(EOF)));
  };
  return(result__HKE);
}

static char __infix_greater_equal__YIB(signed long self__ZIB,signed long other__0IB)
// NUMERIC __infix_greater_equal(INTEGER,INTEGER)
{
  return((__infix_greater__8IB(self__ZIB,other__0IB) | (self__ZIB==other__0IB)));
}

static char __infix_less_equal__QYD(signed long self__RYD,signed long other__SYD)
// NUMERIC __infix_less_equal(INTEGER,INTEGER)
{
  return((! __infix_greater__8IB(self__RYD,other__SYD)));
}

static void exit__LDB(signed long code__NDB)
//- SYSTEM exit(SYSTEM,INTEGER)
{
  exit((code__NDB));
}

static void die_with_code__LTE(signed long code__NTE)
//- OBJECT die_with_code(HANOI,INTEGER)
{
  exit__LDB(code__NTE);
}

static void *item__EUE(signed long idx__GUE)
// COMMAND_LINE item(COMMAND_LINE,INTEGER)
{
  signed char *arg__HUE;
  signed long idx__GWE,___tmp__AWE;
  arg__HUE=NULL;
  arg__HUE=___glob_list_arg__TK[idx__GUE];
  ___tmp__AWE=to_integer__PN( 1024);
  idx__GWE= 0;
  while ((! (__infix_greater__8IB(idx__GWE,___tmp__AWE) || ('\0'==item__F0D(arg__HUE,idx__GWE))))) {
    idx__GWE=__infix_add__9RB(idx__GWE,to_integer__PN( 1));
  };
  return(new_intern__0O(arg__HUE,idx__GWE));
}

static char __infix_greater__8IB(signed long self__9IB,signed long other__AJB)
// NUMERIC __infix_greater(INTEGER,INTEGER)
{
  return((self__9IB>other__AJB));
}

static signed char item__DZD(void *self__EZD,signed long index__FZD)
// ABSTRACT_STRING item(STRING_CONSTANT,INTEGER)
{
  return(item__F0D(((struct __STRING_CONSTANT *)self__EZD)->parent_abstract_string__WH.storage__CP,__infix_sub__KN(index__FZD,to_integer__PN( 1))));
}

static int to_numeric__8JD(signed long self__9JD)
// NUMERIC to_numeric(INTEGER)
{
  return(((int )((self__9JD))));
}

static int __infix_mul__A7E(int self__B7E,int other__C7E)
// NUMERIC __infix_mul(NUMERIC,INTEGER)
{
  return((self__B7E*other__C7E));
}

static int __infix_sub__J7E(int self__K7E,int other__L7E)
// NUMERIC __infix_sub(NUMERIC,INTEGER)
{
  return((self__K7E-other__L7E));
}

static int __infix_add__C8E(int self__D8E,int other__E8E)
// NUMERIC __infix_add(NUMERIC,INTEGER)
{
  return(__infix_sub__0CB(self__D8E,__prefix_sub__G0B(other__E8E)));
}

static signed long __infix_add__9RB(signed long self__ASB,signed long other__BSB)
// NUMERIC __infix_add(INTEGER,NUMERIC)
{
  return(__infix_sub__YSB(self__ASB,__prefix_sub__JSB(other__BSB)));
}

static void *clone__TPF()
// OBJECT clone(TOWER)
{
  void *result__VPF;
  void  *ptr__WPF;
  signed long sz__XPF;
  ptr__WPF=NULL;
  result__VPF=NULL;
  sz__XPF= 0;
  sz__XPF=sizeof(struct __TOWER);
  if ((sz__XPF== 0)) {
    result__VPF=TOWER;
  } else {
    ptr__WPF=allocation__HT(sz__XPF);
    copy__from__size__CDD(ptr__WPF,((void  *)((TOWER))),sz__XPF);
    result__VPF=((void *)((ptr__WPF)));
  };
  return(result__VPF);
}

static void *create__to__5TF(signed long max_index__8TF)
// ARRAY create__to(ARRAY,NUMERIC,INTEGER)
{
  signed long sz__LVF,capacity__Y2F,*result__02F,___tmp__71F,self__04F;
  signed long limit_down__14F,___tmp__94F,*self__P4F,*result__31F;
  signed long nb_elements__21F,___tmp__7AG,self__2CG,limit_down__3CG;
  signed long ___tmp__BDG,*self__RCG,*___tmp__4AG,needed__WXF;
  void *result__9TF,*result__JVF,*self__X1F,*self__0AG,*self__TXF;
  void  *ptr__KVF,*p__Z2F;
  signed long max_index__VXF,self__O7F,self__6DG;
  result__9TF=NULL;
  ptr__KVF=NULL;
  result__JVF=NULL;
  sz__LVF= 0;
  sz__LVF=sizeof(struct __ARRAY__INTEGER);
  if ((sz__LVF== 0)) {
    result__JVF=ARRAY__INTEGER;
  } else {
    ptr__KVF=allocation__HT(sz__LVF);
    copy__from__size__CDD(ptr__KVF,((void  *)((ARRAY__INTEGER))),sz__LVF);
    result__JVF=((void *)((ptr__KVF)));
  };
  result__9TF=result__JVF;
  self__TXF=result__9TF;
  max_index__VXF=max_index__8TF;
  needed__WXF= 0;
  ((struct __ARRAY__INTEGER *)self__TXF)->lower__6RF=to_integer__PN( 1);
  ((struct __ARRAY__INTEGER *)self__TXF)->parent_arrayed_collection__5RF.upper__KUF=max_index__VXF;
  needed__WXF=__infix_add__9RB(__infix_sub__KN(max_index__VXF,to_integer__PN( 1)),to_integer__PN( 1));
  if (__infix_greater__F4D(needed__WXF,to_integer__PN( 0))) {
    if ((! __infix_greater_equal__YIB(((struct __ARRAY__INTEGER *)self__TXF)->parent_arrayed_collection__5RF.capacity__JUF,needed__WXF))) {
      self__X1F=self__TXF;
      nb_elements__21F=needed__WXF;
      result__31F=NULL;
      result__02F=NULL;
      p__Z2F=NULL;
      capacity__Y2F= 0;
      capacity__Y2F=(nb_elements__21F*object_size__JH);
      p__Z2F=allocation__HT(capacity__Y2F);
      result__02F=((signed long *)((void*)(p__Z2F)));
      result__31F=result__02F;
      ___tmp__71F=__infix_sub__KN(nb_elements__21F,to_integer__PN( 1));
      self__P4F=result__31F;
      ___tmp__94F=to_integer__PN( 0);
      self__04F=___tmp__71F;
      limit_down__14F=___tmp__94F;
      if (__infix_greater_equal__YIB(self__04F,limit_down__14F)) {
        put__to__Q5F(self__P4F, 0,self__04F);
        self__O7F=__infix_sub__KN(self__04F,to_integer__PN( 1));
        while (__infix_greater_equal__YIB(self__O7F,limit_down__14F)) {
          put__to__Q5F(self__P4F, 0,self__O7F);
          self__O7F=__infix_sub__KN(self__O7F,to_integer__PN( 1));
        };
      };
      ((struct __ARRAY__INTEGER *)self__X1F)->parent_arrayed_collection__5RF.storage__IUF=result__31F;
      ((struct __ARRAY__INTEGER *)self__X1F)->parent_arrayed_collection__5RF.capacity__JUF=needed__WXF;
    } else {
      self__0AG=self__TXF;
      count__BBG(self__0AG);
      ___tmp__4AG=((struct __ARRAY__INTEGER *)self__0AG)->parent_arrayed_collection__5RF.storage__IUF;
      ___tmp__7AG=__infix_sub__YSB(((struct __ARRAY__INTEGER *)self__0AG)->parent_arrayed_collection__5RF.upper__KUF,((struct __ARRAY__INTEGER *)self__0AG)->lower__6RF);
      self__RCG=___tmp__4AG;
      ___tmp__BDG=to_integer__PN( 0);
      self__2CG=___tmp__7AG;
      limit_down__3CG=___tmp__BDG;
      if (__infix_greater_equal__YIB(self__2CG,limit_down__3CG)) {
        put__to__Q5F(self__RCG, 0,self__2CG);
        self__6DG=__infix_sub__KN(self__2CG,to_integer__PN( 1));
        while (__infix_greater_equal__YIB(self__6DG,limit_down__3CG)) {
          put__to__Q5F(self__RCG, 0,self__6DG);
          self__6DG=__infix_sub__KN(self__6DG,to_integer__PN( 1));
        };
      };
    };
  };
  return(result__9TF);
}

static void put__to__TKG(void *self__UKG,signed long element__VKG,signed long i__WKG)
// ARRAY put__to(ARRAY,INTEGER,INTEGER)
{
  count__BBG(self__UKG);
  put__to__Q5F(((struct __ARRAY__INTEGER *)self__UKG)->parent_arrayed_collection__5RF.storage__IUF,element__VKG,__infix_sub__YSB(i__WKG,((struct __ARRAY__INTEGER *)self__UKG)->lower__6RF));
}

static signed long __infix_sub__KN(signed long self__LN,signed long other__MN)
// NUMERIC __infix_sub(INTEGER,NUMERIC)
{
  return((self__LN-other__MN));
}

static void *empty__2QG(signed long n__4QG)
// TOWER empty(TOWER,INTEGER)
{
  void *result__5QG,*self__CRG;
  result__5QG=NULL;
  result__5QG=clone__TPF();
  self__CRG=result__5QG;
  ((struct __TOWER *)self__CRG)->t__5L=create__to__5TF(n__4QG);
  ((struct __TOWER *)self__CRG)->top__6L=to_integer__PN( 1);
  return(result__5QG);
}

static void move__ZTG(void *self__0TG,signed long how_many__1TG,void *source__2TG,void *intermediate__3TG,void *destination__4TG)
// HANOI move(HANOI,INTEGER,NULLxTOWER,NULLxTOWER,NULLxTOWER)
{
  void *self__7DH,*self__7FH;
  signed long discus__5TG,result__8DH,d__8FH;
  discus__5TG= 0;
  if (__infix_greater__F4D(how_many__1TG,to_integer__PN( 0))) {
    move__ZTG(self__0TG,__infix_sub__KN(how_many__1TG,to_integer__PN( 1)),source__2TG,destination__4TG,intermediate__3TG);
    print__5UG(self__0TG);
    self__7DH=source__2TG;
    result__8DH= 0;
    result__8DH=item__4XG(((struct __TOWER *)self__7DH)->t__5L,((struct __TOWER *)self__7DH)->top__6L);
    put__to__TKG(((struct __TOWER *)self__7DH)->t__5L,to_integer__PN( 0),((struct __TOWER *)self__7DH)->top__6L);
    if (__infix_greater__F4D(((struct __TOWER *)self__7DH)->top__6L,to_integer__PN( 1))) {
      ((struct __TOWER *)self__7DH)->top__6L=__infix_sub__KN(((struct __TOWER *)self__7DH)->top__6L,to_integer__PN( 1));
    };
    discus__5TG=result__8DH;
    self__7FH=destination__4TG;
    d__8FH=discus__5TG;
    if (__infix_greater__8IB(item__4XG(((struct __TOWER *)self__7FH)->t__5L,((struct __TOWER *)self__7FH)->top__6L),d__8FH)) {
      ((struct __TOWER *)self__7FH)->top__6L=__infix_add__9RB(((struct __TOWER *)self__7FH)->top__6L,to_integer__PN( 1));
      put__to__TKG(((struct __TOWER *)self__7FH)->t__5L,d__8FH,((struct __TOWER *)self__7FH)->top__6L);
    };
    if ((item__4XG(((struct __TOWER *)self__7FH)->t__5L,((struct __TOWER *)self__7FH)->top__6L)== 0)) {
      put__to__TKG(((struct __TOWER *)self__7FH)->t__5L,d__8FH,((struct __TOWER *)self__7FH)->top__6L);
    };
    move__ZTG(self__0TG,__infix_sub__KN(how_many__1TG,to_integer__PN( 1)),intermediate__3TG,source__2TG,destination__4TG);
  };
}

static void print__5UG(void *self__6UG)
// HANOI print(HANOI)
{
  signed long ___tmp__8UG,i__9UG,i__4AH,self__2VG,limit_down__3VG;
  int self__7CH;
  signed long ___tmp__BWG,self__KAH;
  print__09('\n');
  ___tmp__8UG=((struct __HANOI *)self__6UG)->nb__JK;
  ___tmp__BWG=to_integer__PN( 1);
  self__2VG=___tmp__8UG;
  limit_down__3VG=___tmp__BWG;
  if (__infix_greater_equal__YIB(self__2VG,limit_down__3VG)) {
    i__9UG=self__2VG;
    print__09(' ');
    show_a_discus__TWG(((struct __HANOI *)self__6UG)->tower1__KK,i__9UG);
    print__09(' ');
    show_a_discus__TWG(((struct __HANOI *)self__6UG)->tower2__LK,i__9UG);
    print__09(' ');
    show_a_discus__TWG(((struct __HANOI *)self__6UG)->tower3__MK,i__9UG);
    print__09('\n');
    self__KAH=__infix_sub__KN(self__2VG,to_integer__PN( 1));
    while (__infix_greater_equal__YIB(self__KAH,limit_down__3VG)) {
      i__4AH=self__KAH;
      print__09(' ');
      show_a_discus__TWG(((struct __HANOI *)self__6UG)->tower1__KK,i__4AH);
      print__09(' ');
      show_a_discus__TWG(((struct __HANOI *)self__6UG)->tower2__LK,i__4AH);
      print__09(' ');
      show_a_discus__TWG(((struct __HANOI *)self__6UG)->tower3__MK,i__4AH);
      print__09('\n');
      self__KAH=__infix_sub__KN(self__KAH,to_integer__PN( 1));
    };
  };
  self__7CH=__infix_sub__0CB((__infix_add__B0B(__infix_mul__A7E( 2,to_numeric__8JD(__infix_add__9RB(((struct __HANOI *)self__6UG)->nb__JK,to_integer__PN( 1)))), 1)* 3), 2);
  while (__infix_greater_equal__D3(self__7CH, 1)) {
    to_integer__PN(self__7CH);
    print__09('-');
    self__7CH=__infix_sub__0CB(self__7CH, 1);
  };
  print__09('\n');
}

static void print_nbx__01(unsigned long n__21)
// MEMORY print_nbx(MEMORY,UINTEGER)
{
  int self__22;
  signed char car__I2,self__15,other__25,___tmp__75;
  car__I2= 0;
  self__22= 28;
  while (__infix_greater_equal__D3(self__22, 0)) {
    car__I2=((signed char )((__infix_and__L4(((unsigned long )((n__21)>>(to_integer__PN(self__22)))),to_uinteger__7Z( 15)))));
    ___tmp__75=to_smallint__85( 10);
    self__15=car__I2;
    other__25=___tmp__75;
    if ((__infix_greater__Q6(self__15,other__25) | __infix_equal_equal__X6(self__15,other__25))) {
      print__09(__infix_add__F8('A',to_character__L7((car__I2-to_smallint__85( 10)))));
    } else {
      print__09(__infix_add__F8('0',to_character__L7(car__I2)));
    };
    self__22=__infix_sub__0CB(self__22, 4);
  };
}

static void print__09(signed char self__19)
//- CHARACTER print(CHARACTER)
{
  put_character__DBB(self__19);
}

static void  *allocation__HT(signed long nb__JT)
// MEMORY allocation(MEMORY,INTEGER)
{
  unsigned long result__YT,index__ZU,size__0U,offset__1U,a__4EB;
  void *first_block__WU,*lst_block__XU,*new_block__YU,**self__8HB;
  void **___tmp__KZ,*cur_block__AWB,*p_block__BWB,*n_block__CWB;
  unsigned long ___tmp__AFB,begin__UX,___tmp__9X,size__EWB;
  void *new_block__DWB,*self__KIC,*self__BMC,*cur_block__JVC;
  unsigned long new_size__FWB,add_size__GWB,size__NVC,new_size__OVC;
  signed long self__JIB,limit_down__KIB,___tmp__SIB,___tmp__5HB;
  unsigned short result__DMC;
  void *p_block__KVC,*n_block__LVC,*new_block__MVC;
  unsigned long add_size__PVC;
  signed long self__SLB;
  result__YT= 0;
  offset__1U= 0;
  lst_block__XU=NULL;
  new_block__YU=NULL;
  first_block__WU=NULL;
  index__ZU= 0;
  size__0U= 0;
  if ((capacity__MR== 0)) {
    begin__UX= 0;
    begin_memory__KR=get_begin_memory__2X;
    capacity__MR=get_capacity_memory__3X;
    ___tmp__9X=begin_memory__KR;
    ___tmp__AFB=to_uinteger__7Z( 16);
    a__4EB= 0;
    a__4EB=__infix_sub__FFB(___tmp__AFB,to_uinteger__7Z( 1));
    begin__UX=__infix_and__8GB(__infix_add__PFB(___tmp__9X,a__4EB),__prefix_logicnot__LGB(a__4EB));
    end_memory__LR=__infix_sub__FFB(__infix_add__PFB(begin__UX,capacity__MR),to_uinteger__7Z( 1));
    small_fat__IR=((void **)((begin__UX)));
    ___tmp__KZ=small_fat__IR;
    ___tmp__5HB=to_integer__PN( 63);
    self__8HB=___tmp__KZ;
    ___tmp__SIB=to_integer__PN( 0);
    self__JIB=___tmp__5HB;
    limit_down__KIB=___tmp__SIB;
    if (__infix_greater_equal__YIB(self__JIB,limit_down__KIB)) {
      put__to__UJB(self__8HB,self__JIB);
      self__SLB=__infix_sub__KN(self__JIB,to_integer__PN( 1));
      while (__infix_greater_equal__YIB(self__SLB,limit_down__KIB)) {
        put__to__UJB(self__8HB,self__SLB);
        self__SLB=__infix_sub__KN(self__SLB,to_integer__PN( 1));
      };
    };
    begin__UX=__infix_add__4MB(begin__UX,to_uinteger__7Z( 256));
    last_block__NR=get_block__KNB(begin__UX);
    make__JOB(last_block__NR,__infix_sub__BGB(__infix_sub__BGB(__infix_add__4MB(end_memory__LR,to_uinteger__7Z( 1)),begin__UX),object_size__EU));
    first_free__JR=last_block__NR;
  };
  if ((! __infix_greater__8IB(nb__JT,to_integer__PN( 128)))) {
    size__0U=to_uinteger__GTB(__infix_and__8SB(__infix_add__9RB(nb__JT,to_integer__PN( 1)),to_integer__PN( 254)));
    index__ZU=__infix_sub__FFB(((unsigned long )((size__0U)>>( 1))),to_uinteger__7Z( 1));
    first_block__WU=small_fat__IR[index__ZU];
    if (((first_block__WU==NULL) || is_small_busy__NTC(first_block__WU,size__0U))) {
      new_block__DWB=NULL;
      new_size__FWB= 0;
      n_block__CWB=NULL;
      p_block__BWB=NULL;
      add_size__GWB= 0;
      cur_block__AWB=NULL;
      size__EWB= 0;
      size__EWB=to_uinteger__7Z((__infix_add__B0B( 4096, 15)& 4294967280LU));
      cur_block__AWB=first_free__JR;
      while (((cur_block__AWB!=NULL) && __infix_less__T1B(size__F1B(cur_block__AWB),size__EWB))) {
        cur_block__AWB=((struct __MEM_BLOCK *)cur_block__AWB)->next_same__6T;
      };
      if ((cur_block__AWB==NULL)) {
        add_size__GWB=__infix_and__L4(__infix_add__4MB(__infix_add__4MB(size__EWB,to_uinteger__7Z( 16)),to_uinteger__7Z( 16777215)),to_uinteger__7Z( 4278190080LU));
        capacity__MR=__infix_add__PFB(capacity__MR,add_size__GWB);
        realloc_c__20(begin_memory__KR,capacity__MR);
        if (is_free__F6B(last_block__NR)) {
          cur_block__AWB=last_block__NR;
          set_size__E7B(cur_block__AWB,__infix_add__PFB(size__F1B(cur_block__AWB),add_size__GWB));
        } else {
          cur_block__AWB=get_block__KNB(__infix_add__4MB(end_memory__LR,to_uinteger__7Z( 1)));
          make__JOB(cur_block__AWB,__infix_sub__FFB(add_size__GWB,to_uinteger__7Z( 16)));
          set_prev__S9B(cur_block__AWB,last_block__NR);
          last_block__NR=cur_block__AWB;
          set_next_same__X9B(cur_block__AWB,first_free__JR);
          if ((first_free__JR!=NULL)) {
            set_prev_same__99B(first_free__JR,cur_block__AWB);
          };
          first_free__JR=cur_block__AWB;
        };
        end_memory__LR=__infix_add__PFB(end_memory__LR,add_size__GWB);
      };
      to_busy__8AC(cur_block__AWB);
      p_block__BWB=((struct __MEM_BLOCK *)cur_block__AWB)->prev_same__5T;
      n_block__CWB=((struct __MEM_BLOCK *)cur_block__AWB)->next_same__6T;
      if ((p_block__BWB==NULL)) {
        first_free__JR=n_block__CWB;
      } else {
        set_next_same__X9B(p_block__BWB,n_block__CWB);
      };
      if ((n_block__CWB!=NULL)) {
        set_prev_same__99B(n_block__CWB,p_block__BWB);
      };
      new_size__FWB=__infix_sub__BGB(size__F1B(cur_block__AWB),size__EWB);
      if (__infix_greater__HEC(new_size__FWB,to_uinteger__7Z(__infix_add__UDC(to_numeric__3DC(object_size__EU))))) {
        new_size__FWB=__infix_sub__BGB(new_size__FWB,object_size__EU);
        new_block__DWB=get_block__KNB(__infix_add__PFB(get_adress__ZEC(cur_block__AWB),size__EWB));
        make__JOB(new_block__DWB,new_size__FWB);
        if ((first_free__JR!=NULL)) {
          set_prev_same__99B(first_free__JR,new_block__DWB);
        };
        set_next_same__X9B(new_block__DWB,first_free__JR);
        first_free__JR=new_block__DWB;
        set_size__E7B(cur_block__AWB,size__EWB);
        set_prev__S9B(new_block__DWB,cur_block__AWB);
        n_block__CWB=get_next__6FC(new_block__DWB);
        if ((n_block__CWB==NULL)) {
          last_block__NR=new_block__DWB;
        } else {
          set_prev__S9B(n_block__CWB,new_block__DWB);
        };
      };
      new_block__YU=cur_block__AWB;
      if ((new_block__YU!=NULL)) {
        self__KIC=new_block__YU;
        ((struct __MEM_BLOCK *)self__KIC)->small_size__7T=to_ushortint__7IC( 4);
        ((struct __MEM_BLOCK *)self__KIC)->first_free__8T=to_ushortint__7IC( 0);
        ((struct __MEM_BLOCK *)self__KIC)->next_same__6T=self__KIC;
        ((struct __MEM_BLOCK *)self__KIC)->prev_same__5T=((struct __MEM_BLOCK *)self__KIC)->next_same__6T;
        put__to__SJC(small_fat__IR,new_block__YU,index__ZU);
        if ((first_block__WU!=NULL)) {
          lst_block__XU=((struct __MEM_BLOCK *)first_block__WU)->prev_same__5T;
          ((struct __MEM_BLOCK *)new_block__YU)->next_same__6T=first_block__WU;
          ((struct __MEM_BLOCK *)new_block__YU)->prev_same__5T=lst_block__XU;
          set_next_same__X9B(lst_block__XU,new_block__YU);
          set_prev_same__99B(first_block__WU,new_block__YU);
        };
      };
      first_block__WU=new_block__YU;
    };
    if ((first_block__WU!=NULL)) {
      self__BMC=first_block__WU;
      result__DMC= 0;
      if ((((struct __MEM_BLOCK *)self__BMC)->first_free__8T== 0)) {
        result__DMC=((struct __MEM_BLOCK *)self__BMC)->small_size__7T;
      } else {
        result__DMC=((unsigned short )((((struct __MEM_BLOCK *)self__BMC)->first_free__8T)<<( 1)));
        ((struct __MEM_BLOCK *)self__BMC)->first_free__8T=((unsigned short *)((get_adress__ZEC(self__BMC))))[((struct __MEM_BLOCK *)self__BMC)->first_free__8T];
      };
      ((struct __MEM_BLOCK *)self__BMC)->small_size__7T=__infix_sub__VSC(((struct __MEM_BLOCK *)self__BMC)->small_size__7T,__infix_sub__VSC(to_ushortint__7IC( 0),((unsigned short )((size__0U)))));
      offset__1U=to_uinteger__4SC(result__DMC);
      if ((is_small_busy__NTC(first_block__WU,size__0U) && (! is_small_busy__NTC(((struct __MEM_BLOCK *)first_block__WU)->next_same__6T,size__0U)))) {
        put__to__SJC(small_fat__IR,((struct __MEM_BLOCK *)first_block__WU)->next_same__6T,index__ZU);
      };
      result__YT=__infix_add__PFB(get_adress__ZEC(first_block__WU),offset__1U);
    };
  } else {
    new_block__MVC=NULL;
    new_size__OVC= 0;
    n_block__LVC=NULL;
    p_block__KVC=NULL;
    add_size__PVC= 0;
    cur_block__JVC=NULL;
    size__NVC= 0;
    size__NVC=to_uinteger__GTB(__infix_and__8SB(__infix_add__9RB(nb__JT,to_integer__PN( 15)),to_integer__PN( 4294967280LU)));
    cur_block__JVC=first_free__JR;
    while (((cur_block__JVC!=NULL) && __infix_less__T1B(size__F1B(cur_block__JVC),size__NVC))) {
      cur_block__JVC=((struct __MEM_BLOCK *)cur_block__JVC)->next_same__6T;
    };
    if ((cur_block__JVC==NULL)) {
      add_size__PVC=__infix_and__L4(__infix_add__4MB(__infix_add__4MB(size__NVC,to_uinteger__7Z( 16)),to_uinteger__7Z( 16777215)),to_uinteger__7Z( 4278190080LU));
      capacity__MR=__infix_add__PFB(capacity__MR,add_size__PVC);
      realloc_c__20(begin_memory__KR,capacity__MR);
      if (is_free__F6B(last_block__NR)) {
        cur_block__JVC=last_block__NR;
        set_size__E7B(cur_block__JVC,__infix_add__PFB(size__F1B(cur_block__JVC),add_size__PVC));
      } else {
        cur_block__JVC=get_block__KNB(__infix_add__4MB(end_memory__LR,to_uinteger__7Z( 1)));
        make__JOB(cur_block__JVC,__infix_sub__FFB(add_size__PVC,to_uinteger__7Z( 16)));
        set_prev__S9B(cur_block__JVC,last_block__NR);
        last_block__NR=cur_block__JVC;
        set_next_same__X9B(cur_block__JVC,first_free__JR);
        if ((first_free__JR!=NULL)) {
          set_prev_same__99B(first_free__JR,cur_block__JVC);
        };
        first_free__JR=cur_block__JVC;
      };
      end_memory__LR=__infix_add__PFB(end_memory__LR,add_size__PVC);
    };
    to_busy__8AC(cur_block__JVC);
    p_block__KVC=((struct __MEM_BLOCK *)cur_block__JVC)->prev_same__5T;
    n_block__LVC=((struct __MEM_BLOCK *)cur_block__JVC)->next_same__6T;
    if ((p_block__KVC==NULL)) {
      first_free__JR=n_block__LVC;
    } else {
      set_next_same__X9B(p_block__KVC,n_block__LVC);
    };
    if ((n_block__LVC!=NULL)) {
      set_prev_same__99B(n_block__LVC,p_block__KVC);
    };
    new_size__OVC=__infix_sub__BGB(size__F1B(cur_block__JVC),size__NVC);
    if (__infix_greater__HEC(new_size__OVC,to_uinteger__7Z(__infix_add__UDC(to_numeric__3DC(object_size__EU))))) {
      new_size__OVC=__infix_sub__BGB(new_size__OVC,object_size__EU);
      new_block__MVC=get_block__KNB(__infix_add__PFB(get_adress__ZEC(cur_block__JVC),size__NVC));
      make__JOB(new_block__MVC,new_size__OVC);
      if ((first_free__JR!=NULL)) {
        set_prev_same__99B(first_free__JR,new_block__MVC);
      };
      set_next_same__X9B(new_block__MVC,first_free__JR);
      first_free__JR=new_block__MVC;
      set_size__E7B(cur_block__JVC,size__NVC);
      set_prev__S9B(new_block__MVC,cur_block__JVC);
      n_block__LVC=get_next__6FC(new_block__MVC);
      if ((n_block__LVC==NULL)) {
        last_block__NR=new_block__MVC;
      } else {
        set_prev__S9B(n_block__LVC,new_block__MVC);
      };
    };
    first_block__WU=cur_block__JVC;
    if ((first_block__WU!=NULL)) {
      result__YT=get_adress__ZEC(first_block__WU);
    };
  };
  if ((result__YT== 0)) {
    print__09('M');
    print__09('E');
    print__09('M');
    print__09(':');
    print__09('N');
    print__09('O');
    print__09('T');
    print__09(' ');
    print__09('E');
    print__09('N');
    print__09('O');
    print__09('U');
    print__09('G');
    print__09('H');
    print__09(' ');
    print__09('M');
    print__09('E');
    print__09('M');
    print__09('O');
    print__09('R');
    print__09('Y');
    while (1);
  };
  return(((void  *)((result__YT))));
}

static void copy__from__size__CDD(void  *dst__EDD,void  *src__FDD,signed long n__GDD)
// MEMORY copy__from__size(MEMORY,POINTER,POINTER,INTEGER)
{
  unsigned long *dst_array_32__MED,*src_array_32__NED,dst_int__AGD;
  int limit_up__XJD,limit_up__CRD,self__OND,self__MUD;
  unsigned char *dst_array_8__8FD,*src_array_8__9FD;
  unsigned long src_int__BGD;
  signed long cpt__CGD,i__LGD,i__9ND,i__YGD,i__7UD;
  src_array_8__9FD=NULL;
  dst_array_8__8FD=NULL;
  src_array_32__NED=NULL;
  dst_array_32__MED=NULL;
  cpt__CGD= 0;
  src_int__BGD= 0;
  dst_int__AGD= 0;
  dst_int__AGD=to_uinteger__9HD(dst__EDD);
  src_int__BGD=to_uinteger__9HD(src__FDD);
  cpt__CGD=((signed long )((n__GDD)>>( 2)));
  if ((cpt__CGD!= 0)) {
    dst_array_32__MED=force_conversion__DJD(dst_int__AGD);
    src_array_32__NED=force_conversion__DJD(src_int__BGD);
    limit_up__XJD=to_numeric__8JD(__infix_sub__KN(cpt__CGD,to_integer__PN( 1)));
    if (__infix_less_equal__JKD( 0,limit_up__XJD)) {
      i__LGD=to_integer__PN( 0);
      put__to__XLD(dst_array_32__MED,item__6KD(src_array_32__NED,i__LGD),i__LGD);
      self__OND=__infix_add__B0B( 0, 1);
      while (__infix_less_equal__JKD(self__OND,limit_up__XJD)) {
        i__9ND=to_integer__PN(self__OND);
        put__to__XLD(dst_array_32__MED,item__6KD(src_array_32__NED,i__9ND),i__9ND);
        self__OND=__infix_add__B0B(self__OND, 1);
      };
    };
    dst_int__AGD=__infix_add__4OD(dst_int__AGD,to_uinteger__GTB(__infix_and__8SB(n__GDD,to_integer__PN( 4294967292LU))));
    src_int__BGD=__infix_add__4OD(src_int__BGD,to_uinteger__GTB(__infix_and__8SB(n__GDD,to_integer__PN( 4294967292LU))));
  };
  cpt__CGD=__infix_and__8SB(n__GDD,to_integer__PN( 3));
  if ((cpt__CGD!= 0)) {
    dst_array_8__8FD=force_conversion__SQD(dst_int__AGD);
    src_array_8__9FD=force_conversion__SQD(src_int__BGD);
    limit_up__CRD=to_numeric__8JD(__infix_sub__KN(cpt__CGD,to_integer__PN( 1)));
    if (__infix_less_equal__JKD( 0,limit_up__CRD)) {
      i__YGD=to_integer__PN( 0);
      put__to__VSD(dst_array_8__8FD,item__4RD(src_array_8__9FD,i__YGD),i__YGD);
      self__MUD=__infix_add__B0B( 0, 1);
      while (__infix_less_equal__JKD(self__MUD,limit_up__CRD)) {
        i__7UD=to_integer__PN(self__MUD);
        put__to__VSD(dst_array_8__8FD,item__4RD(src_array_8__9FD,i__7UD),i__7UD);
        self__MUD=__infix_add__B0B(self__MUD, 1);
      };
    };
  };
}

static void put_character__DBB(signed char c__FBB)
//- STD_OUTPUT put_character(IO,CHARACTER)
{
  fputc((int)(c__FBB),stdout);
}

static signed char code__N8(signed char self__O8)
// CHARACTER code(CHARACTER)
{
  signed char result__P8;
  result__P8= 0;
  result__P8=((signed char )((self__O8)));
  return(result__P8);
}

static char __infix_greater__Q6(signed char self__R6,signed char other__S6)
// NUMERIC __infix_greater(SMALLINT,SMALLINT)
{
  return((self__R6>other__S6));
}

static char __infix_equal_equal__X6(signed char self__Y6,signed char other__Z6)
// NUMERIC __infix_equal_equal(SMALLINT,SMALLINT)
{
  return((self__Y6==other__Z6));
}

static signed char item__F0D(signed char *self__G0D,signed long index__H0D)
// NATIVE_ARRAY item(NATIVE_ARRAY,INTEGER)
{
  return(self__G0D[index__H0D]);
}

static int __prefix_sub__G0B(int self__H0B)
// NUMERIC __prefix_sub(NUMERIC)
{
  return(__infix_sub__0CB( 0,self__H0B));
}

static int __infix_sub__0CB(int self__1CB,int other__2CB)
// NUMERIC __infix_sub(NUMERIC,NUMERIC)
{
  return((self__1CB-other__2CB));
}

static void put__to__Q5F(signed long *self__R5F,signed long element__S5F,signed long index__T5F)
//- NATIVE_ARRAY put__to(NATIVE_ARRAY,INTEGER,INTEGER)
{
  self__R5F[index__T5F]=element__S5F;
}

static void count__BBG(void *self__CBG)
//- ARRAY count(ARRAY)
{
  __infix_add__9RB(__infix_sub__YSB(((struct __ARRAY__INTEGER *)self__CBG)->parent_arrayed_collection__5RF.upper__KUF,((struct __ARRAY__INTEGER *)self__CBG)->lower__6RF),to_integer__PN( 1));
}

static signed long item__4XG(void *self__5XG,signed long i__6XG)
// ARRAY item(ARRAY,INTEGER)
{
  return(((struct __ARRAY__INTEGER *)self__5XG)->parent_arrayed_collection__5RF.storage__IUF[__infix_sub__YSB(i__6XG,((struct __ARRAY__INTEGER *)self__5XG)->lower__6RF)]);
}

static void show_a_discus__TWG(void *self__UWG,signed long d__VWG)
// TOWER show_a_discus(TOWER,INTEGER)
{
  signed long nb_of_free_slots__WWG,nb_of_used_slots__XWG,self__8ZG;
  signed long limit_down__9ZG,___tmp__H0G,self__O2G,limit_down__P2G;
  signed long ___tmp__X2G,self__64G,limit_down__74G,___tmp__F5G;
  signed long self__M7G,limit_down__N7G,___tmp__V7G,self__B1G,self__R3G;
  signed long self__95G,self__P8G;
  nb_of_free_slots__WWG= 0;
  nb_of_used_slots__XWG= 0;
  nb_of_used_slots__XWG=item__4XG(((struct __TOWER *)self__UWG)->t__5L,d__VWG);
  nb_of_free_slots__WWG=__infix_sub__YSB(((struct __ARRAY__INTEGER *)((struct __TOWER *)self__UWG)->t__5L)->parent_arrayed_collection__5RF.upper__KUF,nb_of_used_slots__XWG);
  ___tmp__H0G=to_integer__PN( 1);
  self__8ZG=nb_of_free_slots__WWG;
  limit_down__9ZG=___tmp__H0G;
  if (__infix_greater_equal__YIB(self__8ZG,limit_down__9ZG)) {
    print__09(' ');
    self__B1G=__infix_sub__KN(self__8ZG,to_integer__PN( 1));
    while (__infix_greater_equal__YIB(self__B1G,limit_down__9ZG)) {
      print__09(' ');
      self__B1G=__infix_sub__KN(self__B1G,to_integer__PN( 1));
    };
  };
  ___tmp__X2G=to_integer__PN( 1);
  self__O2G=nb_of_used_slots__XWG;
  limit_down__P2G=___tmp__X2G;
  if (__infix_greater_equal__YIB(self__O2G,limit_down__P2G)) {
    print__09('=');
    self__R3G=__infix_sub__KN(self__O2G,to_integer__PN( 1));
    while (__infix_greater_equal__YIB(self__R3G,limit_down__P2G)) {
      print__09('=');
      self__R3G=__infix_sub__KN(self__R3G,to_integer__PN( 1));
    };
  };
  print__09('|');
  ___tmp__F5G=to_integer__PN( 1);
  self__64G=nb_of_used_slots__XWG;
  limit_down__74G=___tmp__F5G;
  if (__infix_greater_equal__YIB(self__64G,limit_down__74G)) {
    print__09('=');
    self__95G=__infix_sub__KN(self__64G,to_integer__PN( 1));
    while (__infix_greater_equal__YIB(self__95G,limit_down__74G)) {
      print__09('=');
      self__95G=__infix_sub__KN(self__95G,to_integer__PN( 1));
    };
  };
  ___tmp__V7G=to_integer__PN( 1);
  self__M7G=nb_of_free_slots__WWG;
  limit_down__N7G=___tmp__V7G;
  if (__infix_greater_equal__YIB(self__M7G,limit_down__N7G)) {
    print__09(' ');
    self__P8G=__infix_sub__KN(self__M7G,to_integer__PN( 1));
    while (__infix_greater_equal__YIB(self__P8G,limit_down__N7G)) {
      print__09(' ');
      self__P8G=__infix_sub__KN(self__P8G,to_integer__PN( 1));
    };
  };
}

static int __infix_add__B0B(int self__C0B,int other__D0B)
// NUMERIC __infix_add(NUMERIC,NUMERIC)
{
  return(__infix_sub__0CB(self__C0B,__prefix_sub__G0B(other__D0B)));
}

static char __infix_greater_equal__D3(int self__E3,int other__F3)
// NUMERIC __infix_greater_equal(NUMERIC,NUMERIC)
{
  return((__infix_greater__L3(self__E3,other__F3) | (self__E3==other__F3)));
}

static unsigned long __infix_and__L4(unsigned long self__M4,unsigned long other__N4)
// NUMERIC __infix_and(UINTEGER,NUMERIC)
{
  return((self__M4&other__N4));
}

static signed char to_smallint__85(int self__95)
// NUMERIC to_smallint(NUMERIC)
{
  return(((signed char )((self__95))));
}

static signed char to_character__L7(signed char self__M7)
// SMALLINT to_character(SMALLINT)
{
  return(((signed char )((self__M7))));
}

static signed char __infix_add__F8(signed char self__G8,signed char other__H8)
// CHARACTER __infix_add(CHARACTER,CHARACTER)
{
  return(to_character__L7(__infix_sub__S9(code__N8(self__G8),__infix_sub__S9(to_smallint__85( 0),code__N8(other__H8)))));
}

static unsigned long __infix_sub__FFB(unsigned long self__GFB,unsigned long other__HFB)
// NUMERIC __infix_sub(UINTEGER,NUMERIC)
{
  return((self__GFB-other__HFB));
}

static unsigned long __infix_add__PFB(unsigned long self__QFB,unsigned long other__RFB)
// NUMERIC __infix_add(UINTEGER,UINTEGER)
{
  return(__infix_sub__BGB(self__QFB,__prefix_sub__WFB(other__RFB)));
}

static unsigned long __prefix_logicnot__LGB(unsigned long self__MGB)
// NUMERIC __prefix_logicnot(UINTEGER)
{
  return(__infix_sub__BGB(__prefix_sub__WFB(to_uinteger__7Z( 1)),self__MGB));
}

static unsigned long __infix_and__8GB(unsigned long self__9GB,unsigned long other__AHB)
// NUMERIC __infix_and(UINTEGER,UINTEGER)
{
  return((self__9GB&other__AHB));
}

static void put__to__UJB(void **self__VJB,signed long index__XJB)
//- NATIVE_ARRAY put__to(NATIVE_ARRAY,NULL,INTEGER)
{
  self__VJB[index__XJB]=NULL;
}

static unsigned long __infix_add__4MB(unsigned long self__5MB,unsigned long other__6MB)
// NUMERIC __infix_add(UINTEGER,NUMERIC)
{
  return(__infix_sub__BGB(self__5MB,__prefix_sub__WFB(other__6MB)));
}

static void *get_block__KNB(unsigned long p__MNB)
// MEMORY get_block(MEMORY,UINTEGER)
{
  return(((void *)((p__MNB))));
}

static unsigned long __infix_sub__BGB(unsigned long self__CGB,unsigned long other__DGB)
// NUMERIC __infix_sub(UINTEGER,UINTEGER)
{
  return((self__CGB-other__DGB));
}

static void make__JOB(void *self__KOB,unsigned long siz__LOB)
// MEM_BLOCK make(MEM_BLOCK,UINTEGER)
{
  ((struct __MEM_BLOCK *)self__KOB)->size_and_flags__3T=siz__LOB;
  ((struct __MEM_BLOCK *)self__KOB)->next_same__6T=NULL;
  ((struct __MEM_BLOCK *)self__KOB)->prev_same__5T=((struct __MEM_BLOCK *)self__KOB)->next_same__6T;
  ((struct __MEM_BLOCK *)self__KOB)->prev__4T=((struct __MEM_BLOCK *)self__KOB)->prev_same__5T;
}

static signed long __infix_and__8SB(signed long self__9SB,signed long other__ATB)
// NUMERIC __infix_and(INTEGER,NUMERIC)
{
  return((self__9SB&other__ATB));
}

static unsigned long to_uinteger__GTB(signed long self__HTB)
// INTEGER to_uinteger(INTEGER)
{
  return(((unsigned long )((self__HTB))));
}

static char is_small_busy__NTC(void *self__OTC,unsigned long sz__PTC)
// MEM_BLOCK is_small_busy(MEM_BLOCK,UINTEGER)
{
  return(__infix_less__T1B((size__F1B(self__OTC)-to_uinteger__4SC(((struct __MEM_BLOCK *)self__OTC)->small_size__7T)),sz__PTC));
}

static unsigned long size__F1B(void *self__G1B)
// MEM_BLOCK size(MEM_BLOCK)
{
  return(__infix_and__L4(((struct __MEM_BLOCK *)self__G1B)->size_and_flags__3T,to_uinteger__7Z( 4294967294LU)));
}

static char __infix_less__T1B(unsigned long self__U1B,unsigned long other__V1B)
// NUMERIC __infix_less(UINTEGER,UINTEGER)
{
  unsigned long self__31B,other__41B;
  char ___tmp__81B;
  self__31B=self__U1B;
  other__41B=other__V1B;
  ___tmp__81B=(self__31B>other__41B);
  return((! (___tmp__81B | (self__31B==other__41B))));
}

static char is_free__F6B(void *self__G6B)
// MEM_BLOCK is_free(MEM_BLOCK)
{
  return((! (__infix_and__L4(((struct __MEM_BLOCK *)self__G6B)->size_and_flags__3T,to_uinteger__7Z( 1))!= 0)));
}

static void set_size__E7B(void *self__F7B,unsigned long sz__G7B)
//- MEM_BLOCK set_size(MEM_BLOCK,UINTEGER)
{
  ((struct __MEM_BLOCK *)self__F7B)->size_and_flags__3T=__prefix_logicnot__LGB(__infix_and__8GB(__prefix_logicnot__LGB(sz__G7B),__prefix_logicnot__LGB(__infix_and__L4(((struct __MEM_BLOCK *)self__F7B)->size_and_flags__3T,to_uinteger__7Z( 1)))));
}

static void set_prev__S9B(void *self__T9B,void *block__U9B)
//- MEM_BLOCK set_prev(MEM_BLOCK,MEM_BLOCKxNULL)
{
  ((struct __MEM_BLOCK *)self__T9B)->prev__4T=block__U9B;
}

static void set_next_same__X9B(void *self__Y9B,void *block__Z9B)
//- MEM_BLOCK set_next_same(MEM_BLOCK,MEM_BLOCKxNULL)
{
  ((struct __MEM_BLOCK *)self__Y9B)->next_same__6T=block__Z9B;
}

static void set_prev_same__99B(void *self__AAC,void *block__BAC)
//- MEM_BLOCK set_prev_same(MEM_BLOCK,MEM_BLOCKxNULL)
{
  ((struct __MEM_BLOCK *)self__AAC)->prev_same__5T=block__BAC;
}

static void to_busy__8AC(void *self__9AC)
//- MEM_BLOCK to_busy(MEM_BLOCK)
{
  ((struct __MEM_BLOCK *)self__9AC)->size_and_flags__3T=__prefix_logicnot__LGB(__infix_and__8GB(__prefix_logicnot__LGB(((struct __MEM_BLOCK *)self__9AC)->size_and_flags__3T),__prefix_logicnot__LGB(to_uinteger__7Z( 1))));
}

static int to_numeric__3DC(unsigned long self__4DC)
// NUMERIC to_numeric(UINTEGER)
{
  return(((int )((self__4DC))));
}

static int __infix_add__UDC(int other__WDC)
// NUMERIC __infix_add(NUMERIC,UINTEGER)
{
  return(__infix_sub__0CB( 128,__prefix_sub__G0B(other__WDC)));
}

static char __infix_greater__HEC(unsigned long self__IEC,unsigned long other__JEC)
// NUMERIC __infix_greater(UINTEGER,NUMERIC)
{
  return((self__IEC>other__JEC));
}

static unsigned long get_adress__ZEC(void *self__0EC)
// MEM_BLOCK get_adress(MEM_BLOCK)
{
  return(__infix_add__PFB(((unsigned long )((self__0EC))),object_size__EU));
}

static void *get_next__6FC(void *block__8FC)
// MEMORY get_next(MEMORY,MEM_BLOCKxNULL)
{
  void *result__9FC;
  unsigned long next__AGC;
  result__9FC=NULL;
  next__AGC= 0;
  next__AGC=__infix_add__PFB(get_adress__ZEC(block__8FC),size__F1B(block__8FC));
  if ((next__AGC!=__infix_add__4MB(end_memory__LR,to_uinteger__7Z( 1)))) {
    result__9FC=get_block__KNB(next__AGC);
  };
  return(result__9FC);
}

static unsigned short to_ushortint__7IC(int self__8IC)
// NUMERIC to_ushortint(NUMERIC)
{
  return(((unsigned short )((self__8IC))));
}

static void put__to__SJC(void **self__TJC,void *element__UJC,unsigned long index__VJC)
//- NATIVE_ARRAY put__to(NATIVE_ARRAY,MEM_BLOCKxNULL,UINTEGER)
{
  self__TJC[index__VJC]=element__UJC;
}

static unsigned short __infix_sub__VSC(unsigned short self__WSC,unsigned short other__XSC)
// NUMERIC __infix_sub(USHORTINT,USHORTINT)
{
  return((self__WSC-other__XSC));
}

static unsigned long to_uinteger__4SC(unsigned short self__5SC)
// USHORTINT to_uinteger(USHORTINT)
{
  return(((unsigned long )((self__5SC))));
}

static unsigned long to_uinteger__9HD(void  *self__AID)
// POINTER to_uinteger(POINTER)
{
  return(((unsigned long )((self__AID))));
}

static unsigned long *force_conversion__DJD(unsigned long obj__FJD)
// OBJECT force_conversion(NATIVE_ARRAY,UINTEGER)
{
  return(((unsigned long *)((obj__FJD))));
}

static char __infix_less_equal__JKD(int self__KKD,int other__LKD)
// NUMERIC __infix_less_equal(NUMERIC,NUMERIC)
{
  return((! __infix_greater__L3(self__KKD,other__LKD)));
}

static unsigned long item__6KD(unsigned long *self__7KD,signed long index__8KD)
// NATIVE_ARRAY item(NATIVE_ARRAY,INTEGER)
{
  return(self__7KD[index__8KD]);
}

static void put__to__XLD(unsigned long *self__YLD,unsigned long element__ZLD,signed long index__0LD)
//- NATIVE_ARRAY put__to(NATIVE_ARRAY,UINTEGER,INTEGER)
{
  self__YLD[index__0LD]=element__ZLD;
}

static unsigned long __infix_add__4OD(unsigned long self__5OD,unsigned long other__6OD)
// NUMERIC __infix_add(UINTEGER,INTEGER)
{
  return(__infix_sub__BGB(self__5OD,__prefix_sub__WFB(other__6OD)));
}

static unsigned char *force_conversion__SQD(unsigned long obj__UQD)
// OBJECT force_conversion(NATIVE_ARRAY,UINTEGER)
{
  return(((unsigned char *)((obj__UQD))));
}

static unsigned char item__4RD(unsigned char *self__5RD,signed long index__6RD)
// NATIVE_ARRAY item(NATIVE_ARRAY,INTEGER)
{
  return(self__5RD[index__6RD]);
}

static void put__to__VSD(unsigned char *self__WSD,unsigned char element__XSD,signed long index__YSD)
//- NATIVE_ARRAY put__to(NATIVE_ARRAY,USMALLINT,INTEGER)
{
  self__WSD[index__YSD]=element__XSD;
}

static char __infix_greater__L3(int self__M3,int other__N3)
// NUMERIC __infix_greater(NUMERIC,NUMERIC)
{
  return((self__M3>other__N3));
}

static signed char __infix_sub__S9(signed char self__T9,signed char other__U9)
// NUMERIC __infix_sub(SMALLINT,SMALLINT)
{
  return((self__T9-other__U9));
}

static unsigned long __prefix_sub__WFB(unsigned long self__XFB)
// NUMERIC __prefix_sub(UINTEGER)
{
  return(__infix_sub__BGB(to_uinteger__7Z( 0),self__XFB));
}

