// ANSI C code generated by Lisaac compiler (www.isaacOS.com) //

/*
 * EXTERNAL
 */

#include <time.h> /* SYSTEM */
#include <stdio.h>
  
// Hardware 'print_char'
int print_char(char car)
{
  fputc(car,stdout);
}

// Hardware 'exit'
int die_with_code(int code)
{
  exit(code);
}

 /* SYSTEM_IO */

/*
 * STRING CONSTANT
 */

signed char *__string_0="Root";
signed char *__string_1="Directory";
signed char *__string_2="SubFile1";
signed char *__string_3="SubFile2";
signed char *__string_4="SubFile3";
signed char *__string_5="SubDirectory";
signed char *__string_6="SubSubFile1";
signed char *__string_7="SubSubFile2";
signed char *__string_8="File1";
signed char *__string_9="File2";
signed char *__string_10="  ";

/*
 * STRUCT
 */

// Generic Object
struct ___OBJ {
  unsigned long __id;
};

// ABSTRACT_STRING
struct __ABSTRACT_STRING {
  signed char *storage__RM;
  signed long count__SM;
};

// STRING_CONSTANT
struct __STRING_CONSTANT {
  struct __ABSTRACT_STRING parent_abstract_string__WH;
};

// MASTER
struct __MASTER {
  void *root__JK;
};

// NODE
#define __NODE__ 16
struct __NODE {
  unsigned long __id;
  void *label__XK;
};

// NODE_COMPOSITE
#define __NODE_COMPOSITE__ 17
struct __NODE_COMPOSITE {
  unsigned long __id;
  struct __NODE parent_node__6K;
  void *children__7K;
};

// MEM_BLOCK
struct __MEM_BLOCK {
  unsigned long size_and_flags__ES 	__attribute__ ((packed));
  void *prev__FS 	__attribute__ ((packed));
  void *prev_same__GS 	__attribute__ ((packed));
  void *next_same__HS 	__attribute__ ((packed));
  unsigned short small_size__IS 	__attribute__ ((packed));
  unsigned short first_free__JS 	__attribute__ ((packed));
} 	__attribute__ ((packed));

// LINKED_COLLECTION
struct __LINKED_COLLECTION__NODE {
  signed long upper__NZD;
};

// LINKED_LIST
struct __LINKED_LIST__NODE {
  struct __LINKED_COLLECTION__NODE parent_linked_collection__1XD;
  void *first_link__2XD;
  void *last_link__3XD;
  signed long mem_idx__4XD;
  void *mem_lnk__5XD;
};

// LINK
struct __LINK__NODE {
  void *item__13D;
  void *next__23D;
};

// STRING
struct __STRING {
  struct __ABSTRACT_STRING parent_abstract_string__2NE;
  signed long capacity__4NE;
};


/*
 * GLOBAL
 */

// NULL
#ifndef NULL
#define NULL ((void *)0)
#endif
// CHARACTER
signed long pointer_size__OD;
// TRUE
#define TRUE 1
// FALSE
#define FALSE 0
// ABSTRACT_STRING
signed long lower__TM;
struct __ABSTRACT_STRING ABSTRACT_STRING__;
#define ABSTRACT_STRING (&ABSTRACT_STRING__)
// STRING_CONSTANT
struct __STRING_CONSTANT STRING_CONSTANT__;
#define STRING_CONSTANT (&STRING_CONSTANT__)
// MASTER
struct __MASTER MASTER__;
#define MASTER (&MASTER__)
// NODE
void *indent__1K;
struct __NODE NODE__={__NODE__};
#define NODE (&NODE__)
// NODE_COMPOSITE
struct __NODE_COMPOSITE NODE_COMPOSITE__={__NODE_COMPOSITE__};
#define NODE_COMPOSITE (&NODE_COMPOSITE__)
// MEMORY
void **small_fat__KP;
void *first_free__LP;
unsigned long begin_memory__MP;
unsigned long end_memory__NP;
unsigned long capacity__OP;
void *last_block__PP;
// MEM_BLOCK
unsigned long object_size__PS;
struct __MEM_BLOCK MEM_BLOCK__;
#define MEM_BLOCK (&MEM_BLOCK__)
// SYSTEM
unsigned long get_begin_memory__DW;
unsigned long get_capacity_memory__EW;
// LINKED_COLLECTION
signed long lower__MZD;
struct __LINKED_COLLECTION__NODE LINKED_COLLECTION__NODE__;
#define LINKED_COLLECTION__NODE (&LINKED_COLLECTION__NODE__)
// LINKED_LIST
struct __LINKED_LIST__NODE LINKED_LIST__NODE__;
#define LINKED_LIST__NODE (&LINKED_LIST__NODE__)
// LINK
struct __LINK__NODE LINK__NODE__;
#define LINK__NODE (&LINK__NODE__)
// STRING
struct __STRING STRING__;
#define STRING (&STRING__)

/*
 * PROTOTYPE
 */

int main(signed long ___count_arg__LK,signed char **___list_arg__MK);
static unsigned long to_uinteger__IY(int self__JY);
static signed long to_integer__K2(int self__L2);
static unsigned long realloc_c__EZ(unsigned long beg__GZ,unsigned long nb__HZ);
static void  *allocation__SR(signed long nb__UR);
static void copy__from__size__ACD(void  *dst__CCD,void  *src__DCD,signed long n__ECD);
static char __infix_greater__X1(int self__Y1,int other__Z1);
static char __infix_greater_equal__UHB(signed long self__VHB,signed long other__WHB);
static signed char *calloc__FUE(signed long nb_elements__HUE);
static void *new_intern__FM(signed char *p__HM,signed long nb_char__IM);
static void *create__DVD(void *lab__FVD);
static void add__D5D(void *self__E5D,void *n__F5D);
static void *create__SDE(void *lab__UDE);
static void add__8FE(void *self__9FE,void *n__AGE);
static void print__7ME(void *self__8ME);
static void print_nbx__C0(unsigned long n__E0);
static void print__R8(signed char self__S8);
static unsigned long __infix_sub__BEB(unsigned long self__CEB,unsigned long other__DEB);
static unsigned long __infix_add__LEB(unsigned long self__MEB,unsigned long other__NEB);
static unsigned long __prefix_logicnot__HFB(unsigned long self__IFB);
static unsigned long __infix_and__4FB(unsigned long self__5FB,unsigned long other__6FB);
static void put__to__QIB(void **self__RIB,signed long index__TIB);
static signed long __infix_sub__FKB(signed long self__GKB,signed long other__HKB);
static unsigned long __infix_add__2LB(unsigned long self__3LB,unsigned long other__4LB);
static void *get_block__IMB(unsigned long p__KMB);
static unsigned long __infix_sub__7EB(unsigned long self__8EB,unsigned long other__9EB);
static void make__HNB(void *self__INB,unsigned long siz__JNB);
static char __infix_less_equal__EQB(signed long self__FQB,signed long other__GQB);
static signed long __infix_add__7QB(signed long self__8QB,signed long other__9QB);
static signed long __infix_and__6RB(signed long self__7RB,signed long other__8RB);
static unsigned long to_uinteger__ESB(signed long self__FSB);
static unsigned long __infix_greater_greater__LTB(unsigned long self__MTB);
static char is_small_busy__LSC(void *self__MSC,unsigned long sz__NSC);
static int __infix_add__9YB(int self__AZB,int other__BZB);
static unsigned long size__D0B(void *self__E0B);
static char __infix_less__R0B(unsigned long self__S0B,unsigned long other__T0B);
static unsigned long __infix_and__C3(unsigned long self__D3,unsigned long other__E3);
static char is_free__D5B(void *self__E5B);
static void set_size__C6B(void *self__D6B,unsigned long sz__E6B);
static void set_prev__Q8B(void *self__R8B,void *block__S8B);
static void set_next_same__V8B(void *self__W8B,void *block__X8B);
static void set_prev_same__78B(void *self__88B,void *block__98B);
static void to_busy__69B(void *self__79B);
static int to_numeric__1CC(unsigned long self__2CC);
static int __infix_add__SCC(int other__UCC);
static char __infix_greater__FDC(unsigned long self__GDC,unsigned long other__HDC);
static unsigned long get_adress__XDC(void *self__YDC);
static void *get_next__4EC(void *block__6EC);
static unsigned short to_ushortint__5HC(int self__6HC);
static void put__to__QIC(void **self__RIC,void *element__SIC,unsigned long index__TIC);
static void set_prev_same__OKC(void *self__PKC,void *block__QKC);
static unsigned short *memory__POC(void *self__QOC);
static unsigned short to_ushortint__9PC(unsigned long self__AQC);
static unsigned short __infix_sub__TRC(unsigned short self__URC,unsigned short other__VRC);
static unsigned long to_uinteger__2RC(unsigned short self__3RC);
static unsigned long to_uinteger__7GD(void  *self__8GD);
static signed long __infix_greater_greater__MHD(signed long self__NHD,int other__OHD);
static unsigned long *force_conversion__BID(unsigned long obj__DID);
static int to_numeric__6ID(signed long self__7ID);
static char __infix_less_equal__HJD(int self__IJD,int other__JJD);
static unsigned long item__4JD(unsigned long *self__5JD,signed long index__6JD);
static void put__to__VKD(unsigned long *self__WKD,unsigned long element__XKD,signed long index__YKD);
static unsigned long __infix_add__2ND(unsigned long self__3ND,unsigned long other__4ND);
static unsigned char *force_conversion__QPD(unsigned long obj__SPD);
static unsigned char item__2QD(unsigned char *self__3QD,signed long index__4QD);
static void put__to__TRD(unsigned char *self__URD,unsigned char element__VRD,signed long index__WRD);
static char __infix_greater__4HB(signed long self__5HB,signed long other__6HB);
static signed long __infix_mul__HWE(signed long self__IWE,signed long other__JWE);
static void put__to__0XE(signed char *self__1XE,signed char element__2XE,signed long index__3XE);
static void *create__next__T7D(void *i__V7D);
static void set_next__XAE(void *self__YAE,void *n__ZAE);
static void *create__next__SHE(void *i__UHE);
static void print__N1E(void *self__O1E);
static void print__Z6E(void *self__06E);
static signed long __prefix_sub__HRB(signed long self__IRB);
static signed long __infix_sub__WRB(signed long self__XRB,signed long other__YRB);
static char __infix_greater_diese__3QF(unsigned long self__4QF,unsigned long other__5QF);
static char __infix_equal_equal__H1B(unsigned long self__I1B,unsigned long other__J1B);
static void put__to__TYF(void **self__UYF,void *element__VYF,signed long index__WYF);
static void to_free__95F(void *self__A6F);
static char __infix_less_equal__03E(signed long self__13E,signed long other__23E);
static signed char item__P5E(signed char *self__Q5E,signed long index__R5E);
static signed char to_smallint__Z4(int self__04);
static signed char to_character__C6(signed char self__D6);
static signed char __infix_add__66(signed char self__76,signed char other__86);
static int __infix_sub__WBB(int self__XBB,int other__YBB);
static void put_character__99(signed char c__BAB);
static unsigned long __prefix_sub__SEB(unsigned long self__TEB);
static int __prefix_sub__EZB(int self__FZB);
static char __infix_greater__A1B(unsigned long self__B1B,unsigned long other__C1B);
static void *clone__27D();
static signed char code__E7(signed char self__F7);
static signed char __infix_sub__J8(signed char self__K8,signed char other__L8);

/*
 * SOURCE CODE
 */

void copy_object(void *dst,void *src,int n)
{ int cpt,i;                               
  unsigned long *dst_l, *src_l;            
  unsigned char *dst_b, *src_b;            
                                           
  cpt = n >> 2;                            
  dst_l = (unsigned long *)dst;            
  src_l = (unsigned long *)src;            
  for (i=0 ; i<cpt ; i++) {                
    *dst_l = *src_l;                       
    dst_l++;                               
    src_l++;                               
  };                                       
  cpt = n & 3;                             
  dst_b = (unsigned char *)src_l;          
  src_b = (unsigned char *)dst_l;          
  for (i=0 ; i<cpt ; i++) {                
    *dst_b = *src_b;                       
    dst_b++;                               
    src_b++;                               
  };                                       
}                                          
//////////// MAIN ////////////
int main(signed long ___count_arg__LK,signed char **___list_arg__MK)
// MASTER - ANSI code -
{
  void *self__CY,*result__5PE,*self__9TE,*self__ESE,*result__WPE;
  void *file__2K,*dir__BL,*dir2__CL;
  unsigned long ___tmp__HY,___tmp__XMB;
  void  *ptr__6PE;
  signed long ___tmp__E7D,___tmp__CWE,___tmp__G3E,sz__7PE;
  ___tmp__HY=to_uinteger__IY( 268435456);
  ___tmp__XMB=to_uinteger__IY( 16);
  ___tmp__E7D=to_integer__K2( 1);
  ___tmp__CWE=to_integer__K2( 1);
  ___tmp__G3E=to_integer__K2( 1);
  capacity__OP= 0;
  get_capacity_memory__EW=___tmp__HY;
  get_begin_memory__DW=realloc_c__EZ(to_uinteger__IY( 0),get_capacity_memory__EW);
  begin_memory__MP= 0;
  end_memory__NP= 0;
  small_fat__KP=NULL;
  last_block__PP=NULL;
  object_size__PS=___tmp__XMB;
  MEM_BLOCK__.size_and_flags__ES= 0;
  MEM_BLOCK__.next_same__HS=NULL;
  MEM_BLOCK__.prev_same__GS=NULL;
  MEM_BLOCK__.prev__FS=NULL;
  first_free__LP=NULL;
  MEM_BLOCK__.small_size__IS= 0;
  MEM_BLOCK__.first_free__JS= 0;
  ABSTRACT_STRING__.storage__RM=NULL;
  STRING_CONSTANT__.parent_abstract_string__WH.storage__RM=ABSTRACT_STRING__.storage__RM;
  STRING__.parent_abstract_string__2NE.storage__RM=ABSTRACT_STRING__.storage__RM;
  ABSTRACT_STRING__.count__SM= 0;
  STRING_CONSTANT__.parent_abstract_string__WH.count__SM=ABSTRACT_STRING__.count__SM;
  STRING__.parent_abstract_string__2NE.count__SM=ABSTRACT_STRING__.count__SM;
  NODE__.label__XK=NULL;
  NODE_COMPOSITE__.parent_node__6K.label__XK=NODE__.label__XK;
  LINKED_LIST__NODE__.first_link__2XD=NULL;
  LINKED_COLLECTION__NODE__.upper__NZD= 0;
  LINKED_LIST__NODE__.parent_linked_collection__1XD.upper__NZD=LINKED_COLLECTION__NODE__.upper__NZD;
  LINKED_LIST__NODE__.last_link__3XD=NULL;
  LINKED_LIST__NODE__.mem_idx__4XD= 0;
  LINKED_LIST__NODE__.mem_lnk__5XD=NULL;
  NODE_COMPOSITE__.children__7K=NULL;
  MASTER__.root__JK=NULL;
  lower__MZD=___tmp__E7D;
  LINK__NODE__.item__13D=NULL;
  LINK__NODE__.next__23D=NULL;
  STRING__.capacity__4NE= 0;
  pointer_size__OD=___tmp__CWE;
  result__WPE=NULL;
  ptr__6PE=NULL;
  result__5PE=NULL;
  sz__7PE= 0;
  sz__7PE=sizeof(struct __STRING);
  if ((sz__7PE== 0)) {
    result__5PE=STRING;
  } else {
    ptr__6PE=allocation__SR(sz__7PE);
    copy__from__size__ACD(ptr__6PE,((void  *)((STRING))),sz__7PE);
    result__5PE=((void *)((ptr__6PE)));
  };
  result__WPE=result__5PE;
  self__ESE=result__WPE;
  if (__infix_greater__X1( 250, 0)) {
    if ((! __infix_greater_equal__UHB(((struct __STRING *)self__ESE)->capacity__4NE,to_integer__K2( 250)))) {
      self__9TE=self__ESE;
      ((struct __STRING *)self__9TE)->parent_abstract_string__2NE.storage__RM=calloc__FUE(to_integer__K2( 250));
      ((struct __STRING *)self__9TE)->capacity__4NE=to_integer__K2( 250);
    };
  };
  ((struct __STRING *)self__ESE)->parent_abstract_string__2NE.count__SM=to_integer__K2( 0);
  indent__1K=result__WPE;
  lower__TM=___tmp__G3E;
  dir2__CL=NULL;
  file__2K=NULL;
  dir__BL=NULL;
  MASTER__.root__JK=create__DVD(new_intern__FM(__string_0, 4));
  dir__BL=create__DVD(new_intern__FM(__string_1, 9));
  add__D5D(MASTER__.root__JK,dir__BL);
  file__2K=create__SDE(new_intern__FM(__string_2, 8));
  add__8FE(dir__BL,file__2K);
  file__2K=create__SDE(new_intern__FM(__string_3, 8));
  add__8FE(dir__BL,file__2K);
  file__2K=create__SDE(new_intern__FM(__string_4, 8));
  add__8FE(dir__BL,file__2K);
  dir2__CL=create__DVD(new_intern__FM(__string_5, 12));
  add__D5D(dir__BL,dir2__CL);
  file__2K=create__SDE(new_intern__FM(__string_6, 11));
  add__8FE(dir2__CL,file__2K);
  file__2K=create__SDE(new_intern__FM(__string_7, 11));
  add__8FE(dir2__CL,file__2K);
  file__2K=create__SDE(new_intern__FM(__string_8, 5));
  add__8FE(MASTER__.root__JK,file__2K);
  file__2K=create__SDE(new_intern__FM(__string_9, 5));
  add__8FE(MASTER__.root__JK,file__2K);
  print__7ME(MASTER__.root__JK);
}

static unsigned long to_uinteger__IY(int self__JY)
// NUMERIC to_uinteger(NUMERIC)
{
  return(((unsigned long )((self__JY))));
}

static signed long to_integer__K2(int self__L2)
// NUMERIC to_integer(NUMERIC)
{
  return(((signed long )((self__L2))));
}

static unsigned long realloc_c__EZ(unsigned long beg__GZ,unsigned long nb__HZ)
// SYSTEM realloc_c(SYSTEM,UINTEGER,UINTEGER)
{
  unsigned long result__IZ;
  result__IZ= 0;
  result__IZ=((unsigned long )((unsigned long)realloc((void *)(beg__GZ),(nb__HZ)+15)));
  if (((beg__GZ!= 0) && (result__IZ!=beg__GZ))) {
    print_nbx__C0(beg__GZ);
    print__R8('\n');
    print_nbx__C0(result__IZ);
    print__R8('\n');
    exit((to_integer__K2( 1)));
  };
  return(result__IZ);
}

static void  *allocation__SR(signed long nb__UR)
// MEMORY allocation(MEMORY,INTEGER)
{
  unsigned long result__9R,index__AT,size__BT,offset__CT,a__0DB;
  void *first_block__7S,*lst_block__8S,*new_block__9S,**self__4GB;
  void **___tmp__VX,*cur_block__8UB,*p_block__9UB,*n_block__AVB;
  unsigned long ___tmp__6DB,begin__5V,___tmp__KW,size__CVB;
  void *new_block__BVB,*self__IHC,*self__9KC,*cur_block__HUC;
  unsigned long new_size__DVB,add_size__EVB,size__LUC,new_size__MUC;
  signed long self__FHB,limit_down__GHB,___tmp__OHB,___tmp__1GB;
  unsigned short result__BLC;
  void *p_block__IUC,*n_block__JUC,*new_block__KUC;
  unsigned long add_size__NUC;
  signed long self__QKB;
  result__9R= 0;
  offset__CT= 0;
  lst_block__8S=NULL;
  new_block__9S=NULL;
  first_block__7S=NULL;
  index__AT= 0;
  size__BT= 0;
  if ((capacity__OP== 0)) {
    begin__5V= 0;
    begin_memory__MP=get_begin_memory__DW;
    capacity__OP=get_capacity_memory__EW;
    ___tmp__KW=begin_memory__MP;
    ___tmp__6DB=to_uinteger__IY( 16);
    a__0DB= 0;
    a__0DB=__infix_sub__BEB(___tmp__6DB,to_uinteger__IY( 1));
    begin__5V=__infix_and__4FB(__infix_add__LEB(___tmp__KW,a__0DB),__prefix_logicnot__HFB(a__0DB));
    end_memory__NP=__infix_sub__BEB(__infix_add__LEB(begin__5V,capacity__OP),to_uinteger__IY( 1));
    small_fat__KP=((void **)((begin__5V)));
    ___tmp__VX=small_fat__KP;
    ___tmp__1GB=to_integer__K2( 63);
    self__4GB=___tmp__VX;
    ___tmp__OHB=to_integer__K2( 0);
    self__FHB=___tmp__1GB;
    limit_down__GHB=___tmp__OHB;
    if (__infix_greater_equal__UHB(self__FHB,limit_down__GHB)) {
      put__to__QIB(self__4GB,self__FHB);
      self__QKB=__infix_sub__FKB(self__FHB,to_integer__K2( 1));
      while (__infix_greater_equal__UHB(self__QKB,limit_down__GHB)) {
        put__to__QIB(self__4GB,self__QKB);
        self__QKB=__infix_sub__FKB(self__QKB,to_integer__K2( 1));
      };
    };
    begin__5V=__infix_add__2LB(begin__5V,to_uinteger__IY( 256));
    last_block__PP=get_block__IMB(begin__5V);
    make__HNB(last_block__PP,__infix_sub__7EB(__infix_sub__7EB(__infix_add__2LB(end_memory__NP,to_uinteger__IY( 1)),begin__5V),object_size__PS));
    first_free__LP=last_block__PP;
  };
  if (__infix_less_equal__EQB(nb__UR,to_integer__K2( 128))) {
    size__BT=to_uinteger__ESB(__infix_and__6RB(__infix_add__7QB(nb__UR,to_integer__K2( 1)),to_integer__K2( 254)));
    index__AT=__infix_sub__BEB(__infix_greater_greater__LTB(size__BT),to_uinteger__IY( 1));
    first_block__7S=small_fat__KP[index__AT];
    if (((first_block__7S==NULL) || is_small_busy__LSC(first_block__7S,size__BT))) {
      new_block__BVB=NULL;
      new_size__DVB= 0;
      n_block__AVB=NULL;
      p_block__9UB=NULL;
      add_size__EVB= 0;
      cur_block__8UB=NULL;
      size__CVB= 0;
      size__CVB=to_uinteger__IY((__infix_add__9YB( 4096, 15)& 4294967280LU));
      cur_block__8UB=first_free__LP;
      while (((cur_block__8UB!=NULL) && __infix_less__R0B(size__D0B(cur_block__8UB),size__CVB))) {
        cur_block__8UB=((struct __MEM_BLOCK *)cur_block__8UB)->next_same__HS;
      };
      if ((cur_block__8UB==NULL)) {
        add_size__EVB=__infix_and__C3(__infix_add__2LB(__infix_add__2LB(size__CVB,to_uinteger__IY( 16)),to_uinteger__IY( 16777215)),to_uinteger__IY( 4278190080LU));
        capacity__OP=__infix_add__LEB(capacity__OP,add_size__EVB);
        realloc_c__EZ(begin_memory__MP,capacity__OP);
        if (is_free__D5B(last_block__PP)) {
          cur_block__8UB=last_block__PP;
          set_size__C6B(cur_block__8UB,__infix_add__LEB(size__D0B(cur_block__8UB),add_size__EVB));
        } else {
          cur_block__8UB=get_block__IMB(__infix_add__2LB(end_memory__NP,to_uinteger__IY( 1)));
          make__HNB(cur_block__8UB,__infix_sub__BEB(add_size__EVB,to_uinteger__IY( 16)));
          set_prev__Q8B(cur_block__8UB,last_block__PP);
          last_block__PP=cur_block__8UB;
          set_next_same__V8B(cur_block__8UB,first_free__LP);
          if ((first_free__LP!=NULL)) {
            set_prev_same__78B(first_free__LP,cur_block__8UB);
          };
          first_free__LP=cur_block__8UB;
        };
        end_memory__NP=__infix_add__LEB(end_memory__NP,add_size__EVB);
      };
      to_busy__69B(cur_block__8UB);
      p_block__9UB=((struct __MEM_BLOCK *)cur_block__8UB)->prev_same__GS;
      n_block__AVB=((struct __MEM_BLOCK *)cur_block__8UB)->next_same__HS;
      if ((p_block__9UB==NULL)) {
        first_free__LP=n_block__AVB;
      } else {
        set_next_same__V8B(p_block__9UB,n_block__AVB);
      };
      if ((n_block__AVB!=NULL)) {
        set_prev_same__78B(n_block__AVB,p_block__9UB);
      };
      new_size__DVB=__infix_sub__7EB(size__D0B(cur_block__8UB),size__CVB);
      if (__infix_greater__FDC(new_size__DVB,to_uinteger__IY(__infix_add__SCC(to_numeric__1CC(object_size__PS))))) {
        new_size__DVB=__infix_sub__7EB(new_size__DVB,object_size__PS);
        new_block__BVB=get_block__IMB(__infix_add__LEB(get_adress__XDC(cur_block__8UB),size__CVB));
        make__HNB(new_block__BVB,new_size__DVB);
        if ((first_free__LP!=NULL)) {
          set_prev_same__78B(first_free__LP,new_block__BVB);
        };
        set_next_same__V8B(new_block__BVB,first_free__LP);
        first_free__LP=new_block__BVB;
        set_size__C6B(cur_block__8UB,size__CVB);
        set_prev__Q8B(new_block__BVB,cur_block__8UB);
        n_block__AVB=get_next__4EC(new_block__BVB);
        if ((n_block__AVB==NULL)) {
          last_block__PP=new_block__BVB;
        } else {
          set_prev__Q8B(n_block__AVB,new_block__BVB);
        };
      };
      new_block__9S=cur_block__8UB;
      if ((new_block__9S!=NULL)) {
        self__IHC=new_block__9S;
        ((struct __MEM_BLOCK *)self__IHC)->small_size__IS=to_ushortint__5HC( 4);
        ((struct __MEM_BLOCK *)self__IHC)->first_free__JS=to_ushortint__5HC( 0);
        ((struct __MEM_BLOCK *)self__IHC)->next_same__HS=self__IHC;
        ((struct __MEM_BLOCK *)self__IHC)->prev_same__GS=((struct __MEM_BLOCK *)self__IHC)->next_same__HS;
        put__to__QIC(small_fat__KP,new_block__9S,index__AT);
        if ((first_block__7S!=NULL)) {
          lst_block__8S=((struct __MEM_BLOCK *)first_block__7S)->prev_same__GS;
          ((struct __MEM_BLOCK *)new_block__9S)->next_same__HS=first_block__7S;
          set_prev_same__OKC(new_block__9S,lst_block__8S);
          set_next_same__V8B(lst_block__8S,new_block__9S);
          set_prev_same__78B(first_block__7S,new_block__9S);
        };
      };
      first_block__7S=new_block__9S;
    };
    if ((first_block__7S!=NULL)) {
      self__9KC=first_block__7S;
      result__BLC= 0;
      if ((((struct __MEM_BLOCK *)self__9KC)->first_free__JS== 0)) {
        result__BLC=((struct __MEM_BLOCK *)self__9KC)->small_size__IS;
      } else {
        result__BLC=((unsigned short )((((struct __MEM_BLOCK *)self__9KC)->first_free__JS)<<( 1)));
        ((struct __MEM_BLOCK *)self__9KC)->first_free__JS=memory__POC(self__9KC)[((struct __MEM_BLOCK *)self__9KC)->first_free__JS];
      };
      ((struct __MEM_BLOCK *)self__9KC)->small_size__IS=__infix_sub__TRC(((struct __MEM_BLOCK *)self__9KC)->small_size__IS,__infix_sub__TRC(to_ushortint__5HC( 0),to_ushortint__9PC(size__BT)));
      offset__CT=to_uinteger__2RC(result__BLC);
      if ((is_small_busy__LSC(first_block__7S,size__BT) && (! is_small_busy__LSC(((struct __MEM_BLOCK *)first_block__7S)->next_same__HS,size__BT)))) {
        put__to__QIC(small_fat__KP,((struct __MEM_BLOCK *)first_block__7S)->next_same__HS,index__AT);
      };
      result__9R=__infix_add__LEB(get_adress__XDC(first_block__7S),offset__CT);
    };
  } else {
    new_block__KUC=NULL;
    new_size__MUC= 0;
    n_block__JUC=NULL;
    p_block__IUC=NULL;
    add_size__NUC= 0;
    cur_block__HUC=NULL;
    size__LUC= 0;
    size__LUC=to_uinteger__ESB(__infix_and__6RB(__infix_add__7QB(nb__UR,to_integer__K2( 15)),to_integer__K2( 4294967280LU)));
    cur_block__HUC=first_free__LP;
    while (((cur_block__HUC!=NULL) && __infix_less__R0B(size__D0B(cur_block__HUC),size__LUC))) {
      cur_block__HUC=((struct __MEM_BLOCK *)cur_block__HUC)->next_same__HS;
    };
    if ((cur_block__HUC==NULL)) {
      add_size__NUC=__infix_and__C3(__infix_add__2LB(__infix_add__2LB(size__LUC,to_uinteger__IY( 16)),to_uinteger__IY( 16777215)),to_uinteger__IY( 4278190080LU));
      capacity__OP=__infix_add__LEB(capacity__OP,add_size__NUC);
      realloc_c__EZ(begin_memory__MP,capacity__OP);
      if (is_free__D5B(last_block__PP)) {
        cur_block__HUC=last_block__PP;
        set_size__C6B(cur_block__HUC,__infix_add__LEB(size__D0B(cur_block__HUC),add_size__NUC));
      } else {
        cur_block__HUC=get_block__IMB(__infix_add__2LB(end_memory__NP,to_uinteger__IY( 1)));
        make__HNB(cur_block__HUC,__infix_sub__BEB(add_size__NUC,to_uinteger__IY( 16)));
        set_prev__Q8B(cur_block__HUC,last_block__PP);
        last_block__PP=cur_block__HUC;
        set_next_same__V8B(cur_block__HUC,first_free__LP);
        if ((first_free__LP!=NULL)) {
          set_prev_same__78B(first_free__LP,cur_block__HUC);
        };
        first_free__LP=cur_block__HUC;
      };
      end_memory__NP=__infix_add__LEB(end_memory__NP,add_size__NUC);
    };
    to_busy__69B(cur_block__HUC);
    p_block__IUC=((struct __MEM_BLOCK *)cur_block__HUC)->prev_same__GS;
    n_block__JUC=((struct __MEM_BLOCK *)cur_block__HUC)->next_same__HS;
    if ((p_block__IUC==NULL)) {
      first_free__LP=n_block__JUC;
    } else {
      set_next_same__V8B(p_block__IUC,n_block__JUC);
    };
    if ((n_block__JUC!=NULL)) {
      set_prev_same__78B(n_block__JUC,p_block__IUC);
    };
    new_size__MUC=__infix_sub__7EB(size__D0B(cur_block__HUC),size__LUC);
    if (__infix_greater__FDC(new_size__MUC,to_uinteger__IY(__infix_add__SCC(to_numeric__1CC(object_size__PS))))) {
      new_size__MUC=__infix_sub__7EB(new_size__MUC,object_size__PS);
      new_block__KUC=get_block__IMB(__infix_add__LEB(get_adress__XDC(cur_block__HUC),size__LUC));
      make__HNB(new_block__KUC,new_size__MUC);
      if ((first_free__LP!=NULL)) {
        set_prev_same__78B(first_free__LP,new_block__KUC);
      };
      set_next_same__V8B(new_block__KUC,first_free__LP);
      first_free__LP=new_block__KUC;
      set_size__C6B(cur_block__HUC,size__LUC);
      set_prev__Q8B(new_block__KUC,cur_block__HUC);
      n_block__JUC=get_next__4EC(new_block__KUC);
      if ((n_block__JUC==NULL)) {
        last_block__PP=new_block__KUC;
      } else {
        set_prev__Q8B(n_block__JUC,new_block__KUC);
      };
    };
    first_block__7S=cur_block__HUC;
    if ((first_block__7S!=NULL)) {
      result__9R=get_adress__XDC(first_block__7S);
    };
  };
  if ((result__9R== 0)) {
    print__R8('M');
    print__R8('E');
    print__R8('M');
    print__R8(':');
    print__R8('N');
    print__R8('O');
    print__R8('T');
    print__R8(' ');
    print__R8('E');
    print__R8('N');
    print__R8('O');
    print__R8('U');
    print__R8('G');
    print__R8('H');
    print__R8(' ');
    print__R8('M');
    print__R8('E');
    print__R8('M');
    print__R8('O');
    print__R8('R');
    print__R8('Y');
    while (1);
  };
  return(((void  *)((result__9R))));
}

static void copy__from__size__ACD(void  *dst__CCD,void  *src__DCD,signed long n__ECD)
// MEMORY copy__from__size(MEMORY,POINTER,POINTER,INTEGER)
{
  unsigned long *dst_array_32__KDD,*src_array_32__LDD,dst_int__8ED;
  int limit_up__VID,limit_up__AQD,self__MMD,self__KTD;
  unsigned char *dst_array_8__6ED,*src_array_8__7ED;
  unsigned long src_int__9ED;
  signed long cpt__AFD,i__JFD,i__7MD,i__WFD,i__5TD;
  src_array_8__7ED=NULL;
  dst_array_8__6ED=NULL;
  src_array_32__LDD=NULL;
  dst_array_32__KDD=NULL;
  cpt__AFD= 0;
  src_int__9ED= 0;
  dst_int__8ED= 0;
  dst_int__8ED=to_uinteger__7GD(dst__CCD);
  src_int__9ED=to_uinteger__7GD(src__DCD);
  cpt__AFD=__infix_greater_greater__MHD(n__ECD, 2);
  if ((cpt__AFD!= 0)) {
    dst_array_32__KDD=force_conversion__BID(dst_int__8ED);
    src_array_32__LDD=force_conversion__BID(src_int__9ED);
    limit_up__VID=to_numeric__6ID(__infix_sub__FKB(cpt__AFD,to_integer__K2( 1)));
    if (__infix_less_equal__HJD( 0,limit_up__VID)) {
      i__JFD=to_integer__K2( 0);
      put__to__VKD(dst_array_32__KDD,item__4JD(src_array_32__LDD,i__JFD),i__JFD);
      self__MMD=__infix_add__9YB( 0, 1);
      while (__infix_less_equal__HJD(self__MMD,limit_up__VID)) {
        i__7MD=to_integer__K2(self__MMD);
        put__to__VKD(dst_array_32__KDD,item__4JD(src_array_32__LDD,i__7MD),i__7MD);
        self__MMD=__infix_add__9YB(self__MMD, 1);
      };
    };
    dst_int__8ED=__infix_add__2ND(dst_int__8ED,to_uinteger__ESB(__infix_and__6RB(n__ECD,to_integer__K2( 4294967292LU))));
    src_int__9ED=__infix_add__2ND(src_int__9ED,to_uinteger__ESB(__infix_and__6RB(n__ECD,to_integer__K2( 4294967292LU))));
  };
  cpt__AFD=__infix_and__6RB(n__ECD,to_integer__K2( 3));
  if ((cpt__AFD!= 0)) {
    dst_array_8__6ED=force_conversion__QPD(dst_int__8ED);
    src_array_8__7ED=force_conversion__QPD(src_int__9ED);
    limit_up__AQD=to_numeric__6ID(__infix_sub__FKB(cpt__AFD,to_integer__K2( 1)));
    if (__infix_less_equal__HJD( 0,limit_up__AQD)) {
      i__WFD=to_integer__K2( 0);
      put__to__TRD(dst_array_8__6ED,item__2QD(src_array_8__7ED,i__WFD),i__WFD);
      self__KTD=__infix_add__9YB( 0, 1);
      while (__infix_less_equal__HJD(self__KTD,limit_up__AQD)) {
        i__5TD=to_integer__K2(self__KTD);
        put__to__TRD(dst_array_8__6ED,item__2QD(src_array_8__7ED,i__5TD),i__5TD);
        self__KTD=__infix_add__9YB(self__KTD, 1);
      };
    };
  };
}

static char __infix_greater__X1(int self__Y1,int other__Z1)
// NUMERIC __infix_greater(NUMERIC,NUMERIC)
{
  return((self__Y1>other__Z1));
}

static char __infix_greater_equal__UHB(signed long self__VHB,signed long other__WHB)
// NUMERIC __infix_greater_equal(INTEGER,INTEGER)
{
  return((__infix_greater__4HB(self__VHB,other__WHB) | (self__VHB==other__WHB)));
}

static signed char *calloc__FUE(signed long nb_elements__HUE)
// NATIVE_ARRAY calloc(NATIVE_ARRAY,INTEGER)
{
  signed long capacity__DVE,___tmp__MUE,self__AXE,limit_down__BXE;
  void  *p__EVE;
  signed char *result__IUE,*result__FVE,*self__ZWE;
  signed long ___tmp__JXE,self__YZE;
  result__IUE=NULL;
  result__FVE=NULL;
  p__EVE=NULL;
  capacity__DVE= 0;
  capacity__DVE=__infix_mul__HWE(nb_elements__HUE,pointer_size__OD);
  p__EVE=allocation__SR(capacity__DVE);
  result__FVE=((signed char *)((void*)(p__EVE)));
  result__IUE=result__FVE;
  ___tmp__MUE=__infix_sub__FKB(nb_elements__HUE,to_integer__K2( 1));
  self__ZWE=result__IUE;
  ___tmp__JXE=to_integer__K2( 0);
  self__AXE=___tmp__MUE;
  limit_down__BXE=___tmp__JXE;
  if (__infix_greater_equal__UHB(self__AXE,limit_down__BXE)) {
    put__to__0XE(self__ZWE,'\0',self__AXE);
    self__YZE=__infix_sub__FKB(self__AXE,to_integer__K2( 1));
    while (__infix_greater_equal__UHB(self__YZE,limit_down__BXE)) {
      put__to__0XE(self__ZWE,'\0',self__YZE);
      self__YZE=__infix_sub__FKB(self__YZE,to_integer__K2( 1));
    };
  };
  return(result__IUE);
}

static void *new_intern__FM(signed char *p__HM,signed long nb_char__IM)
// STRING_CONSTANT new_intern(STRING_CONSTANT,NATIVE_ARRAY,INTEGER)
{
  void *result__JM,*result__AP,*self__3UD;
  void  *ptr__BP;
  signed long sz__CP;
  result__JM=NULL;
  ptr__BP=NULL;
  result__AP=NULL;
  sz__CP= 0;
  sz__CP=sizeof(struct __STRING_CONSTANT);
  if ((sz__CP== 0)) {
    result__AP=STRING_CONSTANT;
  } else {
    ptr__BP=allocation__SR(sz__CP);
    copy__from__size__ACD(ptr__BP,((void  *)((STRING_CONSTANT))),sz__CP);
    result__AP=((void *)((ptr__BP)));
  };
  result__JM=result__AP;
  self__3UD=result__JM;
  ((struct __STRING_CONSTANT *)self__3UD)->parent_abstract_string__WH.storage__RM=p__HM;
  ((struct __STRING_CONSTANT *)self__3UD)->parent_abstract_string__WH.count__SM=nb_char__IM;
  return(result__JM);
}

static void *create__DVD(void *lab__FVD)
// NODE create(NODE_COMPOSITE,NULLxSTRING_CONSTANT)
{
  void *result__GVD,*result__OVD,*result__D1D,*self__O3D,*result__FZD;
  void *self__UXD;
  void  *ptr__PVD,*ptr__E1D;
  signed long sz__QVD,sz__F1D;
  result__GVD=NULL;
  ptr__PVD=NULL;
  result__OVD=NULL;
  sz__QVD= 0;
  sz__QVD=sizeof(struct __NODE_COMPOSITE);
  if ((sz__QVD== 0)) {
    result__OVD=NODE_COMPOSITE;
  } else {
    ptr__PVD=allocation__SR(sz__QVD);
    copy__from__size__ACD(ptr__PVD,((void  *)((NODE_COMPOSITE))),sz__QVD);
    result__OVD=((void *)((ptr__PVD)));
  };
  result__GVD=result__OVD;
  self__UXD=result__GVD;
  ((struct __NODE_COMPOSITE *)self__UXD)->parent_node__6K.label__XK=lab__FVD;
  result__FZD=NULL;
  ptr__E1D=NULL;
  result__D1D=NULL;
  sz__F1D= 0;
  sz__F1D=sizeof(struct __LINKED_LIST__NODE);
  if ((sz__F1D== 0)) {
    result__D1D=LINKED_LIST__NODE;
  } else {
    ptr__E1D=allocation__SR(sz__F1D);
    copy__from__size__ACD(ptr__E1D,((void  *)((LINKED_LIST__NODE))),sz__F1D);
    result__D1D=((void *)((ptr__E1D)));
  };
  result__FZD=result__D1D;
  self__O3D=result__FZD;
  ((struct __LINKED_LIST__NODE *)self__O3D)->first_link__2XD=NULL;
  ((struct __LINKED_LIST__NODE *)self__O3D)->parent_linked_collection__1XD.upper__NZD=to_integer__K2( 0);
  ((struct __LINKED_LIST__NODE *)self__O3D)->last_link__3XD=NULL;
  ((struct __LINKED_LIST__NODE *)self__O3D)->mem_idx__4XD=to_integer__K2( 0);
  ((struct __LINKED_LIST__NODE *)self__O3D)->mem_lnk__5XD=NULL;
  ((struct __NODE_COMPOSITE *)self__UXD)->children__7K=result__FZD;
  return(result__GVD);
}

static void add__D5D(void *self__E5D,void *n__F5D)
// NODE_COMPOSITE add(NODE_COMPOSITE,NODE_COMPOSITExNULL)
{
  void *self__P7D,*self__RAE,*lnk__M5D,*self__K5D,*element__L5D;
  self__K5D=((struct __NODE_COMPOSITE *)self__E5D)->children__7K;
  element__L5D=n__F5D;
  lnk__M5D=NULL;
  if ((((struct __LINKED_LIST__NODE *)self__K5D)->first_link__2XD==NULL)) {
    self__P7D=self__K5D;
    ((struct __LINKED_LIST__NODE *)self__P7D)->first_link__2XD=create__next__T7D(element__L5D);
    ((struct __LINKED_LIST__NODE *)self__P7D)->parent_linked_collection__1XD.upper__NZD=to_integer__K2( 1);
    ((struct __LINKED_LIST__NODE *)self__P7D)->last_link__3XD=((struct __LINKED_LIST__NODE *)self__K5D)->first_link__2XD;
    ((struct __LINKED_LIST__NODE *)self__P7D)->mem_idx__4XD=to_integer__K2( 1);
    ((struct __LINKED_LIST__NODE *)self__P7D)->mem_lnk__5XD=((struct __LINKED_LIST__NODE *)self__K5D)->first_link__2XD;
  } else {
    self__RAE=self__K5D;
    lnk__M5D=create__next__T7D(element__L5D);
    set_next__XAE(((struct __LINKED_LIST__NODE *)self__K5D)->last_link__3XD,lnk__M5D);
    ((struct __LINKED_LIST__NODE *)self__RAE)->parent_linked_collection__1XD.upper__NZD=__infix_add__7QB(((struct __LINKED_LIST__NODE *)self__K5D)->parent_linked_collection__1XD.upper__NZD,to_integer__K2( 1));
    ((struct __LINKED_LIST__NODE *)self__RAE)->last_link__3XD=lnk__M5D;
  };
}

static void *create__SDE(void *lab__UDE)
// NODE create(NODE,NULLxSTRING_CONSTANT)
{
  void *result__VDE,*result__1DE;
  void  *ptr__2DE;
  signed long sz__3DE;
  result__VDE=NULL;
  ptr__2DE=NULL;
  result__1DE=NULL;
  sz__3DE= 0;
  sz__3DE=sizeof(struct __NODE);
  if ((sz__3DE== 0)) {
    result__1DE=NODE;
  } else {
    ptr__2DE=allocation__SR(sz__3DE);
    copy__from__size__ACD(ptr__2DE,((void  *)((NODE))),sz__3DE);
    result__1DE=((void *)((ptr__2DE)));
  };
  result__VDE=result__1DE;
  ((struct __NODE *)result__VDE)->label__XK=lab__UDE;
  return(result__VDE);
}

static void add__8FE(void *self__9FE,void *n__AGE)
// NODE_COMPOSITE add(NODE_COMPOSITE,NULLxNODE)
{
  void *self__OHE,*self__NIE,*lnk__HGE,*self__FGE,*element__GGE;
  self__FGE=((struct __NODE_COMPOSITE *)self__9FE)->children__7K;
  element__GGE=n__AGE;
  lnk__HGE=NULL;
  if ((((struct __LINKED_LIST__NODE *)self__FGE)->first_link__2XD==NULL)) {
    self__OHE=self__FGE;
    ((struct __LINKED_LIST__NODE *)self__OHE)->first_link__2XD=create__next__SHE(element__GGE);
    ((struct __LINKED_LIST__NODE *)self__OHE)->parent_linked_collection__1XD.upper__NZD=to_integer__K2( 1);
    ((struct __LINKED_LIST__NODE *)self__OHE)->last_link__3XD=((struct __LINKED_LIST__NODE *)self__FGE)->first_link__2XD;
    ((struct __LINKED_LIST__NODE *)self__OHE)->mem_idx__4XD=to_integer__K2( 1);
    ((struct __LINKED_LIST__NODE *)self__OHE)->mem_lnk__5XD=((struct __LINKED_LIST__NODE *)self__FGE)->first_link__2XD;
  } else {
    self__NIE=self__FGE;
    lnk__HGE=create__next__SHE(element__GGE);
    set_next__XAE(((struct __LINKED_LIST__NODE *)self__FGE)->last_link__3XD,lnk__HGE);
    ((struct __LINKED_LIST__NODE *)self__NIE)->parent_linked_collection__1XD.upper__NZD=__infix_add__7QB(((struct __LINKED_LIST__NODE *)self__FGE)->parent_linked_collection__1XD.upper__NZD,to_integer__K2( 1));
    ((struct __LINKED_LIST__NODE *)self__NIE)->last_link__3XD=lnk__HGE;
  };
}

static void print__7ME(void *self__8ME)
// NODE_COMPOSITE print(NODE_COMPOSITE)
{
  unsigned long self__UQF,other__VQF,self__JQF,limit_up__2PF;
  void *___tmp__BNE,*self__ZEF,*self__0PF,*self__JTF,*p_block__L0F;
  void *n_block__M0F,*pp_block__N0F,*nn_block__O0F,*block__P0F,*blk__K0F;
  void *result__5BG,*block__4BG,*p_block__29F,*n_block__39F;
  unsigned long limit_low__3PF,___tmp__VKF,size__Q0F,next__6BG;
  void *pp_block__49F,*nn_block__59F,*block__69F,*blk__19F;
  signed long ___tmp__RFF,___tmp__TFF,size__BKF,index__CKF,nb__6JF;
  void *first_block__7JF,*cur_block__8JF,*p_block__9JF,*n_block__AKF;
  signed long old_size__GIF,old_nb_elts__FFF,new_nb_elts__GFF,i1__VLG;
  void *self__9EF,*self__CCF,*other__DCF,*self__2TG,*self__UUG;
  signed long i2__WLG,other_count__ECF,needed_capacity__FCF,___tmp__0CF;
  void *self__KQG,*self__HPG,*___tmp__MNE,*self__GXG,*___tmp__DNE;
  signed long i__LQG,i__IPG,n__HXG,___tmp__DXG,self__CKG,limit_up__DKG;
  unsigned short idx__MTF;
  void *___tmp__ENE,*___tmp__PNE;
  unsigned long size__79F,p__DKF;
  void  *new_pointer__IIF,*old_ptr__FIF,*old_ptr__IFF,*new_ptr__JFF;
  signed char *new__HFF,*___tmp__RCF,*___tmp__ZCF,*___tmp__YCF;
  signed long self__UOG,limit_up__VOG;
  char result__ABF,result__Q8F,___tmp__9KF;
  print__N1E(indent__1K);
  print__Z6E(((struct __NODE_COMPOSITE *)self__8ME)->parent_node__6K.label__XK);
  print__R8('\n');
  ___tmp__BNE=((struct __NODE_COMPOSITE *)self__8ME)->children__7K;
  result__ABF=FALSE;
  result__ABF=(((struct __LINKED_LIST__NODE *)___tmp__BNE)->first_link__2XD==NULL);
  if (result__ABF) {
  } else {
    ___tmp__DNE=indent__1K;
    ___tmp__ENE=new_intern__FM(__string_10, 2);
    self__CCF=___tmp__DNE;
    other__DCF=___tmp__ENE;
    needed_capacity__FCF= 0;
    other_count__ECF= 0;
    other_count__ECF=((struct __STRING_CONSTANT *)other__DCF)->parent_abstract_string__WH.count__SM;
    needed_capacity__FCF=__infix_sub__WRB(((struct __STRING *)self__CCF)->parent_abstract_string__2NE.count__SM,__prefix_sub__HRB(other_count__ECF));
    if ((! __infix_greater_equal__UHB(((struct __STRING *)self__CCF)->capacity__4NE,needed_capacity__FCF))) {
      if ((((struct __STRING *)self__CCF)->capacity__4NE== 0)) {
        self__ZEF=self__CCF;
        ((struct __STRING *)self__ZEF)->capacity__4NE=needed_capacity__FCF;
        ((struct __STRING *)self__ZEF)->parent_abstract_string__2NE.storage__RM=calloc__FUE(((struct __STRING *)self__CCF)->capacity__4NE);
      } else {
        self__9EF=self__CCF;
        ___tmp__RCF=((struct __STRING *)self__CCF)->parent_abstract_string__2NE.storage__RM;
        old_nb_elts__FFF=((struct __STRING *)self__CCF)->capacity__4NE;
        new_nb_elts__GFF=needed_capacity__FCF;
        new__HFF=NULL;
        new_ptr__JFF=NULL;
        old_ptr__IFF=NULL;
        old_ptr__IFF=((void  *)((___tmp__RCF)));
        ___tmp__RFF=__infix_mul__HWE(old_nb_elts__FFF,pointer_size__OD);
        ___tmp__TFF=__infix_mul__HWE(new_nb_elts__GFF,pointer_size__OD);
        old_ptr__FIF=old_ptr__IFF;
        old_size__GIF=___tmp__RFF;
        new_pointer__IIF=NULL;
        new_pointer__IIF=allocation__SR(___tmp__TFF);
        copy__from__size__ACD(new_pointer__IIF,old_ptr__FIF,old_size__GIF);
        nb__6JF=old_size__GIF;
        p_block__9JF=NULL;
        n_block__AKF=NULL;
        cur_block__8JF=NULL;
        first_block__7JF=NULL;
        index__CKF= 0;
        size__BKF= 0;
        p__DKF= 0;
        p__DKF=to_uinteger__7GD(old_ptr__FIF);
        if (__infix_less_equal__EQB(nb__6JF,to_integer__K2( 128))) {
          size__BKF=__infix_and__6RB(__infix_add__7QB(nb__6JF,to_integer__K2( 1)),to_integer__K2( 254));
          index__CKF=__infix_sub__FKB(__infix_greater_greater__MHD(size__BKF, 1),to_integer__K2( 1));
          first_block__7JF=small_fat__KP[index__CKF];
          cur_block__8JF=first_block__7JF;
          until_do__OPF:
          {
            self__0PF=cur_block__8JF;
            limit_up__2PF= 0;
            limit_low__3PF= 0;
            limit_low__3PF=get_adress__XDC(self__0PF);
            limit_up__2PF=__infix_add__LEB(limit_low__3PF,size__D0B(self__0PF));
            self__JQF=p__DKF;
            self__UQF=self__JQF;
            other__VQF=limit_low__3PF;
            if ((! ((__infix_greater_diese__3QF(self__UQF,other__VQF) | __infix_equal_equal__H1B(self__UQF,other__VQF)) && (! __infix_greater_diese__3QF(self__JQF,limit_up__2PF))))) {
              cur_block__8JF=((struct __MEM_BLOCK *)cur_block__8JF)->next_same__HS;
              goto until_do__OPF;
            };
          };
          ___tmp__VKF=__infix_sub__7EB(p__DKF,get_adress__XDC(cur_block__8JF));
          self__JTF=cur_block__8JF;
          idx__MTF= 0;
          idx__MTF=to_ushortint__9PC(__infix_greater_greater__LTB(___tmp__VKF));
          memory__POC(self__JTF)[idx__MTF]=((struct __MEM_BLOCK *)self__JTF)->first_free__JS;
          ((struct __MEM_BLOCK *)self__JTF)->first_free__JS=idx__MTF;
          ((struct __MEM_BLOCK *)self__JTF)->small_size__IS=(((struct __MEM_BLOCK *)self__JTF)->small_size__IS-((unsigned short )((size__BKF))));
          if ((((struct __MEM_BLOCK *)cur_block__8JF)->small_size__IS== 4)) {
            n_block__AKF=((struct __MEM_BLOCK *)cur_block__8JF)->next_same__HS;
            p_block__9JF=((struct __MEM_BLOCK *)cur_block__8JF)->prev_same__GS;
            set_prev_same__78B(n_block__AKF,p_block__9JF);
            set_next_same__V8B(p_block__9JF,n_block__AKF);
            if ((cur_block__8JF==first_block__7JF)) {
              if ((n_block__AKF==cur_block__8JF)) {
                put__to__QIB(small_fat__KP,index__CKF);
              } else {
                put__to__TYF(small_fat__KP,n_block__AKF,index__CKF);
              };
            };
            blk__K0F=cur_block__8JF;
            nn_block__O0F=NULL;
            pp_block__N0F=NULL;
            block__P0F=NULL;
            n_block__M0F=NULL;
            p_block__L0F=NULL;
            size__Q0F= 0;
            size__Q0F=size__D0B(blk__K0F);
            p_block__L0F=((struct __MEM_BLOCK *)blk__K0F)->prev__FS;
            n_block__M0F=get_next__4EC(blk__K0F);
            if (((p_block__L0F!=NULL) && is_free__D5B(p_block__L0F))) {
              block__P0F=p_block__L0F;
              size__Q0F=__infix_add__LEB(__infix_add__LEB(size__Q0F,size__D0B(block__P0F)),object_size__PS);
            } else {
              block__P0F=blk__K0F;
            };
            if (((n_block__M0F!=NULL) && is_free__D5B(n_block__M0F))) {
              size__Q0F=__infix_add__LEB(__infix_add__LEB(size__Q0F,size__D0B(n_block__M0F)),object_size__PS);
              pp_block__N0F=((struct __MEM_BLOCK *)n_block__M0F)->prev_same__GS;
              nn_block__O0F=((struct __MEM_BLOCK *)n_block__M0F)->next_same__HS;
              if ((pp_block__N0F==NULL)) {
                first_free__LP=nn_block__O0F;
              } else {
                set_next_same__V8B(pp_block__N0F,nn_block__O0F);
              };
              if ((nn_block__O0F!=NULL)) {
                set_prev_same__78B(nn_block__O0F,pp_block__N0F);
              };
              n_block__M0F=get_next__4EC(n_block__M0F);
            };
            set_size__C6B(block__P0F,size__Q0F);
            if ((n_block__M0F==NULL)) {
              last_block__PP=block__P0F;
            } else {
              set_prev__Q8B(n_block__M0F,block__P0F);
            };
            if ((! is_free__D5B(block__P0F))) {
              to_free__95F(block__P0F);
              set_prev_same__OKC(block__P0F,NULL);
              set_next_same__V8B(block__P0F,first_free__LP);
              if ((first_free__LP!=NULL)) {
                set_prev_same__78B(first_free__LP,block__P0F);
              };
              first_free__LP=block__P0F;
            };
            ___tmp__9KF=TRUE;
          } else {
            ___tmp__9KF=FALSE;
          };
          if (___tmp__9KF) {
          } else {
            result__Q8F=FALSE;
            result__Q8F=(cur_block__8JF!=first_block__7JF);
            if (result__Q8F) {
              n_block__AKF=((struct __MEM_BLOCK *)cur_block__8JF)->next_same__HS;
              p_block__9JF=((struct __MEM_BLOCK *)cur_block__8JF)->prev_same__GS;
              set_prev_same__78B(n_block__AKF,p_block__9JF);
              set_next_same__V8B(p_block__9JF,n_block__AKF);
              p_block__9JF=((struct __MEM_BLOCK *)first_block__7JF)->prev_same__GS;
              set_next_same__V8B(cur_block__8JF,first_block__7JF);
              set_prev_same__78B(cur_block__8JF,p_block__9JF);
              set_prev_same__78B(first_block__7JF,cur_block__8JF);
              set_next_same__V8B(p_block__9JF,cur_block__8JF);
              put__to__TYF(small_fat__KP,cur_block__8JF,index__CKF);
            };
          };
        } else {
          blk__19F=get_block__IMB(__infix_sub__7EB(p__DKF,object_size__PS));
          nn_block__59F=NULL;
          pp_block__49F=NULL;
          block__69F=NULL;
          n_block__39F=NULL;
          p_block__29F=NULL;
          size__79F= 0;
          size__79F=size__D0B(blk__19F);
          p_block__29F=((struct __MEM_BLOCK *)blk__19F)->prev__FS;
          block__4BG=blk__19F;
          result__5BG=NULL;
          next__6BG= 0;
          next__6BG=__infix_add__LEB(get_adress__XDC(block__4BG),size__D0B(block__4BG));
          if ((next__6BG!=__infix_add__2LB(end_memory__NP,to_uinteger__IY( 1)))) {
            result__5BG=get_block__IMB(next__6BG);
          };
          n_block__39F=result__5BG;
          if (((p_block__29F!=NULL) && is_free__D5B(p_block__29F))) {
            block__69F=p_block__29F;
            size__79F=__infix_add__LEB(__infix_add__LEB(size__79F,size__D0B(block__69F)),object_size__PS);
          } else {
            block__69F=blk__19F;
          };
          if (((n_block__39F!=NULL) && is_free__D5B(n_block__39F))) {
            size__79F=__infix_add__LEB(__infix_add__LEB(size__79F,size__D0B(n_block__39F)),object_size__PS);
            pp_block__49F=((struct __MEM_BLOCK *)n_block__39F)->prev_same__GS;
            nn_block__59F=((struct __MEM_BLOCK *)n_block__39F)->next_same__HS;
            if ((pp_block__49F==NULL)) {
              first_free__LP=nn_block__59F;
            } else {
              set_next_same__V8B(pp_block__49F,nn_block__59F);
            };
            if ((nn_block__59F!=NULL)) {
              set_prev_same__78B(nn_block__59F,pp_block__49F);
            };
            n_block__39F=get_next__4EC(n_block__39F);
          };
          set_size__C6B(block__69F,size__79F);
          if ((n_block__39F==NULL)) {
            last_block__PP=block__69F;
          } else {
            set_prev__Q8B(n_block__39F,block__69F);
          };
          if ((! is_free__D5B(block__69F))) {
            to_free__95F(block__69F);
            set_prev_same__OKC(block__69F,NULL);
            set_next_same__V8B(block__69F,first_free__LP);
            if ((first_free__LP!=NULL)) {
              set_prev_same__78B(first_free__LP,block__69F);
            };
            first_free__LP=block__69F;
          };
        };
        new_ptr__JFF=new_pointer__IIF;
        new__HFF=((signed char *)((void*)(new_ptr__JFF)));
        self__CKG=old_nb_elts__FFF;
        limit_up__DKG=__infix_sub__FKB(new_nb_elts__GFF,to_integer__K2( 1));
        while (__infix_less_equal__03E(self__CKG,limit_up__DKG)) {
          put__to__0XE(new__HFF,'\0',self__CKG);
          self__CKG=__infix_add__7QB(self__CKG,to_integer__K2( 1));
        };
        ((struct __STRING *)self__9EF)->parent_abstract_string__2NE.storage__RM=new__HFF;
        ((struct __STRING *)self__9EF)->capacity__4NE=needed_capacity__FCF;
      };
    };
    ___tmp__YCF=((struct __STRING *)self__CCF)->parent_abstract_string__2NE.storage__RM;
    ___tmp__0CF=((struct __STRING *)self__CCF)->parent_abstract_string__2NE.count__SM;
    ___tmp__ZCF=((struct __STRING_CONSTANT *)other__DCF)->parent_abstract_string__WH.storage__RM;
    i2__WLG= 0;
    i1__VLG= 0;
    i1__VLG=___tmp__0CF;
    while ((! (i2__WLG==other_count__ECF))) {
      put__to__0XE(___tmp__YCF,item__P5E(___tmp__ZCF,i2__WLG),i1__VLG);
      i2__WLG=__infix_add__7QB(i2__WLG,to_integer__K2( 1));
      i1__VLG=__infix_add__7QB(i1__VLG,to_integer__K2( 1));
    };
    ((struct __STRING *)self__CCF)->parent_abstract_string__2NE.count__SM=needed_capacity__FCF;
    self__UOG=lower__MZD;
    limit_up__VOG=((struct __LINKED_LIST__NODE *)((struct __NODE_COMPOSITE *)self__8ME)->children__7K)->parent_linked_collection__1XD.upper__NZD;
    while (__infix_less_equal__03E(self__UOG,limit_up__VOG)) {
      self__HPG=((struct __NODE_COMPOSITE *)self__8ME)->children__7K;
      i__IPG=self__UOG;
      if ((i__IPG!=((struct __LINKED_LIST__NODE *)self__HPG)->mem_idx__4XD)) {
        self__KQG=self__HPG;
        i__LQG=i__IPG;
        if (__infix_greater__4HB(((struct __LINKED_LIST__NODE *)self__KQG)->mem_idx__4XD,i__LQG)) {
          self__2TG=self__KQG;
          ((struct __LINKED_LIST__NODE *)self__2TG)->mem_idx__4XD=to_integer__K2( 1);
          ((struct __LINKED_LIST__NODE *)self__2TG)->mem_lnk__5XD=((struct __LINKED_LIST__NODE *)self__KQG)->first_link__2XD;
        };
        while ((! (i__LQG==((struct __LINKED_LIST__NODE *)self__KQG)->mem_idx__4XD))) {
          self__UUG=self__KQG;
          ((struct __LINKED_LIST__NODE *)self__UUG)->mem_lnk__5XD=((struct __LINK__NODE *)((struct __LINKED_LIST__NODE *)self__KQG)->mem_lnk__5XD)->next__23D;
          ((struct __LINKED_LIST__NODE *)self__UUG)->mem_idx__4XD=__infix_add__7QB(((struct __LINKED_LIST__NODE *)self__KQG)->mem_idx__4XD,to_integer__K2( 1));
        };
      };
      ___tmp__MNE=((struct __LINK__NODE *)((struct __LINKED_LIST__NODE *)self__HPG)->mem_lnk__5XD)->item__13D;
      if (((struct ___OBJ *)___tmp__MNE)->__id==__NODE_COMPOSITE__) {
        print__7ME(___tmp__MNE);
      } else {
        print__N1E(indent__1K);
        print__Z6E(((struct __NODE *)___tmp__MNE)->label__XK);
        print__R8('\n');
      };
      self__UOG=__infix_add__7QB(self__UOG,to_integer__K2( 1));
    };
    ___tmp__PNE=indent__1K;
    ___tmp__DXG=to_integer__K2( 2);
    self__GXG=___tmp__PNE;
    n__HXG=___tmp__DXG;
    if (__infix_greater__4HB(n__HXG,((struct __STRING *)self__GXG)->parent_abstract_string__2NE.count__SM)) {
      ((struct __STRING *)self__GXG)->parent_abstract_string__2NE.count__SM=to_integer__K2( 0);
    } else {
      ((struct __STRING *)self__GXG)->parent_abstract_string__2NE.count__SM=__infix_sub__WRB(((struct __STRING *)self__GXG)->parent_abstract_string__2NE.count__SM,n__HXG);
    };
  };
}

static void print_nbx__C0(unsigned long n__E0)
// MEMORY print_nbx(MEMORY,UINTEGER)
{
  int self__E1,self__Q1;
  signed char car__U0,self__S4,other__T4,___tmp__Y4;
  car__U0= 0;
  self__E1= 28;
  downto__by__do__D1:
  {
    self__Q1=self__E1;
    if ((__infix_greater__X1(self__Q1, 0) | (self__Q1== 0))) {
      car__U0=((signed char )((__infix_and__C3(((unsigned long )((n__E0)>>(to_integer__K2(self__E1)))),to_uinteger__IY( 15)))));
      ___tmp__Y4=to_smallint__Z4( 10);
      self__S4=car__U0;
      other__T4=___tmp__Y4;
      if (((self__S4>other__T4) | (self__S4==other__T4))) {
        print__R8(__infix_add__66('A',to_character__C6((car__U0-to_smallint__Z4( 10)))));
      } else {
        print__R8(__infix_add__66('0',to_character__C6(car__U0)));
      };
      self__E1=__infix_sub__WBB(self__E1, 4);
      goto downto__by__do__D1;
    };
  };
}

static void print__R8(signed char self__S8)
//- CHARACTER print(CHARACTER)
{
  put_character__99(self__S8);
}

static unsigned long __infix_sub__BEB(unsigned long self__CEB,unsigned long other__DEB)
// NUMERIC __infix_sub(UINTEGER,NUMERIC)
{
  return((self__CEB-other__DEB));
}

static unsigned long __infix_add__LEB(unsigned long self__MEB,unsigned long other__NEB)
// NUMERIC __infix_add(UINTEGER,UINTEGER)
{
  return(__infix_sub__7EB(self__MEB,__prefix_sub__SEB(other__NEB)));
}

static unsigned long __prefix_logicnot__HFB(unsigned long self__IFB)
// NUMERIC __prefix_logicnot(UINTEGER)
{
  return(__infix_sub__7EB(__prefix_sub__SEB(to_uinteger__IY( 1)),self__IFB));
}

static unsigned long __infix_and__4FB(unsigned long self__5FB,unsigned long other__6FB)
// NUMERIC __infix_and(UINTEGER,UINTEGER)
{
  return((self__5FB&other__6FB));
}

static void put__to__QIB(void **self__RIB,signed long index__TIB)
//- NATIVE_ARRAY put__to(NATIVE_ARRAY,NULL,INTEGER)
{
  self__RIB[index__TIB]=NULL;
}

static signed long __infix_sub__FKB(signed long self__GKB,signed long other__HKB)
// NUMERIC __infix_sub(INTEGER,NUMERIC)
{
  return((self__GKB-other__HKB));
}

static unsigned long __infix_add__2LB(unsigned long self__3LB,unsigned long other__4LB)
// NUMERIC __infix_add(UINTEGER,NUMERIC)
{
  return(__infix_sub__7EB(self__3LB,__prefix_sub__SEB(other__4LB)));
}

static void *get_block__IMB(unsigned long p__KMB)
// MEMORY get_block(MEMORY,UINTEGER)
{
  return(((void *)((p__KMB))));
}

static unsigned long __infix_sub__7EB(unsigned long self__8EB,unsigned long other__9EB)
// NUMERIC __infix_sub(UINTEGER,UINTEGER)
{
  return((self__8EB-other__9EB));
}

static void make__HNB(void *self__INB,unsigned long siz__JNB)
// MEM_BLOCK make(MEM_BLOCK,UINTEGER)
{
  ((struct __MEM_BLOCK *)self__INB)->size_and_flags__ES=siz__JNB;
  ((struct __MEM_BLOCK *)self__INB)->next_same__HS=NULL;
  ((struct __MEM_BLOCK *)self__INB)->prev_same__GS=((struct __MEM_BLOCK *)self__INB)->next_same__HS;
  ((struct __MEM_BLOCK *)self__INB)->prev__FS=((struct __MEM_BLOCK *)self__INB)->prev_same__GS;
}

static char __infix_less_equal__EQB(signed long self__FQB,signed long other__GQB)
// NUMERIC __infix_less_equal(INTEGER,NUMERIC)
{
  return((! __infix_greater__4HB(self__FQB,other__GQB)));
}

static signed long __infix_add__7QB(signed long self__8QB,signed long other__9QB)
// NUMERIC __infix_add(INTEGER,NUMERIC)
{
  return(__infix_sub__WRB(self__8QB,__prefix_sub__HRB(other__9QB)));
}

static signed long __infix_and__6RB(signed long self__7RB,signed long other__8RB)
// NUMERIC __infix_and(INTEGER,NUMERIC)
{
  return((self__7RB&other__8RB));
}

static unsigned long to_uinteger__ESB(signed long self__FSB)
// INTEGER to_uinteger(INTEGER)
{
  return(((unsigned long )((self__FSB))));
}

static unsigned long __infix_greater_greater__LTB(unsigned long self__MTB)
// NUMERIC __infix_greater_greater(UINTEGER,NUMERIC)
{
  return(((unsigned long )((self__MTB)>>( 1))));
}

static char is_small_busy__LSC(void *self__MSC,unsigned long sz__NSC)
// MEM_BLOCK is_small_busy(MEM_BLOCK,UINTEGER)
{
  return(__infix_less__R0B((size__D0B(self__MSC)-to_uinteger__2RC(((struct __MEM_BLOCK *)self__MSC)->small_size__IS)),sz__NSC));
}

static int __infix_add__9YB(int self__AZB,int other__BZB)
// NUMERIC __infix_add(NUMERIC,NUMERIC)
{
  return(__infix_sub__WBB(self__AZB,__prefix_sub__EZB(other__BZB)));
}

static unsigned long size__D0B(void *self__E0B)
// MEM_BLOCK size(MEM_BLOCK)
{
  return(__infix_and__C3(((struct __MEM_BLOCK *)self__E0B)->size_and_flags__ES,to_uinteger__IY( 4294967294LU)));
}

static char __infix_less__R0B(unsigned long self__S0B,unsigned long other__T0B)
// NUMERIC __infix_less(UINTEGER,UINTEGER)
{
  unsigned long self__10B,other__20B;
  char ___tmp__60B;
  self__10B=self__S0B;
  other__20B=other__T0B;
  ___tmp__60B=__infix_greater__A1B(self__10B,other__20B);
  return((! (___tmp__60B | __infix_equal_equal__H1B(self__10B,other__20B))));
}

static unsigned long __infix_and__C3(unsigned long self__D3,unsigned long other__E3)
// NUMERIC __infix_and(UINTEGER,NUMERIC)
{
  return((self__D3&other__E3));
}

static char is_free__D5B(void *self__E5B)
// MEM_BLOCK is_free(MEM_BLOCK)
{
  return((! (__infix_and__C3(((struct __MEM_BLOCK *)self__E5B)->size_and_flags__ES,to_uinteger__IY( 1))!= 0)));
}

static void set_size__C6B(void *self__D6B,unsigned long sz__E6B)
//- MEM_BLOCK set_size(MEM_BLOCK,UINTEGER)
{
  ((struct __MEM_BLOCK *)self__D6B)->size_and_flags__ES=__prefix_logicnot__HFB(__infix_and__4FB(__prefix_logicnot__HFB(sz__E6B),__prefix_logicnot__HFB(__infix_and__C3(((struct __MEM_BLOCK *)self__D6B)->size_and_flags__ES,to_uinteger__IY( 1)))));
}

static void set_prev__Q8B(void *self__R8B,void *block__S8B)
//- MEM_BLOCK set_prev(MEM_BLOCK,MEM_BLOCKxNULL)
{
  ((struct __MEM_BLOCK *)self__R8B)->prev__FS=block__S8B;
}

static void set_next_same__V8B(void *self__W8B,void *block__X8B)
//- MEM_BLOCK set_next_same(MEM_BLOCK,MEM_BLOCKxNULL)
{
  ((struct __MEM_BLOCK *)self__W8B)->next_same__HS=block__X8B;
}

static void set_prev_same__78B(void *self__88B,void *block__98B)
//- MEM_BLOCK set_prev_same(MEM_BLOCK,MEM_BLOCKxNULL)
{
  ((struct __MEM_BLOCK *)self__88B)->prev_same__GS=block__98B;
}

static void to_busy__69B(void *self__79B)
//- MEM_BLOCK to_busy(MEM_BLOCK)
{
  ((struct __MEM_BLOCK *)self__79B)->size_and_flags__ES=__prefix_logicnot__HFB(__infix_and__4FB(__prefix_logicnot__HFB(((struct __MEM_BLOCK *)self__79B)->size_and_flags__ES),__prefix_logicnot__HFB(to_uinteger__IY( 1))));
}

static int to_numeric__1CC(unsigned long self__2CC)
// NUMERIC to_numeric(UINTEGER)
{
  return(((int )((self__2CC))));
}

static int __infix_add__SCC(int other__UCC)
// NUMERIC __infix_add(NUMERIC,UINTEGER)
{
  return(__infix_sub__WBB( 128,__prefix_sub__EZB(other__UCC)));
}

static char __infix_greater__FDC(unsigned long self__GDC,unsigned long other__HDC)
// NUMERIC __infix_greater(UINTEGER,NUMERIC)
{
  return((self__GDC>other__HDC));
}

static unsigned long get_adress__XDC(void *self__YDC)
// MEM_BLOCK get_adress(MEM_BLOCK)
{
  return(__infix_add__LEB(((unsigned long )((self__YDC))),object_size__PS));
}

static void *get_next__4EC(void *block__6EC)
// MEMORY get_next(MEMORY,MEM_BLOCKxNULL)
{
  void *result__7EC;
  unsigned long next__8EC;
  result__7EC=NULL;
  next__8EC= 0;
  next__8EC=__infix_add__LEB(get_adress__XDC(block__6EC),size__D0B(block__6EC));
  if ((next__8EC!=__infix_add__2LB(end_memory__NP,to_uinteger__IY( 1)))) {
    result__7EC=get_block__IMB(next__8EC);
  };
  return(result__7EC);
}

static unsigned short to_ushortint__5HC(int self__6HC)
// NUMERIC to_ushortint(NUMERIC)
{
  return(((unsigned short )((self__6HC))));
}

static void put__to__QIC(void **self__RIC,void *element__SIC,unsigned long index__TIC)
//- NATIVE_ARRAY put__to(NATIVE_ARRAY,MEM_BLOCKxNULL,UINTEGER)
{
  self__RIC[index__TIC]=element__SIC;
}

static void set_prev_same__OKC(void *self__PKC,void *block__QKC)
//- MEM_BLOCK set_prev_same(MEM_BLOCK,NULL)
{
  ((struct __MEM_BLOCK *)self__PKC)->prev_same__GS=block__QKC;
}

static unsigned short *memory__POC(void *self__QOC)
// MEM_BLOCK memory(MEM_BLOCK)
{
  return(((unsigned short *)((get_adress__XDC(self__QOC)))));
}

static unsigned short to_ushortint__9PC(unsigned long self__AQC)
// UINTEGER to_ushortint(UINTEGER)
{
  return(((unsigned short )((self__AQC))));
}

static unsigned short __infix_sub__TRC(unsigned short self__URC,unsigned short other__VRC)
// NUMERIC __infix_sub(USHORTINT,USHORTINT)
{
  return((self__URC-other__VRC));
}

static unsigned long to_uinteger__2RC(unsigned short self__3RC)
// USHORTINT to_uinteger(USHORTINT)
{
  return(((unsigned long )((self__3RC))));
}

static unsigned long to_uinteger__7GD(void  *self__8GD)
// POINTER to_uinteger(POINTER)
{
  return(((unsigned long )((self__8GD))));
}

static signed long __infix_greater_greater__MHD(signed long self__NHD,int other__OHD)
// NUMERIC __infix_greater_greater(INTEGER,NUMERIC)
{
  return(((signed long )((self__NHD)>>(other__OHD))));
}

static unsigned long *force_conversion__BID(unsigned long obj__DID)
// OBJECT force_conversion(NATIVE_ARRAY,UINTEGER)
{
  return(((unsigned long *)((obj__DID))));
}

static int to_numeric__6ID(signed long self__7ID)
// NUMERIC to_numeric(INTEGER)
{
  return(((int )((self__7ID))));
}

static char __infix_less_equal__HJD(int self__IJD,int other__JJD)
// NUMERIC __infix_less_equal(NUMERIC,NUMERIC)
{
  return((! __infix_greater__X1(self__IJD,other__JJD)));
}

static unsigned long item__4JD(unsigned long *self__5JD,signed long index__6JD)
// NATIVE_ARRAY item(NATIVE_ARRAY,INTEGER)
{
  return(self__5JD[index__6JD]);
}

static void put__to__VKD(unsigned long *self__WKD,unsigned long element__XKD,signed long index__YKD)
//- NATIVE_ARRAY put__to(NATIVE_ARRAY,UINTEGER,INTEGER)
{
  self__WKD[index__YKD]=element__XKD;
}

static unsigned long __infix_add__2ND(unsigned long self__3ND,unsigned long other__4ND)
// NUMERIC __infix_add(UINTEGER,INTEGER)
{
  return(__infix_sub__7EB(self__3ND,__prefix_sub__SEB(other__4ND)));
}

static unsigned char *force_conversion__QPD(unsigned long obj__SPD)
// OBJECT force_conversion(NATIVE_ARRAY,UINTEGER)
{
  return(((unsigned char *)((obj__SPD))));
}

static unsigned char item__2QD(unsigned char *self__3QD,signed long index__4QD)
// NATIVE_ARRAY item(NATIVE_ARRAY,INTEGER)
{
  return(self__3QD[index__4QD]);
}

static void put__to__TRD(unsigned char *self__URD,unsigned char element__VRD,signed long index__WRD)
//- NATIVE_ARRAY put__to(NATIVE_ARRAY,USMALLINT,INTEGER)
{
  self__URD[index__WRD]=element__VRD;
}

static char __infix_greater__4HB(signed long self__5HB,signed long other__6HB)
// NUMERIC __infix_greater(INTEGER,INTEGER)
{
  return((self__5HB>other__6HB));
}

static signed long __infix_mul__HWE(signed long self__IWE,signed long other__JWE)
// NUMERIC __infix_mul(INTEGER,INTEGER)
{
  return((self__IWE*other__JWE));
}

static void put__to__0XE(signed char *self__1XE,signed char element__2XE,signed long index__3XE)
//- NATIVE_ARRAY put__to(NATIVE_ARRAY,CHARACTER,INTEGER)
{
  self__1XE[index__3XE]=element__2XE;
}

static void *create__next__T7D(void *i__V7D)
// LINK create__next(LINK,NODE_COMPOSITExNULL,NULL)
{
  void *result__X7D,*self__89D;
  result__X7D=NULL;
  result__X7D=clone__27D();
  self__89D=result__X7D;
  ((struct __LINK__NODE *)self__89D)->item__13D=i__V7D;
  ((struct __LINK__NODE *)self__89D)->next__23D=NULL;
  return(result__X7D);
}

static void set_next__XAE(void *self__YAE,void *n__ZAE)
//- LINK set_next(LINK,LINKxNULL)
{
  ((struct __LINK__NODE *)self__YAE)->next__23D=n__ZAE;
}

static void *create__next__SHE(void *i__UHE)
// LINK create__next(LINK,NULLxNODE,NULL)
{
  void *result__WHE,*self__4HE;
  result__WHE=NULL;
  result__WHE=clone__27D();
  self__4HE=result__WHE;
  ((struct __LINK__NODE *)self__4HE)->item__13D=i__UHE;
  ((struct __LINK__NODE *)self__4HE)->next__23D=NULL;
  return(result__WHE);
}

static void print__N1E(void *self__O1E)
// ABSTRACT_STRING print(STRING)
{
  void *s__W1E;
  signed long self__O3E,limit_up__P3E;
  s__W1E=self__O1E;
  self__O3E=lower__TM;
  limit_up__P3E=((struct __STRING *)s__W1E)->parent_abstract_string__2NE.count__SM;
  while (__infix_less_equal__03E(self__O3E,limit_up__P3E)) {
    put_character__99(item__P5E(((struct __STRING *)s__W1E)->parent_abstract_string__2NE.storage__RM,__infix_sub__FKB(self__O3E,to_integer__K2( 1))));
    self__O3E=__infix_add__7QB(self__O3E,to_integer__K2( 1));
  };
}

static void print__Z6E(void *self__06E)
// ABSTRACT_STRING print(STRING_CONSTANT)
{
  void *s__86E;
  signed long self__W8E,limit_up__X8E;
  s__86E=self__06E;
  self__W8E=lower__TM;
  limit_up__X8E=((struct __STRING_CONSTANT *)s__86E)->parent_abstract_string__WH.count__SM;
  while (__infix_less_equal__03E(self__W8E,limit_up__X8E)) {
    put_character__99(item__P5E(((struct __STRING_CONSTANT *)s__86E)->parent_abstract_string__WH.storage__RM,__infix_sub__FKB(self__W8E,to_integer__K2( 1))));
    self__W8E=__infix_add__7QB(self__W8E,to_integer__K2( 1));
  };
}

static signed long __prefix_sub__HRB(signed long self__IRB)
// NUMERIC __prefix_sub(INTEGER)
{
  return(__infix_sub__WRB(to_integer__K2( 0),self__IRB));
}

static signed long __infix_sub__WRB(signed long self__XRB,signed long other__YRB)
// NUMERIC __infix_sub(INTEGER,INTEGER)
{
  return((self__XRB-other__YRB));
}

static char __infix_greater_diese__3QF(unsigned long self__4QF,unsigned long other__5QF)
// NUMERIC __infix_greater_diese(UINTEGER,UINTEGER)
{
  return(__infix_greater__A1B(self__4QF,other__5QF));
}

static char __infix_equal_equal__H1B(unsigned long self__I1B,unsigned long other__J1B)
// NUMERIC __infix_equal_equal(UINTEGER,UINTEGER)
{
  return((self__I1B==other__J1B));
}

static void put__to__TYF(void **self__UYF,void *element__VYF,signed long index__WYF)
//- NATIVE_ARRAY put__to(NATIVE_ARRAY,MEM_BLOCKxNULL,INTEGER)
{
  self__UYF[index__WYF]=element__VYF;
}

static void to_free__95F(void *self__A6F)
//- MEM_BLOCK to_free(MEM_BLOCK)
{
  ((struct __MEM_BLOCK *)self__A6F)->size_and_flags__ES=__infix_and__C3(((struct __MEM_BLOCK *)self__A6F)->size_and_flags__ES,to_uinteger__IY( 4294967294LU));
}

static char __infix_less_equal__03E(signed long self__13E,signed long other__23E)
// NUMERIC __infix_less_equal(INTEGER,INTEGER)
{
  return((! __infix_greater__4HB(self__13E,other__23E)));
}

static signed char item__P5E(signed char *self__Q5E,signed long index__R5E)
// NATIVE_ARRAY item(NATIVE_ARRAY,INTEGER)
{
  return(self__Q5E[index__R5E]);
}

static signed char to_smallint__Z4(int self__04)
// NUMERIC to_smallint(NUMERIC)
{
  return(((signed char )((self__04))));
}

static signed char to_character__C6(signed char self__D6)
// SMALLINT to_character(SMALLINT)
{
  return(((signed char )((self__D6))));
}

static signed char __infix_add__66(signed char self__76,signed char other__86)
// CHARACTER __infix_add(CHARACTER,CHARACTER)
{
  return(to_character__C6(__infix_sub__J8(code__E7(self__76),__infix_sub__J8(to_smallint__Z4( 0),code__E7(other__86)))));
}

static int __infix_sub__WBB(int self__XBB,int other__YBB)
// NUMERIC __infix_sub(NUMERIC,NUMERIC)
{
  return((self__XBB-other__YBB));
}

static void put_character__99(signed char c__BAB)
//- STD_OUTPUT put_character(IO,CHARACTER)
{
  fputc((int)(c__BAB),stdout);
}

static unsigned long __prefix_sub__SEB(unsigned long self__TEB)
// NUMERIC __prefix_sub(UINTEGER)
{
  return(__infix_sub__7EB(to_uinteger__IY( 0),self__TEB));
}

static int __prefix_sub__EZB(int self__FZB)
// NUMERIC __prefix_sub(NUMERIC)
{
  return(__infix_sub__WBB( 0,self__FZB));
}

static char __infix_greater__A1B(unsigned long self__B1B,unsigned long other__C1B)
// NUMERIC __infix_greater(UINTEGER,UINTEGER)
{
  return((self__B1B>other__C1B));
}

static void *clone__27D()
// OBJECT clone(LINK)
{
  void *result__47D;
  void  *ptr__57D;
  signed long sz__67D;
  ptr__57D=NULL;
  result__47D=NULL;
  sz__67D= 0;
  sz__67D=sizeof(struct __LINK__NODE);
  if ((sz__67D== 0)) {
    result__47D=LINK__NODE;
  } else {
    ptr__57D=allocation__SR(sz__67D);
    copy__from__size__ACD(ptr__57D,((void  *)((LINK__NODE))),sz__67D);
    result__47D=((void *)((ptr__57D)));
  };
  return(result__47D);
}

static signed char code__E7(signed char self__F7)
// CHARACTER code(CHARACTER)
{
  signed char result__G7;
  result__G7= 0;
  result__G7=((signed char )((self__F7)));
  return(result__G7);
}

static signed char __infix_sub__J8(signed char self__K8,signed char other__L8)
// NUMERIC __infix_sub(SMALLINT,SMALLINT)
{
  return((self__K8-other__L8));
}

