/* C code generated by Lisaac compiler (www.lisaac.org) */

#define _LARGE_FILE_API
#define _LARGEFILE_SOURCE
#define _LARGEFILE64_SOURCE
int print_string(char *str);
int arg_count;
char **arg_vector;

/*==========================*/
/* EXTERNAL                 */
/*==========================*/

/* FS_MIN */
#include <unistd.h>
/* SYSTEM */
#include <time.h>
/* UINTEGER_64 */
#include <stdint.h>
/* MEMORY */

//#define MINIMUM_SIZE 256
#define MINIMUM_SIZE 384
void *table_size[MINIMUM_SIZE/sizeof(void *)];
void *last_block[64];

/* SYSTEM_IO */

#include <stdio.h>
#include <stdlib.h>

/* Hardware 'print_char' */
void print_char(char car)
{
  fputc(car,stdout);
}

/* Hardware 'exit' */
int die_with_code(int code)
{
  exit(code);
}


/* FLOAT_REAL */
#include <math.h>

/*==========================*/
/* TYPE                     */
/*==========================*/

/* Generic Object */
struct ___OBJ {
  unsigned int __id;
};

typedef struct li__4B_struct __li__4B;
typedef struct li__JIB_struct __li__JIB;
typedef struct li__Y_struct __li__Y;
typedef struct li__GE_struct __li__FE; /* ALIAS with li__GE */
typedef struct li__5WB_struct __li__5WB;
typedef struct li__IJ_struct __li__IJ;
typedef struct li__IJ_struct __li__HJ; /* ALIAS with li__IJ */
typedef struct li__Q3K_struct __li__Q3K;
typedef struct li__GE_struct __li__GE;
/* NULL */
#ifndef NULL
#define NULL ((void *)0)
#endif

typedef void * __li__IB;
typedef unsigned long __li__0VB;
typedef unsigned int __li__U;
typedef signed int __li__K;
typedef char __li__BB;
/* li__4B */
#define __li__4B__ 0
struct li__4B_struct {
  unsigned int __id;
  __li__K li__0D;
  __li__K li__OP;
  __li__BB *li__OQK;
};
/* li__JIB */
#define __li__JIB__ 0
struct li__JIB_struct {
  __li__K li__X3K;
  __li__K li__IBL;
  void **li__53K;
};
/* li__Y */
#define __li__Y__ 1
struct li__Y_struct {
  unsigned int __id;
  __li__K li__ZB;
  __li__BB *li__0B;
};
/* li__GE */
#define __li__GE__ 1
struct li__GE_struct {
  __li__K li__1E;
  __li__K li__K1F;
  void **li__W1F;
};
/* li__FE */
#define __li__FE__ 2
typedef char __li__C;
/* li__5WB */
#define __li__5WB__ 3
struct li__5WB_struct {
  __li__5WB *li__BXB;
  volatile __li__0VB li__CXB;
  __li__5WB *li__DXB;
  __li__5WB *li__EXB;
} __attribute__ ((packed));
/* li__IJ */
#define __li__IJ__ 4
struct li__IJ_struct {
  __li__K li__T2F;
  __li__K li__52F;
  void **li__DZF;
};
/* li__HJ */
#define __li__HJ__ 5
#define li__B__ 1
#define li__I__ 0
/* li__Q3K */
#define __li__Q3K__ 6
struct li__Q3K_struct {
  __li__Y *li__L4K;
  __li__Q3K *li__X4K;
};
typedef signed int __li__Q;
typedef signed char __li__LV;

void *table_type[7];

/*==========================*/
/* GLOBAL                   */
/*==========================*/

__li__4B li__4B_={__li__4B__};
#define li__4B__ (&li__4B_)

__li__JIB li__JIB_;
#define li__JIB__ (&li__JIB_)

__li__Y li__Y_={__li__Y__};
#define li__Y__ (&li__Y_)

__li__GE li__GE_;
#define li__GE__ (&li__GE_)

__li__FE li__FE_;
#define li__FE__ (&li__FE_)

__li__5WB li__5WB_;
#define li__5WB__ (&li__5WB_)

__li__IJ li__IJ_;
#define li__IJ__ (&li__IJ_)

__li__HJ li__HJ_;
#define li__HJ__ (&li__HJ_)

__li__Q3K li__Q3K_;
#define li__Q3K__ (&li__Q3K_)

__li__0VB li__SWB;
__li__0VB li__VWB;
__li__0VB li__S1E;
__li__0VB li__JCP;
__li__IB li__HUD;
__li__5WB *li__Q0P;
__li__IB li__GC;
__li__IB li__ID;
__li__K li__J4;
__li__C li__T4;
__li__K li__44;
__li__JIB *li__QIB;
__li__FE *li__OE;

/*==========================*/
/* STRING CONSTANT          */
/*==========================*/

__li__Y __string_1={__li__Y__,2,"-1"};
__li__Y __string_2={__li__Y__,2,"-2"};
__li__Y __string_3={__li__Y__,12,"BUILD_LABEL\n"};
__li__Y __string_4={__li__Y__,28,"Error: File is not opened !\n"};
__li__Y __string_5={__li__Y__,8,"_label.s"};
__li__Y __string_6={__li__Y__,29,"Error: File is not created !\n"};
__li__Y __string_7={__li__Y__,6,"	.size"};
__li__Y __string_8={__li__Y__,7,"method_"};
__li__Y __string_9={__li__Y__,6,"_end:\n"};
__li__Y __string_10={__li__Y__,4,"@LI "};
__li__Y __string_11={__li__Y__,2,":\n"};
__li__Y __string_12={__li__Y__,4,"_end"};
__li__Y __string_13={__li__Y__,2,"-3"};
__li__Y __string_14={__li__Y__,38,"        .section .data\n__li_mountain:\n"};
__li__Y __string_15={__li__Y__,32,"# Header: <@fin,count table,-1>\n"};
__li__Y __string_16={__li__Y__,14,"        .quad "};
__li__Y __string_17={__li__Y__,5,"_fini"};
__li__Y __string_18={__li__Y__,2,",\t"};
__li__Y __string_19={__li__Y__,63,",\t-1\n# Table mountain: <@current,code p\
osition,backlink index>\n"};
__li__Y __string_20={__li__Y__,11,"\t /* index:"};
__li__Y __string_21={__li__Y__,6," back:"};
__li__Y __string_22={__li__Y__,1," "};
__li__Y __string_23={__li__Y__,3," */"};
__li__Y __string_24={__li__Y__,19,"Not enough memory.\n"};

/*==========================*/
/* FUNCTION HEADER          */
/*==========================*/

/* Source code */
static __li__IB li__S0D(__li__0VB li__U0D,__li__IB li__V0D,__li__U li__W0D);
static void** li__5OI(__li__K li__BPI);
static __li__4B* li__YN(__li__K li__0N);
static void li__CDL(__li__4B *li__DDL,__li__BB li__EDL);
static __li__IB li__EEN(__li__IB li__GEN,__li__0VB li__HEN,__li__0VB li__IEN);
static __li__K li__FHO(__li__K li__HHO);
static void** li__QSO(__li__K li__SSO);
static void li__05K(__li__JIB *li__15K,__li__Y *li__25K);
static void** li__PNI(__li__K li__RNI);
static void li__HR(__li__Y *li__IR);
static void li__IWK(__li__4B *li__JWK,__li__4B *li__KWK);
static __li__BB* li__QXK(__li__4B *li__RXK);
static void li__QS(void *li__SS);
static void li__ZPK(__li__4B *li__0PK,__li__4B *li__1PK);
static void li__ISK(__li__4B *li__JSK,void *li__KSK);
static __li__K li__S1K(__li__4B *li__T1K,void *li__U1K);
static void li__UTK(__li__4B *li__VTK,__li__Y *li__WTK);
static void li__5N(__li__K li__AO,__li__4B *li__BO);
static void li__2UK(__li__4B *li__3UK,__li__4B *li__4UK);
static __li__Y* li__ZHB(__li__4B *li__1HB);
static void li__W4F(__li__FE *li__X4F,__li__Y *li__Y4F);
static void li__WFL(__li__4B *li__XFL,__li__Y *li__YFL);
static __li__C li__FJL(__li__Y *li__GJL,void *li__HJL);
static __li__IB li__D1E(__li__U li__F1E);
static __li__IB li__GLJ(__li__0VB li__ILJ);
static __li__BB* li__MDR(__li__K li__ODR);
static __li__BB* li__E2W(__li__BB *li__F2W,__li__K li__G2W,__li__K li__H2W);
static void li__WET(__li__IB li__YET,__li__IB li__ZET,__li__0VB li__0ET);
static void li__DUW(__li__5WB *li__EUW,__li__IB li__FUW,__li__0VB li__GUW);
static __li__5WB* li__NZP(__li__0VB li__PZP);
static void li__LDW(__li__5WB *li__MDW);
static void li__QPX(__li__5WB *li__RPX);
static void li__XPM(__li__JIB *li__YPM,__li__Y *li__ZPM);
static __li__K li__COM(__li__Y *li__DOM);
static void li__3DR(__li__BB *li__4DR,__li__BB *li__5DR,__li__K li__AER);
static void li__ULW(__li__BB *li__VLW,__li__BB *li__WLW,__li__K li__XLW,__li__K li__YLW);
static __li__5WB* li__5BP();

/*==========================*/
/* SOURCE CODE              */
/*==========================*/

int main(int argc,char **argv)
{
  __li__0VB li__B0C,li__HYB,li__QHDB,li__UHDB;
  __li__IB li__5XB,li__WHDB,li__3UL,li__IGCB;
  __li__4B *li__WO,*li__DHL,*li__QN,*li__ERK,*li__UZK;
  __li__Y *li__D4,*li__E4,*li__F4,*li__NAB,*li__ZBB,*li__SGW,*li__1DX;
  __li__K li__JO,li__SYB,li__QTC,li__OHG,li__ZTL,li__DVL,li__FLX;
  __li__K li__TRCB;
  __li__U li__5HDB;
  __li__HJ *li__4XB,*li__JZB,*li__MGG;
  void **li__12F,**li__HHG;
  __li__BB *li__TO,*li__QP,*li__GGCB;
  __li__C li__1GG,li__UF,li__BEX,li__EEX;
  __li__JIB *li__0BG,*li__FDG;
  void **li__5RM;
  __li__FE *li__XVB,*li__QXB;
  void **li__V1F;
  arg_count  = argc;
  arg_vector = argv;
#ifdef _PTHREAD_H
  pthread_key_create(&current_thread, NULL);
  pthread_attr_init(&thread_attr);
  /*pthread_attr_setdetachstate(&thread_attr,PTHREAD_CREATE_DETACHED);*/
#endif
  ;
  *((__li__HJ *)li__HJ__)=(*li__IJ__);
  li__SWB=((__li__0VB ) 0);
  li__B0C=((__li__0VB ) 0);
  li__VWB=li__B0C;
  li__S1E=((__li__0VB ) 0);
  li__5WB__->li__CXB=((__li__0VB ) 0);
  li__JCP=((__li__0VB ) 0);
  li__HUD=((__li__IB )(NULL));
  li__JO=((__li__K )(arg_count));
  li__4XB=NULL;
  li__5XB=((__li__IB )(NULL));
  li__HYB=((__li__0VB )sizeof(__li__HJ));
  if ((li__HYB ==  0)) {
    li__4XB=li__HJ__;
  } else /* FALSE */ {
    li__SYB=__li__HJ__;
    li__SWB=(__li__0VB)(li__SWB - (__li__0VB)(((__li__0VB ) 0) - li__HYB));
    li__VWB=(__li__0VB)(li__B0C - (__li__0VB)(((__li__0VB ) 0) - li__HYB));
    if ((li__SYB == (__li__K)(-  1))) {
      li__QHDB=(__li__0VB)(((__li__0VB )((__li__K )(sizeof(void *)))) - ((__li__0VB ) 1));
      li__UHDB=(__li__0VB)((__li__0VB)(li__HYB - (__li__0VB)(((__li__0VB ) 0) - li__QHDB)) & (__li__0VB)((__li__0VB)(((__li__0VB ) 0) - li__QHDB) - ((__li__0VB ) 1)));
      li__QHDB=(__li__0VB)(li__UHDB / ((__li__0VB )((__li__K )(sizeof(void *)))));
      li__WHDB=li__S0D(li__UHDB,((__li__IB )(&(table_size[(li__QHDB)-1]))),((__li__U )li__UHDB));
      li__VWB=(__li__0VB)(li__VWB - (__li__0VB)(((__li__0VB ) 0) - li__HYB));
      li__5XB=li__WHDB;
    } else /* FALSE */ {
      li__5HDB=((__li__U )li__SYB);
      li__QHDB=(__li__0VB)(((__li__0VB )((__li__K )(sizeof(void *)))) - ((__li__0VB ) 1));
      li__UHDB=(__li__0VB)((__li__0VB)(li__HYB - (__li__0VB)(((__li__0VB ) 0) - li__QHDB)) & (__li__0VB)((__li__0VB)(((__li__0VB ) 0) - li__QHDB) - ((__li__0VB ) 1)));
      li__WHDB=li__S0D(li__UHDB,((__li__IB )(&(table_type[(li__5HDB)]))),(__li__U)(li__5HDB |  1));
      li__VWB=(__li__0VB)(li__VWB - (__li__0VB)(((__li__0VB ) 0) - li__HYB));
      li__5XB=li__WHDB;
    };
    li__JZB=((__li__HJ *)li__5XB);
    li__4XB=li__JZB;
    *(li__JZB) = *(li__HJ__);
  };
  li__JZB=((__li__HJ *)li__4XB);
  if (((*(li__JZB)).li__T2F < li__JO)) {
    li__12F=li__5OI(li__JO);
    (*(li__JZB)).li__DZF=li__12F;
    (*(li__JZB)).li__T2F=li__JO;
  };
  (*(li__JZB)).li__52F=(__li__K)(-  1);
  li__JZB=li__4XB;
  li__JO= 0;
  li__SYB=(__li__K)(((__li__K )(arg_count)) -  1);
  while ((li__JO <= li__SYB)) {
    li__TO=((__li__BB *)(arg_vector[(li__JO)]));
    li__QTC= 0;
    while ((! ((li__QTC >  1024) || ('\0' == li__TO[li__QTC])))) {
      li__QTC=(__li__K)(li__QTC +  1);
    };
    li__WO=li__YN(li__QTC);
    li__DHL=((__li__4B *)li__WO);
    li__QTC= 0;
    li__DHL->li__0D= 0;
    while ((li__TO[li__QTC] != '\0')) {
      li__CDL(li__DHL,li__TO[li__QTC]);
      li__QTC=(__li__K)(li__QTC +  1);
    };
    li__MGG=((__li__HJ *)li__JZB);
    if (((__li__K)((*(li__MGG)).li__52F +  1) < (*(li__MGG)).li__T2F)) {
      (*(li__MGG)).li__52F=(__li__K)((*(li__MGG)).li__52F +  1);
      li__1GG=li__B__;
    } else /* FALSE */ {
      li__1GG=li__I__;
    };
    if ((! li__1GG)) {
      if (((*(li__MGG)).li__T2F ==  0)) {
        li__HHG=li__5OI( 2);
        (*(li__MGG)).li__DZF=li__HHG;
        (*(li__MGG)).li__T2F= 2;
        (*(li__MGG)).li__52F= 0;
      } else /* FALSE */ {
        li__OHG=(__li__K)((*(li__MGG)).li__T2F <<  1);
        li__HHG=((void **)(*(li__MGG)).li__DZF);
        li__ZTL=(*(li__MGG)).li__T2F;
        li__3UL=li__EEN(((__li__IB )li__HHG),((__li__0VB )(__li__K)(li__ZTL * ((__li__K )(sizeof(void *))))),((__li__0VB )(__li__K)(li__OHG * ((__li__K )(sizeof(void *))))));
        li__HHG=((void **)li__3UL);
        li__DVL=(__li__K)(li__OHG -  1);
        li__FLX=li__ZTL;
        while ((li__FLX <= li__DVL)) {
          li__HHG[li__FLX]=NULL;
          li__FLX=(__li__K)(li__FLX +  1);
        };
        (*(li__MGG)).li__DZF=li__HHG;
        (*(li__MGG)).li__T2F=li__OHG;
        (*(li__MGG)).li__52F=(__li__K)((*(li__MGG)).li__52F +  1);
      };
    };
    ((void **)(*(li__MGG)).li__DZF)[(*(li__MGG)).li__52F]=li__WO;
    li__JO=(__li__K)(li__JO +  1);
  };
  li__WO=li__YN( 128);
  li__GC=((__li__IB )(NULL));
  li__DHL=li__YN( 256);
  li__ID=((__li__IB )(NULL));
  li__QN=li__YN( 256);
  li__0BG=NULL;
  li__5XB=((__li__IB )(NULL));
  li__B0C=((__li__0VB )sizeof(__li__JIB));
  if ((li__B0C ==  0)) {
    li__0BG=li__JIB__;
  } else /* FALSE */ {
    li__QTC=__li__JIB__;
    li__SWB=(__li__0VB)(li__SWB - (__li__0VB)(((__li__0VB ) 0) - li__B0C));
    li__VWB=(__li__0VB)(li__VWB - (__li__0VB)(((__li__0VB ) 0) - li__B0C));
    if ((li__QTC == (__li__K)(-  1))) {
      li__QHDB=(__li__0VB)(((__li__0VB )((__li__K )(sizeof(void *)))) - ((__li__0VB ) 1));
      li__UHDB=(__li__0VB)((__li__0VB)(li__B0C - (__li__0VB)(((__li__0VB ) 0) - li__QHDB)) & (__li__0VB)((__li__0VB)(((__li__0VB ) 0) - li__QHDB) - ((__li__0VB ) 1)));
      li__QHDB=(__li__0VB)(li__UHDB / ((__li__0VB )((__li__K )(sizeof(void *)))));
      li__WHDB=li__S0D(li__UHDB,((__li__IB )(&(table_size[(li__QHDB)-1]))),((__li__U )li__UHDB));
      li__VWB=(__li__0VB)(li__VWB - (__li__0VB)(((__li__0VB ) 0) - li__B0C));
      li__5XB=li__WHDB;
    } else /* FALSE */ {
      li__5HDB=((__li__U )li__QTC);
      li__QHDB=(__li__0VB)(((__li__0VB )((__li__K )(sizeof(void *)))) - ((__li__0VB ) 1));
      li__UHDB=(__li__0VB)((__li__0VB)(li__B0C - (__li__0VB)(((__li__0VB ) 0) - li__QHDB)) & (__li__0VB)((__li__0VB)(((__li__0VB ) 0) - li__QHDB) - ((__li__0VB ) 1)));
      li__WHDB=li__S0D(li__UHDB,((__li__IB )(&(table_type[(li__5HDB)]))),(__li__U)(li__5HDB |  1));
      li__VWB=(__li__0VB)(li__VWB - (__li__0VB)(((__li__0VB ) 0) - li__B0C));
      li__5XB=li__WHDB;
    };
    li__FDG=((__li__JIB *)li__5XB);
    li__0BG=li__FDG;
    *(li__FDG) = *(li__JIB__);
  };
  li__FDG=((__li__JIB *)li__0BG);
  li__JO=li__FHO( 53);
  li__5RM=li__QSO(li__JO);
  li__FDG->li__53K=li__5RM;
  li__FDG->li__X3K=li__JO;
  li__FDG->li__IBL= 0;
  li__05K(((__li__JIB *)li__0BG),(&__string_1));
  li__05K(((__li__JIB *)li__0BG),(&__string_2));
  li__QIB=li__0BG;
  *((__li__FE *)li__FE__)=(*li__GE__);
  li__XVB=NULL;
  li__5XB=((__li__IB )(NULL));
  li__B0C=((__li__0VB )sizeof(__li__FE));
  if ((li__B0C ==  0)) {
    li__XVB=li__FE__;
  } else /* FALSE */ {
    li__QTC=__li__FE__;
    li__SWB=(__li__0VB)(li__SWB - (__li__0VB)(((__li__0VB ) 0) - li__B0C));
    li__VWB=(__li__0VB)(li__VWB - (__li__0VB)(((__li__0VB ) 0) - li__B0C));
    if ((li__QTC == (__li__K)(-  1))) {
      li__QHDB=(__li__0VB)(((__li__0VB )((__li__K )(sizeof(void *)))) - ((__li__0VB ) 1));
      li__UHDB=(__li__0VB)((__li__0VB)(li__B0C - (__li__0VB)(((__li__0VB ) 0) - li__QHDB)) & (__li__0VB)((__li__0VB)(((__li__0VB ) 0) - li__QHDB) - ((__li__0VB ) 1)));
      li__QHDB=(__li__0VB)(li__UHDB / ((__li__0VB )((__li__K )(sizeof(void *)))));
      li__WHDB=li__S0D(li__UHDB,((__li__IB )(&(table_size[(li__QHDB)-1]))),((__li__U )li__UHDB));
      li__VWB=(__li__0VB)(li__VWB - (__li__0VB)(((__li__0VB ) 0) - li__B0C));
      li__5XB=li__WHDB;
    } else /* FALSE */ {
      li__5HDB=((__li__U )li__QTC);
      li__QHDB=(__li__0VB)(((__li__0VB )((__li__K )(sizeof(void *)))) - ((__li__0VB ) 1));
      li__UHDB=(__li__0VB)((__li__0VB)(li__B0C - (__li__0VB)(((__li__0VB ) 0) - li__QHDB)) & (__li__0VB)((__li__0VB)(((__li__0VB ) 0) - li__QHDB) - ((__li__0VB ) 1)));
      li__WHDB=li__S0D(li__UHDB,((__li__IB )(&(table_type[(li__5HDB)]))),(__li__U)(li__5HDB |  1));
      li__VWB=(__li__0VB)(li__VWB - (__li__0VB)(((__li__0VB ) 0) - li__B0C));
      li__5XB=li__WHDB;
    };
    li__QXB=((__li__FE *)li__5XB);
    li__XVB=li__QXB;
    *(li__QXB) = *(li__FE__);
  };
  li__QXB=((__li__FE *)li__XVB);
  if (((*(li__QXB)).li__K1F <  16384)) {
    li__V1F=li__PNI( 16384);
    (*(li__QXB)).li__W1F=li__V1F;
    (*(li__QXB)).li__K1F= 16384;
  };
  (*(li__QXB)).li__1E=(__li__K)(-  1);
  li__OE=li__XVB;
  li__JO= 0;
  li__HR((&__string_3));
  li__IWK(((__li__4B *)li__WO),((void **)(*(((__li__HJ *)li__4XB))).li__DZF)[ 1]);
  li__TO=li__QXK(((__li__4B *)li__WO));
  li__5XB=((__li__IB )(fopen((char*)(li__TO),"rb")));
  li__GC=li__5XB;
  if ((li__5XB == (void *)NULL)) {
    li__QS((&__string_4));
    exit(( 1));
  };
  li__ZPK(((__li__4B *)li__DHL),((void **)(*(((__li__HJ *)li__4XB))).li__DZF)[ 1]);
  li__ERK=((__li__4B *)li__DHL);
  if (( 2 > li__ERK->li__0D)) {
    li__ERK->li__0D= 0;
  } else /* FALSE */ {
    li__ERK->li__0D=(__li__K)(li__ERK->li__0D -  2);
  };
  li__ISK(((__li__4B *)li__DHL),(&__string_5));
  li__IWK(((__li__4B *)li__WO),li__DHL);
  li__TO=li__QXK(((__li__4B *)li__WO));
  li__5XB=((__li__IB )(fopen((char*)(li__TO),"w+b")));
  li__1GG=(li__5XB != (void *)NULL);
  if (li__1GG) {
    fclose((FILE*)((li__5XB)));
  };
  if ((! li__1GG)) {
    li__QS((&__string_6));
    exit(( 1));
  };
  li__IWK(((__li__4B *)li__WO),li__DHL);
  li__TO=li__QXK(((__li__4B *)li__WO));
  li__ID=((__li__IB )(fopen((char*)(li__TO),"wb")));
  li__XL:
  {
    li__WHDB=li__GC;
    li__OHG=li__QN->li__OP;
    li__QP=li__QXK(((__li__4B *)li__QN));
    li__3UL=((__li__IB )(fgets((void *)((li__QP)),(li__OHG),(FILE*)((li__WHDB)))));
    li__UZK=((__li__4B *)li__QN);
    li__UZK->li__0D= 0;
    while ((((__li__BB *)li__QP)[li__UZK->li__0D] != '\0')) {
      li__UZK->li__0D=(__li__K)(li__UZK->li__0D +  1);
    };
    if (((void *)li__UZK->li__OQK != (void *)li__QP)) {
      li__UZK->li__OQK=li__QP;
      li__UZK->li__OP=(__li__K)(li__UZK->li__0D +  1);
    };
    if ((li__3UL != (void *)NULL)) {
      li__D4=NULL;
      li__E4=NULL;
      li__F4=NULL;
      li__J4=(__li__K)(li__J4 +  1);
      li__ZTL=li__S1K(((__li__4B *)li__QN),(&__string_7));
      if (((li__ZTL !=  0) & li__T4)) {
        li__UTK(((__li__4B *)li__DHL),(&__string_8));
        li__5N(li__44,li__DHL);
        li__ISK(((__li__4B *)li__DHL),(&__string_9));
        li__2UK(((__li__4B *)li__QN),li__DHL);
        li__44=(__li__K)(li__44 +  1);
        li__T4=li__I__;
      };
      li__ZTL=li__S1K(((__li__4B *)li__QN),(&__string_10));
      li__DVL=li__ZTL;
      if ((li__ZTL !=  0)) {
        if ((((__li__BB *)((__li__4B *)li__QN)->li__OQK)[(__li__K)((__li__K)(li__ZTL +  4) -  1)] != 'm')) {
          li__DVL=(__li__K)(li__ZTL +  4);
          ((__li__4B *)li__DHL)->li__0D= 0;
          while ((((__li__BB *)((__li__4B *)li__QN)->li__OQK)[(__li__K)(li__DVL -  1)] != ',')) {
            li__CDL(((__li__4B *)li__DHL),((__li__BB *)((__li__4B *)li__QN)->li__OQK)[(__li__K)(li__DVL -  1)]);
            li__DVL=(__li__K)(li__DVL +  1);
          };
          li__NAB=li__ZHB(li__DHL);
          li__F4=li__NAB;
          li__DVL=(__li__K)(li__DVL +  1);
          ((__li__4B *)li__DHL)->li__0D= 0;
          while ((((__li__BB *)((__li__4B *)li__QN)->li__OQK)[(__li__K)(li__DVL -  1)] != ',')) {
            li__CDL(((__li__4B *)li__DHL),((__li__BB *)((__li__4B *)li__QN)->li__OQK)[(__li__K)(li__DVL -  1)]);
            li__DVL=(__li__K)(li__DVL +  1);
          };
          li__NAB=li__ZHB(li__DHL);
          li__D4=li__NAB;
          li__DVL=(__li__K)(li__DVL +  1);
          ((__li__4B *)li__DHL)->li__0D= 0;
          while ((((__li__BB *)((__li__4B *)li__QN)->li__OQK)[(__li__K)(li__DVL -  1)] != '\n')) {
            li__CDL(((__li__4B *)li__DHL),((__li__BB *)((__li__4B *)li__QN)->li__OQK)[(__li__K)(li__DVL -  1)]);
            li__DVL=(__li__K)(li__DVL +  1);
          };
          li__ZBB=li__ZHB(li__DHL);
          li__E4=li__ZBB;
          li__UTK(((__li__4B *)li__QN),li__NAB);
          li__ISK(((__li__4B *)li__QN),(&__string_11));
        } else /* FALSE */ {
          li__UTK(((__li__4B *)li__DHL),(&__string_8));
          li__5N(li__44,li__DHL);
          li__ZPK(((__li__4B *)li__QN),li__DHL);
          li__ISK(((__li__4B *)li__QN),(&__string_11));
          li__ISK(((__li__4B *)li__DHL),(&__string_1));
          li__NAB=li__ZHB(li__DHL);
          li__D4=li__NAB;
          li__UTK(((__li__4B *)li__DHL),(&__string_8));
          li__5N(li__44,li__DHL);
          li__ISK(((__li__4B *)li__DHL),(&__string_12));
          li__NAB=li__ZHB(li__DHL);
          li__F4=li__NAB;
          li__E4=(&__string_13);
          li__T4=li__B__;
        };
        li__W4F(((__li__FE *)li__OE),li__D4);
        li__W4F(((__li__FE *)li__OE),li__F4);
        li__W4F(((__li__FE *)li__OE),li__E4);
      };
      li__IGCB=li__ID;
      li__ZTL=li__QN->li__0D;
      li__GGCB=li__QXK(((__li__4B *)li__QN));
      fwrite((void *)((li__GGCB)),(size_t)(1), (size_t)((li__ZTL)),(FILE*)((li__IGCB)));
      goto li__XL;
    };
  };
  li__UTK(((__li__4B *)li__QN),(&__string_14));
  li__ISK(((__li__4B *)li__QN),(&__string_15));
  li__ISK(((__li__4B *)li__QN),(&__string_16));
  li__ISK(((__li__4B *)li__QN),(&__string_17));
  li__ISK(((__li__4B *)li__QN),(&__string_18));
  li__TRCB=(__li__K)((*(((__li__FE *)li__XVB))).li__1E +  1);
  li__SYB=(__li__K)(li__TRCB +  3);
  li__WO=li__YN( 0);
  li__5N(li__SYB,li__WO);
  li__2UK(((__li__4B *)li__QN),li__WO);
  li__ISK(((__li__4B *)li__QN),(&__string_19));
  li__SYB= 0;
  li__QTC=(*(li__XVB)).li__1E;
  while ((li__SYB <= li__QTC)) {
    li__OHG=li__SYB;
    if ((((__li__BB *)((__li__Y *)((void **)(*(((__li__FE *)li__OE))).li__W1F)[(__li__K)(li__SYB +  2)])->li__0B)[ 0] == '-')) {
      li__D4=((__li__Y *)((void **)(*(((__li__FE *)li__OE))).li__W1F)[(__li__K)(li__SYB +  2)]);
      li__UF=(((__li__BB *)li__D4->li__0B)[(__li__K)(li__D4->li__ZB -  1)] == '3');
    } else /* FALSE */ {
      li__UF=li__I__;
    };
    if (li__UF) {
      li__CDL(((__li__4B *)li__QN),'\n');
    };
    li__ISK(((__li__4B *)li__QN),(&__string_16));
    li__WFL(((__li__4B *)li__QN),((void **)(*(((__li__FE *)li__OE))).li__W1F)[li__SYB]);
    li__ISK(((__li__4B *)li__QN),(&__string_18));
    li__WFL(((__li__4B *)li__QN),((void **)(*(((__li__FE *)li__OE))).li__W1F)[(__li__K)(li__SYB +  1)]);
    li__ISK(((__li__4B *)li__QN),(&__string_18));
    if ((((__li__BB *)((__li__Y *)((void **)(*(((__li__FE *)li__OE))).li__W1F)[(__li__K)(li__SYB +  2)])->li__0B)[ 0] != '-')) {
      li__JO= 0;
      li__4HD:
      {
        li__NAB=((void **)(*(((__li__FE *)li__OE))).li__W1F)[li__JO];
        li__ZBB=((void **)(*(((__li__FE *)li__OE))).li__W1F)[(__li__K)(li__OHG +  2)];
        li__SGW=((__li__Y *)li__NAB);
        if (li__ZBB==NULL) {
          li__1DX=NULL;
        } else /* STRING_CONSTANT */ {
          li__1DX=((__li__Y *)li__ZBB);
        };
        if (((void *)li__1DX != (void *)NULL)) {
          li__BEX=li__FJL(li__SGW,li__1DX);
          li__EEX=li__BEX;
        } else /* FALSE */ {
          li__EEX=li__I__;
        };
        if ((! li__EEX)) {
          li__JO=(__li__K)(li__JO +  3);
          goto li__4HD;
        };
      };
      li__5N((__li__K)(li__JO +  3),li__QN);
    } else /* FALSE */ {
      li__WFL(((__li__4B *)li__QN),((void **)(*(((__li__FE *)li__OE))).li__W1F)[(__li__K)(li__SYB +  2)]);
    };
    li__ISK(((__li__4B *)li__QN),(&__string_20));
    li__5N((__li__K)((__li__K)(li__SYB +  3) /  3),li__QN);
    if ((((__li__BB *)((__li__Y *)((void **)(*(((__li__FE *)li__OE))).li__W1F)[(__li__K)(li__SYB +  2)])->li__0B)[ 0] != '-')) {
      li__ISK(((__li__4B *)li__QN),(&__string_21));
      li__WFL(((__li__4B *)li__QN),((void **)(*(((__li__FE *)li__OE))).li__W1F)[(__li__K)(li__SYB +  2)]);
      li__ISK(((__li__4B *)li__QN),(&__string_22));
      li__5N((__li__K)((__li__K)(li__JO +  3) /  3),li__QN);
    };
    li__ISK(((__li__4B *)li__QN),(&__string_23));
    li__CDL(((__li__4B *)li__QN),'\n');
    li__SYB=(__li__K)(li__SYB +  3);
  };
  li__5XB=li__ID;
  li__JO=li__QN->li__0D;
  li__TO=li__QXK(((__li__4B *)li__QN));
  fwrite((void *)((li__TO)),(size_t)(1), (size_t)((li__JO)),(FILE*)((li__5XB)));
  fclose((FILE*)((li__GC)));
  fclose((FILE*)((li__ID)));
  return(0);
}


static __li__IB li__S0D(__li__0VB li__U0D,__li__IB li__V0D,__li__U li__W0D)
/* (Expanded UINTEGER_CPU{li__0VB},Expanded POINTER{li__IB},Expanded UINTEGER_32{li__U}) With result No recursive, No inlinable. NO CONTEXT! */
{
  __li__IB li__00D,li__FKCB,li__Y0D,li__51D,li__A2D,li__T4D,li__X0D;
  li__00D=((__li__IB )(NULL));
  li__FKCB=((__li__IB *)li__V0D)[ 0];
  li__Y0D=li__FKCB;
  if ((li__FKCB == (void *)NULL)) {
    li__51D=li__D1E(li__W0D);
    li__Y0D=li__51D;
    li__A2D=(void *)((unsigned long)li__51D - (unsigned long)(void *)((unsigned long)((__li__IB )((__li__0VB ) 0)) - (unsigned long)((__li__IB )li__U0D)));
    li__00D=li__A2D;
    ((__li__IB *)li__A2D)[ 0]=NULL;
    ((__li__IB *)li__V0D)[ 0]=li__A2D;
  } else /* FALSE */ {
    li__51D=((__li__IB *)li__Y0D)[ 0];
    li__00D=li__51D;
    if ((li__51D == (void *)NULL)) {
      if (((void *)((unsigned long)(void *)((unsigned long)(void *)((unsigned long)li__Y0D - (unsigned long)li__HUD) & (unsigned long)((__li__IB )((__li__0VB ) 4095))) - (unsigned long)(void *)((unsigned long)((__li__IB )((__li__0VB ) 0)) - (unsigned long)((__li__IB )(__li__0VB)(li__U0D <<  1)))) <= ((__li__IB )((__li__0VB ) 4096)))) {
        li__00D=(void *)((unsigned long)li__Y0D - (unsigned long)(void *)((unsigned long)((__li__IB )((__li__0VB ) 0)) - (unsigned long)((__li__IB )li__U0D)));
      } else /* FALSE */ {
        li__T4D=li__D1E(li__W0D);
        li__00D=li__T4D;
      };
      ((__li__IB *)li__00D)[ 0]=NULL;
      ((__li__IB *)li__V0D)[ 0]=li__00D;
    } else /* FALSE */ {
      ((__li__IB *)li__Y0D)[ 0]=(void *)((unsigned long)((__li__IB *)li__00D)[ 0] & (unsigned long)((__li__IB )(__li__0VB)((__li__0VB)(((__li__0VB ) 0) - ((__li__0VB ) 3)) - ((__li__0VB ) 1))));
      li__Y0D=li__00D;
    };
  };
  li__X0D=li__Y0D;
  return(li__X0D);
}

static void** li__5OI(__li__K li__BPI)
/* (Expanded INTEGER{li__K}) With result No recursive, No inlinable. NO CONTEXT! */
{
  __li__IB li__HDJ;
  __li__K li__BBN;
  void **li__LDJ,**li__CPI;
  li__HDJ=li__GLJ(((__li__0VB )(__li__K)(li__BPI * ((__li__K )(sizeof(void *))))));
  li__LDJ=((void **)li__HDJ);
  li__BBN=(__li__K)(li__BPI -  1);
  while ((li__BBN >=  0)) {
    li__LDJ[li__BBN]=NULL;
    li__BBN=(__li__K)(li__BBN -  1);
  };
  li__CPI=li__LDJ;
  return(li__CPI);
}

static __li__4B* li__YN(__li__K li__0N)
/* (Expanded INTEGER{li__K}) With result No recursive, No inlinable. NO CONTEXT! */
{
  __li__4B *li__KZF,*li__V0F,*li__1N;
  __li__IB li__LZF,li__4EDB;
  __li__0VB li__TZF,li__YEDB,li__2EDB;
  __li__K li__4ZF;
  __li__U li__HFDB;
  __li__BB *li__OZK;
  li__KZF=NULL;
  li__LZF=((__li__IB )(NULL));
  li__TZF=((__li__0VB )sizeof(__li__4B));
  if ((li__TZF ==  0)) {
    li__KZF=li__4B__;
  } else /* FALSE */ {
    li__4ZF=-1;
    li__SWB=(__li__0VB)(li__SWB - (__li__0VB)(((__li__0VB ) 0) - li__TZF));
    li__VWB=(__li__0VB)(li__VWB - (__li__0VB)(((__li__0VB ) 0) - li__TZF));
    if ((li__4ZF == (__li__K)(-  1))) {
      li__YEDB=(__li__0VB)(((__li__0VB )((__li__K )(sizeof(void *)))) - ((__li__0VB ) 1));
      li__2EDB=(__li__0VB)((__li__0VB)(li__TZF - (__li__0VB)(((__li__0VB ) 0) - li__YEDB)) & (__li__0VB)((__li__0VB)(((__li__0VB ) 0) - li__YEDB) - ((__li__0VB ) 1)));
      li__YEDB=(__li__0VB)(li__2EDB / ((__li__0VB )((__li__K )(sizeof(void *)))));
      li__4EDB=li__S0D(li__2EDB,((__li__IB )(&(table_size[(li__YEDB)-1]))),((__li__U )li__2EDB));
      li__VWB=(__li__0VB)(li__VWB - (__li__0VB)(((__li__0VB ) 0) - li__TZF));
      li__LZF=li__4EDB;
    } else /* FALSE */ {
      li__HFDB=((__li__U )li__4ZF);
      li__YEDB=(__li__0VB)(((__li__0VB )((__li__K )(sizeof(void *)))) - ((__li__0VB ) 1));
      li__2EDB=(__li__0VB)((__li__0VB)(li__TZF - (__li__0VB)(((__li__0VB ) 0) - li__YEDB)) & (__li__0VB)((__li__0VB)(((__li__0VB ) 0) - li__YEDB) - ((__li__0VB ) 1)));
      li__4EDB=li__S0D(li__2EDB,((__li__IB )(&(table_type[(li__HFDB)]))),(__li__U)(li__HFDB |  1));
      li__VWB=(__li__0VB)(li__VWB - (__li__0VB)(((__li__0VB ) 0) - li__TZF));
      li__LZF=li__4EDB;
    };
    li__V0F=((__li__4B *)li__LZF);
    li__KZF=li__V0F;
    *(li__V0F) = *(li__4B__);
  };
  li__V0F=((__li__4B *)li__KZF);
  if ((li__0N >  0)) {
    if ((li__V0F->li__OP < li__0N)) {
      li__OZK=li__MDR(li__0N);
      li__V0F->li__OQK=li__OZK;
      li__V0F->li__OP=li__0N;
    };
  };
  li__V0F->li__0D= 0;
  li__1N=li__KZF;
  return(li__1N);
}

static void li__CDL(__li__4B *li__DDL,__li__BB li__EDL)
/* (Strict STRING{li__4B},Expanded CHARACTER{li__BB}) Void No recursive, No inlinable. NO CONTEXT! */
{
  __li__K li__2DL;
  __li__BB *li__VDL;
  if ((li__DDL->li__OP <= li__DDL->li__0D)) {
    if ((li__DDL->li__OP ==  0)) {
      li__DDL->li__OP= 32;
      li__VDL=li__MDR( 32);
      li__DDL->li__OQK=li__VDL;
    } else /* FALSE */ {
      li__2DL=(__li__K)(li__DDL->li__OP <<  1);
      li__VDL=li__E2W(((__li__BB *)li__DDL->li__OQK),li__DDL->li__OP,li__2DL);
      li__DDL->li__OQK=li__VDL;
      li__DDL->li__OP=li__2DL;
    };
  };
  ((__li__BB *)li__DDL->li__OQK)[li__DDL->li__0D]=li__EDL;
  li__DDL->li__0D=(__li__K)(li__DDL->li__0D +  1);
}

static __li__IB li__EEN(__li__IB li__GEN,__li__0VB li__HEN,__li__0VB li__IEN)
/* (Expanded POINTER{li__IB},Expanded UINTEGER_CPU{li__0VB},Expanded UINTEGER_CPU{li__0VB}) With result No recursive, No inlinable. NO CONTEXT! */
{
  __li__IB li__UEN,li__QFN,li__WGCB,li__JEN;
  __li__0VB li__DVCB,li__AFN,li__GFN,li__VKG,li__MGT,li__NIT,li__2ZV;
  __li__5WB *li__2FN,*li__NHT,*li__1IT,*li__0ZV,*li__G5V;
  li__UEN=((__li__IB )(NULL));
  li__DVCB=(__li__0VB)(((__li__0VB )((__li__K )(sizeof(void *)))) - ((__li__0VB ) 1));
  li__AFN=(__li__0VB)((__li__0VB)(li__HEN - (__li__0VB)(((__li__0VB ) 0) - li__DVCB)) & (__li__0VB)((__li__0VB)(((__li__0VB ) 0) - li__DVCB) - ((__li__0VB ) 1)));
  li__DVCB=(__li__0VB)(((__li__0VB )((__li__K )(sizeof(void *)))) - ((__li__0VB ) 1));
  li__GFN=(__li__0VB)((__li__0VB)(li__IEN - (__li__0VB)(((__li__0VB ) 0) - li__DVCB)) & (__li__0VB)((__li__0VB)(((__li__0VB ) 0) - li__DVCB) - ((__li__0VB ) 1)));
  if ((li__AFN <= ((__li__0VB )(MINIMUM_SIZE)))) {
    li__QFN=li__GLJ(li__GFN);
    li__UEN=li__QFN;
    li__WET(li__GEN,li__QFN,li__AFN);
    li__VKG=(__li__0VB)(((__li__0VB )((__li__K )(sizeof(void *)))) - ((__li__0VB ) 1));
    li__MGT=(__li__0VB)((__li__0VB)(li__AFN - (__li__0VB)(((__li__0VB ) 0) - li__VKG)) & (__li__0VB)((__li__0VB)(((__li__0VB ) 0) - li__VKG) - ((__li__0VB ) 1)));
    li__VKG=(__li__0VB)(li__MGT / ((__li__0VB )((__li__K )(sizeof(void *)))));
    li__QFN=((__li__IB )(&(table_size[(li__VKG)-1])));
    li__WGCB=((__li__IB *)li__QFN)[ 0];
    ((__li__IB *)li__GEN)[ 0]=(void *)((unsigned long)(void *)((unsigned long)((__li__IB )((__li__0VB ) 0)) - (unsigned long)(void *)((unsigned long)(void *)((unsigned long)(void *)((unsigned long)((__li__IB )((__li__0VB ) 0)) - (unsigned long)((__li__IB *)li__WGCB)[ 0]) - (unsigned long)((__li__IB )((__li__0VB ) 1))) & (unsigned long)(void *)((unsigned long)(void *)((unsigned long)((__li__IB )((__li__0VB ) 0)) - (unsigned long)((__li__IB )((__li__0VB ) 3))) - (unsigned long)((__li__IB )((__li__0VB ) 1))))) - (unsigned long)((__li__IB )((__li__0VB ) 1)));
    ((__li__IB *)li__WGCB)[ 0]=li__GEN;
    ;
  } else /* FALSE */ {
    li__2FN=((__li__5WB *)(void *)((unsigned long)li__GEN - (unsigned long)((__li__IB )((__li__0VB )(__li__K)(((__li__K )(sizeof(void *))) + ((__li__K )(sizeof(unsigned long))))))));
    li__VKG=(__li__0VB)(((__li__0VB )(void *)((unsigned long)li__GEN - (unsigned long)li__HUD)) >>  26);
    li__NHT=NULL;
    li__MGT=((__li__0VB ) 0);
    li__NIT=(__li__0VB)(li__2FN->li__CXB & (__li__0VB)((__li__0VB)(((__li__0VB ) 0) - ((__li__0VB ) 3)) - ((__li__0VB ) 1)));
    if ((li__GFN > li__NIT)) {
      if ((! ((__li__0VB)(li__2FN->li__CXB & ((__li__0VB ) 2)) !=  0))) {
        li__1IT=((__li__5WB *)(void *)((unsigned long)(void *)((unsigned long)((__li__IB )li__2FN) - (unsigned long)(void *)((unsigned long)((__li__IB )((__li__0VB ) 0)) - (unsigned long)((__li__IB )((__li__0VB )(__li__K)(((__li__K )(sizeof(void *))) + ((__li__K )(sizeof(unsigned long)))))))) - (unsigned long)(void *)((unsigned long)((__li__IB )((__li__0VB ) 0)) - (unsigned long)((__li__IB )(__li__0VB)(li__2FN->li__CXB & (__li__0VB)((__li__0VB)(((__li__0VB ) 0) - ((__li__0VB ) 3)) - ((__li__0VB ) 1)))))));
        li__MGT=(__li__0VB)((__li__0VB)(li__GFN - li__NIT) - ((__li__0VB )(__li__K)(((__li__K )(sizeof(void *))) + ((__li__K )(sizeof(unsigned long))))));
        if ((((__li__0VB)(li__1IT->li__CXB & ((__li__0VB ) 1)) == ((__li__0VB ) 0)) && ((__li__0VB)(li__1IT->li__CXB & (__li__0VB)((__li__0VB)(((__li__0VB ) 0) - ((__li__0VB ) 3)) - ((__li__0VB ) 1))) >= li__MGT))) {
          li__DUW(li__1IT,((__li__IB )li__MGT),li__VKG);
          li__2FN->li__CXB=(__li__0VB)((__li__0VB)(li__2FN->li__CXB - (__li__0VB)(((__li__0VB ) 0) - (__li__0VB)(li__1IT->li__CXB & (__li__0VB)((__li__0VB)(((__li__0VB ) 0) - ((__li__0VB ) 1)) - ((__li__0VB ) 1))))) - (__li__0VB)(((__li__0VB ) 0) - ((__li__0VB )(__li__K)(((__li__K )(sizeof(void *))) + ((__li__K )(sizeof(unsigned long)))))));
          if (((__li__0VB)(li__2FN->li__CXB & ((__li__0VB ) 2)) !=  0)) {
            last_block[(li__VKG)] = (li__2FN);
          } else /* FALSE */ {
            ((__li__5WB *)(void *)((unsigned long)(void *)((unsigned long)((__li__IB )li__2FN) - (unsigned long)(void *)((unsigned long)((__li__IB )((__li__0VB ) 0)) - (unsigned long)((__li__IB )((__li__0VB )(__li__K)(((__li__K )(sizeof(void *))) + ((__li__K )(sizeof(unsigned long)))))))) - (unsigned long)(void *)((unsigned long)((__li__IB )((__li__0VB ) 0)) - (unsigned long)((__li__IB )(__li__0VB)(li__2FN->li__CXB & (__li__0VB)((__li__0VB)(((__li__0VB ) 0) - ((__li__0VB ) 3)) - ((__li__0VB ) 1)))))))->li__BXB=li__2FN;
          };
          li__NHT=li__2FN;
        };
      };
      if (((void *)li__NHT == (void *)NULL)) {
        li__1IT=li__NZP(li__GFN);
        li__NHT=li__1IT;
        li__WET((void *)((unsigned long)((__li__IB )li__2FN) - (unsigned long)(void *)((unsigned long)((__li__IB )((__li__0VB ) 0)) - (unsigned long)((__li__IB )((__li__0VB )(__li__K)(((__li__K )(sizeof(void *))) + ((__li__K )(sizeof(unsigned long)))))))),(void *)((unsigned long)((__li__IB )((__li__5WB *)li__1IT)) - (unsigned long)(void *)((unsigned long)((__li__IB )((__li__0VB ) 0)) - (unsigned long)((__li__IB )((__li__0VB )(__li__K)(((__li__K )(sizeof(void *))) + ((__li__K )(sizeof(unsigned long)))))))),li__NIT);
        li__1IT=((__li__5WB *)(void *)((unsigned long)(void *)((unsigned long)((__li__IB )li__2FN) - (unsigned long)(void *)((unsigned long)((__li__IB )((__li__0VB ) 0)) - (unsigned long)((__li__IB )((__li__0VB )(__li__K)(((__li__K )(sizeof(void *))) + ((__li__K )(sizeof(unsigned long)))))))) - (unsigned long)(void *)((unsigned long)((__li__IB )((__li__0VB ) 0)) - (unsigned long)((__li__IB )(__li__0VB)(li__2FN->li__CXB & (__li__0VB)((__li__0VB)(((__li__0VB ) 0) - ((__li__0VB ) 3)) - ((__li__0VB ) 1)))))));
        li__0ZV=li__2FN->li__BXB;
        li__2ZV=(__li__0VB)(li__2FN->li__CXB & (__li__0VB)((__li__0VB)(((__li__0VB ) 0) - ((__li__0VB ) 1)) - ((__li__0VB ) 1)));
        if ((((void *)li__0ZV == (void *)NULL) || ((__li__0VB)(((__li__5WB *)li__0ZV)->li__CXB & ((__li__0VB ) 1)) != ((__li__0VB ) 0)))) {
          li__0ZV=li__2FN;
          li__LDW(li__2FN);
        } else /* FALSE */ {
          li__2ZV=(__li__0VB)((__li__0VB)(li__2ZV - (__li__0VB)(((__li__0VB ) 0) - li__0ZV->li__CXB)) - (__li__0VB)(((__li__0VB ) 0) - ((__li__0VB )(__li__K)(((__li__K )(sizeof(void *))) + ((__li__K )(sizeof(unsigned long)))))));
        };
        if (((! ((__li__0VB)(li__2FN->li__CXB & ((__li__0VB ) 2)) !=  0)) && ((__li__0VB)(li__1IT->li__CXB & ((__li__0VB ) 1)) == ((__li__0VB ) 0)))) {
          li__2ZV=(__li__0VB)((__li__0VB)(li__2ZV - (__li__0VB)(((__li__0VB ) 0) - li__1IT->li__CXB)) - (__li__0VB)(((__li__0VB ) 0) - ((__li__0VB )(__li__K)(((__li__K )(sizeof(void *))) + ((__li__K )(sizeof(unsigned long)))))));
          li__QPX(li__1IT);
        };
        ((__li__5WB *)li__0ZV)->li__CXB=li__2ZV;
        if (((__li__0VB)(((__li__5WB *)li__0ZV)->li__CXB & ((__li__0VB ) 2)) !=  0)) {
          last_block[(li__VKG)] = (li__0ZV);
        } else /* FALSE */ {
          li__G5V=((__li__5WB *)li__0ZV);
          ((__li__5WB *)(void *)((unsigned long)(void *)((unsigned long)((__li__IB )li__G5V) - (unsigned long)(void *)((unsigned long)((__li__IB )((__li__0VB ) 0)) - (unsigned long)((__li__IB )((__li__0VB )(__li__K)(((__li__K )(sizeof(void *))) + ((__li__K )(sizeof(unsigned long)))))))) - (unsigned long)(void *)((unsigned long)((__li__IB )((__li__0VB ) 0)) - (unsigned long)((__li__IB )(__li__0VB)(li__G5V->li__CXB & (__li__0VB)((__li__0VB)(((__li__0VB ) 0) - ((__li__0VB ) 3)) - ((__li__0VB ) 1)))))))->li__BXB=li__0ZV;
        };
      };
    } else /* FALSE */ {
      li__NHT=li__2FN;
    };
    li__UEN=(void *)((unsigned long)((__li__IB )((__li__5WB *)li__NHT)) - (unsigned long)(void *)((unsigned long)((__li__IB )((__li__0VB ) 0)) - (unsigned long)((__li__IB )((__li__0VB )(__li__K)(((__li__K )(sizeof(void *))) + ((__li__K )(sizeof(unsigned long))))))));
  };
  li__VWB=(__li__0VB)(li__VWB - (__li__0VB)(((__li__0VB ) 0) - (__li__0VB)(li__IEN - li__AFN)));
  li__JEN=li__UEN;
  return(li__JEN);
}

static __li__K li__FHO(__li__K li__HHO)
/* (Expanded INTEGER{li__K}) With result No recursive, No inlinable. NO CONTEXT! */
{
  __li__K li__JHO,li__IHO;
  __li__C li__RHO,li__WHO;
  li__JHO= 0;
  if ((li__HHO <=  11)) {
    li__JHO= 11;
    li__RHO=li__B__;
  } else /* FALSE */ {
    li__RHO=li__I__;
  };
  if (li__RHO) {
    li__RHO=li__B__;
  } else /* FALSE */ {
    li__WHO=(li__HHO <=  23);
    if (li__WHO) {
      li__JHO= 23;
    };
    li__RHO=li__WHO;
  };
  if (li__RHO) {
    li__RHO=li__B__;
  } else /* FALSE */ {
    li__WHO=(li__HHO <=  53);
    if (li__WHO) {
      li__JHO= 53;
    };
    li__RHO=li__WHO;
  };
  if (li__RHO) {
    li__RHO=li__B__;
  } else /* FALSE */ {
    li__WHO=(li__HHO <=  97);
    if (li__WHO) {
      li__JHO= 97;
    };
    li__RHO=li__WHO;
  };
  if (li__RHO) {
    li__RHO=li__B__;
  } else /* FALSE */ {
    li__WHO=(li__HHO <=  193);
    if (li__WHO) {
      li__JHO= 193;
    };
    li__RHO=li__WHO;
  };
  if (li__RHO) {
    li__RHO=li__B__;
  } else /* FALSE */ {
    li__WHO=(li__HHO <=  389);
    if (li__WHO) {
      li__JHO= 389;
    };
    li__RHO=li__WHO;
  };
  if (li__RHO) {
    li__RHO=li__B__;
  } else /* FALSE */ {
    li__WHO=(li__HHO <=  769);
    if (li__WHO) {
      li__JHO= 769;
    };
    li__RHO=li__WHO;
  };
  if (li__RHO) {
    li__RHO=li__B__;
  } else /* FALSE */ {
    li__WHO=(li__HHO <=  1543);
    if (li__WHO) {
      li__JHO= 1543;
    };
    li__RHO=li__WHO;
  };
  if (li__RHO) {
    li__RHO=li__B__;
  } else /* FALSE */ {
    li__WHO=(li__HHO <=  3079);
    if (li__WHO) {
      li__JHO= 3079;
    };
    li__RHO=li__WHO;
  };
  if (li__RHO) {
    li__RHO=li__B__;
  } else /* FALSE */ {
    li__WHO=(li__HHO <=  6151);
    if (li__WHO) {
      li__JHO= 6151;
    };
    li__RHO=li__WHO;
  };
  if (li__RHO) {
    li__RHO=li__B__;
  } else /* FALSE */ {
    li__WHO=(li__HHO <=  12289);
    if (li__WHO) {
      li__JHO= 12289;
    };
    li__RHO=li__WHO;
  };
  if (li__RHO) {
    li__RHO=li__B__;
  } else /* FALSE */ {
    li__WHO=(li__HHO <=  24593);
    if (li__WHO) {
      li__JHO= 24593;
    };
    li__RHO=li__WHO;
  };
  if (li__RHO) {
    li__RHO=li__B__;
  } else /* FALSE */ {
    li__WHO=(li__HHO <=  49157);
    if (li__WHO) {
      li__JHO= 49157;
    };
    li__RHO=li__WHO;
  };
  if (li__RHO) {
    li__RHO=li__B__;
  } else /* FALSE */ {
    li__WHO=(li__HHO <=  98317);
    if (li__WHO) {
      li__JHO= 98317;
    };
    li__RHO=li__WHO;
  };
  if (li__RHO) {
    li__RHO=li__B__;
  } else /* FALSE */ {
    li__WHO=(li__HHO <=  196613);
    if (li__WHO) {
      li__JHO= 196613;
    };
    li__RHO=li__WHO;
  };
  if (li__RHO) {
    li__RHO=li__B__;
  } else /* FALSE */ {
    li__WHO=(li__HHO <=  393241);
    if (li__WHO) {
      li__JHO= 393241;
    };
    li__RHO=li__WHO;
  };
  if (li__RHO) {
    li__RHO=li__B__;
  } else /* FALSE */ {
    li__WHO=(li__HHO <=  786433);
    if (li__WHO) {
      li__JHO= 786433;
    };
    li__RHO=li__WHO;
  };
  if (li__RHO) {
    li__RHO=li__B__;
  } else /* FALSE */ {
    li__WHO=(li__HHO <=  1572869);
    if (li__WHO) {
      li__JHO= 1572869;
    };
    li__RHO=li__WHO;
  };
  if (li__RHO) {
    li__RHO=li__B__;
  } else /* FALSE */ {
    li__WHO=(li__HHO <=  3145739);
    if (li__WHO) {
      li__JHO= 3145739;
    };
    li__RHO=li__WHO;
  };
  if (li__RHO) {
    li__RHO=li__B__;
  } else /* FALSE */ {
    li__WHO=(li__HHO <=  6291469);
    if (li__WHO) {
      li__JHO= 6291469;
    };
    li__RHO=li__WHO;
  };
  if (li__RHO) {
    li__RHO=li__B__;
  } else /* FALSE */ {
    li__WHO=(li__HHO <=  12582917);
    if (li__WHO) {
      li__JHO= 12582917;
    };
    li__RHO=li__WHO;
  };
  if (li__RHO) {
    li__RHO=li__B__;
  } else /* FALSE */ {
    li__WHO=(li__HHO <=  25165843);
    if (li__WHO) {
      li__JHO= 25165843;
    };
    li__RHO=li__WHO;
  };
  if (li__RHO) {
    li__RHO=li__B__;
  } else /* FALSE */ {
    li__WHO=(li__HHO <=  50331653);
    if (li__WHO) {
      li__JHO= 50331653;
    };
    li__RHO=li__WHO;
  };
  if (li__RHO) {
    li__RHO=li__B__;
  } else /* FALSE */ {
    li__WHO=(li__HHO <=  100663319);
    if (li__WHO) {
      li__JHO= 100663319;
    };
    li__RHO=li__WHO;
  };
  if (li__RHO) {
    li__RHO=li__B__;
  } else /* FALSE */ {
    li__WHO=(li__HHO <=  201326611);
    if (li__WHO) {
      li__JHO= 201326611;
    };
    li__RHO=li__WHO;
  };
  if (li__RHO) {
    li__RHO=li__B__;
  } else /* FALSE */ {
    li__WHO=(li__HHO <=  402653189);
    if (li__WHO) {
      li__JHO= 402653189;
    };
    li__RHO=li__WHO;
  };
  if ((! li__RHO)) {
    if ((li__HHO <=  805306457)) {
      li__JHO= 805306457;
    } else /* FALSE */ {
      li__JHO= 1610612741;
    };
  };
  li__IHO=li__JHO;
  return(li__IHO);
}

static void** li__QSO(__li__K li__SSO)
/* (Expanded INTEGER{li__K}) With result No recursive, No inlinable. NO CONTEXT! */
{
  __li__IB li__GAR;
  __li__K li__PNX;
  void **li__KAR,**li__TSO;
  li__GAR=li__GLJ(((__li__0VB )(__li__K)(li__SSO * ((__li__K )(sizeof(void *))))));
  li__KAR=((void **)li__GAR);
  li__PNX=(__li__K)(li__SSO -  1);
  while ((li__PNX >=  0)) {
    li__KAR[li__PNX]=NULL;
    li__PNX=(__li__K)(li__PNX -  1);
  };
  li__TSO=li__KAR;
  return(li__TSO);
}

static void li__05K(__li__JIB *li__15K,__li__Y *li__25K)
/* (Strict HASHED_SET(ABSTRACT_STRING){li__JIB},Strict STRING_CONSTANT{NULLxli__Y}) Void No recursive, No inlinable. NO CONTEXT! */
{
  __li__IB li__2B1,li__SFDB;
  __li__0VB li__EC1,li__MFDB,li__QFDB;
  __li__K li__IAL,li__KAL,li__EAL,li__FVT,li__2UT,li__DWT,li__FWT;
  __li__U li__1FDB;
  __li__Q3K *li__FAL,*li__AVT,*li__BVT,*li__GD1;
  void **li__5UT,**li__IVT;
  li__XPM(li__15K,li__25K);
  li__XPM(li__15K,li__25K);
  li__IAL=li__COM(((__li__Y *)li__25K));
  li__KAL=(__li__K)(li__IAL % li__15K->li__X3K);
  li__EAL=li__KAL;
  li__FAL=((void **)li__15K->li__53K)[li__KAL];
  while ((! (((void *)li__FAL == (void *)NULL) || ((void *)li__FAL->li__L4K == (void *)li__25K)))) {
    li__FAL=li__FAL->li__X4K;
  };
  if (((void *)li__FAL == (void *)NULL)) {
    if ((li__15K->li__X3K == li__15K->li__IBL)) {
      li__AVT=NULL;
      li__BVT=NULL;
      li__FVT=li__FHO((__li__K)(li__15K->li__X3K +  1));
      li__5UT=li__15K->li__53K;
      li__IVT=li__QSO(li__FVT);
      li__15K->li__53K=li__IVT;
      li__2UT=(__li__K)(li__15K->li__X3K -  1);
      li__15K->li__X3K=li__FVT;
      while ((! (li__2UT <  0))) {
        li__AVT=((void **)li__5UT)[li__2UT];
        while (((void *)li__AVT != (void *)NULL)) {
          li__BVT=li__AVT->li__X4K;
          li__DWT=li__COM(((__li__Y *)li__AVT->li__L4K));
          li__FWT=(__li__K)(li__DWT % li__15K->li__X3K);
          ((__li__Q3K *)li__AVT)->li__X4K=((void **)li__15K->li__53K)[li__FWT];
          ((void **)li__15K->li__53K)[li__FWT]=li__AVT;
          li__AVT=li__BVT;
        };
        li__2UT=(__li__K)(li__2UT -  1);
      };
      li__EAL=(__li__K)(li__IAL % li__15K->li__X3K);
    };
    li__AVT=((void **)li__15K->li__53K)[li__EAL];
    li__BVT=NULL;
    li__2B1=((__li__IB )(NULL));
    li__EC1=((__li__0VB )sizeof(__li__Q3K));
    if ((li__EC1 ==  0)) {
      li__BVT=li__Q3K__;
    } else /* FALSE */ {
      li__FVT=__li__Q3K__;
      li__SWB=(__li__0VB)(li__SWB - (__li__0VB)(((__li__0VB ) 0) - li__EC1));
      li__VWB=(__li__0VB)(li__VWB - (__li__0VB)(((__li__0VB ) 0) - li__EC1));
      if ((li__FVT == (__li__K)(-  1))) {
        li__MFDB=(__li__0VB)(((__li__0VB )((__li__K )(sizeof(void *)))) - ((__li__0VB ) 1));
        li__QFDB=(__li__0VB)((__li__0VB)(li__EC1 - (__li__0VB)(((__li__0VB ) 0) - li__MFDB)) & (__li__0VB)((__li__0VB)(((__li__0VB ) 0) - li__MFDB) - ((__li__0VB ) 1)));
        li__MFDB=(__li__0VB)(li__QFDB / ((__li__0VB )((__li__K )(sizeof(void *)))));
        li__SFDB=li__S0D(li__QFDB,((__li__IB )(&(table_size[(li__MFDB)-1]))),((__li__U )li__QFDB));
        li__VWB=(__li__0VB)(li__VWB - (__li__0VB)(((__li__0VB ) 0) - li__EC1));
        li__2B1=li__SFDB;
      } else /* FALSE */ {
        li__1FDB=((__li__U )li__FVT);
        li__MFDB=(__li__0VB)(((__li__0VB )((__li__K )(sizeof(void *)))) - ((__li__0VB ) 1));
        li__QFDB=(__li__0VB)((__li__0VB)(li__EC1 - (__li__0VB)(((__li__0VB ) 0) - li__MFDB)) & (__li__0VB)((__li__0VB)(((__li__0VB ) 0) - li__MFDB) - ((__li__0VB ) 1)));
        li__SFDB=li__S0D(li__QFDB,((__li__IB )(&(table_type[(li__1FDB)]))),(__li__U)(li__1FDB |  1));
        li__VWB=(__li__0VB)(li__VWB - (__li__0VB)(((__li__0VB ) 0) - li__EC1));
        li__2B1=li__SFDB;
      };
      li__GD1=((__li__Q3K *)li__2B1);
      li__BVT=li__GD1;
      *(li__GD1) = *(li__Q3K__);
    };
    li__GD1=((__li__Q3K *)li__BVT);
    li__GD1->li__L4K=li__25K;
    li__GD1->li__X4K=li__AVT;
    li__FAL=li__BVT;
    ((void **)li__15K->li__53K)[li__EAL]=li__BVT;
    li__15K->li__IBL=(__li__K)(li__15K->li__IBL +  1);
  };
  ;
}

static void** li__PNI(__li__K li__RNI)
/* (Expanded INTEGER{li__K}) With result No recursive, No inlinable. NO CONTEXT! */
{
  __li__IB li__RBJ;
  __li__K li__05M;
  void **li__VBJ,**li__SNI;
  li__RBJ=li__GLJ(((__li__0VB )(__li__K)(li__RNI * ((__li__K )(sizeof(void *))))));
  li__VBJ=((void **)li__RBJ);
  li__05M=(__li__K)(li__RNI -  1);
  while ((li__05M >=  0)) {
    li__VBJ[li__05M]=NULL;
    li__05M=(__li__K)(li__05M -  1);
  };
  li__SNI=li__VBJ;
  return(li__SNI);
}

static void li__HR(__li__Y *li__IR)
/* (Strict STRING_CONSTANT{li__Y}) Void No recursive, No inlinable. NO CONTEXT! */
{
  __li__K li__N1G,li__O1G;
  __li__BB *li__O1CB;
  li__N1G= 1;
  li__O1G=li__IR->li__ZB;
  li__O1CB=li__IR->li__0B;
  while ((li__N1G <= li__O1G)) {
    fputc((int)(((__li__BB *)li__O1CB)[(__li__K)(li__N1G -  1)]),stdout);
    li__N1G=(__li__K)(li__N1G +  1);
  };
}

static void li__IWK(__li__4B *li__JWK,__li__4B *li__KWK)
/* (Strict STRING{li__4B},Strict STRING{NULLxli__4B}) Void No recursive, No inlinable. NO CONTEXT! */
{
  __li__BB *li__2WK;
  li__JWK->li__0D=li__KWK->li__0D;
  if ((li__JWK->li__0D >  0)) {
    if ((li__JWK->li__OP < li__JWK->li__0D)) {
      li__2WK=li__MDR(li__JWK->li__0D);
      li__JWK->li__OQK=li__2WK;
      li__JWK->li__OP=li__JWK->li__0D;
    };
    li__3DR(((__li__BB *)li__JWK->li__OQK),li__KWK->li__OQK,(__li__K)(li__JWK->li__0D -  1));
  };
}

static __li__BB* li__QXK(__li__4B *li__RXK)
/* (Strict STRING{li__4B}) With result No recursive, No inlinable. NO CONTEXT! */
{
  __li__BB *li__SXK;
  if ((li__RXK->li__OP > li__RXK->li__0D)) {
    ((__li__BB *)li__RXK->li__OQK)[li__RXK->li__0D]='\0';
  } else /* FALSE */ {
    li__CDL(li__RXK,'\0');
    li__RXK->li__0D=(__li__K)(li__RXK->li__0D -  1);
  };
  li__SXK=li__RXK->li__OQK;
  return(li__SXK);
}

static void li__QS(void *li__SS)
/* (ABSTRACT_STRING{li__Y}) Void No recursive, No inlinable. NO CONTEXT! */
{
  __li__K li__C0,li__D0;
  __li__BB *li__X1CB;
  li__C0= 1;
  li__D0=((__li__Y *)li__SS)->li__ZB;
  li__X1CB=((__li__Y *)li__SS)->li__0B;
  while ((li__C0 <= li__D0)) {
    fputc((int)(((__li__BB *)li__X1CB)[(__li__K)(li__C0 -  1)]),stderr);
    li__C0=(__li__K)(li__C0 +  1);
  };
}

static void li__ZPK(__li__4B *li__0PK,__li__4B *li__1PK)
/* (Strict STRING{li__4B},Strict STRING{NULLxli__4B}) Void No recursive, No inlinable. NO CONTEXT! */
{
  __li__BB *li__NQK;
  li__0PK->li__0D=li__1PK->li__0D;
  if ((li__0PK->li__0D >  0)) {
    if ((li__0PK->li__OP < li__0PK->li__0D)) {
      li__NQK=li__MDR(li__0PK->li__0D);
      li__0PK->li__OQK=li__NQK;
      li__0PK->li__OP=li__0PK->li__0D;
    };
    li__3DR(((__li__BB *)li__0PK->li__OQK),li__1PK->li__OQK,(__li__K)(li__0PK->li__0D -  1));
  };
}

static void li__ISK(__li__4B *li__JSK,void *li__KSK)
/* (Strict STRING{li__4B},ABSTRACT_STRING{li__Y}) Void No recursive, No inlinable. NO CONTEXT! */
{
  __li__K li__LSK,li__VSK;
  __li__BB *li__ETK;
  li__LSK=((__li__Y *)li__KSK)->li__ZB;
  li__VSK=(__li__K)(li__JSK->li__0D + li__LSK);
  if ((li__JSK->li__OP < li__VSK)) {
    if ((li__JSK->li__OP ==  0)) {
      li__JSK->li__OP=li__VSK;
      li__ETK=li__MDR(li__VSK);
      li__JSK->li__OQK=li__ETK;
    } else /* FALSE */ {
      li__ETK=li__E2W(((__li__BB *)li__JSK->li__OQK),li__JSK->li__OP,li__VSK);
      li__JSK->li__OQK=li__ETK;
      li__JSK->li__OP=li__VSK;
    };
  };
  li__ULW(((__li__BB *)li__JSK->li__OQK),((__li__Y *)li__KSK)->li__0B,li__JSK->li__0D,li__LSK);
  li__JSK->li__0D=li__VSK;
}

static __li__K li__S1K(__li__4B *li__T1K,void *li__U1K)
/* (Strict STRING{li__4B},ABSTRACT_STRING{li__Y}) With result No recursive, No inlinable. NO CONTEXT! */
{
  __li__K li__1EM,li__3EM,li__2EM,li__F2CB,li__G2CB,li__H2CB,li__K2CB;
  __li__K li__V1K;
  __li__BB *li__I2CB,*li__J2CB;
  li__1EM= 0;
  li__3EM= 0;
  li__2EM= 1;
  li__F2CB=((__li__Y *)li__U1K)->li__ZB;
  li__G2CB=li__T1K->li__0D;
  li__H2CB=((__li__Y *)li__U1K)->li__ZB;
  li__I2CB=li__T1K->li__OQK;
  li__J2CB=((__li__Y *)li__U1K)->li__0B;
  li__K2CB=((__li__Y *)li__U1K)->li__ZB;
  while ((! ((li__3EM !=  0) || ((__li__K)((__li__K)(li__2EM + li__F2CB) -  1) > li__G2CB)))) {
    li__1EM= 1;
    while ((! ((li__1EM > li__H2CB) || (((__li__BB *)li__I2CB)[(__li__K)((__li__K)((__li__K)(li__2EM + li__1EM) -  1) -  1)] != ((__li__BB *)li__J2CB)[(__li__K)(li__1EM -  1)])))) {
      li__1EM=(__li__K)(li__1EM +  1);
    };
    if ((li__1EM > li__K2CB)) {
      li__3EM=li__2EM;
    } else /* FALSE */ {
      li__2EM=(__li__K)(li__2EM +  1);
    };
  };
  li__V1K=li__3EM;
  return(li__V1K);
}

static void li__UTK(__li__4B *li__VTK,__li__Y *li__WTK)
/* (Strict STRING{li__4B},Strict STRING_CONSTANT{NULLxli__Y}) Void No recursive, No inlinable. NO CONTEXT! */
{
  __li__BB *li__IUK;
  li__VTK->li__0D=li__WTK->li__ZB;
  if ((li__VTK->li__0D >  0)) {
    if ((li__VTK->li__OP < li__VTK->li__0D)) {
      li__IUK=li__MDR(li__VTK->li__0D);
      li__VTK->li__OQK=li__IUK;
      li__VTK->li__OP=li__VTK->li__0D;
    };
    li__3DR(((__li__BB *)li__VTK->li__OQK),li__WTK->li__0B,(__li__K)(li__VTK->li__0D -  1));
  };
}

static void li__5N(__li__K li__AO,__li__4B *li__BO)
/* (Expanded INTEGER{li__K},Strict STRING{NULLxli__4B}) Void No recursive, No inlinable. NO CONTEXT! */
{
  __li__4B *li__3HL;
  __li__Q li__CO,li__XU;
  __li__K li__0U,li__1U;
  __li__BB li__TIL;
  li__CO=((__li__Q )li__AO);
  li__XU= 0;
  li__0U= 0;
  li__1U= 0;
  if ((li__CO ==  0)) {
    li__CDL(((__li__4B *)li__BO),'0');
  } else /* FALSE */ {
    if ((li__CO >  0)) {
      li__XU=li__CO;
    } else /* FALSE */ {
      li__XU=(__li__Q)(- li__CO);
      li__CDL(((__li__4B *)li__BO),'-');
    };
    li__0U=(__li__K)(((__li__4B *)li__BO)->li__0D +  1);
    while ((li__XU !=  0)) {
      li__CDL(((__li__4B *)li__BO),((__li__BB )(((__li__LV)(((__li__LV )(__li__Q)(li__XU %  10)) + ((__li__LV )'0'))))));
      li__XU=(__li__Q)(li__XU /  10);
    };
    li__1U=((__li__4B *)li__BO)->li__0D;
    while ((li__0U < li__1U)) {
      li__3HL=((__li__4B *)li__BO);
      li__TIL=((__li__BB *)li__3HL->li__OQK)[(__li__K)(li__0U -  1)];
      ((__li__BB *)li__3HL->li__OQK)[(__li__K)(li__0U -  1)]=((__li__BB *)li__3HL->li__OQK)[(__li__K)(li__1U -  1)];
      ((__li__BB *)li__3HL->li__OQK)[(__li__K)(li__1U -  1)]=li__TIL;
      li__1U=(__li__K)(li__1U -  1);
      li__0U=(__li__K)(li__0U +  1);
    };
  };
}

static void li__2UK(__li__4B *li__3UK,__li__4B *li__4UK)
/* (Strict STRING{li__4B},Strict STRING{NULLxli__4B}) Void No recursive, No inlinable. NO CONTEXT! */
{
  __li__K li__5UK,li__JVK;
  __li__BB *li__YVK;
  li__5UK=li__4UK->li__0D;
  li__JVK=(__li__K)(li__3UK->li__0D + li__5UK);
  if ((li__3UK->li__OP < li__JVK)) {
    if ((li__3UK->li__OP ==  0)) {
      li__3UK->li__OP=li__JVK;
      li__YVK=li__MDR(li__JVK);
      li__3UK->li__OQK=li__YVK;
    } else /* FALSE */ {
      li__YVK=li__E2W(((__li__BB *)li__3UK->li__OQK),li__3UK->li__OP,li__JVK);
      li__3UK->li__OQK=li__YVK;
      li__3UK->li__OP=li__JVK;
    };
  };
  li__ULW(((__li__BB *)li__3UK->li__OQK),li__4UK->li__OQK,li__3UK->li__0D,li__5UK);
  li__3UK->li__0D=li__JVK;
}

static __li__Y* li__ZHB(__li__4B *li__1HB)
/* (Strict STRING{NULLxli__4B}) With result No recursive, No inlinable. NO CONTEXT! */
{
  __li__Y *li__3HB,*li__V3K,*li__CM4,*li__4EG,*li__DJB,*li__2HB;
  __li__4B *li__WKM,*li__HM4;
  __li__IB li__UDG,li__GGDB;
  __li__0VB li__2DG,li__AGDB,li__EGDB;
  __li__K li__YKM,li__ZKM,li__34N,li__HEG;
  __li__U li__PGDB;
  __li__JIB *li__42K;
  __li__BB *li__0JCB,*li__GFL;
  __li__Q3K *li__U3K;
  __li__C li__Q4K,li__NM4,li__QM4;
  li__3HB=NULL;
  li__42K=((__li__JIB *)li__QIB);
  li__V3K=NULL;
  li__WKM=((__li__4B *)li__1HB);
  li__YKM= 0;
  li__ZKM=li__WKM->li__0D;
  li__34N= 1;
  li__0JCB=li__WKM->li__OQK;
  while ((li__34N <= li__ZKM)) {
    li__YKM=(__li__K)((__li__K)( 5 * li__YKM) + ((__li__K )((__li__LV )((__li__BB *)li__0JCB)[(__li__K)(li__34N -  1)])));
    li__34N=(__li__K)(li__34N +  1);
  };
  if ((li__YKM <  0)) {
    li__YKM=(__li__K)(~ li__YKM);
  };
  li__U3K=((void **)li__42K->li__53K)[(__li__K)(li__YKM % li__42K->li__X3K)];
  li__1LM:
  {
    if (((void *)li__U3K == (void *)NULL)) {
      li__Q4K=li__B__;
    } else /* FALSE */ {
      li__CM4=((__li__Y *)li__U3K->li__L4K);
      if (li__1HB==NULL) {
        li__HM4=NULL;
      } else /* STRING */ {
        li__HM4=((void *)li__1HB);
      };
      if (((void *)li__HM4 != (void *)NULL)) {
        li__NM4=li__FJL(li__CM4,li__HM4);
        li__QM4=li__NM4;
      } else /* FALSE */ {
        li__QM4=li__I__;
      };
      li__Q4K=li__QM4;
    };
    if ((! li__Q4K)) {
      li__U3K=li__U3K->li__X4K;
      goto li__1LM;
    };
  };
  if (((void *)li__U3K != (void *)NULL)) {
    li__V3K=li__U3K->li__L4K;
  };
  if (((void *)li__V3K == (void *)NULL)) {
    li__CM4=NULL;
    li__UDG=((__li__IB )(NULL));
    li__2DG=((__li__0VB )sizeof(__li__Y));
    if ((li__2DG ==  0)) {
      li__CM4=li__Y__;
    } else /* FALSE */ {
      li__HEG=-1;
      li__SWB=(__li__0VB)(li__SWB - (__li__0VB)(((__li__0VB ) 0) - li__2DG));
      li__VWB=(__li__0VB)(li__VWB - (__li__0VB)(((__li__0VB ) 0) - li__2DG));
      if ((li__HEG == (__li__K)(-  1))) {
        li__AGDB=(__li__0VB)(((__li__0VB )((__li__K )(sizeof(void *)))) - ((__li__0VB ) 1));
        li__EGDB=(__li__0VB)((__li__0VB)(li__2DG - (__li__0VB)(((__li__0VB ) 0) - li__AGDB)) & (__li__0VB)((__li__0VB)(((__li__0VB ) 0) - li__AGDB) - ((__li__0VB ) 1)));
        li__AGDB=(__li__0VB)(li__EGDB / ((__li__0VB )((__li__K )(sizeof(void *)))));
        li__GGDB=li__S0D(li__EGDB,((__li__IB )(&(table_size[(li__AGDB)-1]))),((__li__U )li__EGDB));
        li__VWB=(__li__0VB)(li__VWB - (__li__0VB)(((__li__0VB ) 0) - li__2DG));
        li__UDG=li__GGDB;
      } else /* FALSE */ {
        li__PGDB=((__li__U )li__HEG);
        li__AGDB=(__li__0VB)(((__li__0VB )((__li__K )(sizeof(void *)))) - ((__li__0VB ) 1));
        li__EGDB=(__li__0VB)((__li__0VB)(li__2DG - (__li__0VB)(((__li__0VB ) 0) - li__AGDB)) & (__li__0VB)((__li__0VB)(((__li__0VB ) 0) - li__AGDB) - ((__li__0VB ) 1)));
        li__GGDB=li__S0D(li__EGDB,((__li__IB )(&(table_type[(li__PGDB)]))),(__li__U)(li__PGDB |  1));
        li__VWB=(__li__0VB)(li__VWB - (__li__0VB)(((__li__0VB ) 0) - li__2DG));
        li__UDG=li__GGDB;
      };
      li__4EG=((__li__Y *)li__UDG);
      li__CM4=li__4EG;
      *(li__4EG) = *(li__Y__);
    };
    li__4EG=((__li__Y *)li__CM4);
    li__HEG=li__1HB->li__0D;
    if ((li__HEG !=  0)) {
      li__GFL=li__MDR((__li__K)(li__HEG +  1));
      li__4EG->li__0B=li__GFL;
      li__3DR(li__GFL,li__1HB->li__OQK,(__li__K)(li__HEG -  1));
      ((__li__BB *)li__4EG->li__0B)[li__HEG]='\0';
      li__4EG->li__ZB=li__HEG;
    };
    li__3HB=li__CM4;
    li__05K(((__li__JIB *)li__QIB),li__CM4);
  } else /* FALSE */ {
    if (li__V3K==NULL) {
      li__DJB=NULL;
    } else /* STRING_CONSTANT */ {
      li__DJB=((__li__Y *)li__V3K);
    };
    li__3HB=li__DJB;
  };
  li__2HB=li__3HB;
  return(li__2HB);
}

static void li__W4F(__li__FE *li__X4F,__li__Y *li__Y4F)
/* (Strict FAST_ARRAY(ABSTRACT_STRING){li__FE},Strict STRING_CONSTANT{NULLxli__Y}) Void No recursive, No inlinable. NO CONTEXT! */
{
  __li__IB li__GTL;
  __li__K li__Z5F,li__CSL,li__MTL,li__GJX;
  __li__C li__G5F;
  void **li__S5F;
  if (((__li__K)((*(li__X4F)).li__1E +  1) < (*(li__X4F)).li__K1F)) {
    (*(li__X4F)).li__1E=(__li__K)((*(li__X4F)).li__1E +  1);
    li__G5F=li__B__;
  } else /* FALSE */ {
    li__G5F=li__I__;
  };
  if ((! li__G5F)) {
    if (((*(li__X4F)).li__K1F ==  0)) {
      li__S5F=li__PNI( 2);
      (*(li__X4F)).li__W1F=li__S5F;
      (*(li__X4F)).li__K1F= 2;
      (*(li__X4F)).li__1E= 0;
    } else /* FALSE */ {
      li__Z5F=(__li__K)((*(li__X4F)).li__K1F <<  1);
      li__S5F=((void **)(*(li__X4F)).li__W1F);
      li__CSL=(*(li__X4F)).li__K1F;
      li__GTL=li__EEN(((__li__IB )li__S5F),((__li__0VB )(__li__K)(li__CSL * ((__li__K )(sizeof(void *))))),((__li__0VB )(__li__K)(li__Z5F * ((__li__K )(sizeof(void *))))));
      li__S5F=((void **)li__GTL);
      li__MTL=(__li__K)(li__Z5F -  1);
      li__GJX=li__CSL;
      while ((li__GJX <= li__MTL)) {
        li__S5F[li__GJX]=NULL;
        li__GJX=(__li__K)(li__GJX +  1);
      };
      (*(li__X4F)).li__W1F=li__S5F;
      (*(li__X4F)).li__K1F=li__Z5F;
      (*(li__X4F)).li__1E=(__li__K)((*(li__X4F)).li__1E +  1);
    };
  };
  ((void **)(*(li__X4F)).li__W1F)[(*(li__X4F)).li__1E]=li__Y4F;
}

static void li__WFL(__li__4B *li__XFL,__li__Y *li__YFL)
/* (Strict STRING{li__4B},Strict STRING_CONSTANT{NULLxli__Y}) Void No recursive, No inlinable. NO CONTEXT! */
{
  __li__K li__ZFL,li__DGL;
  __li__BB *li__SGL;
  li__ZFL=li__YFL->li__ZB;
  li__DGL=(__li__K)(li__XFL->li__0D + li__ZFL);
  if ((li__XFL->li__OP < li__DGL)) {
    if ((li__XFL->li__OP ==  0)) {
      li__XFL->li__OP=li__DGL;
      li__SGL=li__MDR(li__DGL);
      li__XFL->li__OQK=li__SGL;
    } else /* FALSE */ {
      li__SGL=li__E2W(((__li__BB *)li__XFL->li__OQK),li__XFL->li__OP,li__DGL);
      li__XFL->li__OQK=li__SGL;
      li__XFL->li__OP=li__DGL;
    };
  };
  li__ULW(((__li__BB *)li__XFL->li__OQK),li__YFL->li__0B,li__XFL->li__0D,li__ZFL);
  li__XFL->li__0D=li__DGL;
}

static __li__C li__FJL(__li__Y *li__GJL,void *li__HJL)
/* (Strict STRING_CONSTANT{li__Y},ABSTRACT_STRING{NULLxli__Yxli__4B}) With result No recursive, No inlinable. NO CONTEXT! */
{
  __li__K li__QJL,li__RJL,li__ECU;
  __li__C li__JJL,li__IJL;
  __li__BB *li__CKL,*li__DKL,*li__QBU;
  li__JJL=li__I__;
  li__QJL=li__GJL->li__ZB;
  if (((struct ___OBJ *)li__HJL)->__id==__li__Y__) {
    li__RJL=((__li__Y *)li__HJL)->li__ZB;
  } else /* STRING */ {
    li__RJL=((__li__4B *)li__HJL)->li__0D;
  };
  if ((li__QJL == li__RJL)) {
    if ((li__GJL->li__ZB ==  0)) {
      li__JJL=li__B__;
    } else /* FALSE */ {
      li__CKL=li__GJL->li__0B;
      if (((struct ___OBJ *)li__HJL)->__id==__li__Y__) {
        li__DKL=((__li__Y *)li__HJL)->li__0B;
      } else /* STRING */ {
        li__DKL=((__li__4B *)li__HJL)->li__OQK;
      };
      li__QBU=((__li__BB *)li__CKL);
      li__CKL=li__DKL;
      li__ECU=(__li__K)(li__GJL->li__ZB -  1);
      while (((li__ECU >=  0) && (li__QBU[li__ECU] == ((__li__BB *)li__CKL)[li__ECU]))) {
        li__ECU=(__li__K)(li__ECU -  1);
      };
      li__JJL=(li__ECU <  0);
    };
  };
  li__IJL=li__JJL;
  return(li__IJL);
}

static __li__IB li__D1E(__li__U li__F1E)
/* (Expanded UINTEGER_32{li__U}) With result No recursive, No inlinable. NO CONTEXT! */
{
  __li__0VB li__H1E;
  __li__5WB *li__K1E,*li__L1E,*li__01E;
  __li__IB li__G3E,li__G1E;
  __li__C li__L2E;
  li__H1E=((__li__0VB ) 0);
  li__K1E=NULL;
  li__L1E=NULL;
  li__RCF:
  {
    if ((li__H1E < li__S1E)) {
      li__01E=((__li__5WB *)(last_block[(li__H1E)]));
      li__K1E=li__01E;
      li__L2E=(((__li__0VB)(li__01E->li__CXB & (__li__0VB)((__li__0VB)(((__li__0VB ) 0) - ((__li__0VB ) 3)) - ((__li__0VB ) 1))) < ((__li__0VB ) 4096)) || ((__li__0VB)(li__01E->li__CXB & ((__li__0VB ) 1)) == ((__li__0VB ) 1)));
    } else /* FALSE */ {
      li__L2E=li__I__;
    };
    if (li__L2E) {
      li__H1E=(__li__0VB)(li__H1E - (__li__0VB)(((__li__0VB ) 0) - ((__li__0VB ) 1)));
      goto li__RCF;
    };
  };
  if ((li__H1E >= li__S1E)) {
    li__01E=li__5BP();
    li__K1E=li__01E;
  };
  ((__li__5WB *)li__K1E)->li__CXB=(__li__0VB)(li__K1E->li__CXB - ((__li__0VB ) 4096));
  li__01E=((__li__5WB *)li__K1E);
  li__G3E=((__li__IB )((__li__5WB *)(void *)((unsigned long)(void *)((unsigned long)((__li__IB )li__01E) - (unsigned long)(void *)((unsigned long)((__li__IB )((__li__0VB ) 0)) - (unsigned long)((__li__IB )((__li__0VB )(__li__K)(((__li__K )(sizeof(void *))) + ((__li__K )(sizeof(unsigned long)))))))) - (unsigned long)(void *)((unsigned long)((__li__IB )((__li__0VB ) 0)) - (unsigned long)((__li__IB )(__li__0VB)(li__01E->li__CXB & (__li__0VB)((__li__0VB)(((__li__0VB ) 0) - ((__li__0VB ) 3)) - ((__li__0VB ) 1))))))));
  if (((__li__0VB)(((__li__5WB *)li__K1E)->li__CXB & (__li__0VB)((__li__0VB)(((__li__0VB ) 0) - ((__li__0VB ) 3)) - ((__li__0VB ) 1))) < ((__li__0VB )(MINIMUM_SIZE)))) {
    li__QPX(((__li__5WB *)li__K1E));
    li__L1E=li__K1E->li__BXB;
    if (((void *)li__L1E != (void *)NULL)) {
      ((__li__5WB *)li__L1E)->li__CXB=(__li__0VB)((__li__0VB)(li__L1E->li__CXB - (__li__0VB)(((__li__0VB ) 0) - li__K1E->li__CXB)) - (__li__0VB)(((__li__0VB ) 0) - ((__li__0VB )(__li__K)(((__li__K )(sizeof(void *))) + ((__li__K )(sizeof(unsigned long)))))));
      last_block[(li__H1E)] = (li__L1E);
    };
  };
  ((__li__U *)li__G3E)[ 0]=li__F1E;
  li__G1E=(void *)((unsigned long)li__G3E - (unsigned long)(void *)((unsigned long)((__li__IB )((__li__0VB ) 0)) - (unsigned long)((__li__IB )((__li__0VB ) 4))));
  return(li__G1E);
}

static __li__IB li__GLJ(__li__0VB li__ILJ)
/* (Expanded UINTEGER_CPU{li__0VB}) With result No recursive, No inlinable. NO CONTEXT! */
{
  __li__IB li__QLJ,li__0GDB,li__JLJ;
  __li__0VB li__PLCB,li__1LJ,li__UGDB,li__YGDB;
  __li__5WB *li__LMJ;
  li__QLJ=((__li__IB )(NULL));
  li__PLCB=(__li__0VB)(((__li__0VB )((__li__K )(sizeof(void *)))) - ((__li__0VB ) 1));
  li__1LJ=(__li__0VB)((__li__0VB)(li__ILJ - (__li__0VB)(((__li__0VB ) 0) - li__PLCB)) & (__li__0VB)((__li__0VB)(((__li__0VB ) 0) - li__PLCB) - ((__li__0VB ) 1)));
  if ((li__1LJ <= ((__li__0VB )(MINIMUM_SIZE)))) {
    li__UGDB=(__li__0VB)(((__li__0VB )((__li__K )(sizeof(void *)))) - ((__li__0VB ) 1));
    li__YGDB=(__li__0VB)((__li__0VB)(li__1LJ - (__li__0VB)(((__li__0VB ) 0) - li__UGDB)) & (__li__0VB)((__li__0VB)(((__li__0VB ) 0) - li__UGDB) - ((__li__0VB ) 1)));
    li__UGDB=(__li__0VB)(li__YGDB / ((__li__0VB )((__li__K )(sizeof(void *)))));
    li__0GDB=li__S0D(li__YGDB,((__li__IB )(&(table_size[(li__UGDB)-1]))),((__li__U )li__YGDB));
    li__VWB=(__li__0VB)(li__VWB - (__li__0VB)(((__li__0VB ) 0) - li__1LJ));
    li__QLJ=li__0GDB;
  } else /* FALSE */ {
    li__LMJ=li__NZP(li__1LJ);
    li__QLJ=(void *)((unsigned long)((__li__IB )((__li__5WB *)li__LMJ)) - (unsigned long)(void *)((unsigned long)((__li__IB )((__li__0VB ) 0)) - (unsigned long)((__li__IB )((__li__0VB )(__li__K)(((__li__K )(sizeof(void *))) + ((__li__K )(sizeof(unsigned long))))))));
  };
  li__VWB=(__li__0VB)(li__VWB - (__li__0VB)(((__li__0VB ) 0) - li__ILJ));
  li__JLJ=li__QLJ;
  return(li__JLJ);
}

static __li__BB* li__MDR(__li__K li__ODR)
/* (Expanded INTEGER{li__K}) With result No recursive, No inlinable. NO CONTEXT! */
{
  __li__IB li__YWS;
  __li__K li__0SX;
  __li__BB *li__2WS,*li__PDR;
  li__YWS=li__GLJ(((__li__0VB )li__ODR));
  li__2WS=((__li__BB *)li__YWS);
  li__0SX=(__li__K)(li__ODR -  1);
  while ((li__0SX >=  0)) {
    li__2WS[li__0SX]='\0';
    li__0SX=(__li__K)(li__0SX -  1);
  };
  li__PDR=li__2WS;
  return(li__PDR);
}

static __li__BB* li__E2W(__li__BB *li__F2W,__li__K li__G2W,__li__K li__H2W)
/* (Strict NATIVE_ARRAY(Expanded CHARACTER){li__KB},Expanded INTEGER{li__K},Expanded INTEGER{li__K}) With result No recursive, No inlinable. NO CONTEXT! */
{
  __li__IB li__K3W;
  __li__K li__Q3W,li__ML1;
  __li__BB *li__P3W,*li__I2W;
  li__K3W=li__EEN(((__li__IB )li__F2W),((__li__0VB )li__G2W),((__li__0VB )li__H2W));
  li__P3W=((__li__BB *)li__K3W);
  li__Q3W=(__li__K)(li__H2W -  1);
  li__ML1=li__G2W;
  while ((li__ML1 <= li__Q3W)) {
    li__P3W[li__ML1]='\0';
    li__ML1=(__li__K)(li__ML1 +  1);
  };
  li__I2W=li__P3W;
  return(li__I2W);
}

static void li__WET(__li__IB li__YET,__li__IB li__ZET,__li__0VB li__0ET)
/* (Expanded POINTER{li__IB},Expanded POINTER{li__IB},Expanded UINTEGER_CPU{li__0VB}) Void No recursive, No inlinable. NO CONTEXT! */
{
  __li__K li__4ET,li__NFT;
  __li__IB *li__1ET,*li__2ET;
  li__4ET=((__li__K )li__0ET);
  li__NFT=(__li__K)(li__4ET / ((__li__K )(sizeof(void *))));
  li__1ET=((__li__IB *)li__YET);
  li__2ET=((__li__IB *)li__ZET);
  li__4ET=(__li__K)(li__NFT -  1);
  while ((li__4ET >=  0)) {
    li__2ET[li__4ET]=li__1ET[li__4ET];
    li__4ET=(__li__K)(li__4ET -  1);
  };
}

static void li__DUW(__li__5WB *li__EUW,__li__IB li__FUW,__li__0VB li__GUW)
/* (Strict MEMORY{li__5WB},Expanded POINTER{li__IB},Expanded UINTEGER_CPU{li__0VB}) Void No recursive, No inlinable. NO CONTEXT! */
{
  __li__0VB li__HUW,li__GVW;
  __li__5WB *li__4VW;
  li__QPX(li__EUW);
  li__HUW=li__EUW->li__CXB;
  li__GVW=(__li__0VB)(li__HUW - ((__li__0VB )li__FUW));
  if ((li__GVW > (__li__0VB)((__li__0VB)(((__li__0VB )(MINIMUM_SIZE)) - (__li__0VB)(((__li__0VB ) 0) - ((__li__0VB )(__li__K)(((__li__K )(sizeof(void *))) + ((__li__K )(sizeof(unsigned long))))))) - (__li__0VB)(((__li__0VB ) 0) - ((__li__0VB )(__li__K)(((__li__K )(sizeof(void *))) + ((__li__K )(sizeof(unsigned long))))))))) {
    li__HUW=((__li__0VB )li__FUW);
    li__4VW=((__li__5WB *)(void *)((unsigned long)(void *)((unsigned long)((__li__IB )li__EUW) - (unsigned long)(void *)((unsigned long)((__li__IB )((__li__0VB ) 0)) - (unsigned long)((__li__IB )((__li__0VB )(__li__K)(((__li__K )(sizeof(void *))) + ((__li__K )(sizeof(unsigned long)))))))) - (unsigned long)(void *)((unsigned long)((__li__IB )((__li__0VB ) 0)) - (unsigned long)li__FUW)));
    li__4VW->li__BXB=li__EUW;
    li__4VW->li__CXB=(__li__0VB)(li__GVW - ((__li__0VB )(__li__K)(((__li__K )(sizeof(void *))) + ((__li__K )(sizeof(unsigned long))))));
    li__LDW(li__4VW);
    if (((__li__0VB)(li__4VW->li__CXB & ((__li__0VB ) 2)) !=  0)) {
      last_block[(li__GUW)] = (li__4VW);
    } else /* FALSE */ {
      ((__li__5WB *)(void *)((unsigned long)(void *)((unsigned long)((__li__IB )li__4VW) - (unsigned long)(void *)((unsigned long)((__li__IB )((__li__0VB ) 0)) - (unsigned long)((__li__IB )((__li__0VB )(__li__K)(((__li__K )(sizeof(void *))) + ((__li__K )(sizeof(unsigned long)))))))) - (unsigned long)(void *)((unsigned long)((__li__IB )((__li__0VB ) 0)) - (unsigned long)((__li__IB )(__li__0VB)(li__4VW->li__CXB & (__li__0VB)((__li__0VB)(((__li__0VB ) 0) - ((__li__0VB ) 3)) - ((__li__0VB ) 1)))))))->li__BXB=li__4VW;
    };
  };
  li__EUW->li__CXB=(__li__0VB)((__li__0VB)(((__li__0VB ) 0) - (__li__0VB)((__li__0VB)((__li__0VB)(((__li__0VB ) 0) - li__HUW) - ((__li__0VB ) 1)) & (__li__0VB)((__li__0VB)(((__li__0VB ) 0) - ((__li__0VB ) 1)) - ((__li__0VB ) 1)))) - ((__li__0VB ) 1));
  ;
}

static __li__5WB* li__NZP(__li__0VB li__PZP)
/* (Expanded UINTEGER_CPU{li__0VB}) With result No recursive, No inlinable. NO CONTEXT! */
{
  __li__5WB *li__RZP,*li__N1P,*li__QZP;
  __li__0VB li__S1P;
  li__RZP=li__Q0P;
  while ((((void *)li__RZP != (void *)NULL) && ((__li__0VB)(((__li__5WB *)li__RZP)->li__CXB & (__li__0VB)((__li__0VB)(((__li__0VB ) 0) - ((__li__0VB ) 3)) - ((__li__0VB ) 1))) < li__PZP))) {
    li__RZP=li__RZP->li__DXB;
  };
  if (((void *)li__RZP == (void *)NULL)) {
    li__N1P=li__5BP();
    li__RZP=li__N1P;
  };
  li__S1P=(__li__0VB)(((__li__0VB )(void *)((unsigned long)((__li__IB )((__li__5WB *)li__RZP)) - (unsigned long)li__HUD)) >>  26);
  li__DUW(((__li__5WB *)li__RZP),((__li__IB )li__PZP),li__S1P);
  li__QZP=li__RZP;
  return(li__QZP);
}

static void li__LDW(__li__5WB *li__MDW)
/* (Strict MEMORY{li__5WB}) Void No recursive, No inlinable. NO CONTEXT! */
{
  li__MDW->li__DXB=li__Q0P;
  li__MDW->li__EXB=NULL;
  if (((void *)li__Q0P != (void *)NULL)) {
    ((__li__5WB *)li__Q0P)->li__EXB=li__MDW;
  };
  li__Q0P=li__MDW;
}

static void li__QPX(__li__5WB *li__RPX)
/* (Strict MEMORY{li__5WB}) Void No recursive, No inlinable. NO CONTEXT! */
{
  __li__5WB *li__SPX,*li__TPX;
  li__SPX=li__RPX->li__EXB;
  li__TPX=li__RPX->li__DXB;
  if (((void *)li__SPX == (void *)NULL)) {
    li__Q0P=li__TPX;
  } else /* FALSE */ {
    ((__li__5WB *)li__SPX)->li__DXB=li__TPX;
  };
  if (((void *)li__TPX != (void *)NULL)) {
    ((__li__5WB *)li__TPX)->li__EXB=li__SPX;
  };
}

static void li__XPM(__li__JIB *li__YPM,__li__Y *li__ZPM)
/* (Strict HASHED_SET(ABSTRACT_STRING){li__JIB},Strict STRING_CONSTANT{NULLxli__Y}) With result No recursive, No inlinable. NO CONTEXT! */
{
  __li__K li__DQM;
  __li__Q3K *li__CQM;
  li__DQM=li__COM(((__li__Y *)li__ZPM));
  li__CQM=((void **)li__YPM->li__53K)[(__li__K)(li__DQM % li__YPM->li__X3K)];
  while ((! (((void *)li__CQM == (void *)NULL) || ((void *)li__CQM->li__L4K == (void *)li__ZPM)))) {
    li__CQM=li__CQM->li__X4K;
  };
}

static __li__K li__COM(__li__Y *li__DOM)
/* (Strict STRING_CONSTANT{li__Y}) With result No recursive, No inlinable. NO CONTEXT! */
{
  __li__K li__FOM,li__GOM,li__DCO,li__EOM;
  __li__BB *li__OBDB;
  li__FOM= 0;
  li__GOM=li__DOM->li__ZB;
  li__DCO= 1;
  li__OBDB=li__DOM->li__0B;
  while ((li__DCO <= li__GOM)) {
    li__FOM=(__li__K)((__li__K)( 5 * li__FOM) + ((__li__K )((__li__LV )((__li__BB *)li__OBDB)[(__li__K)(li__DCO -  1)])));
    li__DCO=(__li__K)(li__DCO +  1);
  };
  if ((li__FOM <  0)) {
    li__FOM=(__li__K)(~ li__FOM);
  };
  li__EOM=li__FOM;
  return(li__EOM);
}

static void li__3DR(__li__BB *li__4DR,__li__BB *li__5DR,__li__K li__AER)
/* (Strict NATIVE_ARRAY(Expanded CHARACTER){li__KB},Strict NATIVE_ARRAY(Expanded CHARACTER){NULLxli__KB},Expanded INTEGER{li__K}) Void No recursive, No inlinable. NO CONTEXT! */
{
  __li__K li__5XS;
  li__5XS=li__AER;
  while ((li__5XS >=  0)) {
    li__4DR[li__5XS]=((__li__BB *)li__5DR)[li__5XS];
    li__5XS=(__li__K)(li__5XS -  1);
  };
}

static void li__ULW(__li__BB *li__VLW,__li__BB *li__WLW,__li__K li__XLW,__li__K li__YLW)
/* (Strict NATIVE_ARRAY(Expanded CHARACTER){li__KB},Strict NATIVE_ARRAY(Expanded CHARACTER){NULLxli__KB},Expanded INTEGER{li__K},Expanded INTEGER{li__K}) Void No recursive, No inlinable. NO CONTEXT! */
{
  __li__K li__IMW,li__HMW;
  li__IMW= 0;
  li__HMW=li__XLW;
  while ((li__IMW != li__YLW)) {
    li__VLW[li__HMW]=((__li__BB *)li__WLW)[li__IMW];
    li__IMW=(__li__K)(li__IMW +  1);
    li__HMW=(__li__K)(li__HMW +  1);
  };
}

static __li__5WB* li__5BP()
/* () With result No recursive, No inlinable. NO CONTEXT! */
{
  __li__IB li__LYU,li__NYU;
  __li__0VB li__IYU,li__WYU;
  __li__5WB *li__LDP,*li__BCP;
  if ((li__JCP ==  0)) {
    li__LYU=((__li__IB )(NULL));
    li__NYU=((__li__IB )(NULL));
    li__IYU=((__li__0VB ) 33554432);
    do {
      li__WYU=(__li__0VB)(li__IYU * ((__li__0VB ) 2));
      li__IYU=li__WYU;
      li__LYU=li__NYU;
      li__NYU=((__li__IB )(realloc((li__NYU),(li__WYU))));
    } while ((! ((li__NYU == (void *)NULL) || ((__li__0VB)(li__WYU >>  20) ==  2048))));
    if ((li__NYU == (void *)NULL)) {
      li__IYU=(__li__0VB)(li__IYU / ((__li__0VB ) 2));
    } else /* FALSE */ {
      li__LYU=li__NYU;
    };
    li__JCP=li__IYU;
    li__HUD=li__LYU;
    ;
  };
  li__IYU=(__li__0VB)(li__S1E <<  26);
  li__S1E=(__li__0VB)(li__S1E - (__li__0VB)(((__li__0VB ) 0) - ((__li__0VB ) 1)));
  if (((__li__0VB)(li__IYU - (__li__0VB)(((__li__0VB ) 0) - ((__li__0VB ) 67108864))) > li__JCP)) {
    li__HR((&__string_24));
    exit(( 1));
  };
  li__LDP=((__li__5WB *)(void *)((unsigned long)li__HUD - (unsigned long)(void *)((unsigned long)((__li__IB )((__li__0VB ) 0)) - (unsigned long)((__li__IB )li__IYU))));
  li__LDP->li__BXB=NULL;
  li__LDP->li__CXB=(__li__0VB)((__li__0VB)(((__li__0VB ) 0) - (__li__0VB)((__li__0VB)((__li__0VB)(((__li__0VB ) 0) - (__li__0VB)((__li__0VB)(((__li__0VB ) 0) - (__li__0VB)((__li__0VB)((__li__0VB)(((__li__0VB ) 0) - ((__li__0VB ) 0)) - ((__li__0VB ) 1)) & (__li__0VB)((__li__0VB)(((__li__0VB ) 0) - ((__li__0VB ) 2)) - ((__li__0VB ) 1)))) - ((__li__0VB ) 1))) - ((__li__0VB ) 1)) & (__li__0VB)((__li__0VB)(((__li__0VB ) 0) - ((__li__0VB )(__li__K)( 67108864 - (__li__K)(((__li__K )(sizeof(void *))) + ((__li__K )(sizeof(unsigned long))))))) - ((__li__0VB ) 1)))) - ((__li__0VB ) 1));
  li__LDW(li__LDP);
  last_block[((__li__0VB)(li__S1E - ((__li__0VB ) 1)))] = (li__LDP);
  li__BCP=li__LDP;
  return(li__BCP);
}
