#ifdef __cplusplus
extern "C" {
#endif
/*
ANSI C code generated by SmartEiffel The GNU Eiffel Compiler, Eiffel tools and libraries
Release 1.1 Release (Monday June 16th 2003) [Charlemagne]
Copyright (C), 1994-2003 - INRIA - LORIA - UHP - Nancy 2 - FRANCE
D.COLNET, S.COLLIN, O.ZENDRA, P.RIBET, C.ADRIAN - SmartEiffel@loria.fr
http://SmartEiffel.loria.fr
C Compiler options used: -pipe -O2
*/
#ifdef __cplusplus
}
#endif
#include "lisaac.h"
#ifdef __cplusplus
extern "C" {
#endif

void gc_sweep189(fsoc*c){
gc189*o1,*o2,*flt,flh;
o1=((gc189*)(&(c->first_object)));
if(c->header.state_type==FSO_STORE_CHUNK){
for(;o1<store189;o1++){
if((o1->header.flag)==FSOH_MARKED){
o1->header.flag=FSOH_UNMARKED;
}
else{
o1->header.next=gc_free189;
gc_free189=o1;
}
}
}
else{
int dead=1;
flh.header.next=NULL;
flt=&flh;
o2=o1+c->count_minus_one;
for(;o1<=o2;o2--){
if((o2->header.flag)==FSOH_MARKED){
o2->header.flag=FSOH_UNMARKED;
dead=0;}
else{
flt->header.next=o2;
flt=o2;
}
}
if (dead){
c->next=fsocfl;
fsocfl=c;
c->header.state_type=FSO_FREE_CHUNK;
}
else if(flh.header.next!=NULL){
flt->header.next=gc_free189;
gc_free189=flh.header.next;
}
}
}

void gc_mark189(T189*o){
if(((gc189*)o)->header.flag==FSOH_UNMARKED){
((gc189*)o)->header.flag=FSOH_MARKED;
if(NULL!=o->_operator/*9*/)gc_mark102((T102*)(o->_operator/*9*/));
if(NULL!=o->_value/*5*/)gc_mark139((T139*)(o->_value/*5*/));
if(NULL!=o->_pos/*1*/)gc_mark34((T34*)(o->_pos/*1*/));
}}

void gc_align_mark189(fsoc*c,gc189*p){
gc189*b=((gc189*)(&(c->first_object)));
if((c->header.state_type==FSO_STORE_CHUNK)&&(((char*)p)>=((char*)store189)))return;
if(((char*)p)>((char*)(b+(c->count_minus_one))))return;
if(((char*)p)<((char*)b))return;
if(((((char*)p)-((char*)b))%sizeof(*p))==0){
if(p->header.flag==FSOH_UNMARKED){
T189*o=(&(p->object));
((gc189*)o)->header.flag=FSOH_MARKED;
if(NULL!=o->_operator/*9*/)gc_mark102((T102*)(o->_operator/*9*/));
if(NULL!=o->_value/*5*/)gc_mark139((T139*)(o->_value/*5*/));
if(NULL!=o->_pos/*1*/)gc_mark34((T34*)(o->_pos/*1*/));
}
}
}
fsoc H189={{FSOC_SIZE,FSO_STORE_CHUNK,
(void(*)(mch*,void*))gc_align_mark189,
(void(*)(mch*))gc_sweep189},NULL,(((FSOC_SIZE-sizeof(fsoc)+sizeof(double))/sizeof(gc189))-1)};

T189*new189(void){
gc189*n;
fsoc*c;
if(store_left189>1){
store_left189--;
n=store189++;
}
else if(gc_free189!=NULL){
n=gc_free189;
gc_free189=n->header.next;
}
else if(store_left189==1){
store_left189=0;
store_chunk189->header.state_type=FSO_USED_CHUNK;
n=store189++;
}
else{
c=gc_fsoc_get1();
if(gc_free189!=NULL){
n=gc_free189;
gc_free189=n->header.next;
}
else{
if(c==NULL)c=gc_fsoc_get2();
store_chunk189=c;
*store_chunk189=H189;
store189=((gc189*)(&(store_chunk189->first_object)));
store_left189=H189.count_minus_one;
n=store189++;
}
}
n->header.flag=FSOH_UNMARKED;
n->object=M189;
return((T189*)n);
}

void gc_sweep101(fsoc*c){
gc101*o1,*o2,*flt,flh;
o1=((gc101*)(&(c->first_object)));
if(c->header.state_type==FSO_STORE_CHUNK){
for(;o1<store101;o1++){
if((o1->header.flag)==FSOH_MARKED){
o1->header.flag=FSOH_UNMARKED;
}
else{
o1->header.next=gc_free101;
gc_free101=o1;
}
}
}
else{
int dead=1;
flh.header.next=NULL;
flt=&flh;
o2=o1+c->count_minus_one;
for(;o1<=o2;o2--){
if((o2->header.flag)==FSOH_MARKED){
o2->header.flag=FSOH_UNMARKED;
dead=0;}
else{
flt->header.next=o2;
flt=o2;
}
}
if (dead){
c->next=fsocfl;
fsocfl=c;
c->header.state_type=FSO_FREE_CHUNK;
}
else if(flh.header.next!=NULL){
flt->header.next=gc_free101;
gc_free101=flh.header.next;
}
}
}

void gc_mark101(T101*o){
if(((gc101*)o)->header.flag==FSOH_UNMARKED){
((gc101*)o)->header.flag=FSOH_MARKED;
if(NULL!=o->_position_list/*67*/)gc_mark144((T144*)(o->_position_list/*67*/));
if(NULL!=o->_default_value/*63*/)Xgc_mark96((T0*)(o->_default_value/*63*/));
if(NULL!=o->_c_star/*59*/)gc_mark7((T7*)(o->_c_star/*59*/));
if(NULL!=o->_c_generic_name/*55*/)gc_mark7((T7*)(o->_c_generic_name/*55*/));
if(NULL!=o->_c_name/*51*/)gc_mark7((T7*)(o->_c_name/*51*/));
if(NULL!=o->_source/*47*/)gc_mark7((T7*)(o->_source/*47*/));
if(NULL!=o->_filename/*43*/)gc_mark7((T7*)(o->_filename/*43*/));
if(NULL!=o->_cast_list/*39*/)gc_mark56((T56*)(o->_cast_list/*39*/));
if(NULL!=o->_slots_parent/*31*/)gc_mark62((T62*)(o->_slots_parent/*31*/));
if(NULL!=o->_slots/*27*/)gc_mark62((T62*)(o->_slots/*27*/));
if(NULL!=o->_type_collector/*23*/)gc_mark56((T56*)(o->_type_collector/*23*/));
if(NULL!=o->_generic_list/*19*/)gc_mark34((T34*)(o->_generic_list/*19*/));
if(NULL!=o->_name/*15*/)gc_mark7((T7*)(o->_name/*15*/));
if(NULL!=o->_intern_name/*5*/)gc_mark7((T7*)(o->_intern_name/*5*/));
if(NULL!=o->_position/*1*/)gc_mark40((T40*)(o->_position/*1*/));
}}

void gc_align_mark101(fsoc*c,gc101*p){
gc101*b=((gc101*)(&(c->first_object)));
if((c->header.state_type==FSO_STORE_CHUNK)&&(((char*)p)>=((char*)store101)))return;
if(((char*)p)>((char*)(b+(c->count_minus_one))))return;
if(((char*)p)<((char*)b))return;
if(((((char*)p)-((char*)b))%sizeof(*p))==0){
if(p->header.flag==FSOH_UNMARKED){
T101*o=(&(p->object));
((gc101*)o)->header.flag=FSOH_MARKED;
if(NULL!=o->_position_list/*67*/)gc_mark144((T144*)(o->_position_list/*67*/));
if(NULL!=o->_default_value/*63*/)Xgc_mark96((T0*)(o->_default_value/*63*/));
if(NULL!=o->_c_star/*59*/)gc_mark7((T7*)(o->_c_star/*59*/));
if(NULL!=o->_c_generic_name/*55*/)gc_mark7((T7*)(o->_c_generic_name/*55*/));
if(NULL!=o->_c_name/*51*/)gc_mark7((T7*)(o->_c_name/*51*/));
if(NULL!=o->_source/*47*/)gc_mark7((T7*)(o->_source/*47*/));
if(NULL!=o->_filename/*43*/)gc_mark7((T7*)(o->_filename/*43*/));
if(NULL!=o->_cast_list/*39*/)gc_mark56((T56*)(o->_cast_list/*39*/));
if(NULL!=o->_slots_parent/*31*/)gc_mark62((T62*)(o->_slots_parent/*31*/));
if(NULL!=o->_slots/*27*/)gc_mark62((T62*)(o->_slots/*27*/));
if(NULL!=o->_type_collector/*23*/)gc_mark56((T56*)(o->_type_collector/*23*/));
if(NULL!=o->_generic_list/*19*/)gc_mark34((T34*)(o->_generic_list/*19*/));
if(NULL!=o->_name/*15*/)gc_mark7((T7*)(o->_name/*15*/));
if(NULL!=o->_intern_name/*5*/)gc_mark7((T7*)(o->_intern_name/*5*/));
if(NULL!=o->_position/*1*/)gc_mark40((T40*)(o->_position/*1*/));
}
}
}
fsoc H101={{FSOC_SIZE,FSO_STORE_CHUNK,
(void(*)(mch*,void*))gc_align_mark101,
(void(*)(mch*))gc_sweep101},NULL,(((FSOC_SIZE-sizeof(fsoc)+sizeof(double))/sizeof(gc101))-1)};

T101*new101(void){
gc101*n;
fsoc*c;
if(store_left101>1){
store_left101--;
n=store101++;
}
else if(gc_free101!=NULL){
n=gc_free101;
gc_free101=n->header.next;
}
else if(store_left101==1){
store_left101=0;
store_chunk101->header.state_type=FSO_USED_CHUNK;
n=store101++;
}
else{
c=gc_fsoc_get1();
if(gc_free101!=NULL){
n=gc_free101;
gc_free101=n->header.next;
}
else{
if(c==NULL)c=gc_fsoc_get2();
store_chunk101=c;
*store_chunk101=H101;
store101=((gc101*)(&(store_chunk101->first_object)));
store_left101=H101.count_minus_one;
n=store101++;
}
}
n->header.flag=FSOH_UNMARKED;
n->object=M101;
return((T101*)n);
}

void Xgc_mark13(T0*o){
{int i=o->id;
if (i <= 155) {
if (i <= 131) {
if (i <= 106) {
if (i <= 56) {
if (i <= 41) {
gc_mark41((T41*)o);
}else{
gc_mark56((T56*)o);
}}else{
if (i <= 75) {
gc_mark75((T75*)o);
}else{
gc_mark106((T106*)o);
}}}else{
if (i <= 114) {
if (i <= 108) {
gc_mark108((T108*)o);
}else{
gc_mark114((T114*)o);
}}else{
if (i <= 129) {
gc_mark129((T129*)o);
}else{
gc_mark131((T131*)o);
}}}}else{
if (i <= 147) {
if (i <= 134) {
if (i <= 132) {
gc_mark132((T132*)o);
}else{
gc_mark134((T134*)o);
}}else{
if (i <= 135) {
gc_mark135((T135*)o);
}else{
gc_mark147((T147*)o);
}}}else{
if (i <= 151) {
if (i <= 148) {
gc_mark148((T148*)o);
}else{
gc_mark151((T151*)o);
}}else{
gc_mark155((T155*)o);
}}}}else{
if (i <= 198) {
if (i <= 171) {
if (i <= 159) {
if (i <= 157) {
gc_mark157((T157*)o);
}else{
gc_mark159((T159*)o);
}}else{
if (i <= 163) {
gc_mark163((T163*)o);
}else{
gc_mark171((T171*)o);
}}}else{
if (i <= 173) {
if (i <= 172) {
gc_mark172((T172*)o);
}else{
gc_mark173((T173*)o);
}}else{
if (i <= 176) {
gc_mark176((T176*)o);
}else{
gc_mark198((T198*)o);
}}}}else{
if (i <= 204) {
if (i <= 200) {
if (i <= 199) {
gc_mark199((T199*)o);
}else{
gc_mark200((T200*)o);
}}else{
if (i <= 201) {
gc_mark201((T201*)o);
}else{
gc_mark204((T204*)o);
}}}else{
if (i <= 209) {
if (i <= 208) {
gc_mark208((T208*)o);
}else{
gc_mark209((T209*)o);
}}else{
gc_mark213((T213*)o);
}}}}}}

void Xgc_mark166(T0*o){
{int i=o->id;
if (i <= 168) {
if (i <= 165) {
gc_mark165((T165*)o);
}else{
gc_mark168((T168*)o);
}}else{
gc_mark170((T170*)o);
}}}

void Xgc_mark149(T0*o){
{int i=o->id;
if (i <= 148) {
gc_mark148((T148*)o);
}else{
gc_mark172((T172*)o);
}}}

void Xgc_mark137(T0*o){
{int i=o->id;
if (i <= 136) {
gc_mark136((T136*)o);
}else{
gc_mark196((T196*)o);
}}}

void Xgc_mark26(T0*o){
{int i=o->id;
if (i <= 95) {
if (i <= 93) {
if (i <= 25) {
gc_mark25((T25*)o);
}else{
gc_mark93((T93*)o);
}}else{
gc_mark95((T95*)o);
}}else{
if (i <= 98) {
if (i <= 97) {
gc_mark97((T97*)o);
}else{
gc_mark98((T98*)o);
}}else{
gc_mark101((T101*)o);
}}}}

void Xgc_mark82(T0*o){
{int i=o->id;
if (i <= 131) {
if (i <= 106) {
gc_mark106((T106*)o);
}else{
gc_mark131((T131*)o);
}}else{
if (i <= 163) {
gc_mark163((T163*)o);
}else{
gc_mark171((T171*)o);
}}}}

void Xgc_mark79(T0*o){
{int i=o->id;
if (i <= 157) {
if (i <= 132) {
if (i <= 114) {
if (i <= 106) {
if (i <= 75) {
gc_mark75((T75*)o);
}else{
gc_mark106((T106*)o);
}}else{
if (i <= 108) {
gc_mark108((T108*)o);
}else{
gc_mark114((T114*)o);
}}}else{
if (i <= 131) {
if (i <= 129) {
gc_mark129((T129*)o);
}else{
gc_mark131((T131*)o);
}}else{
gc_mark132((T132*)o);
}}}else{
if (i <= 148) {
if (i <= 135) {
if (i <= 134) {
gc_mark134((T134*)o);
}else{
gc_mark135((T135*)o);
}}else{
if (i <= 147) {
gc_mark147((T147*)o);
}else{
gc_mark148((T148*)o);
}}}else{
if (i <= 155) {
if (i <= 151) {
gc_mark151((T151*)o);
}else{
gc_mark155((T155*)o);
}}else{
gc_mark157((T157*)o);
}}}}else{
if (i <= 198) {
if (i <= 172) {
if (i <= 163) {
if (i <= 159) {
gc_mark159((T159*)o);
}else{
gc_mark163((T163*)o);
}}else{
if (i <= 171) {
gc_mark171((T171*)o);
}else{
gc_mark172((T172*)o);
}}}else{
if (i <= 176) {
if (i <= 173) {
gc_mark173((T173*)o);
}else{
gc_mark176((T176*)o);
}}else{
gc_mark198((T198*)o);
}}}else{
if (i <= 204) {
if (i <= 200) {
if (i <= 199) {
gc_mark199((T199*)o);
}else{
gc_mark200((T200*)o);
}}else{
if (i <= 201) {
gc_mark201((T201*)o);
}else{
gc_mark204((T204*)o);
}}}else{
if (i <= 209) {
if (i <= 208) {
gc_mark208((T208*)o);
}else{
gc_mark209((T209*)o);
}}else{
gc_mark213((T213*)o);
}}}}}}

void Xgc_mark130(T0*o){
{int i=o->id;
if (i <= 199) {
if (i <= 129) {
gc_mark129((T129*)o);
}else{
gc_mark199((T199*)o);
}}else{
if (i <= 200) {
gc_mark200((T200*)o);
}else{
gc_mark201((T201*)o);
}}}}

void Xgc_mark77(T0*o){
{int i=o->id;
if (i <= 157) {
if (i <= 132) {
if (i <= 108) {
if (i <= 75) {
gc_mark75((T75*)o);
}else{
gc_mark108((T108*)o);
}}else{
if (i <= 114) {
gc_mark114((T114*)o);
}else{
gc_mark132((T132*)o);
}}}else{
if (i <= 155) {
if (i <= 135) {
gc_mark135((T135*)o);
}else{
gc_mark155((T155*)o);
}}else{
gc_mark157((T157*)o);
}}}else{
if (i <= 204) {
if (i <= 176) {
if (i <= 159) {
gc_mark159((T159*)o);
}else{
gc_mark176((T176*)o);
}}else{
if (i <= 198) {
gc_mark198((T198*)o);
}else{
gc_mark204((T204*)o);
}}}else{
if (i <= 209) {
if (i <= 208) {
gc_mark208((T208*)o);
}else{
gc_mark209((T209*)o);
}}else{
gc_mark213((T213*)o);
}}}}}

void Xgc_mark53(T0*o){
{int i=o->id;
if (i <= 52) {
gc_mark52((T52*)o);
}else{
gc_mark113((T113*)o);
}}}

void Xgc_mark96(T0*o){
{int i=o->id;
if (i <= 189) {
if (i <= 185) {
if (i <= 136) {
if (i <= 99) {
gc_mark99((T99*)o);
}else{
gc_mark136((T136*)o);
}}else{
if (i <= 183) {
gc_mark183((T183*)o);
}else{
gc_mark185((T185*)o);
}}}else{
if (i <= 187) {
if (i <= 186) {
gc_mark186((T186*)o);
}else{
gc_mark187((T187*)o);
}}else{
if (i <= 188) {
gc_mark188((T188*)o);
}else{
gc_mark189((T189*)o);
}}}}else{
if (i <= 193) {
if (i <= 191) {
if (i <= 190) {
gc_mark190((T190*)o);
}else{
gc_mark191((T191*)o);
}}else{
if (i <= 192) {
gc_mark192((T192*)o);
}else{
gc_mark193((T193*)o);
}}}else{
if (i <= 195) {
if (i <= 194) {
gc_mark194((T194*)o);
}else{
gc_mark195((T195*)o);
}}else{
if (i <= 196) {
gc_mark196((T196*)o);
}else{
gc_mark197((T197*)o);
}}}}}}

void Xgc_mark25(T0*o){
{int i=o->id;
if (i <= 95) {
if (i <= 25) {
gc_mark25((T25*)o);
}else{
gc_mark95((T95*)o);
}}else{
if (i <= 98) {
gc_mark98((T98*)o);
}else{
gc_mark101((T101*)o);
}}}}

void Xgc_mark164(T0*o){
{int i=o->id;
if (i <= 170) {
if (i <= 168) {
if (i <= 165) {
gc_mark165((T165*)o);
}else{
gc_mark168((T168*)o);
}}else{
gc_mark170((T170*)o);
}}else{
if (i <= 225) {
gc_mark225((T225*)o);
}else{
gc_mark227((T227*)o);
}}}}

T6 X77is_constant(T0*C){
T6 R;
{Tid id=((T0*)C)->id;
if(id<=157){
if(id<=132){
if(id<=108){
if(id<=75){
R=(T6)(/*(IRF4.2is_constant*/(0)/*)*/);
}
else{
R=(T6)(/*(IRF4.2is_constant*/(0)/*)*/);
}}
else{
if(id<=114){
R=(T6)(1);
}
else{
R=(T6)(/*(IRF4.2is_constant*/(0)/*)*/);
}}}
else{
if(id<=155){
if(id<=135){
R=(T6)(1);
}
else{
R=(T6)(/*(IRF4.2is_constant*/(0)/*)*/);
}}
else{
R=(T6)(/*(IRF4.2is_constant*/(0)/*)*/);
}}}
else{
if(id<=204){
if(id<=176){
if(id<=159){
R=(T6)(1);
}
else{
R=(T6)(/*(IRF4.2is_constant*/(0)/*)*/);
}}
else{
if(id<=198){
R=(T6)(/*(IRF4.2is_constant*/(0)/*)*/);
}
else{
R=(T6)(/*(IRF4.2is_constant*/(0)/*)*/);
}}}
else{
if(id<=209){
if(id<=208){
R=(T6)(1);
}
else{
R=(T6)(1);
}}
else{
R=(T6)(/*(IRF4.2is_constant*/(0)/*)*/);
}}}}
return R;
}

void X77display(T0*C,T0* a1){
{Tid id=((T0*)C)->id;
if(id<=157){
if(id<=132){
if(id<=108){
if(id<=75){
r75display(((T75*)C),a1);
}
else{
r108display(((T108*)C),a1);
}}
else{
if(id<=114){
r114display(((T114*)C),a1);
}
else{
r132display(((T132*)C),a1);
}}}
else{
if(id<=155){
if(id<=135){
r135display(((T135*)C),a1);
}
else{
r155display(((T155*)C),a1);
}}
else{
r157display(((T157*)C),a1);
}}}
else{
if(id<=204){
if(id<=176){
if(id<=159){
r159display(((T159*)C),a1);
}
else{
r176display(((T176*)C),a1);
}}
else{
if(id<=198){
r198display(((T198*)C),a1);
}
else{
r204display(((T204*)C),a1);
}}}
else{
if(id<=209){
if(id<=208){
r208display(((T208*)C),a1);
}
else{
r209display(((T209*)C),a1);
}}
else{
r213display(((T213*)C),a1);
}}}}
}

void X77sub_get_type(T0*C,T0* a1){
{Tid id=((T0*)C)->id;
if(id<=157){
if(id<=132){
if(id<=108){
if(id<=75){
r75sub_get_type(((T75*)C),a1);
}
else{
r108sub_get_type(((T108*)C),a1);
}}
else{
if(id<=114){
/*[IRF3.6sub_get_type*/{T114* C1=((T114*)C);
T0* b1=a1;
/*l36c9/constant.e*/
r56add(((T56*)b1),(/*RF2*/(C1)->_static_type/*14*/));
}/*]*/
}
else{
r132sub_get_type(((T132*)C),a1);
}}}
else{
if(id<=155){
if(id<=135){
/*[IRF3.6sub_get_type*/{T135* C1=((T135*)C);
T0* b1=a1;
/*l36c9/constant.e*/
r56add(((T56*)b1),(/*RF2*/(C1)->_static_type/*14*/));
}/*]*/
}
else{
r155sub_get_type(((T155*)C),a1);
}}
else{
r157sub_get_type(((T157*)C),a1);
}}}
else{
if(id<=204){
if(id<=176){
if(id<=159){
/*[IRF3.6sub_get_type*/{T159* C1=((T159*)C);
T0* b1=a1;
/*l36c9/constant.e*/
r56add(((T56*)b1),(/*RF2*/(C1)->_static_type/*14*/));
}/*]*/
}
else{
r176sub_get_type(((T176*)C),a1);
}}
else{
if(id<=198){
r198sub_get_type(((T198*)C),a1);
}
else{
r204sub_get_type(((T204*)C),a1);
}}}
else{
if(id<=209){
if(id<=208){
/*[IRF3.6sub_get_type*/{T208* C1=((T208*)C);
T0* b1=a1;
/*l36c9/constant.e*/
r56add(((T56*)b1),(/*RF2*/(C1)->_static_type/*14*/));
}/*]*/
}
else{
/*[IRF3.6sub_get_type*/{T209* C1=((T209*)C);
T0* b1=a1;
/*l36c9/constant.e*/
r56add(((T56*)b1),(/*RF2*/(C1)->_static_type/*14*/));
}/*]*/
}}
else{
/*[IRF3.6sub_get_type*/{T213* C1=((T213*)C);
T0* b1=a1;
/*l19c9/data_star_slot.e*/
r56add(((T56*)b1),(/*RF2*/(C1)->_static_type/*17*/));
}/*]*/
}}}}
}

T6 X77depend(T0*C){
T6 R;
{Tid id=((T0*)C)->id;
if(id<=157){
if(id<=132){
if(id<=108){
if(id<=75){
R=(T6)(r75depend(((T75*)C)));
}
else{
R=(T6)(r108depend(((T108*)C)));
}}
else{
if(id<=114){
R=(T6)(r114depend(((T114*)C)));
}
else{
R=(T6)(r132depend(((T132*)C)));
}}}
else{
if(id<=155){
if(id<=135){
R=(T6)(r135depend(((T135*)C)));
}
else{
R=(T6)(r155depend(((T155*)C)));
}}
else{
R=(T6)(r157depend(((T157*)C)));
}}}
else{
if(id<=204){
if(id<=176){
if(id<=159){
R=(T6)(r159depend(((T159*)C)));
}
else{
R=(T6)(r176depend(((T176*)C)));
}}
else{
if(id<=198){
R=(T6)(r198depend(((T198*)C)));
}
else{
R=(T6)(r204depend(((T204*)C)));
}}}
else{
if(id<=209){
if(id<=208){
R=(T6)(r208depend(((T208*)C)));
}
else{
R=(T6)(r209depend(((T209*)C)));
}}
else{
R=(T6)(r213depend(((T213*)C)));
}}}}
return R;
}

T0* X77my_copy(T0*C){
T0* R;
{Tid id=((T0*)C)->id;
if(id<=157){
if(id<=132){
if(id<=108){
if(id<=75){
R=(r75my_copy(((T75*)C)));
}
else{
R=(r108my_copy(((T108*)C)));
}}
else{
if(id<=114){
R=(r114my_copy(((T114*)C)));
}
else{
R=(r132my_copy(((T132*)C)));
}}}
else{
if(id<=155){
if(id<=135){
R=(r135my_copy(((T135*)C)));
}
else{
R=(r155my_copy(((T155*)C)));
}}
else{
R=(r157my_copy(((T157*)C)));
}}}
else{
if(id<=204){
if(id<=176){
if(id<=159){
R=(r159my_copy(((T159*)C)));
}
else{
R=(r176my_copy(((T176*)C)));
}}
else{
if(id<=198){
R=(r198my_copy(((T198*)C)));
}
else{
R=(r204my_copy(((T204*)C)));
}}}
else{
if(id<=209){
if(id<=208){
R=(r208my_copy(((T208*)C)));
}
else{
R=(r209my_copy(((T209*)C)));
}}
else{
R=(r213my_copy(((T213*)C)));
}}}}
return R;
}

T6 X77is_copy(T0*C){
T6 R;
{Tid id=((T0*)C)->id;
if(id<=157){
if(id<=132){
if(id<=108){
if(id<=75){
R=(T6)(/*(IRF4.2is_copy*/(0)/*)*/);
}
else{
R=(T6)(/*(IRF4.2is_copy*/(0)/*)*/);
}}
else{
if(id<=114){
R=(T6)(1);
}
else{
R=(T6)(1);
}}}
else{
if(id<=155){
if(id<=135){
R=(T6)(1);
}
else{
R=(T6)(/*(IRF4.2is_copy*/(0)/*)*/);
}}
else{
R=(T6)(/*(IRF4.2is_copy*/(0)/*)*/);
}}}
else{
if(id<=204){
if(id<=176){
if(id<=159){
R=(T6)(1);
}
else{
R=(T6)(/*(IRF4.2is_copy*/(0)/*)*/);
}}
else{
if(id<=198){
R=(T6)(r198is_copy(((T198*)C)));
}
else{
R=(T6)(/*(IRF4.2is_copy*/(0)/*)*/);
}}}
else{
if(id<=209){
if(id<=208){
R=(T6)(1);
}
else{
R=(T6)(1);
}}
else{
R=(T6)(/*(IRF4.2is_copy*/(0)/*)*/);
}}}}
return R;
}

T0* X77position(T0*C){
T0* R;
{Tid id=((T0*)C)->id;
if(id<=157){
if(id<=132){
if(id<=108){
if(id<=75){
R=((/*RF2*/(((T75*)C))->_position/*1*/));
}
else{
R=((/*RF2*/(((T108*)C))->_position/*1*/));
}}
else{
if(id<=114){
R=((/*RF2*/(((T114*)C))->_position/*1*/));
}
else{
R=((/*RF2*/(((T132*)C))->_position/*5*/));
}}}
else{
if(id<=155){
if(id<=135){
R=((/*RF2*/(((T135*)C))->_position/*1*/));
}
else{
R=((/*RF2*/(((T155*)C))->_position/*5*/));
}}
else{
R=((/*RF2*/(((T157*)C))->_position/*5*/));
}}}
else{
if(id<=204){
if(id<=176){
if(id<=159){
R=((/*RF2*/(((T159*)C))->_position/*1*/));
}
else{
R=((/*RF2*/(((T176*)C))->_position/*1*/));
}}
else{
if(id<=198){
R=((/*RF2*/(((T198*)C))->_position/*1*/));
}
else{
R=((/*RF2*/(((T204*)C))->_position/*1*/));
}}}
else{
if(id<=209){
if(id<=208){
R=((/*RF2*/(((T208*)C))->_position/*1*/));
}
else{
R=((/*RF2*/(((T209*)C))->_position/*1*/));
}}
else{
R=((/*RF2*/(((T213*)C))->_position/*5*/));
}}}}
return R;
}

void X77remove(T0*C){
{Tid id=((T0*)C)->id;
if(id<=157){
if(id<=132){
if(id<=108){
if(id<=75){
r75remove(((T75*)C));
}
else{
r108remove(((T108*)C));
}}
else{
if(id<=114){
/*[IRF3.1remove*//*]*/
}
else{
r132remove(((T132*)C));
}}}
else{
if(id<=155){
if(id<=135){
/*[IRF3.1remove*//*]*/
}
else{
r155remove(((T155*)C));
}}
else{
r157remove(((T157*)C));
}}}
else{
if(id<=204){
if(id<=176){
if(id<=159){
/*[IRF3.1remove*//*]*/
}
else{
r176remove(((T176*)C));
}}
else{
if(id<=198){
r198remove(((T198*)C));
}
else{
r204remove(((T204*)C));
}}}
else{
if(id<=209){
if(id<=208){
/*[IRF3.1remove*//*]*/
}
else{
/*[IRF3.1remove*//*]*/
}}
else{
r213remove(((T213*)C));
}}}}
}

T0* X77get_type(T0*C){
T0* R;
{Tid id=((T0*)C)->id;
if(id<=157){
if(id<=132){
if(id<=108){
if(id<=75){
R=(r75get_type(((T75*)C)));
}
else{
R=(r108get_type(((T108*)C)));
}}
else{
if(id<=114){
R=(r114get_type(((T114*)C)));
}
else{
R=(r132get_type(((T132*)C)));
}}}
else{
if(id<=155){
if(id<=135){
R=(r135get_type(((T135*)C)));
}
else{
R=(r155get_type(((T155*)C)));
}}
else{
R=(r157get_type(((T157*)C)));
}}}
else{
if(id<=204){
if(id<=176){
if(id<=159){
R=(r159get_type(((T159*)C)));
}
else{
R=(r176get_type(((T176*)C)));
}}
else{
if(id<=198){
R=(r198get_type(((T198*)C)));
}
else{
R=(r204get_type(((T204*)C)));
}}}
else{
if(id<=209){
if(id<=208){
R=(r208get_type(((T208*)C)));
}
else{
R=(r209get_type(((T209*)C)));
}}
else{
R=(r213get_type(((T213*)C)));
}}}}
return R;
}

void X77unlink(T0*C){
{Tid id=((T0*)C)->id;
if(id<=157){
if(id<=132){
if(id<=108){
if(id<=75){
/*[IRF3.3unlink*/((((T75*)(((T75*)C))))->_is_link/*9*/)=(0);
/*]*/
}
else{
/*[IRF3.3unlink*/((((T108*)(((T108*)C))))->_is_link/*9*/)=(0);
/*]*/
}}
else{
if(id<=114){
/*[IRF3.3unlink*/((((T114*)(((T114*)C))))->_is_link/*9*/)=(0);
/*]*/
}
else{
/*[IRF3.3unlink*/((((T132*)(((T132*)C))))->_is_link/*14*/)=(0);
/*]*/
}}}
else{
if(id<=155){
if(id<=135){
/*[IRF3.3unlink*/((((T135*)(((T135*)C))))->_is_link/*9*/)=(0);
/*]*/
}
else{
/*[IRF3.3unlink*/((((T155*)(((T155*)C))))->_is_link/*18*/)=(0);
/*]*/
}}
else{
/*[IRF3.3unlink*/((((T157*)(((T157*)C))))->_is_link/*22*/)=(0);
/*]*/
}}}
else{
if(id<=204){
if(id<=176){
if(id<=159){
/*[IRF3.3unlink*/((((T159*)(((T159*)C))))->_is_link/*9*/)=(0);
/*]*/
}
else{
/*[IRF3.3unlink*/((((T176*)(((T176*)C))))->_is_link/*9*/)=(0);
/*]*/
}}
else{
if(id<=198){
/*[IRF3.3unlink*/((((T198*)(((T198*)C))))->_is_link/*9*/)=(0);
/*]*/
}
else{
/*[IRF3.3unlink*/((((T204*)(((T204*)C))))->_is_link/*9*/)=(0);
/*]*/
}}}
else{
if(id<=209){
if(id<=208){
/*[IRF3.3unlink*/((((T208*)(((T208*)C))))->_is_link/*9*/)=(0);
/*]*/
}
else{
/*[IRF3.3unlink*/((((T209*)(((T209*)C))))->_is_link/*9*/)=(0);
/*]*/
}}
else{
/*[IRF3.3unlink*/((((T213*)(((T213*)C))))->_is_link/*22*/)=(0);
/*]*/
}}}}
}

T0* X77search_block(T0*C){
T0* R;
{Tid id=((T0*)C)->id;
if(id<=157){
if(id<=132){
if(id<=108){
if(id<=75){
R=(r75search_block(((T75*)C)));
}
else{
R=(r108search_block(((T108*)C)));
}}
else{
if(id<=114){
R=(r114search_block(((T114*)C)));
}
else{
R=(r132search_block(((T132*)C)));
}}}
else{
if(id<=155){
if(id<=135){
R=(r135search_block(((T135*)C)));
}
else{
R=(r155search_block(((T155*)C)));
}}
else{
R=(r157search_block(((T157*)C)));
}}}
else{
if(id<=204){
if(id<=176){
if(id<=159){
R=(r159search_block(((T159*)C)));
}
else{
R=(r176search_block(((T176*)C)));
}}
else{
if(id<=198){
R=(r198search_block(((T198*)C)));
}
else{
R=(r204search_block(((T204*)C)));
}}}
else{
if(id<=209){
if(id<=208){
R=(r208search_block(((T208*)C)));
}
else{
R=(r209search_block(((T209*)C)));
}}
else{
R=(r213search_block(((T213*)C)));
}}}}
return R;
}

void X77genere(T0*C,T0* a1){
{Tid id=((T0*)C)->id;
if(id<=157){
if(id<=132){
if(id<=108){
if(id<=75){
r75genere(((T75*)C),a1);
}
else{
r108genere(((T108*)C),a1);
}}
else{
if(id<=114){
r114genere(((T114*)C),a1);
}
else{
r132genere(((T132*)C),a1);
}}}
else{
if(id<=155){
if(id<=135){
/*[IRF3.6genere*/{T0* b1=a1;
/*l89c14/block.e*/
r7append(((T7*)b1),se_ms(7,"\173""BLOCK\175"""));
}/*]*/
}
else{
r155genere(((T155*)C),a1);
}}
else{
r157genere(((T157*)C),a1);
}}}
else{
if(id<=204){
if(id<=176){
if(id<=159){
r159genere(((T159*)C),a1);
}
else{
r176genere(((T176*)C),a1);
}}
else{
if(id<=198){
r198genere(((T198*)C),a1);
}
else{
r204genere(((T204*)C),a1);
}}}
else{
if(id<=209){
if(id<=208){
r208genere(((T208*)C),a1);
}
else{
r209genere(((T209*)C),a1);
}}
else{
r213genere(((T213*)C),a1);
}}}}
}

T2 X77static_type(T0*C){
T2 R;
{Tid id=((T0*)C)->id;
if(id<=157){
if(id<=132){
if(id<=108){
if(id<=75){
R=(r75static_type(((T75*)C)));
}
else{
R=(r108static_type(((T108*)C)));
}}
else{
if(id<=114){
R=((/*RF2*/(((T114*)C))->_static_type/*14*/));
}
else{
R=(r132static_type(((T132*)C)));
}}}
else{
if(id<=155){
if(id<=135){
R=((/*RF2*/(((T135*)C))->_static_type/*14*/));
}
else{
R=((/*RF2*/(((T155*)C))->_static_type/*13*/));
}}
else{
R=((/*RF2*/(((T157*)C))->_static_type/*17*/));
}}}
else{
if(id<=204){
if(id<=176){
if(id<=159){
R=((/*RF2*/(((T159*)C))->_static_type/*14*/));
}
else{
R=((/*RF2*/(((T176*)C))->_static_type/*18*/));
}}
else{
if(id<=198){
R=((/*RF2*/(((T198*)C))->_static_type/*18*/));
}
else{
R=(r204static_type(((T204*)C)));
}}}
else{
if(id<=209){
if(id<=208){
R=((/*RF2*/(((T208*)C))->_static_type/*14*/));
}
else{
R=((/*RF2*/(((T209*)C))->_static_type/*14*/));
}}
else{
R=((/*RF2*/(((T213*)C))->_static_type/*17*/));
}}}}
return R;
}

T0* X77execute(T0*C){
T0* R;
{Tid id=((T0*)C)->id;
if(id<=157){
if(id<=132){
if(id<=108){
if(id<=75){
R=(r75execute(((T75*)C)));
}
else{
R=(r108execute(((T108*)C)));
}}
else{
if(id<=114){
R=(r114execute(((T114*)C)));
}
else{
R=(r132execute(((T132*)C)));
}}}
else{
if(id<=155){
if(id<=135){
R=(r135execute(((T135*)C)));
}
else{
R=(r155execute(((T155*)C)));
}}
else{
R=(r157execute(((T157*)C)));
}}}
else{
if(id<=204){
if(id<=176){
if(id<=159){
R=(r159execute(((T159*)C)));
}
else{
R=(r176execute(((T176*)C)));
}}
else{
if(id<=198){
R=(r198execute(((T198*)C)));
}
else{
R=(r204execute(((T204*)C)));
}}}
else{
if(id<=209){
if(id<=208){
R=(r208execute(((T208*)C)));
}
else{
R=(r209execute(((T209*)C)));
}}
else{
R=(r213execute(((T213*)C)));
}}}}
return R;
}

T2 X77object_id(T0*C){
T2 R;
{Tid id=((T0*)C)->id;
if(id<=157){
if(id<=132){
if(id<=108){
if(id<=75){
R=(r75object_id(((T75*)C)));
}
else{
R=(r108object_id(((T108*)C)));
}}
else{
if(id<=114){
R=(r114object_id(((T114*)C)));
}
else{
R=(r132object_id(((T132*)C)));
}}}
else{
if(id<=155){
if(id<=135){
R=(r135object_id(((T135*)C)));
}
else{
R=(r155object_id(((T155*)C)));
}}
else{
R=(r157object_id(((T157*)C)));
}}}
else{
if(id<=204){
if(id<=176){
if(id<=159){
R=(r159object_id(((T159*)C)));
}
else{
R=(r176object_id(((T176*)C)));
}}
else{
if(id<=198){
R=(r198object_id(((T198*)C)));
}
else{
R=(r204object_id(((T204*)C)));
}}}
else{
if(id<=209){
if(id<=208){
R=(r208object_id(((T208*)C)));
}
else{
R=(r209object_id(((T209*)C)));
}}
else{
R=(r213object_id(((T213*)C)));
}}}}
return R;
}

void X77link(T0*C){
{Tid id=((T0*)C)->id;
if(id<=157){
if(id<=132){
if(id<=108){
if(id<=75){
/*[IRF3.3link*/((((T75*)(((T75*)C))))->_is_link/*9*/)=(1);
/*]*/
}
else{
/*[IRF3.3link*/((((T108*)(((T108*)C))))->_is_link/*9*/)=(1);
/*]*/
}}
else{
if(id<=114){
/*[IRF3.3link*/((((T114*)(((T114*)C))))->_is_link/*9*/)=(1);
/*]*/
}
else{
/*[IRF3.3link*/((((T132*)(((T132*)C))))->_is_link/*14*/)=(1);
/*]*/
}}}
else{
if(id<=155){
if(id<=135){
/*[IRF3.3link*/((((T135*)(((T135*)C))))->_is_link/*9*/)=(1);
/*]*/
}
else{
/*[IRF3.3link*/((((T155*)(((T155*)C))))->_is_link/*18*/)=(1);
/*]*/
}}
else{
/*[IRF3.3link*/((((T157*)(((T157*)C))))->_is_link/*22*/)=(1);
/*]*/
}}}
else{
if(id<=204){
if(id<=176){
if(id<=159){
/*[IRF3.3link*/((((T159*)(((T159*)C))))->_is_link/*9*/)=(1);
/*]*/
}
else{
/*[IRF3.3link*/((((T176*)(((T176*)C))))->_is_link/*9*/)=(1);
/*]*/
}}
else{
if(id<=198){
/*[IRF3.3link*/((((T198*)(((T198*)C))))->_is_link/*9*/)=(1);
/*]*/
}
else{
/*[IRF3.3link*/((((T204*)(((T204*)C))))->_is_link/*9*/)=(1);
/*]*/
}}}
else{
if(id<=209){
if(id<=208){
/*[IRF3.3link*/((((T208*)(((T208*)C))))->_is_link/*9*/)=(1);
/*]*/
}
else{
/*[IRF3.3link*/((((T209*)(((T209*)C))))->_is_link/*9*/)=(1);
/*]*/
}}
else{
/*[IRF3.3link*/((((T213*)(((T213*)C))))->_is_link/*22*/)=(1);
/*]*/
}}}}
}

T6 X115is_fusion(T0*C,T0* a1){
T6 R;
{Tid id=((T0*)C)->id;
if(id<=159){
if(id<=135){
if(id<=114){
R=(T6)(r114is_fusion(((T114*)C),a1));
}
else{
R=(T6)(/*(IRF4.2is_fusion*/(1)/*)*/);
}}
else{
R=(T6)(r159is_fusion(((T159*)C),a1));
}}
else{
if(id<=208){
R=(T6)(r208is_fusion(((T208*)C),a1));
}
else{
R=(T6)(r209is_fusion(((T209*)C),a1));
}}}
return R;
}

T6 X96is_constant(T0*C){
T6 R;
{Tid id=((T0*)C)->id;
if(id<=189){
if(id<=185){
if(id<=136){
if(id<=99){
R=(T6)(r99is_constant(((T99*)C)));
}
else{
R=(T6)(r136is_constant(((T136*)C)));
}}
else{
if(id<=183){
R=(T6)(r183is_constant(((T183*)C)));
}
else{
R=(T6)(r185is_constant(((T185*)C)));
}}}
else{
if(id<=187){
if(id<=186){
R=(T6)(r186is_constant(((T186*)C)));
}
else{
R=(T6)(r187is_constant(((T187*)C)));
}}
else{
if(id<=188){
R=(T6)(r188is_constant(((T188*)C)));
}
else{
R=(T6)(r189is_constant(((T189*)C)));
}}}}
else{
if(id<=193){
if(id<=191){
if(id<=190){
R=(T6)(r190is_constant(((T190*)C)));
}
else{
R=(T6)(r191is_constant(((T191*)C)));
}}
else{
if(id<=192){
R=(T6)(r192is_constant(((T192*)C)));
}
else{
R=(T6)(r193is_constant(((T193*)C)));
}}}
else{
if(id<=195){
if(id<=194){
R=(T6)(r194is_constant(((T194*)C)));
}
else{
R=(T6)(r195is_constant(((T195*)C)));
}}
else{
if(id<=196){
R=(T6)(r196is_constant(((T196*)C)));
}
else{
R=(T6)(r197is_constant(((T197*)C)));
}}}}}
return R;
}

T0* X96to_run(T0*C,T0* a1,T0* a2,T0* a3){
T0* R;
{Tid id=((T0*)C)->id;
if(id<=189){
if(id<=185){
if(id<=136){
if(id<=99){
R=(r99to_run(((T99*)C),a1,a2,a3));
}
else{
R=(r136to_run(((T136*)C),a1,a2,a3));
}}
else{
if(id<=183){
R=(r183to_run(((T183*)C),a1,a2,a3));
}
else{
R=(r185to_run(((T185*)C),a1,a2,a3));
}}}
else{
if(id<=187){
if(id<=186){
R=(r186to_run(((T186*)C),a1,a2,a3));
}
else{
R=(r187to_run(((T187*)C),a1,a2,a3));
}}
else{
if(id<=188){
R=(r188to_run(((T188*)C),a1,a2,a3));
}
else{
R=(r189to_run(((T189*)C),a1,a2,a3));
}}}}
else{
if(id<=193){
if(id<=191){
if(id<=190){
R=(r190to_run(((T190*)C),a1,a2,a3));
}
else{
R=(r191to_run(((T191*)C),a1,a2,a3));
}}
else{
if(id<=192){
R=(r192to_run(((T192*)C),a1,a2,a3));
}
else{
R=(r193to_run(((T193*)C),a1,a2,a3));
}}}
else{
if(id<=195){
if(id<=194){
R=(r194to_run(((T194*)C),a1,a2,a3));
}
else{
R=(r195to_run(((T195*)C),a1,a2,a3));
}}
else{
if(id<=196){
R=(r196to_run(((T196*)C),a1,a2,a3));
}
else{
R=(r197to_run(((T197*)C),a1,a2,a3));
}}}}}
return R;
}

T0* X96runnable(T0*C){
T0* R;
{Tid id=((T0*)C)->id;
if(id<=189){
if(id<=185){
if(id<=136){
if(id<=99){
R=(r99runnable(((T99*)C)));
}
else{
R=(r136runnable(((T136*)C)));
}}
else{
if(id<=183){
R=(r183runnable(((T183*)C)));
}
else{
R=(r185runnable(((T185*)C)));
}}}
else{
if(id<=187){
if(id<=186){
R=(r186runnable(((T186*)C)));
}
else{
R=(r187runnable(((T187*)C)));
}}
else{
if(id<=188){
R=(r188runnable(((T188*)C)));
}
else{
R=(r189runnable(((T189*)C)));
}}}}
else{
if(id<=193){
if(id<=191){
if(id<=190){
R=(r190runnable(((T190*)C)));
}
else{
R=(r191runnable(((T191*)C)));
}}
else{
if(id<=192){
R=(r192runnable(((T192*)C)));
}
else{
R=(r193runnable(((T193*)C)));
}}}
else{
if(id<=195){
if(id<=194){
R=(r194runnable(((T194*)C)));
}
else{
R=(r195runnable(((T195*)C)));
}}
else{
if(id<=196){
R=(/*(IRF4.5runnable*/r196runnable_group(((T196*)C))/*)*/);
}
else{
R=(r197runnable(((T197*)C)));
}}}}}
return R;
}

T0* X26name(T0*C){
T0* R;
{Tid id=((T0*)C)->id;
if(id<=95){
if(id<=93){
if(id<=25){
R=((/*RF2*/(((T25*)C))->_name/*15*/));
}
else{
R=((/*RF2*/(((T93*)C))->_name/*5*/));
}}
else{
R=((/*RF2*/(((T95*)C))->_name/*15*/));
}}
else{
if(id<=98){
if(id<=97){
R=((/*RF2*/(((T97*)C))->_name/*5*/));
}
else{
R=((/*RF2*/(((T98*)C))->_name/*15*/));
}}
else{
R=((/*RF2*/(((T101*)C))->_name/*15*/));
}}}
return R;
}

void X26depend(T0*C){
{Tid id=((T0*)C)->id;
if(id<=95){
if(id<=93){
if(id<=25){
r25depend(((T25*)C));
}
else{
r93depend(((T93*)C));
}}
else{
r95depend(((T95*)C));
}}
else{
if(id<=98){
if(id<=97){
/*[IRF3.2depend*//*l73c14/prototype_head.e*/
X25depend(r97to_run());
/*]*/
}
else{
r98depend(((T98*)C));
}}
else{
r101depend(((T101*)C));
}}}
}

T0* X26proto_run(T0*C){
T0* R;
{Tid id=((T0*)C)->id;
if(id<=95){
if(id<=93){
if(id<=25){
R=(/*(IRF4.4proto_run*/((T0*)(((T25*)C)))/*)*/);
}
else{
R=(/*(IRF4.5proto_run*/r93to_run(((T93*)C))/*)*/);
}}
else{
R=(/*(IRF4.4proto_run*/((T0*)(((T95*)C)))/*)*/);
}}
else{
if(id<=98){
if(id<=97){
R=(/*(IRF4.5proto_run*/r97to_run()/*)*/);
}
else{
R=(/*(IRF4.4proto_run*/((T0*)(((T98*)C)))/*)*/);
}}
else{
R=(/*(IRF4.4proto_run*/((T0*)(((T101*)C)))/*)*/);
}}}
return R;
}

T0* X26position(T0*C){
T0* R;
{Tid id=((T0*)C)->id;
if(id<=95){
if(id<=93){
if(id<=25){
R=((/*RF2*/(((T25*)C))->_position/*1*/));
}
else{
R=(r93position(((T93*)C)));
}}
else{
R=((/*RF2*/(((T95*)C))->_position/*1*/));
}}
else{
if(id<=98){
if(id<=97){
R=(r97position());
}
else{
R=((/*RF2*/(((T98*)C))->_position/*1*/));
}}
else{
R=((/*RF2*/(((T101*)C))->_position/*1*/));
}}}
return R;
}

T2 X26index(T0*C){
T2 R;
{Tid id=((T0*)C)->id;
if(id<=95){
if(id<=93){
if(id<=25){
R=((/*RF2*/(((T25*)C))->_index/*11*/));
}
else{
R=((/*RF2*/(((T93*)C))->_index/*1*/));
}}
else{
R=((/*RF2*/(((T95*)C))->_index/*11*/));
}}
else{
if(id<=98){
if(id<=97){
R=((/*RF2*/(((T97*)C))->_index/*1*/));
}
else{
R=((/*RF2*/(((T98*)C))->_index/*11*/));
}}
else{
R=((/*RF2*/(((T101*)C))->_index/*11*/));
}}}
return R;
}

void X26set_index(T0*C,T2 a1){
{Tid id=((T0*)C)->id;
if(id<=95){
if(id<=93){
if(id<=25){
/*[IRF3.3set_index*/((((T25*)(((T25*)C))))->_index/*11*/)=(a1);
/*]*/
}
else{
/*[IRF3.3set_index*/((((T93*)(((T93*)C))))->_index/*1*/)=(a1);
/*]*/
}}
else{
/*[IRF3.3set_index*/((((T95*)(((T95*)C))))->_index/*11*/)=(a1);
/*]*/
}}
else{
if(id<=98){
if(id<=97){
/*[IRF3.3set_index*/((((T97*)(((T97*)C))))->_index/*1*/)=(a1);
/*]*/
}
else{
/*[IRF3.3set_index*/((((T98*)(((T98*)C))))->_index/*11*/)=(a1);
/*]*/
}}
else{
/*[IRF3.3set_index*/((((T101*)(((T101*)C))))->_index/*11*/)=(a1);
/*]*/
}}}
}

T0* X26intern_name(T0*C){
T0* R;
{Tid id=((T0*)C)->id;
if(id<=95){
if(id<=93){
if(id<=25){
R=((/*RF2*/(((T25*)C))->_intern_name/*5*/));
}
else{
R=((/*RF2*/(((T93*)C))->_intern_name/*9*/));
}}
else{
R=((/*RF2*/(((T95*)C))->_intern_name/*5*/));
}}
else{
if(id<=98){
if(id<=97){
R=((/*RF2*/(((T97*)C))->_intern_name/*9*/));
}
else{
R=((/*RF2*/(((T98*)C))->_intern_name/*5*/));
}}
else{
R=((/*RF2*/(((T101*)C))->_intern_name/*5*/));
}}}
return R;
}

T0* X214next(T0*C){
T0* R;
{Tid id=((T0*)C)->id;
if(id<=154){
R=((/*RF2*/(((T154*)C))->_next/*5*/));
}
else{
R=((/*RF2*/(((T175*)C))->_next/*5*/));
}}
return R;
}

T0* X214item(T0*C){
T0* R;
{Tid id=((T0*)C)->id;
if(id<=154){
R=((/*RF2*/(((T154*)C))->_item/*1*/));
}
else{
R=((/*RF2*/(((T175*)C))->_item/*1*/));
}}
return R;
}

T6 X78depend(T0*C){
T6 R;
{Tid id=((T0*)C)->id;
if(id<=157){
if(id<=131){
if(id<=108){
if(id<=106){
if(id<=75){
R=(T6)(r75depend(((T75*)C)));
}
else{
R=(T6)(r106depend(((T106*)C)));
}}
else{
R=(T6)(r108depend(((T108*)C)));
}}
else{
if(id<=114){
R=(T6)(r114depend(((T114*)C)));
}
else{
R=(T6)(r131depend(((T131*)C)));
}}}
else{
if(id<=135){
if(id<=132){
R=(T6)(r132depend(((T132*)C)));
}
else{
R=(T6)(r135depend(((T135*)C)));
}}
else{
if(id<=155){
R=(T6)(r155depend(((T155*)C)));
}
else{
R=(T6)(r157depend(((T157*)C)));
}}}}
else{
if(id<=198){
if(id<=171){
if(id<=163){
if(id<=159){
R=(T6)(r159depend(((T159*)C)));
}
else{
R=(T6)(r163depend(((T163*)C)));
}}
else{
R=(T6)(r171depend(((T171*)C)));
}}
else{
if(id<=176){
R=(T6)(r176depend(((T176*)C)));
}
else{
R=(T6)(r198depend(((T198*)C)));
}}}
else{
if(id<=208){
if(id<=204){
R=(T6)(r204depend(((T204*)C)));
}
else{
R=(T6)(r208depend(((T208*)C)));
}}
else{
if(id<=209){
R=(T6)(r209depend(((T209*)C)));
}
else{
R=(T6)(r213depend(((T213*)C)));
}}}}}
return R;
}

void X78remove(T0*C){
{Tid id=((T0*)C)->id;
if(id<=157){
if(id<=131){
if(id<=108){
if(id<=106){
if(id<=75){
r75remove(((T75*)C));
}
else{
r106remove(((T106*)C));
}}
else{
r108remove(((T108*)C));
}}
else{
if(id<=114){
/*[IRF3.1remove*//*]*/
}
else{
r131remove(((T131*)C));
}}}
else{
if(id<=135){
if(id<=132){
r132remove(((T132*)C));
}
else{
/*[IRF3.1remove*//*]*/
}}
else{
if(id<=155){
r155remove(((T155*)C));
}
else{
r157remove(((T157*)C));
}}}}
else{
if(id<=198){
if(id<=171){
if(id<=163){
if(id<=159){
/*[IRF3.1remove*//*]*/
}
else{
r163remove(((T163*)C));
}}
else{
r171remove(((T171*)C));
}}
else{
if(id<=176){
r176remove(((T176*)C));
}
else{
r198remove(((T198*)C));
}}}
else{
if(id<=208){
if(id<=204){
r204remove(((T204*)C));
}
else{
/*[IRF3.1remove*//*]*/
}}
else{
if(id<=209){
/*[IRF3.1remove*//*]*/
}
else{
r213remove(((T213*)C));
}}}}}
}

T0* X78get_type(T0*C){
T0* R;
{Tid id=((T0*)C)->id;
if(id<=157){
if(id<=131){
if(id<=108){
if(id<=106){
if(id<=75){
R=(r75get_type(((T75*)C)));
}
else{
R=(r106get_type(((T106*)C)));
}}
else{
R=(r108get_type(((T108*)C)));
}}
else{
if(id<=114){
R=(r114get_type(((T114*)C)));
}
else{
R=(r131get_type(((T131*)C)));
}}}
else{
if(id<=135){
if(id<=132){
R=(r132get_type(((T132*)C)));
}
else{
R=(r135get_type(((T135*)C)));
}}
else{
if(id<=155){
R=(r155get_type(((T155*)C)));
}
else{
R=(r157get_type(((T157*)C)));
}}}}
else{
if(id<=198){
if(id<=171){
if(id<=163){
if(id<=159){
R=(r159get_type(((T159*)C)));
}
else{
R=(r163get_type(((T163*)C)));
}}
else{
R=(r171get_type(((T171*)C)));
}}
else{
if(id<=176){
R=(r176get_type(((T176*)C)));
}
else{
R=(r198get_type(((T198*)C)));
}}}
else{
if(id<=208){
if(id<=204){
R=(r204get_type(((T204*)C)));
}
else{
R=(r208get_type(((T208*)C)));
}}
else{
if(id<=209){
R=(r209get_type(((T209*)C)));
}
else{
R=(r213get_type(((T213*)C)));
}}}}}
return R;
}

T0* X78search_block(T0*C){
T0* R;
{Tid id=((T0*)C)->id;
if(id<=157){
if(id<=131){
if(id<=108){
if(id<=106){
if(id<=75){
R=(r75search_block(((T75*)C)));
}
else{
R=(r106search_block(((T106*)C)));
}}
else{
R=(r108search_block(((T108*)C)));
}}
else{
if(id<=114){
R=(r114search_block(((T114*)C)));
}
else{
R=(r131search_block(((T131*)C)));
}}}
else{
if(id<=135){
if(id<=132){
R=(r132search_block(((T132*)C)));
}
else{
R=(r135search_block(((T135*)C)));
}}
else{
if(id<=155){
R=(r155search_block(((T155*)C)));
}
else{
R=(r157search_block(((T157*)C)));
}}}}
else{
if(id<=198){
if(id<=171){
if(id<=163){
if(id<=159){
R=(r159search_block(((T159*)C)));
}
else{
R=(r163search_block(((T163*)C)));
}}
else{
R=(r171search_block(((T171*)C)));
}}
else{
if(id<=176){
R=(r176search_block(((T176*)C)));
}
else{
R=(r198search_block(((T198*)C)));
}}}
else{
if(id<=208){
if(id<=204){
R=(r204search_block(((T204*)C)));
}
else{
R=(r208search_block(((T208*)C)));
}}
else{
if(id<=209){
R=(r209search_block(((T209*)C)));
}
else{
R=(r213search_block(((T213*)C)));
}}}}}
return R;
}

T2 X78static_type(T0*C){
T2 R;
{Tid id=((T0*)C)->id;
if(id<=157){
if(id<=131){
if(id<=108){
if(id<=106){
if(id<=75){
R=(r75static_type(((T75*)C)));
}
else{
R=(r106static_type(((T106*)C)));
}}
else{
R=(r108static_type(((T108*)C)));
}}
else{
if(id<=114){
R=((/*RF2*/(((T114*)C))->_static_type/*14*/));
}
else{
R=(r131static_type(((T131*)C)));
}}}
else{
if(id<=135){
if(id<=132){
R=(r132static_type(((T132*)C)));
}
else{
R=((/*RF2*/(((T135*)C))->_static_type/*14*/));
}}
else{
if(id<=155){
R=((/*RF2*/(((T155*)C))->_static_type/*13*/));
}
else{
R=((/*RF2*/(((T157*)C))->_static_type/*17*/));
}}}}
else{
if(id<=198){
if(id<=171){
if(id<=163){
if(id<=159){
R=((/*RF2*/(((T159*)C))->_static_type/*14*/));
}
else{
R=((/*RF2*/(((T163*)C))->_static_type/*17*/));
}}
else{
R=((/*RF2*/(((T171*)C))->_static_type/*21*/));
}}
else{
if(id<=176){
R=((/*RF2*/(((T176*)C))->_static_type/*18*/));
}
else{
R=((/*RF2*/(((T198*)C))->_static_type/*18*/));
}}}
else{
if(id<=208){
if(id<=204){
R=(r204static_type(((T204*)C)));
}
else{
R=((/*RF2*/(((T208*)C))->_static_type/*14*/));
}}
else{
if(id<=209){
R=((/*RF2*/(((T209*)C))->_static_type/*14*/));
}
else{
R=((/*RF2*/(((T213*)C))->_static_type/*17*/));
}}}}}
return R;
}

T0* X78execute(T0*C){
T0* R;
{Tid id=((T0*)C)->id;
if(id<=157){
if(id<=131){
if(id<=108){
if(id<=106){
if(id<=75){
R=(r75execute(((T75*)C)));
}
else{
R=(r106execute(((T106*)C)));
}}
else{
R=(r108execute(((T108*)C)));
}}
else{
if(id<=114){
R=(r114execute(((T114*)C)));
}
else{
R=(r131execute(((T131*)C)));
}}}
else{
if(id<=135){
if(id<=132){
R=(r132execute(((T132*)C)));
}
else{
R=(r135execute(((T135*)C)));
}}
else{
if(id<=155){
R=(r155execute(((T155*)C)));
}
else{
R=(r157execute(((T157*)C)));
}}}}
else{
if(id<=198){
if(id<=171){
if(id<=163){
if(id<=159){
R=(r159execute(((T159*)C)));
}
else{
R=(r163execute(((T163*)C)));
}}
else{
R=(r171execute(((T171*)C)));
}}
else{
if(id<=176){
R=(r176execute(((T176*)C)));
}
else{
R=(r198execute(((T198*)C)));
}}}
else{
if(id<=208){
if(id<=204){
R=(r204execute(((T204*)C)));
}
else{
R=(r208execute(((T208*)C)));
}}
else{
if(id<=209){
R=(r209execute(((T209*)C)));
}
else{
R=(r213execute(((T213*)C)));
}}}}}
return R;
}

T0* X13twin(T0*C){
T0* R;
{Tid id=((T0*)C)->id;
if(id<=155){
if(id<=131){
if(id<=106){
if(id<=56){
if(id<=41){
R=(r41twin(((T41*)C)));
}
else{
R=(r56twin(((T56*)C)));
}}
else{
if(id<=75){
R=(r75twin(((T75*)C)));
}
else{
R=(r106twin(((T106*)C)));
}}}
else{
if(id<=114){
if(id<=108){
R=(r108twin(((T108*)C)));
}
else{
R=(r114twin(((T114*)C)));
}}
else{
if(id<=129){
R=(r129twin(((T129*)C)));
}
else{
R=(r131twin(((T131*)C)));
}}}}
else{
if(id<=147){
if(id<=134){
if(id<=132){
R=(r132twin(((T132*)C)));
}
else{
R=(r134twin(((T134*)C)));
}}
else{
if(id<=135){
R=(r135twin(((T135*)C)));
}
else{
R=(r147twin(((T147*)C)));
}}}
else{
if(id<=151){
if(id<=148){
R=(r148twin(((T148*)C)));
}
else{
R=(r151twin(((T151*)C)));
}}
else{
R=(r155twin(((T155*)C)));
}}}}
else{
if(id<=198){
if(id<=171){
if(id<=159){
if(id<=157){
R=(r157twin(((T157*)C)));
}
else{
R=(r159twin(((T159*)C)));
}}
else{
if(id<=163){
R=(r163twin(((T163*)C)));
}
else{
R=(r171twin(((T171*)C)));
}}}
else{
if(id<=173){
if(id<=172){
R=(r172twin(((T172*)C)));
}
else{
R=(r173twin(((T173*)C)));
}}
else{
if(id<=176){
R=(r176twin(((T176*)C)));
}
else{
R=(r198twin(((T198*)C)));
}}}}
else{
if(id<=204){
if(id<=200){
if(id<=199){
R=(r199twin(((T199*)C)));
}
else{
R=(r200twin(((T200*)C)));
}}
else{
if(id<=201){
R=(r201twin(((T201*)C)));
}
else{
R=(r204twin(((T204*)C)));
}}}
else{
if(id<=209){
if(id<=208){
R=(r208twin(((T208*)C)));
}
else{
R=(r209twin(((T209*)C)));
}}
else{
R=(r213twin(((T213*)C)));
}}}}}
return R;
}

T0* X25get_slot_full(T0*C,T0* a1){
T0* R;
{Tid id=((T0*)C)->id;
if(id<=95){
if(id<=25){
R=(r25get_slot_full(((T25*)C),a1));
}
else{
R=(r95get_slot_full(((T95*)C),a1));
}}
else{
if(id<=98){
R=(r98get_slot_full(((T98*)C),a1));
}
else{
R=(r101get_slot_full(((T101*)C),a1));
}}}
return R;
}

void X25depend(T0*C){
{Tid id=((T0*)C)->id;
if(id<=95){
if(id<=25){
r25depend(((T25*)C));
}
else{
r95depend(((T95*)C));
}}
else{
if(id<=98){
r98depend(((T98*)C));
}
else{
r101depend(((T101*)C));
}}}
}

T6 X25is_sub_type(T0*C,T2 a1){
T6 R;
{Tid id=((T0*)C)->id;
if(id<=95){
if(id<=25){
R=(T6)(r25is_sub_type(((T25*)C),a1));
}
else{
R=(T6)(r95is_sub_type(((T95*)C),a1));
}}
else{
if(id<=98){
R=(T6)(r98is_sub_type(((T98*)C),a1));
}
else{
R=(T6)(/*(IRF4.2is_sub_type*/(1)/*)*/);
}}}
return R;
}

void X25set_type_collector(T0*C,T0* a1){
{Tid id=((T0*)C)->id;
if(id<=95){
if(id<=25){
r25set_type_collector(((T25*)C),a1);
}
else{
r95set_type_collector(((T95*)C),a1);
}}
else{
if(id<=98){
r98set_type_collector(((T98*)C),a1);
}
else{
r101set_type_collector(((T101*)C),a1);
}}}
}

void X25genere(T0*C){
{Tid id=((T0*)C)->id;
if(id<=95){
if(id<=25){
r25genere(((T25*)C));
}
else{
/*[IRF3.2genere*//*l53c19/context.e*/
r7append((T7*)(oBC13output_type),se_ms(14,"// ___CONTEXT\n"));
/*l54c19/context.e*/
r7append((T7*)(oBC13output_type),se_ms(101,"struct ___CONTEXT \173""\n  unsigned short proto; \n  unsigned short line; \n  struct ___CONTEXT *back; \n\175""; \n"));
/*]*/
}}
else{
if(id<=98){
r98genere(((T98*)C));
}
else{
/*[IRF3.2genere*//*l53c21/null.e*/
r7append((T7*)(oBC13output_global),se_ms(8,"// NULL\n"));
/*l54c21/null.e*/
r7append((T7*)(oBC13output_global),se_ms(45,"#ifndef NULL\n#define NULL ((void *)0)\n#endif\n"));
/*]*/
}}}
}

void X25parse(T0*C){
{Tid id=((T0*)C)->id;
if(id<=95){
if(id<=25){
r25parse(((T25*)C));
}
else{
r95parse(((T95*)C));
}}
else{
if(id<=98){
r98parse(((T98*)C));
}
else{
r101parse(((T101*)C));
}}}
}

T2 X25sub_check_cycle(T0*C){
T2 R;
{Tid id=((T0*)C)->id;
if(id<=95){
if(id<=25){
R=(r25sub_check_cycle(((T25*)C)));
}
else{
R=(r95sub_check_cycle(((T95*)C)));
}}
else{
if(id<=98){
R=(r98sub_check_cycle(((T98*)C)));
}
else{
R=(r101sub_check_cycle(((T101*)C)));
}}}
return R;
}

T0* X25new_position(T0*C,T2 a1){
T0* R;
{Tid id=((T0*)C)->id;
if(id<=95){
if(id<=25){
R=(r25new_position(((T25*)C),a1));
}
else{
R=(/*(IRF4.3new_position*/(/*RF2*/(((T95*)C))->_position/*1*/)/*)*/);
}}
else{
if(id<=98){
R=(/*(IRF4.3new_position*/(/*RF2*/(((T98*)C))->_position/*1*/)/*)*/);
}
else{
R=(/*(IRF4.3new_position*/(/*RF2*/(((T101*)C))->_position/*1*/)/*)*/);
}}}
return R;
}

void X79display(T0*C,T0* a1){
{Tid id=((T0*)C)->id;
if(id<=157){
if(id<=132){
if(id<=114){
if(id<=106){
if(id<=75){
r75display(((T75*)C),a1);
}
else{
r106display(((T106*)C),a1);
}}
else{
if(id<=108){
r108display(((T108*)C),a1);
}
else{
r114display(((T114*)C),a1);
}}}
else{
if(id<=131){
if(id<=129){
r129display(((T129*)C),a1);
}
else{
r131display(((T131*)C),a1);
}}
else{
r132display(((T132*)C),a1);
}}}
else{
if(id<=148){
if(id<=135){
if(id<=134){
r134display(((T134*)C),a1);
}
else{
r135display(((T135*)C),a1);
}}
else{
if(id<=147){
r147display(((T147*)C),a1);
}
else{
r148display(((T148*)C),a1);
}}}
else{
if(id<=155){
if(id<=151){
r151display(((T151*)C),a1);
}
else{
r155display(((T155*)C),a1);
}}
else{
r157display(((T157*)C),a1);
}}}}
else{
if(id<=198){
if(id<=172){
if(id<=163){
if(id<=159){
r159display(((T159*)C),a1);
}
else{
r163display(((T163*)C),a1);
}}
else{
if(id<=171){
r171display(((T171*)C),a1);
}
else{
r172display(((T172*)C),a1);
}}}
else{
if(id<=176){
if(id<=173){
r173display(((T173*)C),a1);
}
else{
r176display(((T176*)C),a1);
}}
else{
r198display(((T198*)C),a1);
}}}
else{
if(id<=204){
if(id<=200){
if(id<=199){
r199display(((T199*)C),a1);
}
else{
r200display(((T200*)C),a1);
}}
else{
if(id<=201){
r201display(((T201*)C),a1);
}
else{
r204display(((T204*)C),a1);
}}}
else{
if(id<=209){
if(id<=208){
r208display(((T208*)C),a1);
}
else{
r209display(((T209*)C),a1);
}}
else{
r213display(((T213*)C),a1);
}}}}}
}

T6 X79depend(T0*C){
T6 R;
{Tid id=((T0*)C)->id;
if(id<=157){
if(id<=132){
if(id<=114){
if(id<=106){
if(id<=75){
R=(T6)(r75depend(((T75*)C)));
}
else{
R=(T6)(r106depend(((T106*)C)));
}}
else{
if(id<=108){
R=(T6)(r108depend(((T108*)C)));
}
else{
R=(T6)(r114depend(((T114*)C)));
}}}
else{
if(id<=131){
if(id<=129){
R=(T6)(r129depend(((T129*)C)));
}
else{
R=(T6)(r131depend(((T131*)C)));
}}
else{
R=(T6)(r132depend(((T132*)C)));
}}}
else{
if(id<=148){
if(id<=135){
if(id<=134){
R=(T6)(r134depend(((T134*)C)));
}
else{
R=(T6)(r135depend(((T135*)C)));
}}
else{
if(id<=147){
R=(T6)(r147depend(((T147*)C)));
}
else{
R=(T6)(r148depend(((T148*)C)));
}}}
else{
if(id<=155){
if(id<=151){
R=(T6)(r151depend(((T151*)C)));
}
else{
R=(T6)(r155depend(((T155*)C)));
}}
else{
R=(T6)(r157depend(((T157*)C)));
}}}}
else{
if(id<=198){
if(id<=172){
if(id<=163){
if(id<=159){
R=(T6)(r159depend(((T159*)C)));
}
else{
R=(T6)(r163depend(((T163*)C)));
}}
else{
if(id<=171){
R=(T6)(r171depend(((T171*)C)));
}
else{
R=(T6)(r172depend(((T172*)C)));
}}}
else{
if(id<=176){
if(id<=173){
R=(T6)(r173depend(((T173*)C)));
}
else{
R=(T6)(r176depend(((T176*)C)));
}}
else{
R=(T6)(r198depend(((T198*)C)));
}}}
else{
if(id<=204){
if(id<=200){
if(id<=199){
R=(T6)(r199depend(((T199*)C)));
}
else{
R=(T6)(r200depend(((T200*)C)));
}}
else{
if(id<=201){
R=(T6)(r201depend(((T201*)C)));
}
else{
R=(T6)(r204depend(((T204*)C)));
}}}
else{
if(id<=209){
if(id<=208){
R=(T6)(r208depend(((T208*)C)));
}
else{
R=(T6)(r209depend(((T209*)C)));
}}
else{
R=(T6)(r213depend(((T213*)C)));
}}}}}
return R;
}

T0* X79my_copy(T0*C){
T0* R;
{Tid id=((T0*)C)->id;
if(id<=157){
if(id<=132){
if(id<=114){
if(id<=106){
if(id<=75){
R=(r75my_copy(((T75*)C)));
}
else{
R=(r106my_copy(((T106*)C)));
}}
else{
if(id<=108){
R=(r108my_copy(((T108*)C)));
}
else{
R=(r114my_copy(((T114*)C)));
}}}
else{
if(id<=131){
if(id<=129){
R=(r129my_copy(((T129*)C)));
}
else{
R=(r131my_copy(((T131*)C)));
}}
else{
R=(r132my_copy(((T132*)C)));
}}}
else{
if(id<=148){
if(id<=135){
if(id<=134){
R=(r134my_copy(((T134*)C)));
}
else{
R=(r135my_copy(((T135*)C)));
}}
else{
if(id<=147){
R=(r147my_copy(((T147*)C)));
}
else{
R=(r148my_copy(((T148*)C)));
}}}
else{
if(id<=155){
if(id<=151){
R=(r151my_copy(((T151*)C)));
}
else{
R=(r155my_copy(((T155*)C)));
}}
else{
R=(r157my_copy(((T157*)C)));
}}}}
else{
if(id<=198){
if(id<=172){
if(id<=163){
if(id<=159){
R=(r159my_copy(((T159*)C)));
}
else{
R=(r163my_copy(((T163*)C)));
}}
else{
if(id<=171){
R=(r171my_copy(((T171*)C)));
}
else{
R=(r172my_copy(((T172*)C)));
}}}
else{
if(id<=176){
if(id<=173){
R=(r173my_copy(((T173*)C)));
}
else{
R=(r176my_copy(((T176*)C)));
}}
else{
R=(r198my_copy(((T198*)C)));
}}}
else{
if(id<=204){
if(id<=200){
if(id<=199){
R=(r199my_copy(((T199*)C)));
}
else{
R=(r200my_copy(((T200*)C)));
}}
else{
if(id<=201){
R=(r201my_copy(((T201*)C)));
}
else{
R=(r204my_copy(((T204*)C)));
}}}
else{
if(id<=209){
if(id<=208){
R=(r208my_copy(((T208*)C)));
}
else{
R=(r209my_copy(((T209*)C)));
}}
else{
R=(r213my_copy(((T213*)C)));
}}}}}
return R;
}

T6 X79is_copy(T0*C){
T6 R;
{Tid id=((T0*)C)->id;
if(id<=157){
if(id<=132){
if(id<=114){
if(id<=106){
if(id<=75){
R=(T6)(/*(IRF4.2is_copy*/(0)/*)*/);
}
else{
R=(T6)(/*(IRF4.2is_copy*/(0)/*)*/);
}}
else{
if(id<=108){
R=(T6)(/*(IRF4.2is_copy*/(0)/*)*/);
}
else{
R=(T6)(1);
}}}
else{
if(id<=131){
if(id<=129){
R=(T6)(/*(IRF4.2is_copy*/(0)/*)*/);
}
else{
R=(T6)(/*(IRF4.2is_copy*/(0)/*)*/);
}}
else{
R=(T6)(1);
}}}
else{
if(id<=148){
if(id<=135){
if(id<=134){
R=(T6)(/*(IRF4.2is_copy*/(0)/*)*/);
}
else{
R=(T6)(1);
}}
else{
if(id<=147){
R=(T6)(/*(IRF4.2is_copy*/(0)/*)*/);
}
else{
R=(T6)(/*(IRF4.2is_copy*/(0)/*)*/);
}}}
else{
if(id<=155){
if(id<=151){
R=(T6)(/*(IRF4.2is_copy*/(0)/*)*/);
}
else{
R=(T6)(/*(IRF4.2is_copy*/(0)/*)*/);
}}
else{
R=(T6)(/*(IRF4.2is_copy*/(0)/*)*/);
}}}}
else{
if(id<=198){
if(id<=172){
if(id<=163){
if(id<=159){
R=(T6)(1);
}
else{
R=(T6)(/*(IRF4.2is_copy*/(0)/*)*/);
}}
else{
if(id<=171){
R=(T6)(/*(IRF4.2is_copy*/(0)/*)*/);
}
else{
R=(T6)(/*(IRF4.2is_copy*/(0)/*)*/);
}}}
else{
if(id<=176){
if(id<=173){
R=(T6)(/*(IRF4.2is_copy*/(0)/*)*/);
}
else{
R=(T6)(/*(IRF4.2is_copy*/(0)/*)*/);
}}
else{
R=(T6)(r198is_copy(((T198*)C)));
}}}
else{
if(id<=204){
if(id<=200){
if(id<=199){
R=(T6)(/*(IRF4.2is_copy*/(0)/*)*/);
}
else{
R=(T6)(/*(IRF4.2is_copy*/(0)/*)*/);
}}
else{
if(id<=201){
R=(T6)(/*(IRF4.2is_copy*/(0)/*)*/);
}
else{
R=(T6)(/*(IRF4.2is_copy*/(0)/*)*/);
}}}
else{
if(id<=209){
if(id<=208){
R=(T6)(1);
}
else{
R=(T6)(1);
}}
else{
R=(T6)(/*(IRF4.2is_copy*/(0)/*)*/);
}}}}}
return R;
}

void X79remove(T0*C){
{Tid id=((T0*)C)->id;
if(id<=157){
if(id<=132){
if(id<=114){
if(id<=106){
if(id<=75){
r75remove(((T75*)C));
}
else{
r106remove(((T106*)C));
}}
else{
if(id<=108){
r108remove(((T108*)C));
}
else{
/*[IRF3.1remove*//*]*/
}}}
else{
if(id<=131){
if(id<=129){
r129remove(((T129*)C));
}
else{
r131remove(((T131*)C));
}}
else{
r132remove(((T132*)C));
}}}
else{
if(id<=148){
if(id<=135){
if(id<=134){
r134remove(((T134*)C));
}
else{
/*[IRF3.1remove*//*]*/
}}
else{
if(id<=147){
r147remove(((T147*)C));
}
else{
r148remove(((T148*)C));
}}}
else{
if(id<=155){
if(id<=151){
/*[IRF3.5remove*/r108remove(((T108*)((/*RF2*/(((T151*)C))->_list/*21*/))));
/*]*/
}
else{
r155remove(((T155*)C));
}}
else{
r157remove(((T157*)C));
}}}}
else{
if(id<=198){
if(id<=172){
if(id<=163){
if(id<=159){
/*[IRF3.1remove*//*]*/
}
else{
r163remove(((T163*)C));
}}
else{
if(id<=171){
r171remove(((T171*)C));
}
else{
r172remove(((T172*)C));
}}}
else{
if(id<=176){
if(id<=173){
/*[IRF3.5remove*/r108remove(((T108*)((/*RF2*/(((T173*)C))->_list/*21*/))));
/*]*/
}
else{
r176remove(((T176*)C));
}}
else{
r198remove(((T198*)C));
}}}
else{
if(id<=204){
if(id<=200){
if(id<=199){
r199remove(((T199*)C));
}
else{
r200remove(((T200*)C));
}}
else{
if(id<=201){
r201remove(((T201*)C));
}
else{
r204remove(((T204*)C));
}}}
else{
if(id<=209){
if(id<=208){
/*[IRF3.1remove*//*]*/
}
else{
/*[IRF3.1remove*//*]*/
}}
else{
r213remove(((T213*)C));
}}}}}
}

void X79genere(T0*C,T0* a1){
{Tid id=((T0*)C)->id;
if(id<=157){
if(id<=132){
if(id<=114){
if(id<=106){
if(id<=75){
r75genere(((T75*)C),a1);
}
else{
r106genere(((T106*)C),a1);
}}
else{
if(id<=108){
r108genere(((T108*)C),a1);
}
else{
r114genere(((T114*)C),a1);
}}}
else{
if(id<=131){
if(id<=129){
r129genere(((T129*)C),a1);
}
else{
r131genere(((T131*)C),a1);
}}
else{
r132genere(((T132*)C),a1);
}}}
else{
if(id<=148){
if(id<=135){
if(id<=134){
r134genere(((T134*)C),a1);
}
else{
/*[IRF3.6genere*/{T0* b1=a1;
/*l89c14/block.e*/
r7append(((T7*)b1),se_ms(7,"\173""BLOCK\175"""));
}/*]*/
}}
else{
if(id<=147){
r147genere(((T147*)C),a1);
}
else{
r148genere(((T148*)C),a1);
}}}
else{
if(id<=155){
if(id<=151){
r151genere(((T151*)C),a1);
}
else{
r155genere(((T155*)C),a1);
}}
else{
r157genere(((T157*)C),a1);
}}}}
else{
if(id<=198){
if(id<=172){
if(id<=163){
if(id<=159){
r159genere(((T159*)C),a1);
}
else{
r163genere(((T163*)C),a1);
}}
else{
if(id<=171){
r171genere(((T171*)C),a1);
}
else{
r172genere(((T172*)C),a1);
}}}
else{
if(id<=176){
if(id<=173){
r173genere(((T173*)C),a1);
}
else{
r176genere(((T176*)C),a1);
}}
else{
r198genere(((T198*)C),a1);
}}}
else{
if(id<=204){
if(id<=200){
if(id<=199){
r199genere(((T199*)C),a1);
}
else{
r200genere(((T200*)C),a1);
}}
else{
if(id<=201){
r201genere(((T201*)C),a1);
}
else{
r204genere(((T204*)C),a1);
}}}
else{
if(id<=209){
if(id<=208){
r208genere(((T208*)C),a1);
}
else{
r209genere(((T209*)C),a1);
}}
else{
r213genere(((T213*)C),a1);
}}}}}
}

T0* X79execute(T0*C){
T0* R;
{Tid id=((T0*)C)->id;
if(id<=157){
if(id<=132){
if(id<=114){
if(id<=106){
if(id<=75){
R=(r75execute(((T75*)C)));
}
else{
R=(r106execute(((T106*)C)));
}}
else{
if(id<=108){
R=(r108execute(((T108*)C)));
}
else{
R=(r114execute(((T114*)C)));
}}}
else{
if(id<=131){
if(id<=129){
R=(r129execute(((T129*)C)));
}
else{
R=(r131execute(((T131*)C)));
}}
else{
R=(r132execute(((T132*)C)));
}}}
else{
if(id<=148){
if(id<=135){
if(id<=134){
R=(r134execute(((T134*)C)));
}
else{
R=(r135execute(((T135*)C)));
}}
else{
if(id<=147){
R=(r147execute(((T147*)C)));
}
else{
R=(r148execute(((T148*)C)));
}}}
else{
if(id<=155){
if(id<=151){
R=(r151execute(((T151*)C)));
}
else{
R=(r155execute(((T155*)C)));
}}
else{
R=(r157execute(((T157*)C)));
}}}}
else{
if(id<=198){
if(id<=172){
if(id<=163){
if(id<=159){
R=(r159execute(((T159*)C)));
}
else{
R=(r163execute(((T163*)C)));
}}
else{
if(id<=171){
R=(r171execute(((T171*)C)));
}
else{
R=(r172execute(((T172*)C)));
}}}
else{
if(id<=176){
if(id<=173){
R=(r173execute(((T173*)C)));
}
else{
R=(r176execute(((T176*)C)));
}}
else{
R=(r198execute(((T198*)C)));
}}}
else{
if(id<=204){
if(id<=200){
if(id<=199){
R=(r199execute(((T199*)C)));
}
else{
R=(r200execute(((T200*)C)));
}}
else{
if(id<=201){
R=(r201execute(((T201*)C)));
}
else{
R=(r204execute(((T204*)C)));
}}}
else{
if(id<=209){
if(id<=208){
R=(r208execute(((T208*)C)));
}
else{
R=(r209execute(((T209*)C)));
}}
else{
R=(r213execute(((T213*)C)));
}}}}}
return R;
}

T0* X153item(T0*C,T2 a1){
T0* R;
{Tid id=((T0*)C)->id;
if(id<=152){
R=(r152item(((T152*)C),a1));
}
else{
R=(r174item(((T174*)C),a1));
}}
return R;
}

T0* X130build_case_type(T0*C,T0* a1){
T0* R;
{Tid id=((T0*)C)->id;
if(id<=199){
if(id<=129){
R=(r129build_case_type(((T129*)C),a1));
}
else{
R=(r199build_case_type(((T199*)C),a1));
}}
else{
if(id<=200){
R=(r200build_case_type(((T200*)C),a1));
}
else{
R=(r201build_case_type(((T201*)C),a1));
}}}
return R;
}

T0* X130build_case_body(T0*C,T0* a1){
T0* R;
{Tid id=((T0*)C)->id;
if(id<=199){
if(id<=129){
R=(r129build_case_body(((T129*)C),a1));
}
else{
R=(r199build_case_body(((T199*)C),a1));
}}
else{
if(id<=200){
R=(r200build_case_body(((T200*)C),a1));
}
else{
R=(r201build_case_body(((T201*)C),a1));
}}}
return R;
}

T6 X82is_equal(T0*C,T0* a1){
T6 R;
{Tid id=((T0*)C)->id;
if(id<=131){
if(id<=106){
R=(T6)(r106is_equal(((T106*)C),a1));
}
else{
R=(T6)(r131is_equal(((T131*)C),a1));
}}
else{
if(id<=163){
R=(T6)(r163is_equal(((T163*)C),a1));
}
else{
R=(T6)(r171is_equal(((T171*)C),a1));
}}}
return R;
}

void X82sub_get_type(T0*C,T0* a1){
{Tid id=((T0*)C)->id;
if(id<=131){
if(id<=106){
r106sub_get_type(((T106*)C),a1);
}
else{
r131sub_get_type(((T131*)C),a1);
}}
else{
if(id<=163){
r163sub_get_type(((T163*)C),a1);
}
else{
r171sub_get_type(((T171*)C),a1);
}}}
}

T0* X82search_block(T0*C){
T0* R;
{Tid id=((T0*)C)->id;
if(id<=131){
if(id<=106){
R=(r106search_block(((T106*)C)));
}
else{
R=(r131search_block(((T131*)C)));
}}
else{
if(id<=163){
R=(r163search_block(((T163*)C)));
}
else{
R=(r171search_block(((T171*)C)));
}}}
return R;
}

T2 X82object_id(T0*C){
T2 R;
{Tid id=((T0*)C)->id;
if(id<=131){
if(id<=106){
R=(r106object_id(((T106*)C)));
}
else{
R=(r131object_id(((T131*)C)));
}}
else{
if(id<=163){
R=(r163object_id(((T163*)C)));
}
else{
R=(r171object_id(((T171*)C)));
}}}
return R;
}

void X53display(T0*C,T0* a1){
{Tid id=((T0*)C)->id;
if(id<=52){
r52display(((T52*)C),a1);
}
else{
r113display(((T113*)C),a1);
}}
}

T6 X53is_self(T0*C){
T6 R;
{Tid id=((T0*)C)->id;
if(id<=52){
R=(T6)(/*(IRF4.7is_self*/((/*RF2*/(((T52*)C))->_type/*19*/))==(INT8_C(4))/*)*/);
}
else{
R=(T6)((/*RF2*/(((T113*)C))->_is_self/*49*/));
}}
return R;
}

void X53write(T0*C,T0* a1){
{Tid id=((T0*)C)->id;
if(id<=52){
r52write(((T52*)C),a1);
}
else{
r113write(((T113*)C),a1);
}}
}

T0* X53get_type(T0*C){
T0* R;
{Tid id=((T0*)C)->id;
if(id<=52){
R=(r52get_type(((T52*)C)));
}
else{
R=(r113get_type(((T113*)C)));
}}
return R;
}

void X53link(T0*C,T0* a1){
{Tid id=((T0*)C)->id;
if(id<=52){
r52link(((T52*)C),a1);
}
else{
r113link(((T113*)C),a1);
}}
}

T0* X166integer_divide_small_integer(T0*C,T0* a1){
T0* R;
{Tid id=((T0*)C)->id;
if(id<=168){
if(id<=165){
R=(r165integer_divide_small_integer(((T165*)C),a1));
}
else{
R=(r168integer_divide_small_integer(((T168*)C),a1));
}}
else{
R=(r170integer_divide_small_integer(((T170*)C),a1));
}}
return R;
}

T0* X166_ix_4747(T0*C,T0* a1){
T0* R;
{Tid id=((T0*)C)->id;
if(id<=168){
if(id<=165){
R=(r165_ix_4747(((T165*)C),a1));
}
else{
R=(r168_ix_4747(((T168*)C),a1));
}}
else{
R=(r170_ix_4747(((T170*)C),a1));
}}
return R;
}

T0* X166remainder_of_divide_large_positive_integer(T0*C,T0* a1){
T0* R;
{Tid id=((T0*)C)->id;
if(id<=168){
if(id<=165){
R=(r165remainder_of_divide_large_positive_integer(((T165*)C),a1));
}
else{
R=(r168remainder_of_divide_large_positive_integer(((T168*)C),a1));
}}
else{
R=(r170remainder_of_divide_large_positive_integer(((T170*)C),a1));
}}
return R;
}

T0* X166multiply_with_large_negative_integer(T0*C,T0* a1){
T0* R;
{Tid id=((T0*)C)->id;
if(id<=168){
if(id<=165){
R=(r165multiply_with_large_negative_integer(((T165*)C),a1));
}
else{
R=(r168multiply_with_large_negative_integer(((T168*)C),a1));
}}
else{
R=(r170multiply_with_large_negative_integer(((T170*)C),a1));
}}
return R;
}

T0* X166gcd(T0*C,T0* a1){
T0* R;
{Tid id=((T0*)C)->id;
if(id<=168){
if(id<=165){
R=(r165gcd(((T165*)C),a1));
}
else{
R=(r168gcd(((T168*)C),a1));
}}
else{
R=(r170gcd(((T170*)C),a1));
}}
return R;
}

T6 X166is_small_integer(T0*C){
T6 R;
{Tid id=((T0*)C)->id;
if(id<=168){
if(id<=165){
R=(T6)(r165is_small_integer(((T165*)C)));
}
else{
R=(T6)(r168is_small_integer(((T168*)C)));
}}
else{
R=(T6)(r170is_small_integer(((T170*)C)));
}}
return R;
}

T6 X166_ix_6061(T0*C,T0* a1){
T6 R;
{Tid id=((T0*)C)->id;
if(id<=168){
if(id<=165){
R=(T6)(r165_ix_6061(((T165*)C),a1));
}
else{
R=(T6)(r168_ix_6061(((T168*)C),a1));
}}
else{
R=(T6)(r170_ix_6061(((T170*)C),a1));
}}
return R;
}

T0* X166_px_45(T0*C){
T0* R;
{Tid id=((T0*)C)->id;
if(id<=168){
if(id<=165){
R=(r165_px_45(((T165*)C)));
}
else{
R=(r168_px_45(((T168*)C)));
}}
else{
R=(r170_px_45(((T170*)C)));
}}
return R;
}

T0* X166integer_divide_large_positive_integer(T0*C,T0* a1){
T0* R;
{Tid id=((T0*)C)->id;
if(id<=168){
if(id<=165){
R=(r165integer_divide_large_positive_integer(((T165*)C),a1));
}
else{
R=(r168integer_divide_large_positive_integer(((T168*)C),a1));
}}
else{
R=(r170integer_divide_large_positive_integer(((T170*)C),a1));
}}
return R;
}

void X166append_in(T0*C,T0* a1){
{Tid id=((T0*)C)->id;
if(id<=168){
if(id<=165){
/*[IRF3.6append_in*/{T165* C1=((T165*)C);
T0* b1=a1;
/*l72c7/small_integer.e*/
r7append(((T7*)b1),r2to_string((/*RF2*/(C1)->_value/*1*/)));
}/*]*/
}
else{
r168append_in(((T168*)C),a1);
}}
else{
r170append_in(((T170*)C),a1);
}}
}

T2 X166to_integer(T0*C){
T2 R;
{Tid id=((T0*)C)->id;
if(id<=168){
if(id<=165){
R=(/*(IRF4.3to_integer*/(/*RF2*/(((T165*)C))->_value/*1*/)/*)*/);
}
else{
R=(r168to_integer(((T168*)C)));
}}
else{
R=(r170to_integer(((T170*)C)));
}}
return R;
}

T0* X166remainder_of_divide_large_negative_integer(T0*C,T0* a1){
T0* R;
{Tid id=((T0*)C)->id;
if(id<=168){
if(id<=165){
R=(r165remainder_of_divide_large_negative_integer(((T165*)C),a1));
}
else{
R=(r168remainder_of_divide_large_negative_integer(((T168*)C),a1));
}}
else{
R=(r170remainder_of_divide_large_negative_integer(((T170*)C),a1));
}}
return R;
}

T6 X166is_negative(T0*C){
T6 R;
{Tid id=((T0*)C)->id;
if(id<=168){
if(id<=165){
R=(T6)(/*(IRF4.6is_negative*/(int32_t)(((/*RF2*/(((T165*)C))->_value/*1*/))<(INT8_C(0)))/*)*/);
}
else{
R=(T6)(1);
}}
else{
R=(T6)(0);
}}
return R;
}

T0* X166abs(T0*C){
T0* R;
{Tid id=((T0*)C)->id;
if(id<=168){
if(id<=165){
R=(r165abs(((T165*)C)));
}
else{
R=(/*(IRF4.5abs*/r168_px_45(((T168*)C))/*)*/);
}}
else{
R=(/*(IRF4.4abs*/((T0*)(((T170*)C)))/*)*/);
}}
return R;
}

T6 X166_ix_6261(T0*C,T0* a1){
T6 R;
{Tid id=((T0*)C)->id;
if(id<=168){
if(id<=165){
R=(T6)(r165_ix_6261(((T165*)C),a1));
}
else{
R=(T6)(r168_ix_6261(((T168*)C),a1));
}}
else{
R=(T6)(r170_ix_6261(((T170*)C),a1));
}}
return R;
}

T0* X166multiply_with_large_positive_integer(T0*C,T0* a1){
T0* R;
{Tid id=((T0*)C)->id;
if(id<=168){
if(id<=165){
R=(r165multiply_with_large_positive_integer(((T165*)C),a1));
}
else{
R=(r168multiply_with_large_positive_integer(((T168*)C),a1));
}}
else{
R=(r170multiply_with_large_positive_integer(((T170*)C),a1));
}}
return R;
}

T6 X166is_one(T0*C){
T6 R;
{Tid id=((T0*)C)->id;
if(id<=168){
if(id<=165){
R=(T6)(/*(IRF4.7is_one*/((/*RF2*/(((T165*)C))->_value/*1*/))==(INT8_C(1))/*)*/);
}
else{
R=(T6)(0);
}}
else{
R=(T6)(0);
}}
return R;
}

T0* X166_ix_42(T0*C,T0* a1){
T0* R;
{Tid id=((T0*)C)->id;
if(id<=168){
if(id<=165){
R=(r165_ix_42(((T165*)C),a1));
}
else{
R=(r168_ix_42(((T168*)C),a1));
}}
else{
R=(r170_ix_42(((T170*)C),a1));
}}
return R;
}

T0* X166integer_divide_large_negative_integer(T0*C,T0* a1){
T0* R;
{Tid id=((T0*)C)->id;
if(id<=168){
if(id<=165){
R=(r165integer_divide_large_negative_integer(((T165*)C),a1));
}
else{
R=(r168integer_divide_large_negative_integer(((T168*)C),a1));
}}
else{
R=(r170integer_divide_large_negative_integer(((T170*)C),a1));
}}
return R;
}

T6 X166_ix_60(T0*C,T0* a1){
T6 R;
{Tid id=((T0*)C)->id;
if(id<=168){
if(id<=165){
R=(T6)(r165_ix_60(((T165*)C),a1));
}
else{
R=(T6)(r168_ix_60(((T168*)C),a1));
}}
else{
R=(T6)(r170_ix_60(((T170*)C),a1));
}}
return R;
}

T6 X166_ix_62(T0*C,T0* a1){
T6 R;
{Tid id=((T0*)C)->id;
if(id<=168){
if(id<=165){
R=(T6)(r165_ix_62(((T165*)C),a1));
}
else{
R=(T6)(r168_ix_62(((T168*)C),a1));
}}
else{
R=(T6)(r170_ix_62(((T170*)C),a1));
}}
return R;
}

T0* X166_ix_6442(T0*C,T2 a1){
T0* R;
{Tid id=((T0*)C)->id;
if(id<=168){
if(id<=165){
R=(r165_ix_6442(((T165*)C),a1));
}
else{
R=(r168_ix_6442(((T168*)C),a1));
}}
else{
R=(r170_ix_6442(((T170*)C),a1));
}}
return R;
}

T0* X166remainder_of_divide_small_integer(T0*C,T0* a1){
T0* R;
{Tid id=((T0*)C)->id;
if(id<=168){
if(id<=165){
R=(r165remainder_of_divide_small_integer(((T165*)C),a1));
}
else{
R=(r168remainder_of_divide_small_integer(((T168*)C),a1));
}}
else{
R=(r170remainder_of_divide_small_integer(((T170*)C),a1));
}}
return R;
}

T6 X166_ix_6461(T0*C,T2 a1){
T6 R;
{Tid id=((T0*)C)->id;
if(id<=168){
if(id<=165){
R=(T6)(/*(IRF4.7@=*/((/*RF2*/(((T165*)C))->_value/*1*/))==(a1)/*)*/);
}
else{
R=(T6)(r168_ix_6461(((T168*)C),a1));
}}
else{
R=(T6)(r170_ix_6461(((T170*)C),a1));
}}
return R;
}

T6 X164_ix_646261(T0*C,T2 a1){
T6 R;
{Tid id=((T0*)C)->id;
if(id<=170){
if(id<=168){
if(id<=165){
R=(T6)(/*(IRF4.6@>=*/(int32_t)(((/*RF2*/(((T165*)C))->_value/*1*/))>=(a1))/*)*/);
}
else{
R=(T6)(r168_ix_646261(((T168*)C),a1));
}}
else{
R=(T6)(r170_ix_646261(((T170*)C),a1));
}}
else{
if(id<=225){
R=(T6)(r225_ix_646261(((T225*)C),a1));
}
else{
R=(T6)(r227_ix_646261(((T227*)C),a1));
}}}
return R;
}

T0* X164_ix_4747(T0*C,T0* a1){
T0* R;
{Tid id=((T0*)C)->id;
if(id<=170){
if(id<=168){
if(id<=165){
R=(r165_ix_4747(((T165*)C),a1));
}
else{
R=(r168_ix_4747(((T168*)C),a1));
}}
else{
R=(r170_ix_4747(((T170*)C),a1));
}}
else{
if(id<=225){
R=(/*(IRF4.1//*/NULL/*)*/);
}
else{
R=(/*(IRF4.1//*/NULL/*)*/);
}}}
return R;
}

T6 X164is_positive(T0*C){
T6 R;
{Tid id=((T0*)C)->id;
if(id<=170){
if(id<=168){
if(id<=165){
R=(T6)(/*(IRF4.6is_positive*/(int32_t)(((/*RF2*/(((T165*)C))->_value/*1*/))>=(INT8_C(0)))/*)*/);
}
else{
R=(T6)(0);
}}
else{
R=(T6)(1);
}}
else{
if(id<=225){
R=(T6)(/*(IRF4.6is_positive*/r6_px_not((T6)(((T6)((/*RF2*/(((T225*)C))->_is_negative/*1*/)))))/*)*/);
}
else{
R=(T6)(/*(IRF4.6is_positive*/(int32_t)(((/*RF2*/(((T227*)C))->_numerator/*1*/))>=(INT8_C(0)))/*)*/);
}}}
return R;
}

T0* X164_ix_6494(T0*C,T2 a1){
T0* R;
{Tid id=((T0*)C)->id;
if(id<=170){
if(id<=168){
if(id<=165){
R=(r165_ix_6494(((T165*)C),a1));
}
else{
R=(r168_ix_6494(((T168*)C),a1));
}}
else{
R=(r170_ix_6494(((T170*)C),a1));
}}
else{
if(id<=225){
R=(r225_ix_6494(((T225*)C),a1));
}
else{
R=(r227_ix_6494(((T227*)C),a1));
}}}
return R;
}

T6 X164greater_with_large_negative_integer(T0*C,T0* a1){
T6 R;
{Tid id=((T0*)C)->id;
if(id<=170){
if(id<=168){
if(id<=165){
R=(T6)(/*(IRF4.2greater_with_large_negative_integer*/(1)/*)*/);
}
else{
R=(T6)(r168greater_with_large_negative_integer(((T168*)C),a1));
}}
else{
R=(T6)(oBC170greater_with_large_negative_integer);
}}
else{
if(id<=225){
R=(T6)(r225greater_with_large_negative_integer(((T225*)C),a1));
}
else{
R=(T6)(oBC227greater_with_large_negative_integer);
}}}
return R;
}

T6 X164is_abstract_integer(T0*C){
T6 R;
{Tid id=((T0*)C)->id;
if(id<=170){
if(id<=168){
if(id<=165){
R=(T6)(r165is_abstract_integer(((T165*)C)));
}
else{
R=(T6)(r168is_abstract_integer(((T168*)C)));
}}
else{
R=(T6)(r170is_abstract_integer(((T170*)C)));
}}
else{
if(id<=225){
R=(T6)(r225is_abstract_integer(((T225*)C)));
}
else{
R=(T6)(r227is_abstract_integer(((T227*)C)));
}}}
return R;
}

T0* X164add_with_small_fraction(T0*C,T0* a1){
T0* R;
{Tid id=((T0*)C)->id;
if(id<=170){
if(id<=168){
if(id<=165){
R=(r165add_with_small_fraction(((T165*)C),a1));
}
else{
R=(r168add_with_small_fraction(((T168*)C),a1));
}}
else{
R=(r170add_with_small_fraction(((T170*)C),a1));
}}
else{
if(id<=225){
R=(r225add_with_small_fraction(((T225*)C),a1));
}
else{
R=(r227add_with_small_fraction(((T227*)C),a1));
}}}
return R;
}

T0* X164multiply_with_small_fraction(T0*C,T0* a1){
T0* R;
{Tid id=((T0*)C)->id;
if(id<=170){
if(id<=168){
if(id<=165){
R=(r165multiply_with_small_fraction(((T165*)C),a1));
}
else{
R=(r168multiply_with_small_fraction(((T168*)C),a1));
}}
else{
R=(r170multiply_with_small_fraction(((T170*)C),a1));
}}
else{
if(id<=225){
R=(r225multiply_with_small_fraction(((T225*)C),a1));
}
else{
R=(r227multiply_with_small_fraction(((T227*)C),a1));
}}}
return R;
}

T0* X164factorial(T0*C){
T0* R;
{Tid id=((T0*)C)->id;
if(id<=170){
if(id<=168){
if(id<=165){
R=(r165factorial(((T165*)C)));
}
else{
R=(r168factorial(((T168*)C)));
}}
else{
R=(r170factorial(((T170*)C)));
}}
else{
if(id<=225){
R=(r225factorial(((T225*)C)));
}
else{
R=(r227factorial(((T227*)C)));
}}}
return R;
}

T6 X164greater_with_small_fraction(T0*C,T0* a1){
T6 R;
{Tid id=((T0*)C)->id;
if(id<=170){
if(id<=168){
if(id<=165){
R=(T6)(r165greater_with_small_fraction(((T165*)C),a1));
}
else{
R=(T6)(r168greater_with_small_fraction(a1));
}}
else{
R=(T6)(oBC170greater_with_small_fraction);
}}
else{
if(id<=225){
R=(T6)(r225greater_with_small_fraction(((T225*)C),a1));
}
else{
R=(T6)(r227greater_with_small_fraction(((T227*)C),a1));
}}}
return R;
}

T0* X164_ix_644747(T0*C,T2 a1){
T0* R;
{Tid id=((T0*)C)->id;
if(id<=170){
if(id<=168){
if(id<=165){
R=(r165_ix_644747(((T165*)C),a1));
}
else{
R=(r168_ix_644747(((T168*)C),a1));
}}
else{
R=(r170_ix_644747(((T170*)C),a1));
}}
else{
if(id<=225){
R=(/*(IRF4.1@//*/NULL/*)*/);
}
else{
R=(/*(IRF4.1@//*/NULL/*)*/);
}}}
return R;
}

T0* X164multiply_with_large_negative_integer(T0*C,T0* a1){
T0* R;
{Tid id=((T0*)C)->id;
if(id<=170){
if(id<=168){
if(id<=165){
R=(r165multiply_with_large_negative_integer(((T165*)C),a1));
}
else{
R=(r168multiply_with_large_negative_integer(((T168*)C),a1));
}}
else{
R=(r170multiply_with_large_negative_integer(((T170*)C),a1));
}}
else{
if(id<=225){
R=(r225multiply_with_large_negative_integer(((T225*)C),a1));
}
else{
R=(r227multiply_with_large_negative_integer(((T227*)C),a1));
}}}
return R;
}

T0* X164to_string(T0*C){
T0* R;
{Tid id=((T0*)C)->id;
if(id<=170){
if(id<=168){
if(id<=165){
R=(r165to_string(((T165*)C)));
}
else{
R=(r168to_string(((T168*)C)));
}}
else{
R=(r170to_string(((T170*)C)));
}}
else{
if(id<=225){
R=(r225to_string(((T225*)C)));
}
else{
R=(r227to_string(((T227*)C)));
}}}
return R;
}

T6 X164greater_with_large_positive_integer(T0*C,T0* a1){
T6 R;
{Tid id=((T0*)C)->id;
if(id<=170){
if(id<=168){
if(id<=165){
R=(T6)(r165greater_with_large_positive_integer(a1));
}
else{
R=(T6)(r168greater_with_large_positive_integer(a1));
}}
else{
R=(T6)(r170greater_with_large_positive_integer(((T170*)C),a1));
}}
else{
if(id<=225){
R=(T6)(r225greater_with_large_positive_integer(((T225*)C),a1));
}
else{
R=(T6)(r227greater_with_large_positive_integer(a1));
}}}
return R;
}

T0* X164add_with_large_negative_integer(T0*C,T0* a1){
T0* R;
{Tid id=((T0*)C)->id;
if(id<=170){
if(id<=168){
if(id<=165){
R=(r165add_with_large_negative_integer(((T165*)C),a1));
}
else{
R=(r168add_with_large_negative_integer(((T168*)C),a1));
}}
else{
R=(r170add_with_large_negative_integer(((T170*)C),a1));
}}
else{
if(id<=225){
R=(r225add_with_large_negative_integer(((T225*)C),a1));
}
else{
R=(r227add_with_large_negative_integer(((T227*)C),a1));
}}}
return R;
}

T6 X164greater_with_large_fraction(T0*C,T0* a1){
T6 R;
{Tid id=((T0*)C)->id;
if(id<=170){
if(id<=168){
if(id<=165){
R=(T6)(r165greater_with_large_fraction(((T165*)C),a1));
}
else{
R=(T6)(r168greater_with_large_fraction(((T168*)C),a1));
}}
else{
R=(T6)(r170greater_with_large_fraction(((T170*)C),a1));
}}
else{
if(id<=225){
R=(T6)(r225greater_with_large_fraction(((T225*)C),a1));
}
else{
R=(T6)(r227greater_with_large_fraction(((T227*)C),a1));
}}}
return R;
}

T0* X164gcd(T0*C,T0* a1){
T0* R;
{Tid id=((T0*)C)->id;
if(id<=170){
if(id<=168){
if(id<=165){
R=(r165gcd(((T165*)C),a1));
}
else{
R=(r168gcd(((T168*)C),a1));
}}
else{
R=(r170gcd(((T170*)C),a1));
}}
else{
if(id<=225){
R=(r225gcd(((T225*)C),a1));
}
else{
R=(r227gcd(((T227*)C),a1));
}}}
return R;
}

T6 X164odd(T0*C){
T6 R;
{Tid id=((T0*)C)->id;
if(id<=170){
if(id<=168){
if(id<=165){
R=(T6)(r165odd(((T165*)C)));
}
else{
R=(T6)(r168odd(((T168*)C)));
}}
else{
R=(T6)(r170odd(((T170*)C)));
}}
else{
if(id<=225){
R=(T6)(r225odd());
}
else{
R=(T6)(r227odd());
}}}
return R;
}

T0* X164multiply_with_large_fraction(T0*C,T0* a1){
T0* R;
{Tid id=((T0*)C)->id;
if(id<=170){
if(id<=168){
if(id<=165){
R=(r165multiply_with_large_fraction(((T165*)C),a1));
}
else{
R=(r168multiply_with_large_fraction(((T168*)C),a1));
}}
else{
R=(r170multiply_with_large_fraction(((T170*)C),a1));
}}
else{
if(id<=225){
R=(r225multiply_with_large_fraction(((T225*)C),a1));
}
else{
R=(r227multiply_with_large_fraction(((T227*)C),a1));
}}}
return R;
}

T0* X164inverse(T0*C){
T0* R;
{Tid id=((T0*)C)->id;
if(id<=170){
if(id<=168){
if(id<=165){
R=(r165inverse(((T165*)C)));
}
else{
R=(r168inverse(((T168*)C)));
}}
else{
R=(r170inverse(((T170*)C)));
}}
else{
if(id<=225){
R=(r225inverse(((T225*)C)));
}
else{
R=(r227inverse(((T227*)C)));
}}}
return R;
}

T0* X164_px_45(T0*C){
T0* R;
{Tid id=((T0*)C)->id;
if(id<=170){
if(id<=168){
if(id<=165){
R=(r165_px_45(((T165*)C)));
}
else{
R=(r168_px_45(((T168*)C)));
}}
else{
R=(r170_px_45(((T170*)C)));
}}
else{
if(id<=225){
R=(r225_px_45(((T225*)C)));
}
else{
R=(r227_px_45(((T227*)C)));
}}}
return R;
}

T2 X164to_integer(T0*C){
T2 R;
{Tid id=((T0*)C)->id;
if(id<=170){
if(id<=168){
if(id<=165){
R=(/*(IRF4.3to_integer*/(/*RF2*/(((T165*)C))->_value/*1*/)/*)*/);
}
else{
R=(r168to_integer(((T168*)C)));
}}
else{
R=(r170to_integer(((T170*)C)));
}}
else{
if(id<=225){
R=(r225to_integer());
}
else{
R=(r227to_integer());
}}}
return R;
}

T0* X164add_with_large_fraction(T0*C,T0* a1){
T0* R;
{Tid id=((T0*)C)->id;
if(id<=170){
if(id<=168){
if(id<=165){
R=(r165add_with_large_fraction(((T165*)C),a1));
}
else{
R=(r168add_with_large_fraction(((T168*)C),a1));
}}
else{
R=(r170add_with_large_fraction(((T170*)C),a1));
}}
else{
if(id<=225){
R=(r225add_with_large_fraction(((T225*)C),a1));
}
else{
R=(r227add_with_large_fraction(((T227*)C),a1));
}}}
return R;
}

T6 X164is_negative(T0*C){
T6 R;
{Tid id=((T0*)C)->id;
if(id<=170){
if(id<=168){
if(id<=165){
R=(T6)(/*(IRF4.6is_negative*/(int32_t)(((/*RF2*/(((T165*)C))->_value/*1*/))<(INT8_C(0)))/*)*/);
}
else{
R=(T6)(1);
}}
else{
R=(T6)(0);
}}
else{
if(id<=225){
R=(T6)((/*RF2*/(((T225*)C))->_is_negative/*1*/));
}
else{
R=(T6)(/*(IRF4.6is_negative*/(int32_t)(((/*RF2*/(((T227*)C))->_numerator/*1*/))<(INT8_C(0)))/*)*/);
}}}
return R;
}

T6 X164_ix_6261(T0*C,T0* a1){
T6 R;
{Tid id=((T0*)C)->id;
if(id<=170){
if(id<=168){
if(id<=165){
R=(T6)(r165_ix_6261(((T165*)C),a1));
}
else{
R=(T6)(r168_ix_6261(((T168*)C),a1));
}}
else{
R=(T6)(r170_ix_6261(((T170*)C),a1));
}}
else{
if(id<=225){
R=(T6)(r225_ix_6261(((T225*)C),a1));
}
else{
R=(T6)(r227_ix_6261(((T227*)C),a1));
}}}
return R;
}

T0* X164add_with_large_positive_integer(T0*C,T0* a1){
T0* R;
{Tid id=((T0*)C)->id;
if(id<=170){
if(id<=168){
if(id<=165){
R=(r165add_with_large_positive_integer(((T165*)C),a1));
}
else{
R=(r168add_with_large_positive_integer(((T168*)C),a1));
}}
else{
R=(r170add_with_large_positive_integer(((T170*)C),a1));
}}
else{
if(id<=225){
R=(r225add_with_large_positive_integer(((T225*)C),a1));
}
else{
R=(r227add_with_large_positive_integer(((T227*)C),a1));
}}}
return R;
}

T2 X164compare(T0*C,T0* a1){
T2 R;
{Tid id=((T0*)C)->id;
if(id<=170){
if(id<=168){
if(id<=165){
R=(r165compare(((T165*)C),a1));
}
else{
R=(r168compare(((T168*)C),a1));
}}
else{
R=(r170compare(((T170*)C),a1));
}}
else{
if(id<=225){
R=(r225compare(((T225*)C),a1));
}
else{
R=(r227compare(((T227*)C),a1));
}}}
return R;
}

T0* X164multiply_with_large_positive_integer(T0*C,T0* a1){
T0* R;
{Tid id=((T0*)C)->id;
if(id<=170){
if(id<=168){
if(id<=165){
R=(r165multiply_with_large_positive_integer(((T165*)C),a1));
}
else{
R=(r168multiply_with_large_positive_integer(((T168*)C),a1));
}}
else{
R=(r170multiply_with_large_positive_integer(((T170*)C),a1));
}}
else{
if(id<=225){
R=(r225multiply_with_large_positive_integer(((T225*)C),a1));
}
else{
R=(r227multiply_with_large_positive_integer(((T227*)C),a1));
}}}
return R;
}

T6 X164is_one(T0*C){
T6 R;
{Tid id=((T0*)C)->id;
if(id<=170){
if(id<=168){
if(id<=165){
R=(T6)(/*(IRF4.7is_one*/((/*RF2*/(((T165*)C))->_value/*1*/))==(INT8_C(1))/*)*/);
}
else{
R=(T6)(0);
}}
else{
R=(T6)(0);
}}
else{
if(id<=225){
R=(T6)(0);
}
else{
R=(T6)(0);
}}}
return R;
}

T0* X164_ix_42(T0*C,T0* a1){
T0* R;
{Tid id=((T0*)C)->id;
if(id<=170){
if(id<=168){
if(id<=165){
R=(r165_ix_42(((T165*)C),a1));
}
else{
R=(r168_ix_42(((T168*)C),a1));
}}
else{
R=(r170_ix_42(((T170*)C),a1));
}}
else{
if(id<=225){
R=(r225_ix_42(((T225*)C),a1));
}
else{
R=(r227_ix_42(((T227*)C),a1));
}}}
return R;
}

T0* X164_ix_43(T0*C,T0* a1){
T0* R;
{Tid id=((T0*)C)->id;
if(id<=170){
if(id<=168){
if(id<=165){
R=(r165_ix_43(((T165*)C),a1));
}
else{
R=(r168_ix_43(((T168*)C),a1));
}}
else{
R=(r170_ix_43(((T170*)C),a1));
}}
else{
if(id<=225){
R=(r225_ix_43(((T225*)C),a1));
}
else{
R=(r227_ix_43(((T227*)C),a1));
}}}
return R;
}

T0* X164_ix_45(T0*C,T0* a1){
T0* R;
{Tid id=((T0*)C)->id;
if(id<=170){
if(id<=168){
if(id<=165){
R=(r165_ix_45(((T165*)C),a1));
}
else{
R=(r168_ix_45(((T168*)C),a1));
}}
else{
R=(r170_ix_45(((T170*)C),a1));
}}
else{
if(id<=225){
R=(r225_ix_45(((T225*)C),a1));
}
else{
R=(r227_ix_45(((T227*)C),a1));
}}}
return R;
}

T0* X164_ix_47(T0*C,T0* a1){
T0* R;
{Tid id=((T0*)C)->id;
if(id<=170){
if(id<=168){
if(id<=165){
R=(r165_ix_47(((T165*)C),a1));
}
else{
R=(r168_ix_47(((T168*)C),a1));
}}
else{
R=(r170_ix_47(((T170*)C),a1));
}}
else{
if(id<=225){
R=(r225_ix_47(((T225*)C),a1));
}
else{
R=(r227_ix_47(((T227*)C),a1));
}}}
return R;
}

T6 X164_ix_60(T0*C,T0* a1){
T6 R;
{Tid id=((T0*)C)->id;
if(id<=170){
if(id<=168){
if(id<=165){
R=(T6)(r165_ix_60(((T165*)C),a1));
}
else{
R=(T6)(r168_ix_60(((T168*)C),a1));
}}
else{
R=(T6)(r170_ix_60(((T170*)C),a1));
}}
else{
if(id<=225){
R=(T6)(r225_ix_60(((T225*)C),a1));
}
else{
R=(T6)(r227_ix_60(((T227*)C),a1));
}}}
return R;
}

T0* X164_ix_6442(T0*C,T2 a1){
T0* R;
{Tid id=((T0*)C)->id;
if(id<=170){
if(id<=168){
if(id<=165){
R=(r165_ix_6442(((T165*)C),a1));
}
else{
R=(r168_ix_6442(((T168*)C),a1));
}}
else{
R=(r170_ix_6442(((T170*)C),a1));
}}
else{
if(id<=225){
R=(r225_ix_6442(((T225*)C),a1));
}
else{
R=(r227_ix_6442(((T227*)C),a1));
}}}
return R;
}

T6 X164_ix_62(T0*C,T0* a1){
T6 R;
{Tid id=((T0*)C)->id;
if(id<=170){
if(id<=168){
if(id<=165){
R=(T6)(r165_ix_62(((T165*)C),a1));
}
else{
R=(T6)(r168_ix_62(((T168*)C),a1));
}}
else{
R=(T6)(r170_ix_62(((T170*)C),a1));
}}
else{
if(id<=225){
R=(T6)(r225_ix_62(((T225*)C),a1));
}
else{
R=(T6)(r227_ix_62(((T227*)C),a1));
}}}
return R;
}

T0* X164_ix_6443(T0*C,T2 a1){
T0* R;
{Tid id=((T0*)C)->id;
if(id<=170){
if(id<=168){
if(id<=165){
R=(r165_ix_6443(((T165*)C),a1));
}
else{
R=(r168_ix_6443(((T168*)C),a1));
}}
else{
R=(r170_ix_6443(((T170*)C),a1));
}}
else{
if(id<=225){
R=(r225_ix_6443(((T225*)C),a1));
}
else{
R=(r227_ix_6443(((T227*)C),a1));
}}}
return R;
}

T0* X164_ix_6445(T0*C,T2 a1){
T0* R;
{Tid id=((T0*)C)->id;
if(id<=170){
if(id<=168){
if(id<=165){
R=(r165_ix_6445(((T165*)C),a1));
}
else{
R=(r168_ix_6445(((T168*)C),a1));
}}
else{
R=(r170_ix_6445(((T170*)C),a1));
}}
else{
if(id<=225){
R=(r225_ix_6445(((T225*)C),a1));
}
else{
R=(r227_ix_6445(((T227*)C),a1));
}}}
return R;
}

T6 X164is_zero(T0*C){
T6 R;
{Tid id=((T0*)C)->id;
if(id<=170){
if(id<=168){
if(id<=165){
R=(T6)(/*(IRF4.7is_zero*/((/*RF2*/(((T165*)C))->_value/*1*/))==(INT8_C(0))/*)*/);
}
else{
R=(T6)(0);
}}
else{
R=(T6)(0);
}}
else{
if(id<=225){
R=(T6)(0);
}
else{
R=(T6)(0);
}}}
return R;
}

T6 X164_ix_6460(T0*C,T2 a1){
T6 R;
{Tid id=((T0*)C)->id;
if(id<=170){
if(id<=168){
if(id<=165){
R=(T6)(/*(IRF4.6@<*/(int32_t)(((/*RF2*/(((T165*)C))->_value/*1*/))<(a1))/*)*/);
}
else{
R=(T6)(r168_ix_6460(((T168*)C),a1));
}}
else{
R=(T6)(r170_ix_6460(((T170*)C),a1));
}}
else{
if(id<=225){
R=(T6)(r225_ix_6460(((T225*)C),a1));
}
else{
R=(T6)(r227_ix_6460(((T227*)C),a1));
}}}
return R;
}

T6 X164_ix_6461(T0*C,T2 a1){
T6 R;
{Tid id=((T0*)C)->id;
if(id<=170){
if(id<=168){
if(id<=165){
R=(T6)(/*(IRF4.7@=*/((/*RF2*/(((T165*)C))->_value/*1*/))==(a1)/*)*/);
}
else{
R=(T6)(r168_ix_6461(((T168*)C),a1));
}}
else{
R=(T6)(r170_ix_6461(((T170*)C),a1));
}}
else{
if(id<=225){
R=(T6)(r225_ix_6461(a1));
}
else{
R=(T6)(r227_ix_6461(a1));
}}}
return R;
}

T6 X164_ix_6462(T0*C,T2 a1){
T6 R;
{Tid id=((T0*)C)->id;
if(id<=170){
if(id<=168){
if(id<=165){
R=(T6)(/*(IRF4.6@>*/(int32_t)(((/*RF2*/(((T165*)C))->_value/*1*/))>(a1))/*)*/);
}
else{
R=(T6)(r168_ix_6462(((T168*)C),a1));
}}
else{
R=(T6)(r170_ix_6462(((T170*)C),a1));
}}
else{
if(id<=225){
R=(T6)(r225_ix_6462(((T225*)C),a1));
}
else{
R=(T6)(r227_ix_6462(((T227*)C),a1));
}}}
return R;
}

T0* T5toT224(T5 source){
T224*destination=new224();
destination->_item=source;
return (T0*)destination;
}

#ifdef __cplusplus
}
#endif
